### ISSUE TITLE
Identifiers validation failed for dataset Colección de Peces de Agua Dulce del Instituto de Investigación de Recursos Biológicos Alexander von Humboldt (IAvH-P)

### ISSUE THREAD

**Issue by gbif-pipelines** [gbif/ingestion-management#1000]
Identifier validation failed for the dataset [Colección de Peces de Agua Dulce del Instituto de Investigación de Recursos Biológicos Alexander von Humboldt (IAvH-P)](https://registry.gbif.org/dataset/75bcbf8f-5e58-4714-9eba-382129702022):
- Crawler attempt: 348
- Publishing organization: [Instituto de Investigación de Recursos Biológicos Alexander von Humboldt](https://registry.gbif.org/organization/2a7e3080-28a9-11dd-97cd-b8a03c50a862)
- Publishing country: COLOMBIA
- Installation: [IPT IAvH](https://registry.gbif.org/installation/804b8dd0-07ac-4a30-bf92-3c1d862faf5e)
- Number of occurrences indexed for this dataset at the time of the issue: 22983
- Cause: GBIF ID problems exceed 50% threshold: 100% duplicates; 29867 total records; 29867 absent records
- Pipelines execution steps: [http://api.gbif.org/v1/pipelines/history/execution/3526359/step](http://api.gbif.org/v1/pipelines/history/execution/3526359/step)

```
New IDs sample:


```

```
Old IDs sample:

IAvH:COLECCIONES:PECES:I2D-BIO_2013IPT015:IAvH-P-22471
IAvH:COLECCIONES:PECES:I2D-BIO_2013IPT015:IAvH-P-22472
IAvH:COLECCIONES:PECES:I2D-BIO_2013IPT015:IAvH-P-22473
IAvH:COLECCIONES:PECES:I2D-BIO_2013IPT015:IAvH-P-22474
IAvH:COLECCIONES:PECES:I2D-BIO_2013IPT015:IAvH-P-22475
IAvH:COLECCIONES:PECES:I2D-BIO_2013IPT015:IAvH-P-22476
IAvH:COLECCIONES:PECES:I2D-BIO_2013IPT015:IAvH-P-22477
IAvH:COLECCIONES:PECES:I2D-BIO_2013IPT015:IAvH-P-22478
IAvH:COLECCIONES:PECES:I2D-BIO_2013IPT015:IAvH-P-22479
IAvH:COLECCIONES:PECES:I2D-BIO_2013IPT015:IAvH-P-22480
```

<details>
<summary>Publisher email</summary>

Hello,

I am contacting you from the GBIF Secretariat about a dataset published by the [Colección de Peces de Agua Dulce del Instituto de Investigación de Recursos Biológicos Alexander von Humboldt (IAvH-P)](https://registry.gbif.org/dataset/75bcbf8f-5e58-4714-9eba-382129702022) : https://doi.org/10.15472/7oysm0.
We noticed that the occurrenceIDs were changed. We have temporarily paused the ingestions of this dataset.

As you might already know, when an occurrence record has a new occurrenceID for a given dataset, our system considers it to be a new occurrence.
This means that it will be given a new gbifid and a new occurrence URL (like this one: https://www.gbif.org/occurrence/1252968762) and the old gbifid and URL will be deprecated.

In this case, this means that the occurrence URLs would be deprecated when ingesting the newest versions of these datasets.

We would like to check with you if those changes were intentional. Do you know if this is the case?
Please let us know, thanks! We are happy to resume the dataset ingestion.

Note that some users rely on those occurrence URLs and gbifids (like https://bionomia.net for example). In an attempt to improve
the stability of the occurrence URLs and gbifids, we have implemented a warning system to detect these type of changes in datasets (see this news item).
If the data publisher can provide us with a list of old and new occurrenceIDs per record, we can avoid the identifier and URL changes. Could that be an option?

Please let us know if you have any question. Thanks!

All the best,

</details>

You can skip/fix identifier validation using [the registry UI](https://registry.gbif.org/dataset/75bcbf8f-5e58-4714-9eba-382129702022/ingestion-history).

**Comment by ManonGros** [comment]
@EstebanMH-SiB

**Comment by gbif-pipelines** [comment]
Identifier validation still  failing for the dataset [Colección de Peces de Agua Dulce del Instituto de Investigación de Recursos Biológicos Alexander von Humboldt (IAvH-P)](https://registry.gbif.org/dataset/75bcbf8f-5e58-4714-9eba-382129702022):
- Crawler attempt: 373
- Publishing organization: [Instituto de Investigación de Recursos Biológicos Alexander von Humboldt](https://registry.gbif.org/organization/2a7e3080-28a9-11dd-97cd-b8a03c50a862)
- Publishing country: COLOMBIA
- Installation: [IPT IAvH](https://registry.gbif.org/installation/804b8dd0-07ac-4a30-bf92-3c1d862faf5e)
- Number of occurrences indexed for this dataset at the time of the issue: 22983
- Cause: GBIF ID problems exceed 50% threshold: 100% duplicates; 29867 total records; 29867 absent records
- Pipelines execution steps: [http://api.gbif.org/v1/pipelines/history/execution/3997580/step](http://api.gbif.org/v1/pipelines/history/execution/3997580/step)

```
New IDs sample:


```


```
Old IDs sample:

IAvH:COLECCIONES:PECES:I2D-BIO_2013IPT015:IAvH-P-22471
IAvH:COLECCIONES:PECES:I2D-BIO_2013IPT015:IAvH-P-22472
IAvH:COLECCIONES:PECES:I2D-BIO_2013IPT015:IAvH-P-22473
IAvH:COLECCIONES:PECES:I2D-BIO_2013IPT015:IAvH-P-22474
IAvH:COLECCIONES:PECES:I2D-BIO_2013IPT015:IAvH-P-22475
IAvH:COLECCIONES:PECES:I2D-BIO_2013IPT015:IAvH-P-22476
IAvH:COLECCIONES:PECES:I2D-BIO_2013IPT015:IAvH-P-22477
IAvH:COLECCIONES:PECES:I2D-BIO_2013IPT015:IAvH-P-22478
IAvH:COLECCIONES:PECES:I2D-BIO_2013IPT015:IAvH-P-22479
IAvH:COLECCIONES:PECES:I2D-BIO_2013IPT015:IAvH-P-22480
```

<details>
<summary>Publisher email</summary>

Hello,

I am contacting you from the GBIF Secretariat about a dataset published by the [Colección de Peces de Agua Dulce del Instituto de Investigación de Recursos Biológicos Alexander von Humboldt (IAvH-P)](https://registry.gbif.org/dataset/75bcbf8f-5e58-4714-9eba-382129702022) : https://doi.org/10.15472/7oysm0.
We noticed that the occurrenceIDs were changed. We have temporarily paused the ingestions of this dataset.

As you might already know, when an occurrence record has a new occurrenceID for a given dataset, our system considers it to be a new occurrence.
This means that it will be given a new gbifid and a new occurrence URL (like this one: https://www.gbif.org/occurrence/1252968762) and the old gbifid and URL will be deprecated.

In this case, this means that the occurrence URLs would be deprecated when ingesting the newest versions of these datasets.

We would like to check with you if those changes were intentional. Do you know if this is the case?
Please let us know, thanks! We are happy to resume the dataset ingestion.

Note that some users rely on those occurrence URLs and gbifids (like https://bionomia.net for example). In an attempt to improve
the stability of the occurrence URLs and gbifids, we have implemented a warning system to detect these type of changes in datasets (see this news item).
If the data publisher can provide us with a list of old and new occurrenceIDs per record, we can avoid the identifier and URL changes. Could that be an option?

Please let us know if you have any question. Thanks!

All the best,

</details>


You can skip/fix identifier validation using [the registry UI](https://registry.gbif.org/dataset/75bcbf8f-5e58-4714-9eba-382129702022/ingestion-history).

**Comment by gbif-pipelines** [comment]
Identifier validation still  failing for the dataset [Colección de Peces de Agua Dulce del Instituto de Investigación de Recursos Biológicos Alexander von Humboldt (IAvH-P)](https://registry.gbif.org/dataset/75bcbf8f-5e58-4714-9eba-382129702022):
- Crawler attempt: 376
- Publishing organization: [Instituto de Investigación de Recursos Biológicos Alexander von Humboldt](https://registry.gbif.org/organization/2a7e3080-28a9-11dd-97cd-b8a03c50a862)
- Publishing country: COLOMBIA
- Installation: [IPT IAvH](https://registry.gbif.org/installation/804b8dd0-07ac-4a30-bf92-3c1d862faf5e)
- Number of occurrences indexed for this dataset at the time of the issue: 22983
- Cause: GBIF ID problems exceed 50% threshold: 100% duplicates; 29867 total records; 29867 absent records
- Pipelines execution steps: [http://api.gbif.org/v1/pipelines/history/execution/4052648/step](http://api.gbif.org/v1/pipelines/history/execution/4052648/step)

```
New IDs sample:


```


```
Old IDs sample:

IAvH:COLECCIONES:PECES:I2D-BIO_2013IPT015:IAvH-P-22471
IAvH:COLECCIONES:PECES:I2D-BIO_2013IPT015:IAvH-P-22472
IAvH:COLECCIONES:PECES:I2D-BIO_2013IPT015:IAvH-P-22473
IAvH:COLECCIONES:PECES:I2D-BIO_2013IPT015:IAvH-P-22474
IAvH:COLECCIONES:PECES:I2D-BIO_2013IPT015:IAvH-P-22475
IAvH:COLECCIONES:PECES:I2D-BIO_2013IPT015:IAvH-P-22476
IAvH:COLECCIONES:PECES:I2D-BIO_2013IPT015:IAvH-P-22477
IAvH:COLECCIONES:PECES:I2D-BIO_2013IPT015:IAvH-P-22478
IAvH:COLECCIONES:PECES:I2D-BIO_2013IPT015:IAvH-P-22479
IAvH:COLECCIONES:PECES:I2D-BIO_2013IPT015:IAvH-P-22480
```

<details>
<summary>Publisher email</summary>

Hello,

I am contacting you from the GBIF Secretariat about a dataset published by the [Colección de Peces de Agua Dulce del Instituto de Investigación de Recursos Biológicos Alexander von Humboldt (IAvH-P)](https://registry.gbif.org/dataset/75bcbf8f-5e58-4714-9eba-382129702022) : https://doi.org/10.15472/7oysm0.
We noticed that the occurrenceIDs were changed. We have temporarily paused the ingestions of this dataset.

As you might already know, when an occurrence record has a new occurrenceID for a given dataset, our system considers it to be a new occurrence.
This means that it will be given a new gbifid and a new occurrence URL (like this one: https://www.gbif.org/occurrence/1252968762) and the old gbifid and URL will be deprecated.

In this case, this means that the occurrence URLs would be deprecated when ingesting the newest versions of these datasets.

We would like to check with you if those changes were intentional. Do you know if this is the case?
Please let us know, thanks! We are happy to resume the dataset ingestion.

Note that some users rely on those occurrence URLs and gbifids (like https://bionomia.net for example). In an attempt to improve
the stability of the occurrence URLs and gbifids, we have implemented a warning system to detect these type of changes in datasets (see this news item).
If the data publisher can provide us with a list of old and new occurrenceIDs per record, we can avoid the identifier and URL changes. Could that be an option?

Please let us know if you have any question. Thanks!

All the best,

</details>


You can skip/fix identifier validation using [the registry UI](https://registry.gbif.org/dataset/75bcbf8f-5e58-4714-9eba-382129702022/ingestion-history).
