### ISSUE TITLE
Identifiers validation failed for dataset Artrópodos de los Parques Distritales Ecológicos de Montaña

### ISSUE THREAD

**Issue by gbif-pipelines** [gbif/ingestion-management#1008]
Identifier validation failed for the dataset [Artrópodos de los Parques Distritales Ecológicos de Montaña](https://registry.gbif.org/dataset/865c11e6-8d75-4acb-8f09-5d909e08ed6b):
- Crawler attempt: 61
- Publishing organization: [Secretaría Distrital de Ambiente](https://registry.gbif.org/organization/e70c4151-0d1a-414d-b70e-e87ac1e812b7)
- Publishing country: COLOMBIA
- Installation: [Datos sobre Biodiversidad de Colombia](https://registry.gbif.org/installation/68845aab-a453-4816-b36d-a3ec8455deb0)
- Number of occurrences indexed for this dataset at the time of the issue: 2186
- Cause: GBIF ID problems exceed 50% threshold: 100% duplicates; 1453 total records; 1453 absent records
- Pipelines execution steps: [http://api.gbif.org/v1/pipelines/history/execution/3578170/step](http://api.gbif.org/v1/pipelines/history/execution/3578170/step)

```
New IDs sample:


```

```
Old IDs sample:

SDA:ENT:RDH/PEDM:REG1
SDA:ENT:RDH/PEDM:REG10
SDA:ENT:RDH/PEDM:REG100
SDA:ENT:RDH/PEDM:REG101
SDA:ENT:RDH/PEDM:REG103
SDA:ENT:RDH/PEDM:REG104
SDA:ENT:RDH/PEDM:REG105
SDA:ENT:RDH/PEDM:REG106
SDA:ENT:RDH/PEDM:REG107
SDA:ENT:RDH/PEDM:REG109
```

<details>
<summary>Publisher email</summary>

Hello,

I am contacting you from the GBIF Secretariat about a dataset published by the [Artrópodos de los Parques Distritales Ecológicos de Montaña](https://registry.gbif.org/dataset/865c11e6-8d75-4acb-8f09-5d909e08ed6b) : https://doi.org/10.15472/cwrg3e.
We noticed that the occurrenceIDs were changed. We have temporarily paused the ingestions of this dataset.

As you might already know, when an occurrence record has a new occurrenceID for a given dataset, our system considers it to be a new occurrence.
This means that it will be given a new gbifid and a new occurrence URL (like this one: https://www.gbif.org/occurrence/1252968762) and the old gbifid and URL will be deprecated.

In this case, this means that the occurrence URLs would be deprecated when ingesting the newest versions of these datasets.

We would like to check with you if those changes were intentional. Do you know if this is the case?
Please let us know, thanks! We are happy to resume the dataset ingestion.

Note that some users rely on those occurrence URLs and gbifids (like https://bionomia.net for example). In an attempt to improve
the stability of the occurrence URLs and gbifids, we have implemented a warning system to detect these type of changes in datasets (see this news item).
If the data publisher can provide us with a list of old and new occurrenceIDs per record, we can avoid the identifier and URL changes. Could that be an option?

Please let us know if you have any question. Thanks!

All the best,

</details>

You can skip/fix identifier validation using [the registry UI](https://registry.gbif.org/dataset/865c11e6-8d75-4acb-8f09-5d909e08ed6b/ingestion-history).

**Comment by EstebanMH-SiB** [comment]
This is an old dataset in wich some ocurrences changed from one to another and is hard to keep track wich occurrenceIDs belongs to everyone. We can reindexit as it is

**Comment by ManonGros** [comment]
Thanks @EstebanMH-SiB ! I resumed the ingestions for this dataset
