### ISSUE TITLE
Identifiers validation failed for dataset Trawl Catch and Species Abundance from the 2019 Gulf of Alaska International Year of the Salmon Expedition

### ISSUE THREAD

**Issue by gbif-pipelines** [gbif/ingestion-management#1014]
Identifier validation failed for the dataset [Trawl Catch and Species Abundance from the 2019 Gulf of Alaska International Year of the Salmon Expedition](https://registry.gbif.org/dataset/7f1bf640-dd56-41e2-a827-a3175aed4d95):
- Crawler attempt: 63
- Publishing organization: [Canadian node of the Ocean Biogeographic Information System (OBIS Canada)](https://registry.gbif.org/organization/09a9c196-cb5b-4fa1-afc2-3499b868b225)
- Publishing country: CANADA
- Installation: [OBIS Canada](https://registry.gbif.org/installation/5ff1c992-5c84-40aa-bd9a-c1743a870c32)
- Number of occurrences indexed for this dataset at the time of the issue: 2809
- Cause: GBIF ID problems exceed 50% threshold: 97% duplicates; 2809 total records; 2721 absent records
- Pipelines execution steps: [http://api.gbif.org/v1/pipelines/history/execution/3585776/step](http://api.gbif.org/v1/pipelines/history/execution/3585776/step)

```
New IDs sample:

IYS:GoA2019:Stn3:trawl:sample70:occ
IYS:GoA2019:Stn3:trawl:sample64:occ
IYS:GoA2019:Stn2:trawl:sample30:occ
IYS:GoA2019:Stn2:trawl:sample12:occ
IYS:GoA2019:Stn3:trawl:sample59:occ
IYS:GoA2019:Stn3:trawl:sample51:occ
IYS:GoA2019:Stn3:trawl:sample78:occ
IYS:GoA2019:Stn3:trawl:sample46:occ
IYS:GoA2019:Stn3:trawl:sample52:occ
IYS:GoA2019:Stn2:trawl:sample5:occ
```

```
Old IDs sample:

IYS:GoA2019:Stn10:trawl:occ:59
IYS:GoA2019:Stn10:trawl:occ:60
IYS:GoA2019:Stn10:trawl:occ:61
IYS:GoA2019:Stn10:trawl:occ:62
IYS:GoA2019:Stn10:trawl:occ:63
IYS:GoA2019:Stn10:trawl:occ:64
IYS:GoA2019:Stn10:trawl:sample359:occ
IYS:GoA2019:Stn10:trawl:sample360:occ
IYS:GoA2019:Stn10:trawl:sample361:occ
IYS:GoA2019:Stn10:trawl:sample362:occ
```

<details>
<summary>Publisher email</summary>

Hello,

I am contacting you from the GBIF Secretariat about a dataset published by the [Trawl Catch and Species Abundance from the 2019 Gulf of Alaska International Year of the Salmon Expedition](https://registry.gbif.org/dataset/7f1bf640-dd56-41e2-a827-a3175aed4d95) : https://doi.org/10.21966/dphz-as73.
We noticed that the occurrenceIDs were changed. We have temporarily paused the ingestions of this dataset.

As you might already know, when an occurrence record has a new occurrenceID for a given dataset, our system considers it to be a new occurrence.
This means that it will be given a new gbifid and a new occurrence URL (like this one: https://www.gbif.org/occurrence/1252968762) and the old gbifid and URL will be deprecated.

In this case, this means that the occurrence URLs would be deprecated when ingesting the newest versions of these datasets.

We would like to check with you if those changes were intentional. Do you know if this is the case?
Please let us know, thanks! We are happy to resume the dataset ingestion.

Note that some users rely on those occurrence URLs and gbifids (like https://bionomia.net for example). In an attempt to improve
the stability of the occurrence URLs and gbifids, we have implemented a warning system to detect these type of changes in datasets (see this news item).
If the data publisher can provide us with a list of old and new occurrenceIDs per record, we can avoid the identifier and URL changes. Could that be an option?

Please let us know if you have any question. Thanks!

All the best,

</details>

You can skip/fix identifier validation using [the registry UI](https://registry.gbif.org/dataset/7f1bf640-dd56-41e2-a827-a3175aed4d95/ingestion-history).

**Comment by jhnwllr** [comment]
I don't understand why this was flagged. All of the old occurrenceIds are present in the new version.
