### ISSUE TITLE
Identifiers validation failed for dataset Registros de ocurrencia de Gomortega keule en bosque nativo de las regiones del Maule, de Ñuble y del Biobío , Chile.

### ISSUE THREAD

**Issue by gbif-pipelines** [gbif/ingestion-management#1017]
Identifier validation failed for the dataset [Registros de ocurrencia de Gomortega keule en bosque nativo de las regiones del Maule, de Ñuble y del Biobío , Chile.](https://registry.gbif.org/dataset/5d358c1d-86c8-4512-9068-abccfa192e09):
- Crawler attempt: 31
- Publishing organization: [Laboratorio de Ecologia de Paisaje - UdeC](https://registry.gbif.org/organization/08f187e1-0c50-4012-8fa5-1bed03b0b346)
- Publishing country: CHILE
- Installation: [IPT v.2.3.2](https://registry.gbif.org/installation/faeb021c-ab9f-4c80-9587-3749a8f6fb23)
- Number of occurrences indexed for this dataset at the time of the issue: 390
- Cause: GBIF ID problems exceed 50% threshold: 100% duplicates; 251 total records; 251 absent records
- Pipelines execution steps: [http://api.gbif.org/v1/pipelines/history/execution/3588266/step](http://api.gbif.org/v1/pipelines/history/execution/3588266/step)

```
New IDs sample:


```

```
Old IDs sample:

LEPUDEC:PITAO:349
LEPUDEC:PITAO:347
LEPUDEC:PITAO:348
LEPUDEC:PITAO:323
LEPUDEC:PITAO:327
LEPUDEC:PITAO:350
LEPUDEC:PITAO:351
LEPUDEC:PITAO:352
LEPUDEC:PITAO:353
LEPUDEC:PITAO:354
```

<details>
<summary>Publisher email</summary>

Hello,

I am contacting you from the GBIF Secretariat about a dataset published by the [Registros de ocurrencia de Gomortega keule en bosque nativo de las regiones del Maule, de Ñuble y del Biobío , Chile.](https://registry.gbif.org/dataset/5d358c1d-86c8-4512-9068-abccfa192e09) : https://doi.org/10.15468/44s9as.
We noticed that the occurrenceIDs were changed. We have temporarily paused the ingestions of this dataset.

As you might already know, when an occurrence record has a new occurrenceID for a given dataset, our system considers it to be a new occurrence.
This means that it will be given a new gbifid and a new occurrence URL (like this one: https://www.gbif.org/occurrence/1252968762) and the old gbifid and URL will be deprecated.

In this case, this means that the occurrence URLs would be deprecated when ingesting the newest versions of these datasets.

We would like to check with you if those changes were intentional. Do you know if this is the case?
Please let us know, thanks! We are happy to resume the dataset ingestion.

Note that some users rely on those occurrence URLs and gbifids (like https://bionomia.net for example). In an attempt to improve
the stability of the occurrence URLs and gbifids, we have implemented a warning system to detect these type of changes in datasets (see this news item).
If the data publisher can provide us with a list of old and new occurrenceIDs per record, we can avoid the identifier and URL changes. Could that be an option?

Please let us know if you have any question. Thanks!

All the best,

</details>

You can skip/fix identifier validation using [the registry UI](https://registry.gbif.org/dataset/5d358c1d-86c8-4512-9068-abccfa192e09/ingestion-history).

**Comment by jhnwllr** [comment]
I looks like a large change in the number of occurrences here because the dataset went from 0 to 251 occurrences.

**Comment by jhnwllr** [comment]
I am going to allow failed ids.
