### ISSUE TITLE
Identifiers validation failed for dataset Lund University Biological Museum - Insect collections Specimens

### ISSUE THREAD

**Issue by gbif-pipelines** [gbif/ingestion-management#1022]
Identifier validation failed for the dataset [Lund University Biological Museum - Insect collections Specimens](https://registry.gbif.org/dataset/b23c2479-214f-4160-9f98-bd3831ab131b):
- Crawler attempt: 5
- Publishing organization: [Lund University Biological Museum](https://registry.gbif.org/organization/c0758a16-296b-4ec3-97fd-8a057d9060f3)
- Publishing country: SWEDEN
- Installation: [IPT GBIF-Sweden](https://registry.gbif.org/installation/4346b227-ca68-4d54-8a77-909148492e0b)
- Number of occurrences indexed for this dataset at the time of the issue: 43398
- Cause: GBIF ID problems exceed 50% threshold: 83% duplicates; 252589 total records; 209166 absent records
- Pipelines execution steps: [http://api.gbif.org/v1/pipelines/history/execution/3595197/step](http://api.gbif.org/v1/pipelines/history/execution/3595197/step)

```
New IDs sample:

MZLU:Entomology:MZLU-ODON00005282
MZLU:Entomology:MZLU-DIPT00052145
MZLU:Entomology:MZLU-ODON00005283
MZLU:Entomology:MZLU-DIPT00052148
MZLU:Entomology:MZLU-00117658
MZLU:Entomology:MZLU-00117655
MZLU:Entomology:MZLU-HYM00026393
MZLU:Entomology:MZLU-ODON00005277
MZLU:Entomology:MZLU-ODON00005273
MZLU:Entomology:MZLU-00117648
```

```
Old IDs sample:

MZLU:Entomology:MZLU-00167963
MZLU:Entomology:MZLU-00167965
MZLU:Entomology:MZLU-00167966
MZLU:Entomology:MZLU-HEM00001859
MZLU:Entomology:MZLU-HYM00060938
MZLU:Entomology:MZLU-HYM00060983
MZLU:Entomology:MZLU-HYM00060985
MZLU:Entomology:MZLU-HYM00060987
MZLU:Entomology:MZLU-HYM00060990
MZLU:Entomology:MZLU-00181554
```

<details>
<summary>Publisher email</summary>

Hello,

I am contacting you from the GBIF Secretariat about a dataset published by the [Lund University Biological Museum - Insect collections Specimens](https://registry.gbif.org/dataset/b23c2479-214f-4160-9f98-bd3831ab131b) : https://doi.org/10.15468/hxfuwr.
We noticed that the occurrenceIDs were changed. We have temporarily paused the ingestions of this dataset.

As you might already know, when an occurrence record has a new occurrenceID for a given dataset, our system considers it to be a new occurrence.
This means that it will be given a new gbifid and a new occurrence URL (like this one: https://www.gbif.org/occurrence/1252968762) and the old gbifid and URL will be deprecated.

In this case, this means that the occurrence URLs would be deprecated when ingesting the newest versions of these datasets.

We would like to check with you if those changes were intentional. Do you know if this is the case?
Please let us know, thanks! We are happy to resume the dataset ingestion.

Note that some users rely on those occurrence URLs and gbifids (like https://bionomia.net for example). In an attempt to improve
the stability of the occurrence URLs and gbifids, we have implemented a warning system to detect these type of changes in datasets (see this news item).
If the data publisher can provide us with a list of old and new occurrenceIDs per record, we can avoid the identifier and URL changes. Could that be an option?

Please let us know if you have any question. Thanks!

All the best,

</details>

You can skip/fix identifier validation using [the registry UI](https://registry.gbif.org/dataset/b23c2479-214f-4160-9f98-bd3831ab131b/ingestion-history).

**Comment by jhnwllr** [comment]
These publishers seem to know what they are doing, so I am going to turn off checks for this dataset.
