### ISSUE TITLE
Identifiers validation failed for dataset Occurrence dataset of demersal fish and benthic organisms in the deep-sea off the northeastern coast of Japan, recorded by ROV after the 2011 Earthquake off the Pacific coast of Tohoku

### ISSUE THREAD

**Issue by gbif-pipelines** [gbif/ingestion-management#1030]
Identifier validation failed for the dataset [Occurrence dataset of demersal fish and benthic organisms in the deep-sea off the northeastern coast of Japan, recorded by ROV after the 2011 Earthquake off the Pacific coast of Tohoku](https://registry.gbif.org/dataset/6e885b85-394f-4733-af8b-0a8b6a24beba):
- Crawler attempt: 55
- Publishing organization: [National Museum of Nature and Science, Japan](https://registry.gbif.org/organization/4fd82480-ea1c-11da-8db4-b8a03c50a862)
- Publishing country: JAPAN
- Installation: [IPT Installation by National Museum of Nature and Science, Japan](https://registry.gbif.org/installation/82d6992a-b20b-4e74-b6ac-6b971b2c485d)
- Number of occurrences indexed for this dataset at the time of the issue: 22063
- Cause: GBIF ID problems exceed 50% threshold: 100% duplicates; 22063 total records; 22063 absent records
- Pipelines execution steps: [http://api.gbif.org/v1/pipelines/history/execution/3597158/step](http://api.gbif.org/v1/pipelines/history/execution/3597158/step)

```
New IDs sample:


```

```
Old IDs sample:

urn:catalog:JAMSTEC:teams_rov:004095
urn:catalog:JAMSTEC:teams_rov:004096
urn:catalog:JAMSTEC:teams_rov:004097
urn:catalog:JAMSTEC:teams_rov:004098
urn:catalog:JAMSTEC:teams_rov:004099
urn:catalog:JAMSTEC:teams_rov:004100
urn:catalog:JAMSTEC:teams_rov:004101
urn:catalog:JAMSTEC:teams_rov:004102
urn:catalog:JAMSTEC:teams_rov:004103
urn:catalog:JAMSTEC:teams_rov:004104
```

<details>
<summary>Publisher email</summary>

Hello,

I am contacting you from the GBIF Secretariat about a dataset published by the [Occurrence dataset of demersal fish and benthic organisms in the deep-sea off the northeastern coast of Japan, recorded by ROV after the 2011 Earthquake off the Pacific coast of Tohoku](https://registry.gbif.org/dataset/6e885b85-394f-4733-af8b-0a8b6a24beba) : https://doi.org/10.48518/00006.
We noticed that the occurrenceIDs were changed. We have temporarily paused the ingestions of this dataset.

As you might already know, when an occurrence record has a new occurrenceID for a given dataset, our system considers it to be a new occurrence.
This means that it will be given a new gbifid and a new occurrence URL (like this one: https://www.gbif.org/occurrence/1252968762) and the old gbifid and URL will be deprecated.

In this case, this means that the occurrence URLs would be deprecated when ingesting the newest versions of these datasets.

We would like to check with you if those changes were intentional. Do you know if this is the case?
Please let us know, thanks! We are happy to resume the dataset ingestion.

Note that some users rely on those occurrence URLs and gbifids (like https://bionomia.net for example). In an attempt to improve
the stability of the occurrence URLs and gbifids, we have implemented a warning system to detect these type of changes in datasets (see this news item).
If the data publisher can provide us with a list of old and new occurrenceIDs per record, we can avoid the identifier and URL changes. Could that be an option?

Please let us know if you have any question. Thanks!

All the best,

</details>

You can skip/fix identifier validation using [the registry UI](https://registry.gbif.org/dataset/6e885b85-394f-4733-af8b-0a8b6a24beba/ingestion-history).

**Comment by jhnwllr** [comment]
Hi @jhnwllr, <br> 				Could you take a look at this occurrenceId issue? <br> 				There are also other open issues similar to this one which can be found here : <br> 				[other issues](https://github.com/gbif/ingestion-management/issues?q=is%3Aissue+is%3Aopen+label%3A%22inst%3A+82d6992a-b20b-4e74-b6ac-6b971b2c485d%22)

**Comment by jhnwllr** [comment]
Hi @n_ktotsum, <br> 				Could you take a look at this occurrenceId issue? <br> 				There are also other open issues similar to this one which can be found here : <br> 				[other issues](https://github.com/gbif/ingestion-management/issues?q=is%3Aissue+is%3Aopen+label%3A%22inst%3A+82d6992a-b20b-4e74-b6ac-6b971b2c485d%22)

**Comment by jhnwllr** [comment]
Hi @ktotsum, <br> 				Could you take a look at this occurrenceId issue? <br> 				There are also other open issues similar to this one which can be found here : <br> 				[other issues](https://github.com/gbif/ingestion-management/issues?q=is%3Aissue+is%3Aopen+label%3A%22inst%3A+82d6992a-b20b-4e74-b6ac-6b971b2c485d%22)
