### ISSUE TITLE
Identifiers validation failed for dataset ArtenFinder

### ISSUE THREAD

**Issue by gbif-pipelines** [gbif/ingestion-management#1050]
Identifier validation failed for the dataset [ArtenFinder](https://registry.gbif.org/dataset/aa6c5ee6-d4d7-4a65-a04f-379cffbf4842):
- Crawler attempt: 288
- Publishing organization: [Stiftung Naturschutz Berlin](https://registry.gbif.org/organization/2754e9c0-0e43-4f65-968a-6f16b9c378ce)
- Publishing country: GERMANY
- Installation: [BioCASe installation Stiftung Naturschutz Berlin](https://registry.gbif.org/installation/dcceb601-2fb0-49dc-9cd2-7c00056f2b2c)
- Number of occurrences indexed for this dataset at the time of the issue: 264348
- Cause: GBIF ID problems exceed 50% threshold: 100% duplicates; 1000087 total records; 1000087 absent records
- Pipelines execution steps: [http://api.gbif.org/v1/pipelines/history/execution/3650414/step](http://api.gbif.org/v1/pipelines/history/execution/3650414/step)

```
New IDs sample:


```

```
Old IDs sample:


```

<details>
<summary>Publisher email</summary>

Hello,

I am contacting you from the GBIF Secretariat about a dataset published by the [ArtenFinder](https://registry.gbif.org/dataset/aa6c5ee6-d4d7-4a65-a04f-379cffbf4842) : https://doi.org/10.15468/jnnald.
We noticed that the occurrenceIDs were changed. We have temporarily paused the ingestions of this dataset.

As you might already know, when an occurrence record has a new occurrenceID for a given dataset, our system considers it to be a new occurrence.
This means that it will be given a new gbifid and a new occurrence URL (like this one: https://www.gbif.org/occurrence/1252968762) and the old gbifid and URL will be deprecated.

In this case, this means that the occurrence URLs would be deprecated when ingesting the newest versions of these datasets.

We would like to check with you if those changes were intentional. Do you know if this is the case?
Please let us know, thanks! We are happy to resume the dataset ingestion.

Note that some users rely on those occurrence URLs and gbifids (like https://bionomia.net for example). In an attempt to improve
the stability of the occurrence URLs and gbifids, we have implemented a warning system to detect these type of changes in datasets (see this news item).
If the data publisher can provide us with a list of old and new occurrenceIDs per record, we can avoid the identifier and URL changes. Could that be an option?

Please let us know if you have any question. Thanks!

All the best,

</details>

You can skip/fix identifier validation using [the registry UI](https://registry.gbif.org/dataset/aa6c5ee6-d4d7-4a65-a04f-379cffbf4842/ingestion-history).

**Comment by ManonGros** [comment]
The endpoint and source was changed.
