### ISSUE TITLE
Identifiers validation failed for dataset Mid-winter count of water birds and other bird species in Bulgaria

### ISSUE THREAD

**Issue by gbif-pipelines** [gbif/ingestion-management#1055]
Identifier validation failed for the dataset [Mid-winter count of water birds and other bird species in Bulgaria](https://registry.gbif.org/dataset/7683cc47-cb13-4bad-9614-387c66aa8df0):
- Crawler attempt: 3
- Publishing organization: [Bulgarian Society for the Protection of Birds](https://registry.gbif.org/organization/d1fec91e-5b53-4cff-9b31-10fed530a3c3)
- Publishing country: BULGARIA
- Installation: [GBIF Europe and Central Asia](https://registry.gbif.org/installation/17a83780-3060-4851-9d6f-029d5fcb81c9)
- Number of occurrences indexed for this dataset at the time of the issue: 0
- Cause: GBIF ID problems exceed 50% threshold: 100% duplicates; 131502 total records; 131502 absent records
- Pipelines execution steps: [http://api.gbif.org/v1/pipelines/history/execution/3659952/step](http://api.gbif.org/v1/pipelines/history/execution/3659952/step)

```
New IDs sample:


```

```
Old IDs sample:

https://smartbirds.org/monitoring/birds2138917
https://smartbirds.org/monitoring/birds2138918
https://smartbirds.org/monitoring/birds2138919
https://smartbirds.org/monitoring/birds2138920
https://smartbirds.org/monitoring/birds2138921
https://smartbirds.org/monitoring/birds2138922
https://smartbirds.org/monitoring/birds2138923
https://smartbirds.org/monitoring/birds2138924
https://smartbirds.org/monitoring/birds2138925
https://smartbirds.org/monitoring/birds2138926
```

<details>
<summary>Publisher email</summary>

Hello,

I am contacting you from the GBIF Secretariat about a dataset published by the [Mid-winter count of water birds and other bird species in Bulgaria](https://registry.gbif.org/dataset/7683cc47-cb13-4bad-9614-387c66aa8df0) : https://doi.org/10.15468/sg5qp9.
We noticed that the occurrenceIDs were changed. We have temporarily paused the ingestions of this dataset.

As you might already know, when an occurrence record has a new occurrenceID for a given dataset, our system considers it to be a new occurrence.
This means that it will be given a new gbifid and a new occurrence URL (like this one: https://www.gbif.org/occurrence/1252968762) and the old gbifid and URL will be deprecated.

In this case, this means that the occurrence URLs would be deprecated when ingesting the newest versions of these datasets.

We would like to check with you if those changes were intentional. Do you know if this is the case?
Please let us know, thanks! We are happy to resume the dataset ingestion.

Note that some users rely on those occurrence URLs and gbifids (like https://bionomia.net for example). In an attempt to improve
the stability of the occurrence URLs and gbifids, we have implemented a warning system to detect these type of changes in datasets (see this news item).
If the data publisher can provide us with a list of old and new occurrenceIDs per record, we can avoid the identifier and URL changes. Could that be an option?

Please let us know if you have any question. Thanks!

All the best,

</details>

You can skip/fix identifier validation using [the registry UI](https://registry.gbif.org/dataset/7683cc47-cb13-4bad-9614-387c66aa8df0/ingestion-history).

**Comment by ManonGros** [comment]
I contacted @spalp on Slack
