### ISSUE TITLE
Identifiers validation failed for dataset Mammal assemblages recorded by camera traps inside and outside the evacuation zone of the Fukushima Daiichi Nuclear Power Plant accident

### ISSUE THREAD

**Issue by gbif-pipelines** [gbif/ingestion-management#1057]
Identifier validation failed for the dataset [Mammal assemblages recorded by camera traps inside and outside the evacuation zone of the Fukushima Daiichi Nuclear Power Plant accident](https://registry.gbif.org/dataset/60807e2a-422e-48a4-b79d-eeb35820a8bb):
- Crawler attempt: 330
- Publishing organization: [National Institute of Genetics, ROIS](https://registry.gbif.org/organization/c3367060-856b-11d9-8486-b8a03c50a862)
- Publishing country: JAPAN
- Installation: [National Institute of Genetics, ROIS](https://registry.gbif.org/installation/8120860c-d51c-4f5f-b865-3c8e39eb6915)
- Number of occurrences indexed for this dataset at the time of the issue: 6860
- Cause: GBIF ID problems exceed 50% threshold: 71% duplicates; 23824 total records; 16972 absent records
- Pipelines execution steps: [http://api.gbif.org/v1/pipelines/history/execution/3663849/step](http://api.gbif.org/v1/pipelines/history/execution/3663849/step)

```
New IDs sample:

NIES:FukushimaMonitoringMammal:4652
NIES:FukushimaMonitoringMammal:6014
NIES:FukushimaMonitoringMammal:4689
NIES:FukushimaMonitoringMammal:6007
NIES:FukushimaMonitoringMammal:4658
NIES:FukushimaMonitoringMammal:6025
NIES:FukushimaMonitoringMammal:4655
NIES:FukushimaMonitoringMammal:5986
NIES:FukushimaMonitoringMammal:6008
NIES:FukushimaMonitoringMammal:6006
```

```
Old IDs sample:

NIES:FukushimaMonitoringMammal:5352
NIES:FukushimaMonitoringMammal:5404
NIES:FukushimaMonitoringMammal:5413
NIES:FukushimaMonitoringMammal:5444
NIES:FukushimaMonitoringMammal:5446
NIES:FukushimaMonitoringMammal:5467
NIES:FukushimaMonitoringMammal:5488
NIES:FukushimaMonitoringMammal:5500
NIES:FukushimaMonitoringMammal:5511
NIES:FukushimaMonitoringMammal:5533
```

<details>
<summary>Publisher email</summary>

Hello,

I am contacting you from the GBIF Secretariat about a dataset published by the [Mammal assemblages recorded by camera traps inside and outside the evacuation zone of the Fukushima Daiichi Nuclear Power Plant accident](https://registry.gbif.org/dataset/60807e2a-422e-48a4-b79d-eeb35820a8bb) : https://doi.org/10.1007/s11284-016-1366-7.
We noticed that the occurrenceIDs were changed. We have temporarily paused the ingestions of this dataset.

As you might already know, when an occurrence record has a new occurrenceID for a given dataset, our system considers it to be a new occurrence.
This means that it will be given a new gbifid and a new occurrence URL (like this one: https://www.gbif.org/occurrence/1252968762) and the old gbifid and URL will be deprecated.

In this case, this means that the occurrence URLs would be deprecated when ingesting the newest versions of these datasets.

We would like to check with you if those changes were intentional. Do you know if this is the case?
Please let us know, thanks! We are happy to resume the dataset ingestion.

Note that some users rely on those occurrence URLs and gbifids (like https://bionomia.net for example). In an attempt to improve
the stability of the occurrence URLs and gbifids, we have implemented a warning system to detect these type of changes in datasets (see this news item).
If the data publisher can provide us with a list of old and new occurrenceIDs per record, we can avoid the identifier and URL changes. Could that be an option?

Please let us know if you have any question. Thanks!

All the best,

</details>

You can skip/fix identifier validation using [the registry UI](https://registry.gbif.org/dataset/60807e2a-422e-48a4-b79d-eeb35820a8bb/ingestion-history).

**Comment by ktotsu** [comment]
This is due to the large change in record counts. Could you resume the ingestion? Thanks!

**Comment by ManonGros** [comment]
Thanks for letting us know @ktotsu ! We resumed the dataset ingestion.
