### ISSUE TITLE
Identifiers validation failed for dataset Cepario de Hongos Entomopatógenos

### ISSUE THREAD

**Issue by gbif-pipelines** [gbif/ingestion-management#1176]
Identifier validation failed for the dataset [Cepario de Hongos Entomopatógenos](https://registry.gbif.org/dataset/7769142c-903a-4648-8aa2-d7e8eaf394e8):
- Crawler attempt: 237
- Publishing organization: [Centro Nacional de Investigaciones del Café - Cenicafé](https://registry.gbif.org/organization/da583013-8a1b-4570-b0e4-c7cb25b2e7bf)
- Publishing country: COLOMBIA
- Installation: [Datos sobre Biodiversidad de Colombia](https://registry.gbif.org/installation/68845aab-a453-4816-b36d-a3ec8455deb0)
- Number of occurrences indexed for this dataset at the time of the issue: 4
- Cause: GBIF ID problems exceed 50% threshold: 100% duplicates; 6 total records; 6 absent records
- Pipelines execution steps: [http://api.gbif.org/v1/pipelines/history/execution/3705159/step](http://api.gbif.org/v1/pipelines/history/execution/3705159/step)

```
New IDs sample:


```

```
Old IDs sample:

CENICAFEColección de Microorganismos- CenicaféT1801
CENICAFEColección de Microorganismos- CenicaféBo1701
CENICAFEColección de Microorganismos- CenicaféT1802
CENICAFEColección de Microorganismos- CenicaféBb1701
```

<details>
<summary>Publisher email</summary>

Hello,

I am contacting you from the GBIF Secretariat about a dataset published by the [Cepario de Hongos Entomopatógenos](https://registry.gbif.org/dataset/7769142c-903a-4648-8aa2-d7e8eaf394e8) : https://doi.org/10.15472/n2egc4.
We noticed that the occurrenceIDs were changed. We have temporarily paused the ingestions of this dataset.

As you might already know, when an occurrence record has a new occurrenceID for a given dataset, our system considers it to be a new occurrence.
This means that it will be given a new gbifid and a new occurrence URL (like this one: https://www.gbif.org/occurrence/1252968762) and the old gbifid and URL will be deprecated.

In this case, this means that the occurrence URLs would be deprecated when ingesting the newest versions of these datasets.

We would like to check with you if those changes were intentional. Do you know if this is the case?
Please let us know, thanks! We are happy to resume the dataset ingestion.

Note that some users rely on those occurrence URLs and gbifids (like https://bionomia.net for example). In an attempt to improve
the stability of the occurrence URLs and gbifids, we have implemented a warning system to detect these type of changes in datasets (see this news item).
If the data publisher can provide us with a list of old and new occurrenceIDs per record, we can avoid the identifier and URL changes. Could that be an option?

Please let us know if you have any question. Thanks!

All the best,

</details>

You can skip/fix identifier validation using [the registry UI](https://registry.gbif.org/dataset/7769142c-903a-4648-8aa2-d7e8eaf394e8/ingestion-history).

**Comment by EstebanMH-SiB** [comment]
We did some small changes in an old occurrenceID with white spaces, here is the file to map the old and new occurrenceIDs
[ChangeOccurrenceID_Hongos_Cenicafe.txt](https://github.com/gbif/ingestion-management/files/14696407/ChangeOccurrenceID_Hongos_Cenicafe.txt)
