### ISSUE TITLE
Identifiers validation failed for dataset NCSM Non-molluscan Invertebrates Collection

### ISSUE THREAD

**Issue by gbif-pipelines** [gbif/ingestion-management#1179]
Identifier validation failed for the dataset [NCSM Non-molluscan Invertebrates Collection](https://registry.gbif.org/dataset/96cdea48-b78a-4345-ae6d-b2c7c6e0278a):
- Crawler attempt: 297
- Publishing organization: [North Carolina State Museum of Natural Sciences](https://registry.gbif.org/organization/69e7f900-ed5b-11dd-ac7e-b8a03c50a862)
- Publishing country: UNITED_STATES
- Installation: [IPT - Hosted by VertNet](https://registry.gbif.org/installation/a957a663-2f17-415f-b1c8-5cf6398df8ed)
- Number of occurrences indexed for this dataset at the time of the issue: 12497
- Cause: GBIF ID problems exceed 50% threshold: 100% duplicates; 31878 total records; 31878 absent records
- Pipelines execution steps: [http://api.gbif.org/v1/pipelines/history/execution/3721005/step](http://api.gbif.org/v1/pipelines/history/execution/3721005/step)

```
New IDs sample:


```

```
Old IDs sample:

7560E525-0E60-4A01-B2D7-1095AB301706
E844FB5C-8AA8-4F9C-B44C-2FD1A81A6FCD
C3B202C8-8D2F-4EE9-8EF4-B4142F2C78AA
DF437BA0-C7B6-4706-A344-8D24EA4F5FB1
B9E3D645-7661-4FAC-BD5E-5C16DAA7466C
9ED41CED-F1D7-43E8-8DE2-131ADCE64AD5
8A4315BE-AE7F-4533-BA97-9A30217F3B43
07C53B51-B5F5-47FA-8C7E-45DAE2FE2641
0C0774BC-9D4D-4C63-8ABE-9D832C36691A
0D631A71-C037-4F81-AEC4-1961E97D1416
```

<details>
<summary>Publisher email</summary>

Hello,

I am contacting you from the GBIF Secretariat about a dataset published by the [NCSM Non-molluscan Invertebrates Collection](https://registry.gbif.org/dataset/96cdea48-b78a-4345-ae6d-b2c7c6e0278a) : https://doi.org/10.36102/dwc.8.
We noticed that the occurrenceIDs were changed. We have temporarily paused the ingestions of this dataset.

As you might already know, when an occurrence record has a new occurrenceID for a given dataset, our system considers it to be a new occurrence.
This means that it will be given a new gbifid and a new occurrence URL (like this one: https://www.gbif.org/occurrence/1252968762) and the old gbifid and URL will be deprecated.

In this case, this means that the occurrence URLs would be deprecated when ingesting the newest versions of these datasets.

We would like to check with you if those changes were intentional. Do you know if this is the case?
Please let us know, thanks! We are happy to resume the dataset ingestion.

Note that some users rely on those occurrence URLs and gbifids (like https://bionomia.net for example). In an attempt to improve
the stability of the occurrence URLs and gbifids, we have implemented a warning system to detect these type of changes in datasets (see this news item).
If the data publisher can provide us with a list of old and new occurrenceIDs per record, we can avoid the identifier and URL changes. Could that be an option?

Please let us know if you have any question. Thanks!

All the best,

</details>

You can skip/fix identifier validation using [the registry UI](https://registry.gbif.org/dataset/96cdea48-b78a-4345-ae6d-b2c7c6e0278a/ingestion-history).

**Comment by gbif-pipelines** [comment]
Identifier validation still  failing for the dataset [NCSM Non-molluscan Invertebrates Collection](https://registry.gbif.org/dataset/96cdea48-b78a-4345-ae6d-b2c7c6e0278a):
- Crawler attempt: 298
- Publishing organization: [North Carolina State Museum of Natural Sciences](https://registry.gbif.org/organization/69e7f900-ed5b-11dd-ac7e-b8a03c50a862)
- Publishing country: UNITED_STATES
- Installation: [IPT - Hosted by VertNet](https://registry.gbif.org/installation/a957a663-2f17-415f-b1c8-5cf6398df8ed)
- Number of occurrences indexed for this dataset at the time of the issue: 12497
- Cause: GBIF ID problems exceed 50% threshold: 61% duplicates; 31878 total records; 19383 absent records
- Pipelines execution steps: [http://api.gbif.org/v1/pipelines/history/execution/3725297/step](http://api.gbif.org/v1/pipelines/history/execution/3725297/step)

```
New IDs sample:

cc9d651f-2f05-43bd-b3b6-bdb6dc1db12a
517b8bda-3b5e-4326-8a94-61b48b00a3ac
d07cfe9b-f70a-4b00-8b98-512f83b6ebb2
169119b0-0180-4bf0-ad5c-4216f15e55e9
ea8a83c9-afb2-4dc5-935e-184c5b932ec3
13781514-911e-44e4-ada7-d10d9068a95b
edfd42b9-7bd6-44e4-9963-7dcd5813cb14
5f86a85b-1bcb-4794-b146-8ddfd0865e3b
03eab738-daed-461b-93a4-7d096d0a9791
79011f54-ad74-4135-ac25-de5658d2907b
```


```
Old IDs sample:

7560E525-0E60-4A01-B2D7-1095AB301706
E844FB5C-8AA8-4F9C-B44C-2FD1A81A6FCD
C3B202C8-8D2F-4EE9-8EF4-B4142F2C78AA
DF437BA0-C7B6-4706-A344-8D24EA4F5FB1
B9E3D645-7661-4FAC-BD5E-5C16DAA7466C
9ED41CED-F1D7-43E8-8DE2-131ADCE64AD5
8A4315BE-AE7F-4533-BA97-9A30217F3B43
07C53B51-B5F5-47FA-8C7E-45DAE2FE2641
0C0774BC-9D4D-4C63-8ABE-9D832C36691A
0D631A71-C037-4F81-AEC4-1961E97D1416
```

<details>
<summary>Publisher email</summary>

Hello,

I am contacting you from the GBIF Secretariat about a dataset published by the [NCSM Non-molluscan Invertebrates Collection](https://registry.gbif.org/dataset/96cdea48-b78a-4345-ae6d-b2c7c6e0278a) : https://doi.org/10.36102/dwc.8.
We noticed that the occurrenceIDs were changed. We have temporarily paused the ingestions of this dataset.

As you might already know, when an occurrence record has a new occurrenceID for a given dataset, our system considers it to be a new occurrence.
This means that it will be given a new gbifid and a new occurrence URL (like this one: https://www.gbif.org/occurrence/1252968762) and the old gbifid and URL will be deprecated.

In this case, this means that the occurrence URLs would be deprecated when ingesting the newest versions of these datasets.

We would like to check with you if those changes were intentional. Do you know if this is the case?
Please let us know, thanks! We are happy to resume the dataset ingestion.

Note that some users rely on those occurrence URLs and gbifids (like https://bionomia.net for example). In an attempt to improve
the stability of the occurrence URLs and gbifids, we have implemented a warning system to detect these type of changes in datasets (see this news item).
If the data publisher can provide us with a list of old and new occurrenceIDs per record, we can avoid the identifier and URL changes. Could that be an option?

Please let us know if you have any question. Thanks!

All the best,

</details>


You can skip/fix identifier validation using [the registry UI](https://registry.gbif.org/dataset/96cdea48-b78a-4345-ae6d-b2c7c6e0278a/ingestion-history).

**Comment by ManonGros** [comment]
The IPT administrator contacted us. The dataset contained the mapping of old to new identifiers in the resourceRelationship extension. I migrated the identifier. The dataset got stopped again but this time because of the huge number of records added. I resumed the dataset ingestion.
