### ISSUE TITLE
Identifiers validation failed for dataset Biodiversity data of the Banc D'Arguin National Park. Information for education, conservation and management.

### ISSUE THREAD

**Issue by gbif-pipelines** [gbif/ingestion-management#1186]
Identifier validation failed for the dataset [Biodiversity data of the Banc D'Arguin National Park. Information for education, conservation and management.](https://registry.gbif.org/dataset/e5c183ea-9aab-4fd1-a07b-3fbe18fcbe4c):
- Crawler attempt: 25
- Publishing organization: [OBIS Secretariat](https://registry.gbif.org/organization/b94c4428-77c1-47e0-a8c2-2b08228d8dd8)
- Publishing country: BELGIUM
- Installation: [OBIS Secretariat](https://registry.gbif.org/installation/abb56026-1a4c-4ae8-b376-397c06871d89)
- Number of occurrences indexed for this dataset at the time of the issue: 2298
- Cause: GBIF ID problems exceed 50% threshold: 84% duplicates; 3100 total records; 2618 absent records
- Pipelines execution steps: [http://api.gbif.org/v1/pipelines/history/execution/3739951/step](http://api.gbif.org/v1/pipelines/history/execution/3739951/step)

```
New IDs sample:

banc-darguin-ccmar-2023:occurrence:9f241b2ebd2b7ad36ac296d4ee9131e2
banc-darguin-ccmar-2023:occurrence:7cdcc81de0f367f313f1b500d2c4cc85
banc-darguin-ccmar-2023:occurrence:3138e5f5cf7a5ef5311530d88cf2120e
banc-darguin-ccmar-2023:occurrence:f9f738dc0e04c768df652bda392cdfc3
banc-darguin-ccmar-2023:occurrence:36a2d6d1640afc8e46672ba705ced4be
banc-darguin-ccmar-2023:occurrence:8d48e5679e36823d751d7382ca8a3028
banc-darguin-ccmar-2023:occurrence:0b232773c8b45b01b6c71f635582f3fd
banc-darguin-ccmar-2023:occurrence:21ebb211a2c204c7454e593197fadb5a
banc-darguin-ccmar-2023:occurrence:75c587fc9fb4e4d65f18faaa237228c7
banc-darguin-ccmar-2023:occurrence:154a4b76d63c094afa7208609a9dd13f
```

```
Old IDs sample:

banc-darguin-ccmar-2023:occurrence:092aa857d484b9b45f7c29863c38a6ea
banc-darguin-ccmar-2023:occurrence:0eedecc6f5eb68b8654a31d8312c04b8
banc-darguin-ccmar-2023:occurrence:123d3ed4905f759d684debe2a83b092b
banc-darguin-ccmar-2023:occurrence:1bc119268874e8fb8523ff6380d868fc
banc-darguin-ccmar-2023:occurrence:2428700722e017722e9464e2bc1a565b
banc-darguin-ccmar-2023:occurrence:27a2613cc37091376a877547d2f2de63
banc-darguin-ccmar-2023:occurrence:3c3ae8117357674057f623a8475779a5
banc-darguin-ccmar-2023:occurrence:3f387c2835ca21b715fa3e527a4843dc
banc-darguin-ccmar-2023:occurrence:471c972d40ff1df85053146c5c5061b4
banc-darguin-ccmar-2023:occurrence:48e0a3cd720cddc9be7031c112182cb3
```

<details>
<summary>Publisher email</summary>

Hello,

I am contacting you from the GBIF Secretariat about a dataset published by the [Biodiversity data of the Banc D'Arguin National Park. Information for education, conservation and management.](https://registry.gbif.org/dataset/e5c183ea-9aab-4fd1-a07b-3fbe18fcbe4c) : https://doi.org/10.25607/krhjji.
We noticed that the occurrenceIDs were changed. We have temporarily paused the ingestions of this dataset.

As you might already know, when an occurrence record has a new occurrenceID for a given dataset, our system considers it to be a new occurrence.
This means that it will be given a new gbifid and a new occurrence URL (like this one: https://www.gbif.org/occurrence/1252968762) and the old gbifid and URL will be deprecated.

In this case, this means that the occurrence URLs would be deprecated when ingesting the newest versions of these datasets.

We would like to check with you if those changes were intentional. Do you know if this is the case?
Please let us know, thanks! We are happy to resume the dataset ingestion.

Note that some users rely on those occurrence URLs and gbifids (like https://bionomia.net for example). In an attempt to improve
the stability of the occurrence URLs and gbifids, we have implemented a warning system to detect these type of changes in datasets (see this news item).
If the data publisher can provide us with a list of old and new occurrenceIDs per record, we can avoid the identifier and URL changes. Could that be an option?

Please let us know if you have any question. Thanks!

All the best,

</details>

You can skip/fix identifier validation using [the registry UI](https://registry.gbif.org/dataset/e5c183ea-9aab-4fd1-a07b-3fbe18fcbe4c/ingestion-history).

**Comment by gbif-pipelines** [comment]
Identifier validation still  failing for the dataset [Biodiversity data of the Banc D'Arguin National Park. Information for education, conservation and management.](https://registry.gbif.org/dataset/e5c183ea-9aab-4fd1-a07b-3fbe18fcbe4c):
- Crawler attempt: 26
- Publishing organization: [OBIS Secretariat](https://registry.gbif.org/organization/b94c4428-77c1-47e0-a8c2-2b08228d8dd8)
- Publishing country: BELGIUM
- Installation: [OBIS Secretariat](https://registry.gbif.org/installation/abb56026-1a4c-4ae8-b376-397c06871d89)
- Number of occurrences indexed for this dataset at the time of the issue: 2298
- Cause: GBIF ID problems exceed 50% threshold: 84% duplicates; 3100 total records; 2618 absent records
- Pipelines execution steps: [http://api.gbif.org/v1/pipelines/history/execution/3739954/step](http://api.gbif.org/v1/pipelines/history/execution/3739954/step)

```
New IDs sample:

banc-darguin-ccmar-2023:occurrence:9f241b2ebd2b7ad36ac296d4ee9131e2
banc-darguin-ccmar-2023:occurrence:7cdcc81de0f367f313f1b500d2c4cc85
banc-darguin-ccmar-2023:occurrence:3138e5f5cf7a5ef5311530d88cf2120e
banc-darguin-ccmar-2023:occurrence:f9f738dc0e04c768df652bda392cdfc3
banc-darguin-ccmar-2023:occurrence:36a2d6d1640afc8e46672ba705ced4be
banc-darguin-ccmar-2023:occurrence:8d48e5679e36823d751d7382ca8a3028
banc-darguin-ccmar-2023:occurrence:0b232773c8b45b01b6c71f635582f3fd
banc-darguin-ccmar-2023:occurrence:75c587fc9fb4e4d65f18faaa237228c7
banc-darguin-ccmar-2023:occurrence:21ebb211a2c204c7454e593197fadb5a
banc-darguin-ccmar-2023:occurrence:154a4b76d63c094afa7208609a9dd13f
```


```
Old IDs sample:

banc-darguin-ccmar-2023:occurrence:092aa857d484b9b45f7c29863c38a6ea
banc-darguin-ccmar-2023:occurrence:0eedecc6f5eb68b8654a31d8312c04b8
banc-darguin-ccmar-2023:occurrence:123d3ed4905f759d684debe2a83b092b
banc-darguin-ccmar-2023:occurrence:1bc119268874e8fb8523ff6380d868fc
banc-darguin-ccmar-2023:occurrence:2428700722e017722e9464e2bc1a565b
banc-darguin-ccmar-2023:occurrence:27a2613cc37091376a877547d2f2de63
banc-darguin-ccmar-2023:occurrence:3c3ae8117357674057f623a8475779a5
banc-darguin-ccmar-2023:occurrence:3f387c2835ca21b715fa3e527a4843dc
banc-darguin-ccmar-2023:occurrence:471c972d40ff1df85053146c5c5061b4
banc-darguin-ccmar-2023:occurrence:48e0a3cd720cddc9be7031c112182cb3
```

<details>
<summary>Publisher email</summary>

Hello,

I am contacting you from the GBIF Secretariat about a dataset published by the [Biodiversity data of the Banc D'Arguin National Park. Information for education, conservation and management.](https://registry.gbif.org/dataset/e5c183ea-9aab-4fd1-a07b-3fbe18fcbe4c) : https://doi.org/10.25607/krhjji.
We noticed that the occurrenceIDs were changed. We have temporarily paused the ingestions of this dataset.

As you might already know, when an occurrence record has a new occurrenceID for a given dataset, our system considers it to be a new occurrence.
This means that it will be given a new gbifid and a new occurrence URL (like this one: https://www.gbif.org/occurrence/1252968762) and the old gbifid and URL will be deprecated.

In this case, this means that the occurrence URLs would be deprecated when ingesting the newest versions of these datasets.

We would like to check with you if those changes were intentional. Do you know if this is the case?
Please let us know, thanks! We are happy to resume the dataset ingestion.

Note that some users rely on those occurrence URLs and gbifids (like https://bionomia.net for example). In an attempt to improve
the stability of the occurrence URLs and gbifids, we have implemented a warning system to detect these type of changes in datasets (see this news item).
If the data publisher can provide us with a list of old and new occurrenceIDs per record, we can avoid the identifier and URL changes. Could that be an option?

Please let us know if you have any question. Thanks!

All the best,

</details>


You can skip/fix identifier validation using [the registry UI](https://registry.gbif.org/dataset/e5c183ea-9aab-4fd1-a07b-3fbe18fcbe4c/ingestion-history).

**Comment by jhnwllr** [comment]
https://registry.gbif.org/dataset/e5c183ea-9aab-4fd1-a07b-3fbe18fcbe4c/machineTag
This dataset has a disabled ingestion management machineTag, so I am not sure why it's here...
