### ISSUE TITLE
Identifiers validation failed for dataset Magnoliophyta del Herbario BAB (Instituto de Recursos Biológicos CIRN-INTA)

### ISSUE THREAD

**Issue by gbif-pipelines** [gbif/ingestion-management#12]
Identifier validation failed for the dataset [Magnoliophyta del Herbario BAB (Instituto de Recursos Biológicos CIRN-INTA)](https://registry.gbif.org/dataset/14bda39a-de67-4504-b1e3-883d7ed118d6):
- Crawler attempt: 148
- Publishing organization: [Herbario BAB, Instituto de Recursos Biológicos-INTA](https://registry.gbif.org/organization/4c43ef1b-b005-4ed5-840b-7886d53fb069)
- Publishing country: ARGENTINA
- Installation: [Ministerio de Ciencia, Tecnología e Innovación Productiva IPT](https://registry.gbif.org/installation/4fd221cd-129c-404f-ab62-fdd2377d12ac)
- Number of occurrences indexed for this dataset at the time of the issue: 2113
- Cause: GBIF IDs hit maximum allowed - 50%, duplicates - 100%, total records count 3058, absent records count 3058
- Step metrics: 
```

```

- Pipelines execution steps: [http://api.gbif.org/v1/pipelines/history/execution/3039743/step](http://api.gbif.org/v1/pipelines/history/execution/3039743/step)
<details>
<summary>Publisher email</summary>

Hello,

I am contacting you from the GBIF Secretariat about a dataset published by the [Magnoliophyta del Herbario BAB (Instituto de Recursos Biológicos CIRN-INTA)](https://registry.gbif.org/dataset/14bda39a-de67-4504-b1e3-883d7ed118d6) : https://doi.org/10.15468/bsj52c.
We noticed that the occurrenceIDs were changed. We have temporarily paused the ingestions of this dataset.

As you might already know, when an occurrence record has a new occurrenceID for a given dataset, our system considers it to be a new occurrence.
This means that it will be given a new gbifid and a new occurrence URL (like this one: https://www.gbif.org/occurrence/1252968762) and the old gbifid and URL will be deprecated.

In this case, this means that the occurrence URLs would be deprecated when ingesting the newest versions of these datasets.

We would like to check with you if those changes were intentional. Do you know if this is the case?
Please let us know, thanks! We are happy to resume the dataset ingestion.

Note that some users rely on those occurrence URLs and gbifids (like https://bionomia.net for example). In an attempt to improve
the stability of the occurrence URLs and gbifids, we have implemented a warning system to detect these type of changes in datasets (see this news item).
If the data publisher can provide us with a list of old and new occurrenceIDs per record, we can avoid the identifier and URL changes. Could that be an option?

Please let us know if you have any question. Thanks!

All the best,

</details>

You can skip/fix identifier validation using [the registry UI](https://registry.gbif.org/dataset/14bda39a-de67-4504-b1e3-883d7ed118d6/ingestion-history).

**Comment by jhnwllr** [comment]
contacted 05-23-2023

**Comment by gbif-pipelines** [comment]
Identifier validation still  failing for the dataset [Magnoliophyta del Herbario BAB (Instituto de Recursos Biológicos CIRN-INTA)](https://registry.gbif.org/dataset/14bda39a-de67-4504-b1e3-883d7ed118d6):
- Crawler attempt: 149
- Publishing organization: [Herbario BAB, Instituto de Recursos Biológicos-INTA](https://registry.gbif.org/organization/4c43ef1b-b005-4ed5-840b-7886d53fb069)
- Publishing country: ARGENTINA
- Installation: [Ministerio de Ciencia, Tecnología e Innovación Productiva IPT](https://registry.gbif.org/installation/4fd221cd-129c-404f-ab62-fdd2377d12ac)
- Number of occurrences indexed for this dataset at the time of the issue: 2113
- Cause: GBIF IDs hit maximum allowed - 50%, duplicates - 100%, total records count 3058, absent records count 3058
- Step metrics: 
```

```

- Pipelines execution steps: [http://api.gbif.org/v1/pipelines/history/execution/3052059/step](http://api.gbif.org/v1/pipelines/history/execution/3052059/step)
<details>
<summary>Publisher email</summary>

Hello,

I am contacting you from the GBIF Secretariat about a dataset published by the [Magnoliophyta del Herbario BAB (Instituto de Recursos Biológicos CIRN-INTA)](https://registry.gbif.org/dataset/14bda39a-de67-4504-b1e3-883d7ed118d6) : https://doi.org/10.15468/bsj52c.
We noticed that the occurrenceIDs were changed. We have temporarily paused the ingestions of this dataset.

As you might already know, when an occurrence record has a new occurrenceID for a given dataset, our system considers it to be a new occurrence.
This means that it will be given a new gbifid and a new occurrence URL (like this one: https://www.gbif.org/occurrence/1252968762) and the old gbifid and URL will be deprecated.

In this case, this means that the occurrence URLs would be deprecated when ingesting the newest versions of these datasets.

We would like to check with you if those changes were intentional. Do you know if this is the case?
Please let us know, thanks! We are happy to resume the dataset ingestion.

Note that some users rely on those occurrence URLs and gbifids (like https://bionomia.net for example). In an attempt to improve
the stability of the occurrence URLs and gbifids, we have implemented a warning system to detect these type of changes in datasets (see this news item).
If the data publisher can provide us with a list of old and new occurrenceIDs per record, we can avoid the identifier and URL changes. Could that be an option?

Please let us know if you have any question. Thanks!

All the best,

</details>


You can skip/fix identifier validation using [the registry UI](https://registry.gbif.org/dataset/14bda39a-de67-4504-b1e3-883d7ed118d6/ingestion-history).

**Comment by gbif-pipelines** [comment]
Identifier validation still  failing for the dataset [Magnoliophyta del Herbario BAB (Instituto de Recursos Biológicos CIRN-INTA)](https://registry.gbif.org/dataset/14bda39a-de67-4504-b1e3-883d7ed118d6):
- Crawler attempt: 150
- Publishing organization: [Herbario BAB, Instituto de Recursos Biológicos-INTA](https://registry.gbif.org/organization/4c43ef1b-b005-4ed5-840b-7886d53fb069)
- Publishing country: ARGENTINA
- Installation: [Ministerio de Ciencia, Tecnología e Innovación Productiva IPT](https://registry.gbif.org/installation/4fd221cd-129c-404f-ab62-fdd2377d12ac)
- Number of occurrences indexed for this dataset at the time of the issue: 2113
- Cause: GBIF IDs hit maximum allowed - 50%, duplicates - 100%, total records count 3058, absent records count 3058
- Pipelines execution steps: [http://api.gbif.org/v1/pipelines/history/execution/3061648/step](http://api.gbif.org/v1/pipelines/history/execution/3061648/step)
<details>
<summary>Publisher email</summary>

Hello,

I am contacting you from the GBIF Secretariat about a dataset published by the [Magnoliophyta del Herbario BAB (Instituto de Recursos Biológicos CIRN-INTA)](https://registry.gbif.org/dataset/14bda39a-de67-4504-b1e3-883d7ed118d6) : https://doi.org/10.15468/bsj52c.
We noticed that the occurrenceIDs were changed. We have temporarily paused the ingestions of this dataset.

As you might already know, when an occurrence record has a new occurrenceID for a given dataset, our system considers it to be a new occurrence.
This means that it will be given a new gbifid and a new occurrence URL (like this one: https://www.gbif.org/occurrence/1252968762) and the old gbifid and URL will be deprecated.

In this case, this means that the occurrence URLs would be deprecated when ingesting the newest versions of these datasets.

We would like to check with you if those changes were intentional. Do you know if this is the case?
Please let us know, thanks! We are happy to resume the dataset ingestion.

Note that some users rely on those occurrence URLs and gbifids (like https://bionomia.net for example). In an attempt to improve
the stability of the occurrence URLs and gbifids, we have implemented a warning system to detect these type of changes in datasets (see this news item).
If the data publisher can provide us with a list of old and new occurrenceIDs per record, we can avoid the identifier and URL changes. Could that be an option?

Please let us know if you have any question. Thanks!

All the best,

</details>


You can skip/fix identifier validation using [the registry UI](https://registry.gbif.org/dataset/14bda39a-de67-4504-b1e3-883d7ed118d6/ingestion-history).

**Comment by gbif-pipelines** [comment]
Identifier validation still  failing for the dataset [Magnoliophyta del Herbario BAB (Instituto de Recursos Biológicos CIRN-INTA)](https://registry.gbif.org/dataset/14bda39a-de67-4504-b1e3-883d7ed118d6):
- Crawler attempt: 154
- Publishing organization: [Herbario BAB, Instituto de Recursos Biológicos-INTA](https://registry.gbif.org/organization/4c43ef1b-b005-4ed5-840b-7886d53fb069)
- Publishing country: ARGENTINA
- Installation: [Ministerio de Ciencia, Tecnología e Innovación Productiva IPT](https://registry.gbif.org/installation/4fd221cd-129c-404f-ab62-fdd2377d12ac)
- Number of occurrences indexed for this dataset at the time of the issue: 2113
- Cause: GBIF IDs hit maximum allowed - 50%, duplicates - 100%, total records count 3058, absent records count 3058
- Pipelines execution steps: [http://api.gbif.org/v1/pipelines/history/execution/3105241/step](http://api.gbif.org/v1/pipelines/history/execution/3105241/step)
<details>
<summary>Publisher email</summary>

Hello,

I am contacting you from the GBIF Secretariat about a dataset published by the [Magnoliophyta del Herbario BAB (Instituto de Recursos Biológicos CIRN-INTA)](https://registry.gbif.org/dataset/14bda39a-de67-4504-b1e3-883d7ed118d6) : https://doi.org/10.15468/bsj52c.
We noticed that the occurrenceIDs were changed. We have temporarily paused the ingestions of this dataset.

As you might already know, when an occurrence record has a new occurrenceID for a given dataset, our system considers it to be a new occurrence.
This means that it will be given a new gbifid and a new occurrence URL (like this one: https://www.gbif.org/occurrence/1252968762) and the old gbifid and URL will be deprecated.

In this case, this means that the occurrence URLs would be deprecated when ingesting the newest versions of these datasets.

We would like to check with you if those changes were intentional. Do you know if this is the case?
Please let us know, thanks! We are happy to resume the dataset ingestion.

Note that some users rely on those occurrence URLs and gbifids (like https://bionomia.net for example). In an attempt to improve
the stability of the occurrence URLs and gbifids, we have implemented a warning system to detect these type of changes in datasets (see this news item).
If the data publisher can provide us with a list of old and new occurrenceIDs per record, we can avoid the identifier and URL changes. Could that be an option?

Please let us know if you have any question. Thanks!

All the best,

</details>


You can skip/fix identifier validation using [the registry UI](https://registry.gbif.org/dataset/14bda39a-de67-4504-b1e3-883d7ed118d6/ingestion-history).

**Comment by gbif-pipelines** [comment]
Identifier validation still  failing for the dataset [Magnoliophyta del Herbario BAB (Instituto de Recursos Biológicos CIRN-INTA)](https://registry.gbif.org/dataset/14bda39a-de67-4504-b1e3-883d7ed118d6):
- Crawler attempt: 156
- Publishing organization: [Herbario BAB, Instituto de Recursos Biológicos-INTA](https://registry.gbif.org/organization/4c43ef1b-b005-4ed5-840b-7886d53fb069)
- Publishing country: ARGENTINA
- Installation: [Ministerio de Ciencia, Tecnología e Innovación Productiva IPT](https://registry.gbif.org/installation/4fd221cd-129c-404f-ab62-fdd2377d12ac)
- Number of occurrences indexed for this dataset at the time of the issue: 2113
- Cause: GBIF ID problems exceed 50% threshold: 100% duplicates; 3058 total records; 3058 absent records
- Pipelines execution steps: [http://api.gbif.org/v1/pipelines/history/execution/3192984/step](http://api.gbif.org/v1/pipelines/history/execution/3192984/step)
<details>
<summary>Publisher email</summary>

Hello,

I am contacting you from the GBIF Secretariat about a dataset published by the [Magnoliophyta del Herbario BAB (Instituto de Recursos Biológicos CIRN-INTA)](https://registry.gbif.org/dataset/14bda39a-de67-4504-b1e3-883d7ed118d6) : https://doi.org/10.15468/bsj52c.
We noticed that the occurrenceIDs were changed. We have temporarily paused the ingestions of this dataset.

As you might already know, when an occurrence record has a new occurrenceID for a given dataset, our system considers it to be a new occurrence.
This means that it will be given a new gbifid and a new occurrence URL (like this one: https://www.gbif.org/occurrence/1252968762) and the old gbifid and URL will be deprecated.

In this case, this means that the occurrence URLs would be deprecated when ingesting the newest versions of these datasets.

We would like to check with you if those changes were intentional. Do you know if this is the case?
Please let us know, thanks! We are happy to resume the dataset ingestion.

Note that some users rely on those occurrence URLs and gbifids (like https://bionomia.net for example). In an attempt to improve
the stability of the occurrence URLs and gbifids, we have implemented a warning system to detect these type of changes in datasets (see this news item).
If the data publisher can provide us with a list of old and new occurrenceIDs per record, we can avoid the identifier and URL changes. Could that be an option?

Please let us know if you have any question. Thanks!

All the best,

</details>


You can skip/fix identifier validation using [the registry UI](https://registry.gbif.org/dataset/14bda39a-de67-4504-b1e3-883d7ed118d6/ingestion-history).

**Comment by jhnwllr** [comment]
Closing because of no response from publisher.
