### ISSUE TITLE
Identifiers validation failed for dataset Taxonomy and geography of species of the genus Parrya in the flora of Uzbekistan

### ISSUE THREAD

**Issue by gbif-pipelines** [gbif/ingestion-management#1362]
Identifier validation failed for the dataset [Taxonomy and geography of species of the genus Parrya in the flora of Uzbekistan](https://registry.gbif.org/dataset/751005ce-d8f1-402e-8845-d3eb9b82be80):
- Crawler attempt: 32
- Publishing organization: [Institute of Botany of the Academy of Sciences of the Republic of Uzbekistan](https://registry.gbif.org/organization/e605f64f-2091-41b6-92d4-8c71008de217)
- Publishing country: UZBEKISTAN
- Installation: [Uzbekistan IPT](https://registry.gbif.org/installation/ecf8b170-4886-49fd-be0c-89c4c5ce6a6e)
- Number of occurrences indexed for this dataset at the time of the issue: 401
- Cause: GBIF ID problems exceed 50% threshold: 100% duplicates; 401 total records; 401 absent records
- Pipelines execution steps: [http://api.gbif.org/v1/pipelines/history/execution/3754302/step](http://api.gbif.org/v1/pipelines/history/execution/3754302/step)

```
New IDs sample:


```

```
Old IDs sample:

103
104
105
106
107
108
109
110
111
112
```

<details>
<summary>Publisher email</summary>

Hello,

I am contacting you from the GBIF Secretariat about a dataset published by the [Taxonomy and geography of species of the genus Parrya in the flora of Uzbekistan](https://registry.gbif.org/dataset/751005ce-d8f1-402e-8845-d3eb9b82be80) : https://doi.org/10.15468/6kfxuc.
We noticed that the occurrenceIDs were changed. We have temporarily paused the ingestions of this dataset.

As you might already know, when an occurrence record has a new occurrenceID for a given dataset, our system considers it to be a new occurrence.
This means that it will be given a new gbifid and a new occurrence URL (like this one: https://www.gbif.org/occurrence/1252968762) and the old gbifid and URL will be deprecated.

In this case, this means that the occurrence URLs would be deprecated when ingesting the newest versions of these datasets.

We would like to check with you if those changes were intentional. Do you know if this is the case?
Please let us know, thanks! We are happy to resume the dataset ingestion.

Note that some users rely on those occurrence URLs and gbifids (like https://bionomia.net for example). In an attempt to improve
the stability of the occurrence URLs and gbifids, we have implemented a warning system to detect these type of changes in datasets (see this news item).
If the data publisher can provide us with a list of old and new occurrenceIDs per record, we can avoid the identifier and URL changes. Could that be an option?

Please let us know if you have any question. Thanks!

All the best,

</details>

You can skip/fix identifier validation using [the registry UI](https://registry.gbif.org/dataset/751005ce-d8f1-402e-8845-d3eb9b82be80/ingestion-history).

**Comment by gbif-pipelines** [comment]
Identifier validation still  failing for the dataset [Taxonomy and geography of species of the genus Parrya in the flora of Uzbekistan](https://registry.gbif.org/dataset/751005ce-d8f1-402e-8845-d3eb9b82be80):
- Crawler attempt: 33
- Publishing organization: [Institute of Botany of the Academy of Sciences of the Republic of Uzbekistan](https://registry.gbif.org/organization/e605f64f-2091-41b6-92d4-8c71008de217)
- Publishing country: UZBEKISTAN
- Installation: [Uzbekistan IPT](https://registry.gbif.org/installation/ecf8b170-4886-49fd-be0c-89c4c5ce6a6e)
- Number of occurrences indexed for this dataset at the time of the issue: 401
- Cause: GBIF ID problems exceed 50% threshold: 100% duplicates; 401 total records; 401 absent records
- Pipelines execution steps: [http://api.gbif.org/v1/pipelines/history/execution/3756836/step](http://api.gbif.org/v1/pipelines/history/execution/3756836/step)

```
New IDs sample:


```


```
Old IDs sample:

103
104
105
106
107
108
109
110
111
112
```

<details>
<summary>Publisher email</summary>

Hello,

I am contacting you from the GBIF Secretariat about a dataset published by the [Taxonomy and geography of species of the genus Parrya in the flora of Uzbekistan](https://registry.gbif.org/dataset/751005ce-d8f1-402e-8845-d3eb9b82be80) : https://doi.org/10.15468/6kfxuc.
We noticed that the occurrenceIDs were changed. We have temporarily paused the ingestions of this dataset.

As you might already know, when an occurrence record has a new occurrenceID for a given dataset, our system considers it to be a new occurrence.
This means that it will be given a new gbifid and a new occurrence URL (like this one: https://www.gbif.org/occurrence/1252968762) and the old gbifid and URL will be deprecated.

In this case, this means that the occurrence URLs would be deprecated when ingesting the newest versions of these datasets.

We would like to check with you if those changes were intentional. Do you know if this is the case?
Please let us know, thanks! We are happy to resume the dataset ingestion.

Note that some users rely on those occurrence URLs and gbifids (like https://bionomia.net for example). In an attempt to improve
the stability of the occurrence URLs and gbifids, we have implemented a warning system to detect these type of changes in datasets (see this news item).
If the data publisher can provide us with a list of old and new occurrenceIDs per record, we can avoid the identifier and URL changes. Could that be an option?

Please let us know if you have any question. Thanks!

All the best,

</details>


You can skip/fix identifier validation using [the registry UI](https://registry.gbif.org/dataset/751005ce-d8f1-402e-8845-d3eb9b82be80/ingestion-history).

**Comment by gbif-pipelines** [comment]
Identifier validation still  failing for the dataset [Taxonomy and geography of species of the genus Parrya in the flora of Uzbekistan](https://registry.gbif.org/dataset/751005ce-d8f1-402e-8845-d3eb9b82be80):
- Crawler attempt: 34
- Publishing organization: [Institute of Botany of the Academy of Sciences of the Republic of Uzbekistan](https://registry.gbif.org/organization/e605f64f-2091-41b6-92d4-8c71008de217)
- Publishing country: UZBEKISTAN
- Installation: [Uzbekistan IPT](https://registry.gbif.org/installation/ecf8b170-4886-49fd-be0c-89c4c5ce6a6e)
- Number of occurrences indexed for this dataset at the time of the issue: 401
- Cause: GBIF ID problems exceed 50% threshold: 100% duplicates; 401 total records; 401 absent records
- Pipelines execution steps: [http://api.gbif.org/v1/pipelines/history/execution/3756868/step](http://api.gbif.org/v1/pipelines/history/execution/3756868/step)

```
New IDs sample:


```


```
Old IDs sample:

103
104
105
106
107
108
109
110
111
112
```

<details>
<summary>Publisher email</summary>

Hello,

I am contacting you from the GBIF Secretariat about a dataset published by the [Taxonomy and geography of species of the genus Parrya in the flora of Uzbekistan](https://registry.gbif.org/dataset/751005ce-d8f1-402e-8845-d3eb9b82be80) : https://doi.org/10.15468/6kfxuc.
We noticed that the occurrenceIDs were changed. We have temporarily paused the ingestions of this dataset.

As you might already know, when an occurrence record has a new occurrenceID for a given dataset, our system considers it to be a new occurrence.
This means that it will be given a new gbifid and a new occurrence URL (like this one: https://www.gbif.org/occurrence/1252968762) and the old gbifid and URL will be deprecated.

In this case, this means that the occurrence URLs would be deprecated when ingesting the newest versions of these datasets.

We would like to check with you if those changes were intentional. Do you know if this is the case?
Please let us know, thanks! We are happy to resume the dataset ingestion.

Note that some users rely on those occurrence URLs and gbifids (like https://bionomia.net for example). In an attempt to improve
the stability of the occurrence URLs and gbifids, we have implemented a warning system to detect these type of changes in datasets (see this news item).
If the data publisher can provide us with a list of old and new occurrenceIDs per record, we can avoid the identifier and URL changes. Could that be an option?

Please let us know if you have any question. Thanks!

All the best,

</details>


You can skip/fix identifier validation using [the registry UI](https://registry.gbif.org/dataset/751005ce-d8f1-402e-8845-d3eb9b82be80/ingestion-history).

**Comment by aliyevakumush77** [comment]
Hello, dear GBIF helpdesk, 
I am a publisher of the Institute of Botany of the Academy of Sciences of the Republic of Uzbekistan. I published the dataset, and I tried to prepare a list of the relationships between the old occurrenceIDs and the new occurrenceIDs for migrating GBIF identifiers.
[parrya.txt](https://github.com/gbif/ingestion-management/files/15011684/parrya.txt)
Please help me deal with the identifier issues.
Kumush

**Comment by gbif-pipelines** [comment]
Identifier validation still  failing for the dataset [Taxonomy and geography of species of the genus Parrya in the flora of Uzbekistan](https://registry.gbif.org/dataset/751005ce-d8f1-402e-8845-d3eb9b82be80):
- Crawler attempt: 35
- Publishing organization: [Institute of Botany of the Academy of Sciences of the Republic of Uzbekistan](https://registry.gbif.org/organization/e605f64f-2091-41b6-92d4-8c71008de217)
- Publishing country: UZBEKISTAN
- Installation: [Uzbekistan IPT](https://registry.gbif.org/installation/ecf8b170-4886-49fd-be0c-89c4c5ce6a6e)
- Number of occurrences indexed for this dataset at the time of the issue: 401
- Cause: GBIF ID problems exceed 50% threshold: 100% duplicates; 401 total records; 401 absent records
- Pipelines execution steps: [http://api.gbif.org/v1/pipelines/history/execution/3758133/step](http://api.gbif.org/v1/pipelines/history/execution/3758133/step)

```
New IDs sample:


```


```
Old IDs sample:

103
104
105
106
107
108
109
110
111
112
```

<details>
<summary>Publisher email</summary>

Hello,

I am contacting you from the GBIF Secretariat about a dataset published by the [Taxonomy and geography of species of the genus Parrya in the flora of Uzbekistan](https://registry.gbif.org/dataset/751005ce-d8f1-402e-8845-d3eb9b82be80) : https://doi.org/10.15468/6kfxuc.
We noticed that the occurrenceIDs were changed. We have temporarily paused the ingestions of this dataset.

As you might already know, when an occurrence record has a new occurrenceID for a given dataset, our system considers it to be a new occurrence.
This means that it will be given a new gbifid and a new occurrence URL (like this one: https://www.gbif.org/occurrence/1252968762) and the old gbifid and URL will be deprecated.

In this case, this means that the occurrence URLs would be deprecated when ingesting the newest versions of these datasets.

We would like to check with you if those changes were intentional. Do you know if this is the case?
Please let us know, thanks! We are happy to resume the dataset ingestion.

Note that some users rely on those occurrence URLs and gbifids (like https://bionomia.net for example). In an attempt to improve
the stability of the occurrence URLs and gbifids, we have implemented a warning system to detect these type of changes in datasets (see this news item).
If the data publisher can provide us with a list of old and new occurrenceIDs per record, we can avoid the identifier and URL changes. Could that be an option?

Please let us know if you have any question. Thanks!

All the best,

</details>


You can skip/fix identifier validation using [the registry UI](https://registry.gbif.org/dataset/751005ce-d8f1-402e-8845-d3eb9b82be80/ingestion-history).

**Comment by jhnwllr** [comment]
Thanks @rukayaj and @aliyevakumush77  the occurrenceIds have been migrated.
