### ISSUE TITLE
Identifiers validation failed for dataset 2023 insect_specimen_CNU_500

### ISSUE THREAD

**Issue by gbif-pipelines** [gbif/ingestion-management#1385]
Identifier validation failed for the dataset [2023 insect_specimen_CNU_500](https://registry.gbif.org/dataset/55511e18-9ddc-44af-ad31-70301713a5b2):
- Crawler attempt: 2
- Publishing organization: [National Science Museum of Korea](https://registry.gbif.org/organization/eb07eeb0-3db9-11d9-8439-b8a03c50a862)
- Publishing country: KOREA_SOUTH
- Installation: [KBIF IPT](https://registry.gbif.org/installation/a299935f-3216-4a11-bc3b-c370b2325eff)
- Number of occurrences indexed for this dataset at the time of the issue: 0
- Cause: GBIF ID problems exceed 50% threshold: 100% duplicates; 500 total records; 500 absent records
- Pipelines execution steps: [http://api.gbif.org/v1/pipelines/history/execution/3757737/step](http://api.gbif.org/v1/pipelines/history/execution/3757737/step)

```
New IDs sample:


```

```
Old IDs sample:

NSMK-OB-PI-230600001
NSMK-OB-PI-230600002
NSMK-OB-PI-230600003
NSMK-OB-PI-230600004
NSMK-OB-PI-230600005
NSMK-OB-PI-230600006
NSMK-OB-PI-230600007
NSMK-OB-PI-230600008
NSMK-OB-PI-230600009
NSMK-OB-PI-230600010
```

<details>
<summary>Publisher email</summary>

Hello,

I am contacting you from the GBIF Secretariat about a dataset published by the [2023 insect_specimen_CNU_500](https://registry.gbif.org/dataset/55511e18-9ddc-44af-ad31-70301713a5b2) : https://doi.org/10.15468/ufa9a3.
We noticed that the occurrenceIDs were changed. We have temporarily paused the ingestions of this dataset.

As you might already know, when an occurrence record has a new occurrenceID for a given dataset, our system considers it to be a new occurrence.
This means that it will be given a new gbifid and a new occurrence URL (like this one: https://www.gbif.org/occurrence/1252968762) and the old gbifid and URL will be deprecated.

In this case, this means that the occurrence URLs would be deprecated when ingesting the newest versions of these datasets.

We would like to check with you if those changes were intentional. Do you know if this is the case?
Please let us know, thanks! We are happy to resume the dataset ingestion.

Note that some users rely on those occurrence URLs and gbifids (like https://bionomia.net for example). In an attempt to improve
the stability of the occurrence URLs and gbifids, we have implemented a warning system to detect these type of changes in datasets (see this news item).
If the data publisher can provide us with a list of old and new occurrenceIDs per record, we can avoid the identifier and URL changes. Could that be an option?

Please let us know if you have any question. Thanks!

All the best,

</details>

You can skip/fix identifier validation using [the registry UI](https://registry.gbif.org/dataset/55511e18-9ddc-44af-ad31-70301713a5b2/ingestion-history).

**Comment by jhnwllr** [comment]
Number of occurrences indexed for this dataset at the time of the issue: 0 - are we flagging new dataset now?

**Comment by jhnwllr** [comment]
dataset was deleted and then re-published
