### ISSUE TITLE
Identifiers validation failed for dataset Kakila database of marine mammal observation data around the French archipelago of Guadeloupe in the AGOA sanctuary - French Antilles

### ISSUE THREAD

**Issue by gbif-pipelines** [gbif/ingestion-management#1386]
Identifier validation failed for the dataset [Kakila database of marine mammal observation data around the French archipelago of Guadeloupe in the AGOA sanctuary - French Antilles](https://registry.gbif.org/dataset/cba4183b-96a1-468a-a1c2-f7c9830f924e):
- Crawler attempt: 93
- Publishing organization: [Observatoire Hommes-Milieux Littoral Caraïbe](https://registry.gbif.org/organization/72aa40c3-01ab-41ba-9b94-515dfadd93bb)
- Publishing country: FRANCE
- Installation: [IPT GBIF France](https://registry.gbif.org/installation/791e3715-7452-4dd0-a906-db21a3852427)
- Number of occurrences indexed for this dataset at the time of the issue: 2731
- Cause: GBIF ID problems exceed 50% threshold: 100% duplicates; 4703 total records; 4703 absent records
- Pipelines execution steps: [http://api.gbif.org/v1/pipelines/history/execution/3757829/step](http://api.gbif.org/v1/pipelines/history/execution/3757829/step)

```
New IDs sample:


```

```
Old IDs sample:

017a9d06-fb7f-4368-9b70-f2ec2f2b47e1
01ed3de5-24b9-4618-a41b-f9d8f943dbc4
02e634d6-dfe0-4a8e-aae0-81274faaaa66
03d8e6c6-1bed-46ca-840f-4d758787be16
0c6f0ba2-1517-4733-b9e3-39870b779490
34c0fb39-b306-4746-b93c-06b44ec53dc9
3a7134c6-5be2-4765-9ed0-a4ffc5db6a2c
3bb66be9-007e-48d6-8598-1e2ec600d783
3f951bce-03ca-4615-8e28-7f84725740a7
54c19d7e-2378-4867-a8d5-38e1c924e086
```

<details>
<summary>Publisher email</summary>

Hello,

I am contacting you from the GBIF Secretariat about a dataset published by the [Kakila database of marine mammal observation data around the French archipelago of Guadeloupe in the AGOA sanctuary - French Antilles](https://registry.gbif.org/dataset/cba4183b-96a1-468a-a1c2-f7c9830f924e) : https://doi.org/10.15468/qrhurc.
We noticed that the occurrenceIDs were changed. We have temporarily paused the ingestions of this dataset.

As you might already know, when an occurrence record has a new occurrenceID for a given dataset, our system considers it to be a new occurrence.
This means that it will be given a new gbifid and a new occurrence URL (like this one: https://www.gbif.org/occurrence/1252968762) and the old gbifid and URL will be deprecated.

In this case, this means that the occurrence URLs would be deprecated when ingesting the newest versions of these datasets.

We would like to check with you if those changes were intentional. Do you know if this is the case?
Please let us know, thanks! We are happy to resume the dataset ingestion.

Note that some users rely on those occurrence URLs and gbifids (like https://bionomia.net for example). In an attempt to improve
the stability of the occurrence URLs and gbifids, we have implemented a warning system to detect these type of changes in datasets (see this news item).
If the data publisher can provide us with a list of old and new occurrenceIDs per record, we can avoid the identifier and URL changes. Could that be an option?

Please let us know if you have any question. Thanks!

All the best,

</details>

You can skip/fix identifier validation using [the registry UI](https://registry.gbif.org/dataset/cba4183b-96a1-468a-a1c2-f7c9830f924e/ingestion-history).

**Comment by gbif-pipelines** [comment]
Identifier validation still  failing for the dataset [Kakila database of marine mammal observation data around the French archipelago of Guadeloupe in the AGOA sanctuary - French Antilles](https://registry.gbif.org/dataset/cba4183b-96a1-468a-a1c2-f7c9830f924e):
- Crawler attempt: 94
- Publishing organization: [Observatoire Hommes-Milieux Littoral Caraïbe](https://registry.gbif.org/organization/72aa40c3-01ab-41ba-9b94-515dfadd93bb)
- Publishing country: FRANCE
- Installation: [IPT GBIF France](https://registry.gbif.org/installation/791e3715-7452-4dd0-a906-db21a3852427)
- Number of occurrences indexed for this dataset at the time of the issue: 2731
- Cause: GBIF ID problems exceed 50% threshold: 100% duplicates; 4703 total records; 4703 absent records
- Pipelines execution steps: [http://api.gbif.org/v1/pipelines/history/execution/3757841/step](http://api.gbif.org/v1/pipelines/history/execution/3757841/step)

```
New IDs sample:


```


```
Old IDs sample:

017a9d06-fb7f-4368-9b70-f2ec2f2b47e1
01ed3de5-24b9-4618-a41b-f9d8f943dbc4
02e634d6-dfe0-4a8e-aae0-81274faaaa66
03d8e6c6-1bed-46ca-840f-4d758787be16
0c6f0ba2-1517-4733-b9e3-39870b779490
34c0fb39-b306-4746-b93c-06b44ec53dc9
3a7134c6-5be2-4765-9ed0-a4ffc5db6a2c
3bb66be9-007e-48d6-8598-1e2ec600d783
3f951bce-03ca-4615-8e28-7f84725740a7
54c19d7e-2378-4867-a8d5-38e1c924e086
```

<details>
<summary>Publisher email</summary>

Hello,

I am contacting you from the GBIF Secretariat about a dataset published by the [Kakila database of marine mammal observation data around the French archipelago of Guadeloupe in the AGOA sanctuary - French Antilles](https://registry.gbif.org/dataset/cba4183b-96a1-468a-a1c2-f7c9830f924e) : https://doi.org/10.15468/qrhurc.
We noticed that the occurrenceIDs were changed. We have temporarily paused the ingestions of this dataset.

As you might already know, when an occurrence record has a new occurrenceID for a given dataset, our system considers it to be a new occurrence.
This means that it will be given a new gbifid and a new occurrence URL (like this one: https://www.gbif.org/occurrence/1252968762) and the old gbifid and URL will be deprecated.

In this case, this means that the occurrence URLs would be deprecated when ingesting the newest versions of these datasets.

We would like to check with you if those changes were intentional. Do you know if this is the case?
Please let us know, thanks! We are happy to resume the dataset ingestion.

Note that some users rely on those occurrence URLs and gbifids (like https://bionomia.net for example). In an attempt to improve
the stability of the occurrence URLs and gbifids, we have implemented a warning system to detect these type of changes in datasets (see this news item).
If the data publisher can provide us with a list of old and new occurrenceIDs per record, we can avoid the identifier and URL changes. Could that be an option?

Please let us know if you have any question. Thanks!

All the best,

</details>


You can skip/fix identifier validation using [the registry UI](https://registry.gbif.org/dataset/cba4183b-96a1-468a-a1c2-f7c9830f924e/ingestion-history).

**Comment by gbif-pipelines** [comment]
Identifier validation still  failing for the dataset [Kakila database of marine mammal observation data around the French archipelago of Guadeloupe in the AGOA sanctuary - French Antilles](https://registry.gbif.org/dataset/cba4183b-96a1-468a-a1c2-f7c9830f924e):
- Crawler attempt: 97
- Publishing organization: [Observatoire Hommes-Milieux Littoral Caraïbe](https://registry.gbif.org/organization/72aa40c3-01ab-41ba-9b94-515dfadd93bb)
- Publishing country: FRANCE
- Installation: [IPT GBIF France](https://registry.gbif.org/installation/791e3715-7452-4dd0-a906-db21a3852427)
- Number of occurrences indexed for this dataset at the time of the issue: 2731
- Cause: GBIF ID problems exceed 50% threshold: 100% duplicates; 4703 total records; 4703 absent records
- Pipelines execution steps: [http://api.gbif.org/v1/pipelines/history/execution/3757844/step](http://api.gbif.org/v1/pipelines/history/execution/3757844/step)

```
New IDs sample:


```


```
Old IDs sample:

017a9d06-fb7f-4368-9b70-f2ec2f2b47e1
01ed3de5-24b9-4618-a41b-f9d8f943dbc4
02e634d6-dfe0-4a8e-aae0-81274faaaa66
03d8e6c6-1bed-46ca-840f-4d758787be16
0c6f0ba2-1517-4733-b9e3-39870b779490
34c0fb39-b306-4746-b93c-06b44ec53dc9
3a7134c6-5be2-4765-9ed0-a4ffc5db6a2c
3bb66be9-007e-48d6-8598-1e2ec600d783
3f951bce-03ca-4615-8e28-7f84725740a7
54c19d7e-2378-4867-a8d5-38e1c924e086
```

<details>
<summary>Publisher email</summary>

Hello,

I am contacting you from the GBIF Secretariat about a dataset published by the [Kakila database of marine mammal observation data around the French archipelago of Guadeloupe in the AGOA sanctuary - French Antilles](https://registry.gbif.org/dataset/cba4183b-96a1-468a-a1c2-f7c9830f924e) : https://doi.org/10.15468/qrhurc.
We noticed that the occurrenceIDs were changed. We have temporarily paused the ingestions of this dataset.

As you might already know, when an occurrence record has a new occurrenceID for a given dataset, our system considers it to be a new occurrence.
This means that it will be given a new gbifid and a new occurrence URL (like this one: https://www.gbif.org/occurrence/1252968762) and the old gbifid and URL will be deprecated.

In this case, this means that the occurrence URLs would be deprecated when ingesting the newest versions of these datasets.

We would like to check with you if those changes were intentional. Do you know if this is the case?
Please let us know, thanks! We are happy to resume the dataset ingestion.

Note that some users rely on those occurrence URLs and gbifids (like https://bionomia.net for example). In an attempt to improve
the stability of the occurrence URLs and gbifids, we have implemented a warning system to detect these type of changes in datasets (see this news item).
If the data publisher can provide us with a list of old and new occurrenceIDs per record, we can avoid the identifier and URL changes. Could that be an option?

Please let us know if you have any question. Thanks!

All the best,

</details>


You can skip/fix identifier validation using [the registry UI](https://registry.gbif.org/dataset/cba4183b-96a1-468a-a1c2-f7c9830f924e/ingestion-history).

**Comment by SophiePamerlon** [comment]
Hi @jhnwllr , thanks for contacting me! I was going to message you about this issue but I saw the github notification first :)
We just did a resource migration + data publisher change for this specific dataset because of issues with its publication workflow, everything should be ok and stable now but the occurrenceIDs might have changed between its old & new versions (it should not happen again). Could you please launch its ingestion now?

**Comment by jhnwllr** [comment]
@SophiePamerlon do you happen to have the mappings from the **old occurrenceIds** to the **new occurrenceIds**?

**Comment by SophiePamerlon** [comment]
@jhnwllr Unfortunately not, but the old occurrenceIDs were not correct/complete and should be discarded (we only migrated the old resource to a new IPT & data publisher to keep its DOI and citations on GBIF)

**Comment by jhnwllr** [comment]
@SophiePamerlon ok I have let the dataset ingest now. Thanks for looking into this.

**Comment by SophiePamerlon** [comment]
@jhnwllr Thank you John for your help with this issue!
