### ISSUE TITLE
Identifiers validation failed for dataset Fototrampeo Área Metropolitana del Valle de Aburrá

### ISSUE THREAD

**Issue by gbif-pipelines** [gbif/ingestion-management#1390]
Identifier validation failed for the dataset [Fototrampeo Área Metropolitana del Valle de Aburrá](https://registry.gbif.org/dataset/1347e6fd-46fc-4933-8d6b-529d235eefb3):
- Crawler attempt: 29
- Publishing organization: [Área Metropolitana del Valle de Aburrá](https://registry.gbif.org/organization/bad9baef-be05-4410-83c8-31060a9bafb7)
- Publishing country: COLOMBIA
- Installation: [Datos sobre Biodiversidad de Colombia](https://registry.gbif.org/installation/68845aab-a453-4816-b36d-a3ec8455deb0)
- Number of occurrences indexed for this dataset at the time of the issue: 2423
- Cause: GBIF ID problems exceed 50% threshold: 100% duplicates; 3568 total records; 3568 absent records
- Pipelines execution steps: [http://api.gbif.org/v1/pipelines/history/execution/3792677/step](http://api.gbif.org/v1/pipelines/history/execution/3792677/step)

```
New IDs sample:


```

```
Old IDs sample:

IAVH:OBSERVACIONCONMAQUINA:TELEMETRIA-ABURRA:0745
IAVH:OBSERVACIONCONMAQUINA:TELEMETRIA-ABURRA:0746
IAVH:OBSERVACIONCONMAQUINA:TELEMETRIA-ABURRA:0747
IAVH:OBSERVACIONCONMAQUINA:TELEMETRIA-ABURRA:0748
IAVH:OBSERVACIONCONMAQUINA:TELEMETRIA-ABURRA:0749
IAVH:OBSERVACIONCONMAQUINA:TELEMETRIA-ABURRA:0750
IAVH:OBSERVACIONCONMAQUINA:TELEMETRIA-ABURRA:0751
IAVH:OBSERVACIONCONMAQUINA:TELEMETRIA-ABURRA:0752
IAVH:OBSERVACIONCONMAQUINA:TELEMETRIA-ABURRA:0753
IAVH:OBSERVACIONCONMAQUINA:TELEMETRIA-ABURRA:0754
```

<details>
<summary>Publisher email</summary>

Hello,

I am contacting you from the GBIF Secretariat about a dataset published by the [Fototrampeo Área Metropolitana del Valle de Aburrá](https://registry.gbif.org/dataset/1347e6fd-46fc-4933-8d6b-529d235eefb3) : https://doi.org/10.15472/wfdfxy.
We noticed that the occurrenceIDs were changed. We have temporarily paused the ingestions of this dataset.

As you might already know, when an occurrence record has a new occurrenceID for a given dataset, our system considers it to be a new occurrence.
This means that it will be given a new gbifid and a new occurrence URL (like this one: https://www.gbif.org/occurrence/1252968762) and the old gbifid and URL will be deprecated.

In this case, this means that the occurrence URLs would be deprecated when ingesting the newest versions of these datasets.

We would like to check with you if those changes were intentional. Do you know if this is the case?
Please let us know, thanks! We are happy to resume the dataset ingestion.

Note that some users rely on those occurrence URLs and gbifids (like https://bionomia.net for example). In an attempt to improve
the stability of the occurrence URLs and gbifids, we have implemented a warning system to detect these type of changes in datasets (see this news item).
If the data publisher can provide us with a list of old and new occurrenceIDs per record, we can avoid the identifier and URL changes. Could that be an option?

Please let us know if you have any question. Thanks!

All the best,

</details>

You can skip/fix identifier validation using [the registry UI](https://registry.gbif.org/dataset/1347e6fd-46fc-4933-8d6b-529d235eefb3/ingestion-history).

**Comment by EstebanMH-SiB** [comment]
We can reindex this dataset, we try it to recover the original occurrenceID but the publisher told us it is not possible.

**Comment by EstebanMH-SiB** [comment]
@jhnwllr can we please reingest this dataset? And also this one from another issue https://github.com/gbif/ingestion-management/issues/1592
