### ISSUE TITLE
Identifiers validation failed for dataset ibbi observations

### ISSUE THREAD

**Issue by gbif-pipelines** [gbif/ingestion-management#1393]
Identifier validation failed for the dataset [ibbi observations](https://registry.gbif.org/dataset/a3c6c702-6050-4e69-b358-8934bdc97994):
- Crawler attempt: 7
- Publishing organization: [Blåst Spel AS](https://registry.gbif.org/organization/623a4940-3a7f-439f-a75f-e5a192a1e745)
- Publishing country: NORWAY
- Installation: [ibbi HTTP Installation](https://registry.gbif.org/installation/207273d4-82d8-4e80-9c29-91e7786a387d)
- Number of occurrences indexed for this dataset at the time of the issue: 1
- Cause: GBIF ID problems exceed 50% threshold: 100% duplicates; 2 total records; 2 absent records
- Pipelines execution steps: [http://api.gbif.org/v1/pipelines/history/execution/3809025/step](http://api.gbif.org/v1/pipelines/history/execution/3809025/step)

```
New IDs sample:


```

```
Old IDs sample:

GAIA:BU37j27gZYniB2eNQ4g3
```

<details>
<summary>Publisher email</summary>

Hello,

I am contacting you from the GBIF Secretariat about a dataset published by the [ibbi observations](https://registry.gbif.org/dataset/a3c6c702-6050-4e69-b358-8934bdc97994) : https://doi.org/10.15468/m94g82.
We noticed that the occurrenceIDs were changed. We have temporarily paused the ingestions of this dataset.

As you might already know, when an occurrence record has a new occurrenceID for a given dataset, our system considers it to be a new occurrence.
This means that it will be given a new gbifid and a new occurrence URL (like this one: https://www.gbif.org/occurrence/1252968762) and the old gbifid and URL will be deprecated.

In this case, this means that the occurrence URLs would be deprecated when ingesting the newest versions of these datasets.

We would like to check with you if those changes were intentional. Do you know if this is the case?
Please let us know, thanks! We are happy to resume the dataset ingestion.

Note that some users rely on those occurrence URLs and gbifids (like https://bionomia.net for example). In an attempt to improve
the stability of the occurrence URLs and gbifids, we have implemented a warning system to detect these type of changes in datasets (see this news item).
If the data publisher can provide us with a list of old and new occurrenceIDs per record, we can avoid the identifier and URL changes. Could that be an option?

Please let us know if you have any question. Thanks!

All the best,

</details>

You can skip/fix identifier validation using [the registry UI](https://registry.gbif.org/dataset/a3c6c702-6050-4e69-b358-8934bdc97994/ingestion-history).

**Comment by gbif-pipelines** [comment]
Identifier validation still  failing for the dataset [ibbi observations](https://registry.gbif.org/dataset/a3c6c702-6050-4e69-b358-8934bdc97994):
- Crawler attempt: 9
- Publishing organization: [Blåst Spel AS](https://registry.gbif.org/organization/623a4940-3a7f-439f-a75f-e5a192a1e745)
- Publishing country: NORWAY
- Installation: [ibbi HTTP Installation](https://registry.gbif.org/installation/207273d4-82d8-4e80-9c29-91e7786a387d)
- Number of occurrences indexed for this dataset at the time of the issue: 1
- Cause: GBIF ID problems exceed 50% threshold: 100% duplicates; 2 total records; 2 absent records
- Pipelines execution steps: [http://api.gbif.org/v1/pipelines/history/execution/3809032/step](http://api.gbif.org/v1/pipelines/history/execution/3809032/step)

```
New IDs sample:


```


```
Old IDs sample:

GAIA:BU37j27gZYniB2eNQ4g3
```

<details>
<summary>Publisher email</summary>

Hello,

I am contacting you from the GBIF Secretariat about a dataset published by the [ibbi observations](https://registry.gbif.org/dataset/a3c6c702-6050-4e69-b358-8934bdc97994) : https://doi.org/10.15468/m94g82.
We noticed that the occurrenceIDs were changed. We have temporarily paused the ingestions of this dataset.

As you might already know, when an occurrence record has a new occurrenceID for a given dataset, our system considers it to be a new occurrence.
This means that it will be given a new gbifid and a new occurrence URL (like this one: https://www.gbif.org/occurrence/1252968762) and the old gbifid and URL will be deprecated.

In this case, this means that the occurrence URLs would be deprecated when ingesting the newest versions of these datasets.

We would like to check with you if those changes were intentional. Do you know if this is the case?
Please let us know, thanks! We are happy to resume the dataset ingestion.

Note that some users rely on those occurrence URLs and gbifids (like https://bionomia.net for example). In an attempt to improve
the stability of the occurrence URLs and gbifids, we have implemented a warning system to detect these type of changes in datasets (see this news item).
If the data publisher can provide us with a list of old and new occurrenceIDs per record, we can avoid the identifier and URL changes. Could that be an option?

Please let us know if you have any question. Thanks!

All the best,

</details>


You can skip/fix identifier validation using [the registry UI](https://registry.gbif.org/dataset/a3c6c702-6050-4e69-b358-8934bdc97994/ingestion-history).

**Comment by jhnwllr** [comment]
Was let through because it is two occurrence records.
