### ISSUE TITLE
Identifiers validation failed for dataset INSDC Host Organism Sequences

### ISSUE THREAD

**Issue by gbif-pipelines** [gbif/ingestion-management#14]
Identifier validation failed for the dataset [INSDC Host Organism Sequences](https://registry.gbif.org/dataset/393b8c26-e4e0-4dd0-a218-93fc074ebf4e):
- Crawler attempt: 118
- Publishing organization: [European Nucleotide Archive (EMBL-EBI)](https://registry.gbif.org/organization/ada9d123-ddb4-467d-8891-806ea8d94230)
- Publishing country: UNITED_KINGDOM
- Installation: [GBIF Europe and Central Asia](https://registry.gbif.org/installation/17a83780-3060-4851-9d6f-029d5fcb81c9)
- Number of occurrences indexed for this dataset at the time of the issue: 1345328
- Cause: GBIF IDs hit maximum allowed - 50%, duplicates - 86%, total records count 9816697, absent records count 8478821
- Step metrics: 
```

```

- Pipelines execution steps: [http://api.gbif.org/v1/pipelines/history/execution/3042140/step](http://api.gbif.org/v1/pipelines/history/execution/3042140/step)
<details>
<summary>Publisher email</summary>

Hello,

I am contacting you from the GBIF Secretariat about a dataset published by the [INSDC Host Organism Sequences](https://registry.gbif.org/dataset/393b8c26-e4e0-4dd0-a218-93fc074ebf4e) : https://doi.org/10.15468/e97kmy.
We noticed that the occurrenceIDs were changed. We have temporarily paused the ingestions of this dataset.

As you might already know, when an occurrence record has a new occurrenceID for a given dataset, our system considers it to be a new occurrence.
This means that it will be given a new gbifid and a new occurrence URL (like this one: https://www.gbif.org/occurrence/1252968762) and the old gbifid and URL will be deprecated.

In this case, this means that the occurrence URLs would be deprecated when ingesting the newest versions of these datasets.

We would like to check with you if those changes were intentional. Do you know if this is the case?
Please let us know, thanks! We are happy to resume the dataset ingestion.

Note that some users rely on those occurrence URLs and gbifids (like https://bionomia.net for example). In an attempt to improve
the stability of the occurrence URLs and gbifids, we have implemented a warning system to detect these type of changes in datasets (see this news item).
If the data publisher can provide us with a list of old and new occurrenceIDs per record, we can avoid the identifier and URL changes. Could that be an option?

Please let us know if you have any question. Thanks!

All the best,

</details>

You can skip/fix identifier validation using [the registry UI](https://registry.gbif.org/dataset/393b8c26-e4e0-4dd0-a218-93fc074ebf4e/ingestion-history).

**Comment by ManonGros** [comment]
I think there is a problem with this dataset, see https://github.com/gbif/portal-feedback/issues/4864#issuecomment-1633800202, I don't think we should ingest the dataset until the issue is solved.

**Comment by MattBlissett** [comment]
The fixed dataset ingested without any interference with identifiers.
