### ISSUE TITLE
Identifiers validation failed for dataset Biomonitoreo de Hormigas para la Ecoreserva La Tribuna (Neiva-Huila) -  Proyecto FIBRAS

### ISSUE THREAD

**Issue by gbif-pipelines** [gbif/ingestion-management#1411]
Identifier validation failed for the dataset [Biomonitoreo de Hormigas para la Ecoreserva La Tribuna (Neiva-Huila) -  Proyecto FIBRAS](https://registry.gbif.org/dataset/8c444794-966c-4c4a-bf00-2c9c91ee1be7):
- Crawler attempt: 2
- Publishing organization: [Ecopetrol S.A.](https://registry.gbif.org/organization/d5ef14a1-5177-4547-9ce2-46d84a4214eb)
- Publishing country: COLOMBIA
- Installation: [Datos sobre Biodiversidad de Colombia](https://registry.gbif.org/installation/68845aab-a453-4816-b36d-a3ec8455deb0)
- Number of occurrences indexed for this dataset at the time of the issue: 0
- Cause: GBIF ID problems exceed 50% threshold: 100% duplicates; 3238 total records; 3238 absent records
- Pipelines execution steps: [http://api.gbif.org/v1/pipelines/history/execution/3860371/step](http://api.gbif.org/v1/pipelines/history/execution/3860371/step)

```
New IDs sample:


```

```
Old IDs sample:

IAvH:SI-FIBRAS:TRIBUNA:DIPTERA:ESPECIMENPRESERVADO:I2D-BIO_2022_076:4785
IAvH:SI-FIBRAS:TRIBUNA:DIPTERA:ESPECIMENPRESERVADO:I2D-BIO_2022_076:4786
IAvH:SI-FIBRAS:TRIBUNA:DIPTERA:ESPECIMENPRESERVADO:I2D-BIO_2022_076:4787
IAvH:SI-FIBRAS:TRIBUNA:DIPTERA:ESPECIMENPRESERVADO:I2D-BIO_2022_076:4788
IAvH:SI-FIBRAS:TRIBUNA:DIPTERA:ESPECIMENPRESERVADO:I2D-BIO_2022_076:4789
IAvH:SI-FIBRAS:TRIBUNA:DIPTERA:ESPECIMENPRESERVADO:I2D-BIO_2022_076:4790
IAvH:SI-FIBRAS:TRIBUNA:DIPTERA:ESPECIMENPRESERVADO:I2D-BIO_2022_076:4791
IAvH:SI-FIBRAS:TRIBUNA:DIPTERA:ESPECIMENPRESERVADO:I2D-BIO_2022_076:4792
IAvH:SI-FIBRAS:TRIBUNA:DIPTERA:ESPECIMENPRESERVADO:I2D-BIO_2022_076:4793
IAvH:SI-FIBRAS:TRIBUNA:DIPTERA:ESPECIMENPRESERVADO:I2D-BIO_2022_076:4794
```

<details>
<summary>Publisher email</summary>

Hello,

I am contacting you from the GBIF Secretariat about a dataset published by the [Biomonitoreo de Hormigas para la Ecoreserva La Tribuna (Neiva-Huila) -  Proyecto FIBRAS](https://registry.gbif.org/dataset/8c444794-966c-4c4a-bf00-2c9c91ee1be7) : https://doi.org/10.15472/c1bv3e.
We noticed that the occurrenceIDs were changed. We have temporarily paused the ingestions of this dataset.

As you might already know, when an occurrence record has a new occurrenceID for a given dataset, our system considers it to be a new occurrence.
This means that it will be given a new gbifid and a new occurrence URL (like this one: https://www.gbif.org/occurrence/1252968762) and the old gbifid and URL will be deprecated.

In this case, this means that the occurrence URLs would be deprecated when ingesting the newest versions of these datasets.

We would like to check with you if those changes were intentional. Do you know if this is the case?
Please let us know, thanks! We are happy to resume the dataset ingestion.

Note that some users rely on those occurrence URLs and gbifids (like https://bionomia.net for example). In an attempt to improve
the stability of the occurrence URLs and gbifids, we have implemented a warning system to detect these type of changes in datasets (see this news item).
If the data publisher can provide us with a list of old and new occurrenceIDs per record, we can avoid the identifier and URL changes. Could that be an option?

Please let us know if you have any question. Thanks!

All the best,

</details>

You can skip/fix identifier validation using [the registry UI](https://registry.gbif.org/dataset/8c444794-966c-4c4a-bf00-2c9c91ee1be7/ingestion-history).

**Comment by EstebanMH-SiB** [comment]
I make a mistake and uploaded an incorrect file the first time, so we just need to reindex this dataset

**Comment by jhnwllr** [comment]
@EstebanMH-SiB Just let me know when I should re-ingest. If the occurrenceIds are not changed in the new version, it should ingest without issue.

**Comment by EstebanMH-SiB** [comment]
Thank you @jhnwllr, you can re-ingest it now

**Comment by gbif-pipelines** [comment]
Identifier validation still  failing for the dataset [Biomonitoreo de Hormigas para la Ecoreserva La Tribuna (Neiva-Huila) -  Proyecto FIBRAS](https://registry.gbif.org/dataset/8c444794-966c-4c4a-bf00-2c9c91ee1be7):
- Crawler attempt: 3
- Publishing organization: [Ecopetrol S.A.](https://registry.gbif.org/organization/d5ef14a1-5177-4547-9ce2-46d84a4214eb)
- Publishing country: COLOMBIA
- Installation: [Datos sobre Biodiversidad de Colombia](https://registry.gbif.org/installation/68845aab-a453-4816-b36d-a3ec8455deb0)
- Number of occurrences indexed for this dataset at the time of the issue: 4802
- Cause: GBIF ID problems exceed 50% threshold: 100% duplicates; 3238 total records; 3238 absent records
- Pipelines execution steps: [http://api.gbif.org/v1/pipelines/history/execution/3861249/step](http://api.gbif.org/v1/pipelines/history/execution/3861249/step)

```
New IDs sample:


```


```
Old IDs sample:

IAvH:SI-FIBRAS:TRIBUNA:DIPTERA:ESPECIMENPRESERVADO:I2D-BIO_2022_076:4785
IAvH:SI-FIBRAS:TRIBUNA:DIPTERA:ESPECIMENPRESERVADO:I2D-BIO_2022_076:4786
IAvH:SI-FIBRAS:TRIBUNA:DIPTERA:ESPECIMENPRESERVADO:I2D-BIO_2022_076:4787
IAvH:SI-FIBRAS:TRIBUNA:DIPTERA:ESPECIMENPRESERVADO:I2D-BIO_2022_076:4788
IAvH:SI-FIBRAS:TRIBUNA:DIPTERA:ESPECIMENPRESERVADO:I2D-BIO_2022_076:4789
IAvH:SI-FIBRAS:TRIBUNA:DIPTERA:ESPECIMENPRESERVADO:I2D-BIO_2022_076:4790
IAvH:SI-FIBRAS:TRIBUNA:DIPTERA:ESPECIMENPRESERVADO:I2D-BIO_2022_076:4791
IAvH:SI-FIBRAS:TRIBUNA:DIPTERA:ESPECIMENPRESERVADO:I2D-BIO_2022_076:4792
IAvH:SI-FIBRAS:TRIBUNA:DIPTERA:ESPECIMENPRESERVADO:I2D-BIO_2022_076:4793
IAvH:SI-FIBRAS:TRIBUNA:DIPTERA:ESPECIMENPRESERVADO:I2D-BIO_2022_076:4794
```

<details>
<summary>Publisher email</summary>

Hello,

I am contacting you from the GBIF Secretariat about a dataset published by the [Biomonitoreo de Hormigas para la Ecoreserva La Tribuna (Neiva-Huila) -  Proyecto FIBRAS](https://registry.gbif.org/dataset/8c444794-966c-4c4a-bf00-2c9c91ee1be7) : https://doi.org/10.15472/c1bv3e.
We noticed that the occurrenceIDs were changed. We have temporarily paused the ingestions of this dataset.

As you might already know, when an occurrence record has a new occurrenceID for a given dataset, our system considers it to be a new occurrence.
This means that it will be given a new gbifid and a new occurrence URL (like this one: https://www.gbif.org/occurrence/1252968762) and the old gbifid and URL will be deprecated.

In this case, this means that the occurrence URLs would be deprecated when ingesting the newest versions of these datasets.

We would like to check with you if those changes were intentional. Do you know if this is the case?
Please let us know, thanks! We are happy to resume the dataset ingestion.

Note that some users rely on those occurrence URLs and gbifids (like https://bionomia.net for example). In an attempt to improve
the stability of the occurrence URLs and gbifids, we have implemented a warning system to detect these type of changes in datasets (see this news item).
If the data publisher can provide us with a list of old and new occurrenceIDs per record, we can avoid the identifier and URL changes. Could that be an option?

Please let us know if you have any question. Thanks!

All the best,

</details>


You can skip/fix identifier validation using [the registry UI](https://registry.gbif.org/dataset/8c444794-966c-4c4a-bf00-2c9c91ee1be7/ingestion-history).

**Comment by jhnwllr** [comment]
@EstebanMH-SiB it still appears to be caught by the occurrenceId checker and version 2.3 seems to still have different occurrenceIds than from what is currently on GBIf.

**Comment by EstebanMH-SiB** [comment]
You can re index version 2.3, is the correct one with 315 events and 3238 occurrences
