### ISSUE TITLE
Identifiers validation failed for dataset Happywhale - Risso's Dolphin in North Atlantic Ocean

### ISSUE THREAD

**Issue by gbif-pipelines** [gbif/ingestion-management#1428]
Identifier validation failed for the dataset [Happywhale - Risso's Dolphin in North Atlantic Ocean](https://registry.gbif.org/dataset/f44af5b2-ca68-46a9-8a59-5a2d1e233e6c):
- Crawler attempt: 166
- Publishing organization: [OBIS-SEAMAP](https://registry.gbif.org/organization/67b2263f-6990-4d9d-b32b-20aa72ef4fbc)
- Publishing country: UNITED_STATES
- Installation: [OBIS-SEAMAP IPT](https://registry.gbif.org/installation/beeeddea-c02a-43d5-aec7-b534daca34d6)
- Number of occurrences indexed for this dataset at the time of the issue: 93
- Cause: GBIF ID problems exceed 50% threshold: 81% duplicates; 470 total records; 379 absent records
- Pipelines execution steps: [http://api.gbif.org/v1/pipelines/history/execution/3912808/step](http://api.gbif.org/v1/pipelines/history/execution/3912808/step)

```
New IDs sample:

120537
120527
120535
126906
453669
453668
453666
453787
453791
453789
```

```
Old IDs sample:

452424
452425
452426
452427
452428
452429
452430
452431
452432
452753
```

<details>
<summary>Publisher email</summary>

Hello,

I am contacting you from the GBIF Secretariat about a dataset published by the [Happywhale - Risso's Dolphin in North Atlantic Ocean](https://registry.gbif.org/dataset/f44af5b2-ca68-46a9-8a59-5a2d1e233e6c) : https://doi.org/10.15468/v9vhyn.
We noticed that the occurrenceIDs were changed. We have temporarily paused the ingestions of this dataset.

As you might already know, when an occurrence record has a new occurrenceID for a given dataset, our system considers it to be a new occurrence.
This means that it will be given a new gbifid and a new occurrence URL (like this one: https://www.gbif.org/occurrence/1252968762) and the old gbifid and URL will be deprecated.

In this case, this means that the occurrence URLs would be deprecated when ingesting the newest versions of these datasets.

We would like to check with you if those changes were intentional. Do you know if this is the case?
Please let us know, thanks! We are happy to resume the dataset ingestion.

Note that some users rely on those occurrence URLs and gbifids (like https://bionomia.net for example). In an attempt to improve
the stability of the occurrence URLs and gbifids, we have implemented a warning system to detect these type of changes in datasets (see this news item).
If the data publisher can provide us with a list of old and new occurrenceIDs per record, we can avoid the identifier and URL changes. Could that be an option?

Please let us know if you have any question. Thanks!

All the best,

</details>

You can skip/fix identifier validation using [the registry UI](https://registry.gbif.org/dataset/f44af5b2-ca68-46a9-8a59-5a2d1e233e6c/ingestion-history).

**Comment by jhnwllr** [comment]
From aggregated dataset publisher. Skipping id checks because the publisher requested that on other datasets.
