### ISSUE TITLE
Identifiers validation failed for dataset Avifauna de los Parques Ecológicos Distritales de Montaña del Distrito Capital

### ISSUE THREAD

**Issue by gbif-pipelines** [gbif/ingestion-management#15]
Identifier validation failed for the dataset [Avifauna de los Parques Ecológicos Distritales de Montaña del Distrito Capital](https://registry.gbif.org/dataset/b83b93b8-4b97-4cd2-b979-3801c622bc52):
- Crawler attempt: 170
- Publishing organization: [Secretaría Distrital de Ambiente](https://registry.gbif.org/organization/e70c4151-0d1a-414d-b70e-e87ac1e812b7)
- Publishing country: COLOMBIA
- Installation: [Datos sobre Biodiversidad de Colombia](https://registry.gbif.org/installation/68845aab-a453-4816-b36d-a3ec8455deb0)
- Number of occurrences indexed for this dataset at the time of the issue: 1296
- Cause: GBIF IDs hit maximum allowed - 50%, duplicates - 100%, total records count 5464, absent records count 5464
- Step metrics: 
```

```

- Pipelines execution steps: [http://api.gbif.org/v1/pipelines/history/execution/3042179/step](http://api.gbif.org/v1/pipelines/history/execution/3042179/step)
<details>
<summary>Publisher email</summary>

Hello,

I am contacting you from the GBIF Secretariat about a dataset published by the [Avifauna de los Parques Ecológicos Distritales de Montaña del Distrito Capital](https://registry.gbif.org/dataset/b83b93b8-4b97-4cd2-b979-3801c622bc52) : https://doi.org/10.15472/dslemn.
We noticed that the occurrenceIDs were changed. We have temporarily paused the ingestions of this dataset.

As you might already know, when an occurrence record has a new occurrenceID for a given dataset, our system considers it to be a new occurrence.
This means that it will be given a new gbifid and a new occurrence URL (like this one: https://www.gbif.org/occurrence/1252968762) and the old gbifid and URL will be deprecated.

In this case, this means that the occurrence URLs would be deprecated when ingesting the newest versions of these datasets.

We would like to check with you if those changes were intentional. Do you know if this is the case?
Please let us know, thanks! We are happy to resume the dataset ingestion.

Note that some users rely on those occurrence URLs and gbifids (like https://bionomia.net for example). In an attempt to improve
the stability of the occurrence URLs and gbifids, we have implemented a warning system to detect these type of changes in datasets (see this news item).
If the data publisher can provide us with a list of old and new occurrenceIDs per record, we can avoid the identifier and URL changes. Could that be an option?

Please let us know if you have any question. Thanks!

All the best,

</details>

You can skip/fix identifier validation using [the registry UI](https://registry.gbif.org/dataset/b83b93b8-4b97-4cd2-b979-3801c622bc52/ingestion-history).

**Comment by EstebanMH-SiB** [comment]
For this dataset we can continue the ingestion process, the publisher did a change in how occurrenceID are created and is not possible to recover the original information

**Comment by jhnwllr** [comment]
Yes I will allow ingestion for this dataset.
