### ISSUE TITLE
Identifiers validation failed for dataset Colección Ornitológica de la Universidad Industrial de Santander

### ISSUE THREAD

**Issue by gbif-pipelines** [gbif/ingestion-management#1592]
Identifier validation failed for the dataset [Colección Ornitológica de la Universidad Industrial de Santander](https://registry.gbif.org/dataset/34ca7b9c-6a2f-465e-9cac-7d71c792c670):
- Crawler attempt: 358
- Publishing organization: [Universidad Industrial de Santander](https://registry.gbif.org/organization/6c147991-c3bf-453d-a778-3bea9a534804)
- Publishing country: COLOMBIA
- Installation: [Datos sobre Biodiversidad de Colombia](https://registry.gbif.org/installation/68845aab-a453-4816-b36d-a3ec8455deb0)
- Number of occurrences indexed for this dataset at the time of the issue: 1581
- Cause: GBIF ID problems exceed 50% threshold: 100% duplicates; 3058 total records; 3058 absent records
- Pipelines execution steps: [http://api.gbif.org/v1/pipelines/history/execution/4204426/step](http://api.gbif.org/v1/pipelines/history/execution/4204426/step)

```
New IDs sample:


```

```
Old IDs sample:

UIS:UIS-O-1476
UIS:UIS-O-1474
UIS:UIS-O-1475
UIS:UIS-O-1477
UIS:UIS-O-1478
UIS:UIS-O-1479
UIS:UIS-O-1480
UIS:UIS-O-1481
UIS:UIS-O-1482
UIS:UIS-O-1483
```

<details>
<summary>Publisher email</summary>

Hello,

I am contacting you from the GBIF Secretariat about a dataset published by the [Colección Ornitológica de la Universidad Industrial de Santander](https://registry.gbif.org/dataset/34ca7b9c-6a2f-465e-9cac-7d71c792c670) : https://doi.org/10.15472/w2sefh.
We noticed that the occurrenceIDs were changed. We have temporarily paused the ingestions of this dataset.

As you might already know, when an occurrence record has a new occurrenceID for a given dataset, our system considers it to be a new occurrence.
This means that it will be given a new gbifid and a new occurrence URL (like this one: https://www.gbif.org/occurrence/1252968762) and the old gbifid and URL will be deprecated.

In this case, this means that the occurrence URLs would be deprecated when ingesting the newest versions of these datasets.

We would like to check with you if those changes were intentional. Do you know if this is the case?
Please let us know, thanks! We are happy to resume the dataset ingestion.

Note that some users rely on those occurrence URLs and gbifids (like https://bionomia.net for example). In an attempt to improve
the stability of the occurrence URLs and gbifids, we have implemented a warning system to detect these type of changes in datasets (see this news item).
If the data publisher can provide us with a list of old and new occurrenceIDs per record, we can avoid the identifier and URL changes. Could that be an option?

Please let us know if you have any question. Thanks!

All the best,

</details>

You can skip/fix identifier validation using [the registry UI](https://registry.gbif.org/dataset/34ca7b9c-6a2f-465e-9cac-7d71c792c670/ingestion-history).

**Comment by EstebanMH-SiB** [comment]
The publisher told us that it is not possible to connect old occurrenceIDs with the new ones, so we can proceed indexing this one

**Comment by gbif-pipelines** [comment]
Identifier validation still  failing for the dataset [Colección Ornitológica de la Universidad Industrial de Santander](https://registry.gbif.org/dataset/34ca7b9c-6a2f-465e-9cac-7d71c792c670):
- Crawler attempt: 360
- Publishing organization: [Universidad Industrial de Santander](https://registry.gbif.org/organization/6c147991-c3bf-453d-a778-3bea9a534804)
- Publishing country: COLOMBIA
- Installation: [Datos sobre Biodiversidad de Colombia](https://registry.gbif.org/installation/68845aab-a453-4816-b36d-a3ec8455deb0)
- Number of occurrences indexed for this dataset at the time of the issue: 1581
- Cause: GBIF ID problems exceed 50% threshold: 100% duplicates; 3058 total records; 3058 absent records
- Pipelines execution steps: [http://api.gbif.org/v1/pipelines/history/execution/4238225/step](http://api.gbif.org/v1/pipelines/history/execution/4238225/step)

```
New IDs sample:


```


```
Old IDs sample:

UIS:UIS-O-1476
UIS:UIS-O-1474
UIS:UIS-O-1475
UIS:UIS-O-1477
UIS:UIS-O-1478
UIS:UIS-O-1479
UIS:UIS-O-1480
UIS:UIS-O-1481
UIS:UIS-O-1482
UIS:UIS-O-1483
```

<details>
<summary>Publisher email</summary>

Hello,

I am contacting you from the GBIF Secretariat about a dataset published by the [Colección Ornitológica de la Universidad Industrial de Santander](https://registry.gbif.org/dataset/34ca7b9c-6a2f-465e-9cac-7d71c792c670) : https://doi.org/10.15472/w2sefh.
We noticed that the occurrenceIDs were changed. We have temporarily paused the ingestions of this dataset.

As you might already know, when an occurrence record has a new occurrenceID for a given dataset, our system considers it to be a new occurrence.
This means that it will be given a new gbifid and a new occurrence URL (like this one: https://www.gbif.org/occurrence/1252968762) and the old gbifid and URL will be deprecated.

In this case, this means that the occurrence URLs would be deprecated when ingesting the newest versions of these datasets.

We would like to check with you if those changes were intentional. Do you know if this is the case?
Please let us know, thanks! We are happy to resume the dataset ingestion.

Note that some users rely on those occurrence URLs and gbifids (like https://bionomia.net for example). In an attempt to improve
the stability of the occurrence URLs and gbifids, we have implemented a warning system to detect these type of changes in datasets (see this news item).
If the data publisher can provide us with a list of old and new occurrenceIDs per record, we can avoid the identifier and URL changes. Could that be an option?

Please let us know if you have any question. Thanks!

All the best,

</details>


You can skip/fix identifier validation using [the registry UI](https://registry.gbif.org/dataset/34ca7b9c-6a2f-465e-9cac-7d71c792c670/ingestion-history).
