### ISSUE TITLE
Identifiers validation failed for dataset CRI - Herbário Pe. Dr. Raulino Reitz

### ISSUE THREAD

**Issue by gbif-pipelines** [gbif/ingestion-management#16]
Identifier validation failed for the dataset [CRI - Herbário Pe. Dr. Raulino Reitz](https://registry.gbif.org/dataset/bb080d40-c63b-4529-bf21-d1782a81e024):
- Crawler attempt: 390
- Publishing organization: [Universidade do Extremo Sul Catarinense](https://registry.gbif.org/organization/2ccb1a0b-1194-4acf-9921-b5daad99cbb8)
- Publishing country: BRAZIL
- Installation: [speciesLink Network / INCT-HVFF IPT](https://registry.gbif.org/installation/b38ff2b7-c8af-454e-b5af-ee760f0d5bca)
- Number of occurrences indexed for this dataset at the time of the issue: 14781
- Cause: GBIF IDs hit maximum allowed - 50%, duplicates - 100%, total records count 14845, absent records count 14845
- Step metrics: 
```

```

- Pipelines execution steps: [http://api.gbif.org/v1/pipelines/history/execution/3042314/step](http://api.gbif.org/v1/pipelines/history/execution/3042314/step)
<details>
<summary>Publisher email</summary>

Hello,

I am contacting you from the GBIF Secretariat about a dataset published by the [CRI - Herbário Pe. Dr. Raulino Reitz](https://registry.gbif.org/dataset/bb080d40-c63b-4529-bf21-d1782a81e024) : https://doi.org/10.15468/wvampl.
We noticed that the occurrenceIDs were changed. We have temporarily paused the ingestions of this dataset.

As you might already know, when an occurrence record has a new occurrenceID for a given dataset, our system considers it to be a new occurrence.
This means that it will be given a new gbifid and a new occurrence URL (like this one: https://www.gbif.org/occurrence/1252968762) and the old gbifid and URL will be deprecated.

In this case, this means that the occurrence URLs would be deprecated when ingesting the newest versions of these datasets.

We would like to check with you if those changes were intentional. Do you know if this is the case?
Please let us know, thanks! We are happy to resume the dataset ingestion.

Note that some users rely on those occurrence URLs and gbifids (like https://bionomia.net for example). In an attempt to improve
the stability of the occurrence URLs and gbifids, we have implemented a warning system to detect these type of changes in datasets (see this news item).
If the data publisher can provide us with a list of old and new occurrenceIDs per record, we can avoid the identifier and URL changes. Could that be an option?

Please let us know if you have any question. Thanks!

All the best,

</details>

You can skip/fix identifier validation using [the registry UI](https://registry.gbif.org/dataset/bb080d40-c63b-4529-bf21-d1782a81e024/ingestion-history).

**Comment by jhnwllr** [comment]
contacted 07-18-2023

**Comment by gbif-pipelines** [comment]
Identifier validation still  failing for the dataset [CRI - Herbário Pe. Dr. Raulino Reitz](https://registry.gbif.org/dataset/bb080d40-c63b-4529-bf21-d1782a81e024):
- Crawler attempt: 394
- Publishing organization: [Universidade do Extremo Sul Catarinense](https://registry.gbif.org/organization/2ccb1a0b-1194-4acf-9921-b5daad99cbb8)
- Publishing country: BRAZIL
- Installation: [speciesLink Network / INCT-HVFF IPT](https://registry.gbif.org/installation/b38ff2b7-c8af-454e-b5af-ee760f0d5bca)
- Number of occurrences indexed for this dataset at the time of the issue: 14781
- Cause: GBIF IDs hit maximum allowed - 50%, duplicates - 100%, total records count 14845, absent records count 14845
- Pipelines execution steps: [http://api.gbif.org/v1/pipelines/history/execution/3072451/step](http://api.gbif.org/v1/pipelines/history/execution/3072451/step)
<details>
<summary>Publisher email</summary>

Hello,

I am contacting you from the GBIF Secretariat about a dataset published by the [CRI - Herbário Pe. Dr. Raulino Reitz](https://registry.gbif.org/dataset/bb080d40-c63b-4529-bf21-d1782a81e024) : https://doi.org/10.15468/wvampl.
We noticed that the occurrenceIDs were changed. We have temporarily paused the ingestions of this dataset.

As you might already know, when an occurrence record has a new occurrenceID for a given dataset, our system considers it to be a new occurrence.
This means that it will be given a new gbifid and a new occurrence URL (like this one: https://www.gbif.org/occurrence/1252968762) and the old gbifid and URL will be deprecated.

In this case, this means that the occurrence URLs would be deprecated when ingesting the newest versions of these datasets.

We would like to check with you if those changes were intentional. Do you know if this is the case?
Please let us know, thanks! We are happy to resume the dataset ingestion.

Note that some users rely on those occurrence URLs and gbifids (like https://bionomia.net for example). In an attempt to improve
the stability of the occurrence URLs and gbifids, we have implemented a warning system to detect these type of changes in datasets (see this news item).
If the data publisher can provide us with a list of old and new occurrenceIDs per record, we can avoid the identifier and URL changes. Could that be an option?

Please let us know if you have any question. Thanks!

All the best,

</details>


You can skip/fix identifier validation using [the registry UI](https://registry.gbif.org/dataset/bb080d40-c63b-4529-bf21-d1782a81e024/ingestion-history).

**Comment by gbif-pipelines** [comment]
Identifier validation still  failing for the dataset [CRI - Herbário Pe. Dr. Raulino Reitz](https://registry.gbif.org/dataset/bb080d40-c63b-4529-bf21-d1782a81e024):
- Crawler attempt: 395
- Publishing organization: [Universidade do Extremo Sul Catarinense](https://registry.gbif.org/organization/2ccb1a0b-1194-4acf-9921-b5daad99cbb8)
- Publishing country: BRAZIL
- Installation: [speciesLink Network / INCT-HVFF IPT](https://registry.gbif.org/installation/b38ff2b7-c8af-454e-b5af-ee760f0d5bca)
- Number of occurrences indexed for this dataset at the time of the issue: 14781
- Cause: GBIF IDs hit maximum allowed - 50%, duplicates - 100%, total records count 14845, absent records count 14845
- Pipelines execution steps: [http://api.gbif.org/v1/pipelines/history/execution/3083289/step](http://api.gbif.org/v1/pipelines/history/execution/3083289/step)
<details>
<summary>Publisher email</summary>

Hello,

I am contacting you from the GBIF Secretariat about a dataset published by the [CRI - Herbário Pe. Dr. Raulino Reitz](https://registry.gbif.org/dataset/bb080d40-c63b-4529-bf21-d1782a81e024) : https://doi.org/10.15468/wvampl.
We noticed that the occurrenceIDs were changed. We have temporarily paused the ingestions of this dataset.

As you might already know, when an occurrence record has a new occurrenceID for a given dataset, our system considers it to be a new occurrence.
This means that it will be given a new gbifid and a new occurrence URL (like this one: https://www.gbif.org/occurrence/1252968762) and the old gbifid and URL will be deprecated.

In this case, this means that the occurrence URLs would be deprecated when ingesting the newest versions of these datasets.

We would like to check with you if those changes were intentional. Do you know if this is the case?
Please let us know, thanks! We are happy to resume the dataset ingestion.

Note that some users rely on those occurrence URLs and gbifids (like https://bionomia.net for example). In an attempt to improve
the stability of the occurrence URLs and gbifids, we have implemented a warning system to detect these type of changes in datasets (see this news item).
If the data publisher can provide us with a list of old and new occurrenceIDs per record, we can avoid the identifier and URL changes. Could that be an option?

Please let us know if you have any question. Thanks!

All the best,

</details>


You can skip/fix identifier validation using [the registry UI](https://registry.gbif.org/dataset/bb080d40-c63b-4529-bf21-d1782a81e024/ingestion-history).

**Comment by gbif-pipelines** [comment]
Identifier validation still  failing for the dataset [CRI - Herbário Pe. Dr. Raulino Reitz](https://registry.gbif.org/dataset/bb080d40-c63b-4529-bf21-d1782a81e024):
- Crawler attempt: 396
- Publishing organization: [Universidade do Extremo Sul Catarinense](https://registry.gbif.org/organization/2ccb1a0b-1194-4acf-9921-b5daad99cbb8)
- Publishing country: BRAZIL
- Installation: [speciesLink Network / INCT-HVFF IPT](https://registry.gbif.org/installation/b38ff2b7-c8af-454e-b5af-ee760f0d5bca)
- Number of occurrences indexed for this dataset at the time of the issue: 14781
- Cause: GBIF IDs hit maximum allowed - 50%, duplicates - 100%, total records count 14845, absent records count 14845
- Pipelines execution steps: [http://api.gbif.org/v1/pipelines/history/execution/3083844/step](http://api.gbif.org/v1/pipelines/history/execution/3083844/step)
<details>
<summary>Publisher email</summary>

Hello,

I am contacting you from the GBIF Secretariat about a dataset published by the [CRI - Herbário Pe. Dr. Raulino Reitz](https://registry.gbif.org/dataset/bb080d40-c63b-4529-bf21-d1782a81e024) : https://doi.org/10.15468/wvampl.
We noticed that the occurrenceIDs were changed. We have temporarily paused the ingestions of this dataset.

As you might already know, when an occurrence record has a new occurrenceID for a given dataset, our system considers it to be a new occurrence.
This means that it will be given a new gbifid and a new occurrence URL (like this one: https://www.gbif.org/occurrence/1252968762) and the old gbifid and URL will be deprecated.

In this case, this means that the occurrence URLs would be deprecated when ingesting the newest versions of these datasets.

We would like to check with you if those changes were intentional. Do you know if this is the case?
Please let us know, thanks! We are happy to resume the dataset ingestion.

Note that some users rely on those occurrence URLs and gbifids (like https://bionomia.net for example). In an attempt to improve
the stability of the occurrence URLs and gbifids, we have implemented a warning system to detect these type of changes in datasets (see this news item).
If the data publisher can provide us with a list of old and new occurrenceIDs per record, we can avoid the identifier and URL changes. Could that be an option?

Please let us know if you have any question. Thanks!

All the best,

</details>


You can skip/fix identifier validation using [the registry UI](https://registry.gbif.org/dataset/bb080d40-c63b-4529-bf21-d1782a81e024/ingestion-history).

**Comment by gbif-pipelines** [comment]
Identifier validation still  failing for the dataset [CRI - Herbário Pe. Dr. Raulino Reitz](https://registry.gbif.org/dataset/bb080d40-c63b-4529-bf21-d1782a81e024):
- Crawler attempt: 397
- Publishing organization: [Universidade do Extremo Sul Catarinense](https://registry.gbif.org/organization/2ccb1a0b-1194-4acf-9921-b5daad99cbb8)
- Publishing country: BRAZIL
- Installation: [speciesLink Network / INCT-HVFF IPT](https://registry.gbif.org/installation/b38ff2b7-c8af-454e-b5af-ee760f0d5bca)
- Number of occurrences indexed for this dataset at the time of the issue: 14781
- Cause: GBIF IDs hit maximum allowed - 50%, duplicates - 100%, total records count 14845, absent records count 14845
- Pipelines execution steps: [http://api.gbif.org/v1/pipelines/history/execution/3096218/step](http://api.gbif.org/v1/pipelines/history/execution/3096218/step)
<details>
<summary>Publisher email</summary>

Hello,

I am contacting you from the GBIF Secretariat about a dataset published by the [CRI - Herbário Pe. Dr. Raulino Reitz](https://registry.gbif.org/dataset/bb080d40-c63b-4529-bf21-d1782a81e024) : https://doi.org/10.15468/wvampl.
We noticed that the occurrenceIDs were changed. We have temporarily paused the ingestions of this dataset.

As you might already know, when an occurrence record has a new occurrenceID for a given dataset, our system considers it to be a new occurrence.
This means that it will be given a new gbifid and a new occurrence URL (like this one: https://www.gbif.org/occurrence/1252968762) and the old gbifid and URL will be deprecated.

In this case, this means that the occurrence URLs would be deprecated when ingesting the newest versions of these datasets.

We would like to check with you if those changes were intentional. Do you know if this is the case?
Please let us know, thanks! We are happy to resume the dataset ingestion.

Note that some users rely on those occurrence URLs and gbifids (like https://bionomia.net for example). In an attempt to improve
the stability of the occurrence URLs and gbifids, we have implemented a warning system to detect these type of changes in datasets (see this news item).
If the data publisher can provide us with a list of old and new occurrenceIDs per record, we can avoid the identifier and URL changes. Could that be an option?

Please let us know if you have any question. Thanks!

All the best,

</details>


You can skip/fix identifier validation using [the registry UI](https://registry.gbif.org/dataset/bb080d40-c63b-4529-bf21-d1782a81e024/ingestion-history).

**Comment by gbif-pipelines** [comment]
Identifier validation still  failing for the dataset [CRI - Herbário Pe. Dr. Raulino Reitz](https://registry.gbif.org/dataset/bb080d40-c63b-4529-bf21-d1782a81e024):
- Crawler attempt: 398
- Publishing organization: [Universidade do Extremo Sul Catarinense](https://registry.gbif.org/organization/2ccb1a0b-1194-4acf-9921-b5daad99cbb8)
- Publishing country: BRAZIL
- Installation: [speciesLink Network / INCT-HVFF IPT](https://registry.gbif.org/installation/b38ff2b7-c8af-454e-b5af-ee760f0d5bca)
- Number of occurrences indexed for this dataset at the time of the issue: 14781
- Cause: GBIF ID problems exceed 50% threshold: 100% duplicates; 14845 total records; 14845 absent records
- Pipelines execution steps: [http://api.gbif.org/v1/pipelines/history/execution/3173151/step](http://api.gbif.org/v1/pipelines/history/execution/3173151/step)
<details>
<summary>Publisher email</summary>

Hello,

I am contacting you from the GBIF Secretariat about a dataset published by the [CRI - Herbário Pe. Dr. Raulino Reitz](https://registry.gbif.org/dataset/bb080d40-c63b-4529-bf21-d1782a81e024) : https://doi.org/10.15468/wvampl.
We noticed that the occurrenceIDs were changed. We have temporarily paused the ingestions of this dataset.

As you might already know, when an occurrence record has a new occurrenceID for a given dataset, our system considers it to be a new occurrence.
This means that it will be given a new gbifid and a new occurrence URL (like this one: https://www.gbif.org/occurrence/1252968762) and the old gbifid and URL will be deprecated.

In this case, this means that the occurrence URLs would be deprecated when ingesting the newest versions of these datasets.

We would like to check with you if those changes were intentional. Do you know if this is the case?
Please let us know, thanks! We are happy to resume the dataset ingestion.

Note that some users rely on those occurrence URLs and gbifids (like https://bionomia.net for example). In an attempt to improve
the stability of the occurrence URLs and gbifids, we have implemented a warning system to detect these type of changes in datasets (see this news item).
If the data publisher can provide us with a list of old and new occurrenceIDs per record, we can avoid the identifier and URL changes. Could that be an option?

Please let us know if you have any question. Thanks!

All the best,

</details>


You can skip/fix identifier validation using [the registry UI](https://registry.gbif.org/dataset/bb080d40-c63b-4529-bf21-d1782a81e024/ingestion-history).

**Comment by gbif-pipelines** [comment]
Identifier validation still  failing for the dataset [CRI - Herbário Pe. Dr. Raulino Reitz](https://registry.gbif.org/dataset/bb080d40-c63b-4529-bf21-d1782a81e024):
- Crawler attempt: 399
- Publishing organization: [Universidade do Extremo Sul Catarinense](https://registry.gbif.org/organization/2ccb1a0b-1194-4acf-9921-b5daad99cbb8)
- Publishing country: BRAZIL
- Installation: [speciesLink Network / INCT-HVFF IPT](https://registry.gbif.org/installation/b38ff2b7-c8af-454e-b5af-ee760f0d5bca)
- Number of occurrences indexed for this dataset at the time of the issue: 14781
- Cause: GBIF ID problems exceed 50% threshold: 100% duplicates; 14845 total records; 14845 absent records
- Pipelines execution steps: [http://api.gbif.org/v1/pipelines/history/execution/3184849/step](http://api.gbif.org/v1/pipelines/history/execution/3184849/step)
<details>
<summary>Publisher email</summary>

Hello,

I am contacting you from the GBIF Secretariat about a dataset published by the [CRI - Herbário Pe. Dr. Raulino Reitz](https://registry.gbif.org/dataset/bb080d40-c63b-4529-bf21-d1782a81e024) : https://doi.org/10.15468/wvampl.
We noticed that the occurrenceIDs were changed. We have temporarily paused the ingestions of this dataset.

As you might already know, when an occurrence record has a new occurrenceID for a given dataset, our system considers it to be a new occurrence.
This means that it will be given a new gbifid and a new occurrence URL (like this one: https://www.gbif.org/occurrence/1252968762) and the old gbifid and URL will be deprecated.

In this case, this means that the occurrence URLs would be deprecated when ingesting the newest versions of these datasets.

We would like to check with you if those changes were intentional. Do you know if this is the case?
Please let us know, thanks! We are happy to resume the dataset ingestion.

Note that some users rely on those occurrence URLs and gbifids (like https://bionomia.net for example). In an attempt to improve
the stability of the occurrence URLs and gbifids, we have implemented a warning system to detect these type of changes in datasets (see this news item).
If the data publisher can provide us with a list of old and new occurrenceIDs per record, we can avoid the identifier and URL changes. Could that be an option?

Please let us know if you have any question. Thanks!

All the best,

</details>


You can skip/fix identifier validation using [the registry UI](https://registry.gbif.org/dataset/bb080d40-c63b-4529-bf21-d1782a81e024/ingestion-history).

**Comment by gbif-pipelines** [comment]
Identifier validation still  failing for the dataset [CRI - Herbário Pe. Dr. Raulino Reitz](https://registry.gbif.org/dataset/bb080d40-c63b-4529-bf21-d1782a81e024):
- Crawler attempt: 400
- Publishing organization: [Universidade do Extremo Sul Catarinense](https://registry.gbif.org/organization/2ccb1a0b-1194-4acf-9921-b5daad99cbb8)
- Publishing country: BRAZIL
- Installation: [speciesLink Network / INCT-HVFF IPT](https://registry.gbif.org/installation/b38ff2b7-c8af-454e-b5af-ee760f0d5bca)
- Number of occurrences indexed for this dataset at the time of the issue: 14781
- Cause: GBIF ID problems exceed 50% threshold: 100% duplicates; 14845 total records; 14845 absent records
- Pipelines execution steps: [http://api.gbif.org/v1/pipelines/history/execution/3257832/step](http://api.gbif.org/v1/pipelines/history/execution/3257832/step)
<details>
<summary>Publisher email</summary>

Hello,

I am contacting you from the GBIF Secretariat about a dataset published by the [CRI - Herbário Pe. Dr. Raulino Reitz](https://registry.gbif.org/dataset/bb080d40-c63b-4529-bf21-d1782a81e024) : https://doi.org/10.15468/wvampl.
We noticed that the occurrenceIDs were changed. We have temporarily paused the ingestions of this dataset.

As you might already know, when an occurrence record has a new occurrenceID for a given dataset, our system considers it to be a new occurrence.
This means that it will be given a new gbifid and a new occurrence URL (like this one: https://www.gbif.org/occurrence/1252968762) and the old gbifid and URL will be deprecated.

In this case, this means that the occurrence URLs would be deprecated when ingesting the newest versions of these datasets.

We would like to check with you if those changes were intentional. Do you know if this is the case?
Please let us know, thanks! We are happy to resume the dataset ingestion.

Note that some users rely on those occurrence URLs and gbifids (like https://bionomia.net for example). In an attempt to improve
the stability of the occurrence URLs and gbifids, we have implemented a warning system to detect these type of changes in datasets (see this news item).
If the data publisher can provide us with a list of old and new occurrenceIDs per record, we can avoid the identifier and URL changes. Could that be an option?

Please let us know if you have any question. Thanks!

All the best,

</details>


You can skip/fix identifier validation using [the registry UI](https://registry.gbif.org/dataset/bb080d40-c63b-4529-bf21-d1782a81e024/ingestion-history).

**Comment by jhnwllr** [comment]
closing because no response from publisher
