### ISSUE TITLE
Identifiers validation failed for dataset University of British Columbia Herbarium (UBC) - Fungi Collection

### ISSUE THREAD

**Issue by gbif-pipelines** [gbif/ingestion-management#1605]
Identifier validation failed for the dataset [University of British Columbia Herbarium (UBC) - Fungi Collection](https://registry.gbif.org/dataset/ca1bcd7e-7387-42f9-81ba-1470db55e3e8):
- Crawler attempt: 359
- Publishing organization: [University of British Columbia](https://registry.gbif.org/organization/b542788f-0dc2-4a2b-b652-fceced449591)
- Publishing country: CANADA
- Installation: [Canadensys repository](https://registry.gbif.org/installation/7c519b4c-1100-4f39-a95a-9b679b4542e4)
- Number of occurrences indexed for this dataset at the time of the issue: 33150
- Cause: GBIF ID problems exceed 50% threshold: 100% duplicates; 34974 total records; 34972 absent records
- Pipelines execution steps: [http://api.gbif.org/v1/pipelines/history/execution/4241130/step](http://api.gbif.org/v1/pipelines/history/execution/4241130/step)

```
New IDs sample:

2A5BF98C-1B1E-F945-AD41-B179E0C3773D
658F34E2-1ED5-D84D-B047-1582BFF6F1B7
```

```
Old IDs sample:

97682755-2B4C-6C42-9361-7C7110EA0777
5D52D7C2-EF4E-0A4B-B898-36DB42B33AFB
55B43FCF-A68F-AC49-B63B-7435777CC8F8
ECC3C915-C09B-D746-B9DA-09B812A57F74
F91D1B91-F51D-184B-9D30-D3677DE6CC12
75026115-3774-5A48-8536-5E3CD640EC71
82A4A4DE-67B3-9140-B86D-8A07F616489C
B4871603-B50D-EF4F-B599-E379B118DF05
33C14B05-8168-D243-AA19-2437E3C22FAE
734F8718-68EF-4149-AF72-2CBE125AF2D4
```

<details>
<summary>Publisher email</summary>

Hello,

I am contacting you from the GBIF Secretariat about a dataset published by the [University of British Columbia Herbarium (UBC) - Fungi Collection](https://registry.gbif.org/dataset/ca1bcd7e-7387-42f9-81ba-1470db55e3e8) : https://doi.org/10.5886/h4px7g4b.
We noticed that the occurrenceIDs were changed. We have temporarily paused the ingestions of this dataset.

As you might already know, when an occurrence record has a new occurrenceID for a given dataset, our system considers it to be a new occurrence.
This means that it will be given a new gbifid and a new occurrence URL (like this one: https://www.gbif.org/occurrence/1252968762) and the old gbifid and URL will be deprecated.

In this case, this means that the occurrence URLs would be deprecated when ingesting the newest versions of these datasets.

We would like to check with you if those changes were intentional. Do you know if this is the case?
Please let us know, thanks! We are happy to resume the dataset ingestion.

Note that some users rely on those occurrence URLs and gbifids (like https://bionomia.net for example). In an attempt to improve
the stability of the occurrence URLs and gbifids, we have implemented a warning system to detect these type of changes in datasets (see this news item).
If the data publisher can provide us with a list of old and new occurrenceIDs per record, we can avoid the identifier and URL changes. Could that be an option?

Please let us know if you have any question. Thanks!

All the best,

</details>

You can skip/fix identifier validation using [the registry UI](https://registry.gbif.org/dataset/ca1bcd7e-7387-42f9-81ba-1470db55e3e8/ingestion-history).

**Comment by mpitblado** [comment]
Good afternoon,

No need to send the email, I will look into this and correct it!

**Comment by mpitblado** [comment]
Thanks for the warning, now solved and next version successfully pushed out to resolve conflict.
