### ISSUE TITLE
Identifiers validation failed for dataset Mediterranean Germplams Genebank - Triticum collection (ITA436-MGG-Triticum)

### ISSUE THREAD

**Issue by gbif-pipelines** [gbif/ingestion-management#1618]
Identifier validation failed for the dataset [Mediterranean Germplams Genebank - Triticum collection (ITA436-MGG-Triticum)](https://registry.gbif.org/dataset/dd10d30a-76f7-47fa-abeb-a213f1646f12):
- Crawler attempt: 82
- Publishing organization: [Consiglio Nazionale delle Ricerche, Istituto di Bioscienze e BioRisorse (CNR-IBBR)](https://registry.gbif.org/organization/6563e0ba-fab7-431c-b897-b6bf364f4f1e)
- Publishing country: ITALY
- Installation: [Institute of Biosciences and Bioresources CNR-IBBR, Bari, Italy](https://registry.gbif.org/installation/28a58a05-55e0-4f3a-9ad3-7e0137247f80)
- Number of occurrences indexed for this dataset at the time of the issue: 14310
- Cause: GBIF ID problems exceed 50% threshold: 100% duplicates; 14310 total records; 14310 absent records
- Pipelines execution steps: [http://api.gbif.org/v1/pipelines/history/execution/4334450/step](http://api.gbif.org/v1/pipelines/history/execution/4334450/step)

```
New IDs sample:


```

```
Old IDs sample:

https://biomemory.cnr.it/dbrecord/b5180f26-efa0-8579-56c2-46f33a9f7bf6
https://biomemory.cnr.it/dbrecord/1be0ae52-e944-3949-076b-1f9db0120336
https://biomemory.cnr.it/dbrecord/208e9b5f-9be1-dc22-faa0-033b978fa0bc
https://biomemory.cnr.it/dbrecord/3941d9d3-8f63-2b0b-a2ff-f0733740b40c
https://biomemory.cnr.it/dbrecord/3d74483f-06ca-b53a-7c26-6a0a2c305bee
https://biomemory.cnr.it/dbrecord/3d7d9b46-34f8-6183-ed56-34cfbd1a9b0a
https://biomemory.cnr.it/dbrecord/44d10476-42b2-5fad-1887-17d54861b5b1
https://biomemory.cnr.it/dbrecord/4c8fcafe-c890-2d3e-3942-4f76e4843375
https://biomemory.cnr.it/dbrecord/4f5eaa46-8f60-b13d-75b4-462cd735945d
https://biomemory.cnr.it/dbrecord/5deafbb9-c7e9-3e44-d09d-279fb40b01b2
```

<details>
<summary>Publisher email</summary>

Hello,

I am contacting you from the GBIF Secretariat about a dataset published by the [Mediterranean Germplams Genebank - Triticum collection (ITA436-MGG-Triticum)](https://registry.gbif.org/dataset/dd10d30a-76f7-47fa-abeb-a213f1646f12) : https://doi.org/10.15468/frm59p.
We noticed that the occurrenceIDs were changed. We have temporarily paused the ingestions of this dataset.

As you might already know, when an occurrence record has a new occurrenceID for a given dataset, our system considers it to be a new occurrence.
This means that it will be given a new gbifid and a new occurrence URL (like this one: https://www.gbif.org/occurrence/1252968762) and the old gbifid and URL will be deprecated.

In this case, this means that the occurrence URLs would be deprecated when ingesting the newest versions of these datasets.

We would like to check with you if those changes were intentional. Do you know if this is the case?
Please let us know, thanks! We are happy to resume the dataset ingestion.

Note that some users rely on those occurrence URLs and gbifids (like https://bionomia.net for example). In an attempt to improve
the stability of the occurrence URLs and gbifids, we have implemented a warning system to detect these type of changes in datasets (see this news item).
If the data publisher can provide us with a list of old and new occurrenceIDs per record, we can avoid the identifier and URL changes. Could that be an option?

Please let us know if you have any question. Thanks!

All the best,

</details>

You can skip/fix identifier validation using [the registry UI](https://registry.gbif.org/dataset/dd10d30a-76f7-47fa-abeb-a213f1646f12/ingestion-history).

**Comment by jhnwllr** [comment]
@spalp @OlegBorodin77 do you have any contact with these publishers?

**Comment by gbif-pipelines** [comment]
Identifier validation still  failing for the dataset [Mediterranean Germplams Genebank - Triticum collection (ITA436-MGG-Triticum)](https://registry.gbif.org/dataset/dd10d30a-76f7-47fa-abeb-a213f1646f12):
- Crawler attempt: 83
- Publishing organization: [Consiglio Nazionale delle Ricerche, Istituto di Bioscienze e BioRisorse (CNR-IBBR)](https://registry.gbif.org/organization/6563e0ba-fab7-431c-b897-b6bf364f4f1e)
- Publishing country: ITALY
- Installation: [Institute of Biosciences and Bioresources CNR-IBBR, Bari, Italy](https://registry.gbif.org/installation/28a58a05-55e0-4f3a-9ad3-7e0137247f80)
- Number of occurrences indexed for this dataset at the time of the issue: 14310
- Cause: GBIF ID problems exceed 50% threshold: 100% duplicates; 14310 total records; 14310 absent records
- Pipelines execution steps: [http://api.gbif.org/v1/pipelines/history/execution/4335581/step](http://api.gbif.org/v1/pipelines/history/execution/4335581/step)

```
New IDs sample:


```


```
Old IDs sample:

https://biomemory.cnr.it/dbrecord/b5180f26-efa0-8579-56c2-46f33a9f7bf6
https://biomemory.cnr.it/dbrecord/1be0ae52-e944-3949-076b-1f9db0120336
https://biomemory.cnr.it/dbrecord/208e9b5f-9be1-dc22-faa0-033b978fa0bc
https://biomemory.cnr.it/dbrecord/3941d9d3-8f63-2b0b-a2ff-f0733740b40c
https://biomemory.cnr.it/dbrecord/3d74483f-06ca-b53a-7c26-6a0a2c305bee
https://biomemory.cnr.it/dbrecord/3d7d9b46-34f8-6183-ed56-34cfbd1a9b0a
https://biomemory.cnr.it/dbrecord/44d10476-42b2-5fad-1887-17d54861b5b1
https://biomemory.cnr.it/dbrecord/4c8fcafe-c890-2d3e-3942-4f76e4843375
https://biomemory.cnr.it/dbrecord/4f5eaa46-8f60-b13d-75b4-462cd735945d
https://biomemory.cnr.it/dbrecord/5deafbb9-c7e9-3e44-d09d-279fb40b01b2
```

<details>
<summary>Publisher email</summary>

Hello,

I am contacting you from the GBIF Secretariat about a dataset published by the [Mediterranean Germplams Genebank - Triticum collection (ITA436-MGG-Triticum)](https://registry.gbif.org/dataset/dd10d30a-76f7-47fa-abeb-a213f1646f12) : https://doi.org/10.15468/frm59p.
We noticed that the occurrenceIDs were changed. We have temporarily paused the ingestions of this dataset.

As you might already know, when an occurrence record has a new occurrenceID for a given dataset, our system considers it to be a new occurrence.
This means that it will be given a new gbifid and a new occurrence URL (like this one: https://www.gbif.org/occurrence/1252968762) and the old gbifid and URL will be deprecated.

In this case, this means that the occurrence URLs would be deprecated when ingesting the newest versions of these datasets.

We would like to check with you if those changes were intentional. Do you know if this is the case?
Please let us know, thanks! We are happy to resume the dataset ingestion.

Note that some users rely on those occurrence URLs and gbifids (like https://bionomia.net for example). In an attempt to improve
the stability of the occurrence URLs and gbifids, we have implemented a warning system to detect these type of changes in datasets (see this news item).
If the data publisher can provide us with a list of old and new occurrenceIDs per record, we can avoid the identifier and URL changes. Could that be an option?

Please let us know if you have any question. Thanks!

All the best,

</details>


You can skip/fix identifier validation using [the registry UI](https://registry.gbif.org/dataset/dd10d30a-76f7-47fa-abeb-a213f1646f12/ingestion-history).

**Comment by spalp** [comment]
> [@spalp](https://github.com/spalp) [@OlegBorodin77](https://github.com/OlegBorodin77) do you have any contact with these publishers?

I have been in contact only with CNR-ISMAR (they publish their datasets via the ECA cloud IPT), not CNR-IBBR.
