### ISSUE TITLE
Identifiers validation failed for dataset Palaeozoological Collections (PZ), Swedish Museum of Natural History (NRM)

### ISSUE THREAD

**Issue by gbif-pipelines** [gbif/ingestion-management#1628]
Identifier validation failed for the dataset [Palaeozoological Collections (PZ), Swedish Museum of Natural History (NRM)](https://registry.gbif.org/dataset/20ab8294-5253-46ca-bdb2-eab1b5e75657):
- Crawler attempt: 1075
- Publishing organization: [Swedish Museum of Natural History](https://registry.gbif.org/organization/6ba9a8cc-513a-4a51-bf93-6f5de8040a96)
- Publishing country: SWEDEN
- Installation: [IPT GBIF-Sweden](https://registry.gbif.org/installation/4346b227-ca68-4d54-8a77-909148492e0b)
- Number of occurrences indexed for this dataset at the time of the issue: 74109
- Cause: GBIF ID problems exceed 50% threshold: 100% duplicates; 360772 total records; 360772 absent records
- Pipelines execution steps: [http://api.gbif.org/v1/pipelines/history/execution/4418062/step](http://api.gbif.org/v1/pipelines/history/execution/4418062/step)

```
New IDs sample:


```

```
Old IDs sample:

NRM:PZ:389797
NRM:PZ:389799
NRM:PZ:389800
NRM:PZ:389801
NRM:PZ:389802
NRM:PZ:389803
NRM:PZ:389804
NRM:PZ:389807
NRM:PZ:389808
NRM:PZ:389809
```

<details>
<summary>Publisher email</summary>

Hello,

I am contacting you from the GBIF Secretariat about a dataset published by the [Palaeozoological Collections (PZ), Swedish Museum of Natural History (NRM)](https://registry.gbif.org/dataset/20ab8294-5253-46ca-bdb2-eab1b5e75657) : https://doi.org/10.15468/zffolj.
We noticed that the occurrenceIDs were changed. We have temporarily paused the ingestions of this dataset.

As you might already know, when an occurrence record has a new occurrenceID for a given dataset, our system considers it to be a new occurrence.
This means that it will be given a new gbifid and a new occurrence URL (like this one: https://www.gbif.org/occurrence/1252968762) and the old gbifid and URL will be deprecated.

In this case, this means that the occurrence URLs would be deprecated when ingesting the newest versions of these datasets.

We would like to check with you if those changes were intentional. Do you know if this is the case?
Please let us know, thanks! We are happy to resume the dataset ingestion.

Note that some users rely on those occurrence URLs and gbifids (like https://bionomia.net for example). In an attempt to improve
the stability of the occurrence URLs and gbifids, we have implemented a warning system to detect these type of changes in datasets (see this news item).
If the data publisher can provide us with a list of old and new occurrenceIDs per record, we can avoid the identifier and URL changes. Could that be an option?

Please let us know if you have any question. Thanks!

All the best,

</details>

You can skip/fix identifier validation using [the registry UI](https://registry.gbif.org/dataset/20ab8294-5253-46ca-bdb2-eab1b5e75657/ingestion-history).

**Comment by gbif-pipelines** [comment]
Identifier validation still  failing for the dataset [Palaeozoological Collections (PZ), Swedish Museum of Natural History (NRM)](https://registry.gbif.org/dataset/20ab8294-5253-46ca-bdb2-eab1b5e75657):
- Crawler attempt: 1077
- Publishing organization: [Swedish Museum of Natural History](https://registry.gbif.org/organization/6ba9a8cc-513a-4a51-bf93-6f5de8040a96)
- Publishing country: SWEDEN
- Installation: [IPT GBIF-Sweden](https://registry.gbif.org/installation/4346b227-ca68-4d54-8a77-909148492e0b)
- Number of occurrences indexed for this dataset at the time of the issue: 74109
- Cause: GBIF ID problems exceed 50% threshold: 80% duplicates; 360772 total records; 287923 absent records
- Pipelines execution steps: [http://api.gbif.org/v1/pipelines/history/execution/4423517/step](http://api.gbif.org/v1/pipelines/history/execution/4423517/step)

```
New IDs sample:

NRM:PAL:Ar0018417
NRM:PAL:Ar0018446
NRM:PAL:Ar0018438
NRM:PAL:Ar0018445
NRM:PAL:Ar0018458
NRM:PAL:Ar0018453
NRM:PAL:Ar0018468
NRM:PAL:Ar0007878
NRM:PAL:Ar0007872
NRM:PAL:Ar0007874
```


```
Old IDs sample:

NRM:PZ:389797
NRM:PZ:389799
NRM:PZ:389800
NRM:PZ:389801
NRM:PZ:389802
NRM:PZ:389803
NRM:PZ:389804
NRM:PZ:389807
NRM:PZ:389808
NRM:PZ:389809
```

<details>
<summary>Publisher email</summary>

Hello,

I am contacting you from the GBIF Secretariat about a dataset published by the [Palaeozoological Collections (PZ), Swedish Museum of Natural History (NRM)](https://registry.gbif.org/dataset/20ab8294-5253-46ca-bdb2-eab1b5e75657) : https://doi.org/10.15468/zffolj.
We noticed that the occurrenceIDs were changed. We have temporarily paused the ingestions of this dataset.

As you might already know, when an occurrence record has a new occurrenceID for a given dataset, our system considers it to be a new occurrence.
This means that it will be given a new gbifid and a new occurrence URL (like this one: https://www.gbif.org/occurrence/1252968762) and the old gbifid and URL will be deprecated.

In this case, this means that the occurrence URLs would be deprecated when ingesting the newest versions of these datasets.

We would like to check with you if those changes were intentional. Do you know if this is the case?
Please let us know, thanks! We are happy to resume the dataset ingestion.

Note that some users rely on those occurrence URLs and gbifids (like https://bionomia.net for example). In an attempt to improve
the stability of the occurrence URLs and gbifids, we have implemented a warning system to detect these type of changes in datasets (see this news item).
If the data publisher can provide us with a list of old and new occurrenceIDs per record, we can avoid the identifier and URL changes. Could that be an option?

Please let us know if you have any question. Thanks!

All the best,

</details>


You can skip/fix identifier validation using [the registry UI](https://registry.gbif.org/dataset/20ab8294-5253-46ca-bdb2-eab1b5e75657/ingestion-history).

**Comment by ManonGros** [comment]
The node sent us a file to migrate occurrenceID (we migrated them). The dataset was still stopped because of the large number of new records. I have let the ingestion go through.
