### ISSUE TITLE
Identifiers validation failed for dataset JOI - Herbário Joinvillea

### ISSUE THREAD

**Issue by gbif-pipelines** [gbif/ingestion-management#18]
Identifier validation failed for the dataset [JOI - Herbário Joinvillea](https://registry.gbif.org/dataset/05776b2b-eda0-4a70-ba81-986e3f100e1a):
- Crawler attempt: 336
- Publishing organization: [Universidade da Região de Joinville](https://registry.gbif.org/organization/efe6e324-c6aa-4ed0-9693-80e7ba5bab12)
- Publishing country: BRAZIL
- Installation: [speciesLink Network / INCT-HVFF IPT](https://registry.gbif.org/installation/b38ff2b7-c8af-454e-b5af-ee760f0d5bca)
- Number of occurrences indexed for this dataset at the time of the issue: 18112
- Cause: GBIF IDs hit maximum allowed - 50%, duplicates - 100%, total records count 18153, absent records count 18153
- Step metrics: 
```

```

- Pipelines execution steps: [http://api.gbif.org/v1/pipelines/history/execution/3042367/step](http://api.gbif.org/v1/pipelines/history/execution/3042367/step)
<details>
<summary>Publisher email</summary>

Hello,

I am contacting you from the GBIF Secretariat about a dataset published by the [JOI - Herbário Joinvillea](https://registry.gbif.org/dataset/05776b2b-eda0-4a70-ba81-986e3f100e1a) : https://doi.org/10.15468/xykprp.
We noticed that the occurrenceIDs were changed. We have temporarily paused the ingestions of this dataset.

As you might already know, when an occurrence record has a new occurrenceID for a given dataset, our system considers it to be a new occurrence.
This means that it will be given a new gbifid and a new occurrence URL (like this one: https://www.gbif.org/occurrence/1252968762) and the old gbifid and URL will be deprecated.

In this case, this means that the occurrence URLs would be deprecated when ingesting the newest versions of these datasets.

We would like to check with you if those changes were intentional. Do you know if this is the case?
Please let us know, thanks! We are happy to resume the dataset ingestion.

Note that some users rely on those occurrence URLs and gbifids (like https://bionomia.net for example). In an attempt to improve
the stability of the occurrence URLs and gbifids, we have implemented a warning system to detect these type of changes in datasets (see this news item).
If the data publisher can provide us with a list of old and new occurrenceIDs per record, we can avoid the identifier and URL changes. Could that be an option?

Please let us know if you have any question. Thanks!

All the best,

</details>

You can skip/fix identifier validation using [the registry UI](https://registry.gbif.org/dataset/05776b2b-eda0-4a70-ba81-986e3f100e1a/ingestion-history).

**Comment by jhnwllr** [comment]
contacted 04-14-2023

**Comment by gbif-pipelines** [comment]
Identifier validation still  failing for the dataset [JOI - Herbário Joinvillea](https://registry.gbif.org/dataset/05776b2b-eda0-4a70-ba81-986e3f100e1a):
- Crawler attempt: 338
- Publishing organization: [Universidade da Região de Joinville](https://registry.gbif.org/organization/efe6e324-c6aa-4ed0-9693-80e7ba5bab12)
- Publishing country: BRAZIL
- Installation: [speciesLink Network / INCT-HVFF IPT](https://registry.gbif.org/installation/b38ff2b7-c8af-454e-b5af-ee760f0d5bca)
- Number of occurrences indexed for this dataset at the time of the issue: 18112
- Cause: GBIF IDs hit maximum allowed - 50%, duplicates - 100%, total records count 18153, absent records count 18153
- Step metrics: 
```

```

- Pipelines execution steps: [http://api.gbif.org/v1/pipelines/history/execution/3052515/step](http://api.gbif.org/v1/pipelines/history/execution/3052515/step)
<details>
<summary>Publisher email</summary>

Hello,

I am contacting you from the GBIF Secretariat about a dataset published by the [JOI - Herbário Joinvillea](https://registry.gbif.org/dataset/05776b2b-eda0-4a70-ba81-986e3f100e1a) : https://doi.org/10.15468/xykprp.
We noticed that the occurrenceIDs were changed. We have temporarily paused the ingestions of this dataset.

As you might already know, when an occurrence record has a new occurrenceID for a given dataset, our system considers it to be a new occurrence.
This means that it will be given a new gbifid and a new occurrence URL (like this one: https://www.gbif.org/occurrence/1252968762) and the old gbifid and URL will be deprecated.

In this case, this means that the occurrence URLs would be deprecated when ingesting the newest versions of these datasets.

We would like to check with you if those changes were intentional. Do you know if this is the case?
Please let us know, thanks! We are happy to resume the dataset ingestion.

Note that some users rely on those occurrence URLs and gbifids (like https://bionomia.net for example). In an attempt to improve
the stability of the occurrence URLs and gbifids, we have implemented a warning system to detect these type of changes in datasets (see this news item).
If the data publisher can provide us with a list of old and new occurrenceIDs per record, we can avoid the identifier and URL changes. Could that be an option?

Please let us know if you have any question. Thanks!

All the best,

</details>


You can skip/fix identifier validation using [the registry UI](https://registry.gbif.org/dataset/05776b2b-eda0-4a70-ba81-986e3f100e1a/ingestion-history).

**Comment by gbif-pipelines** [comment]
Identifier validation still  failing for the dataset [JOI - Herbário Joinvillea](https://registry.gbif.org/dataset/05776b2b-eda0-4a70-ba81-986e3f100e1a):
- Crawler attempt: 338
- Publishing organization: [Universidade da Região de Joinville](https://registry.gbif.org/organization/efe6e324-c6aa-4ed0-9693-80e7ba5bab12)
- Publishing country: BRAZIL
- Installation: [speciesLink Network / INCT-HVFF IPT](https://registry.gbif.org/installation/b38ff2b7-c8af-454e-b5af-ee760f0d5bca)
- Number of occurrences indexed for this dataset at the time of the issue: 18112
- Cause: GBIF IDs hit maximum allowed - 50%, duplicates - 100%, total records count 18153, absent records count 18153
- Pipelines execution steps: [http://api.gbif.org/v1/pipelines/history/execution/3062050/step](http://api.gbif.org/v1/pipelines/history/execution/3062050/step)
<details>
<summary>Publisher email</summary>

Hello,

I am contacting you from the GBIF Secretariat about a dataset published by the [JOI - Herbário Joinvillea](https://registry.gbif.org/dataset/05776b2b-eda0-4a70-ba81-986e3f100e1a) : https://doi.org/10.15468/xykprp.
We noticed that the occurrenceIDs were changed. We have temporarily paused the ingestions of this dataset.

As you might already know, when an occurrence record has a new occurrenceID for a given dataset, our system considers it to be a new occurrence.
This means that it will be given a new gbifid and a new occurrence URL (like this one: https://www.gbif.org/occurrence/1252968762) and the old gbifid and URL will be deprecated.

In this case, this means that the occurrence URLs would be deprecated when ingesting the newest versions of these datasets.

We would like to check with you if those changes were intentional. Do you know if this is the case?
Please let us know, thanks! We are happy to resume the dataset ingestion.

Note that some users rely on those occurrence URLs and gbifids (like https://bionomia.net for example). In an attempt to improve
the stability of the occurrence URLs and gbifids, we have implemented a warning system to detect these type of changes in datasets (see this news item).
If the data publisher can provide us with a list of old and new occurrenceIDs per record, we can avoid the identifier and URL changes. Could that be an option?

Please let us know if you have any question. Thanks!

All the best,

</details>


You can skip/fix identifier validation using [the registry UI](https://registry.gbif.org/dataset/05776b2b-eda0-4a70-ba81-986e3f100e1a/ingestion-history).

**Comment by gbif-pipelines** [comment]
Identifier validation still  failing for the dataset [JOI - Herbário Joinvillea](https://registry.gbif.org/dataset/05776b2b-eda0-4a70-ba81-986e3f100e1a):
- Crawler attempt: 339
- Publishing organization: [Universidade da Região de Joinville](https://registry.gbif.org/organization/efe6e324-c6aa-4ed0-9693-80e7ba5bab12)
- Publishing country: BRAZIL
- Installation: [speciesLink Network / INCT-HVFF IPT](https://registry.gbif.org/installation/b38ff2b7-c8af-454e-b5af-ee760f0d5bca)
- Number of occurrences indexed for this dataset at the time of the issue: 18112
- Cause: GBIF IDs hit maximum allowed - 50%, duplicates - 100%, total records count 18153, absent records count 18153
- Pipelines execution steps: [http://api.gbif.org/v1/pipelines/history/execution/3062190/step](http://api.gbif.org/v1/pipelines/history/execution/3062190/step)
<details>
<summary>Publisher email</summary>

Hello,

I am contacting you from the GBIF Secretariat about a dataset published by the [JOI - Herbário Joinvillea](https://registry.gbif.org/dataset/05776b2b-eda0-4a70-ba81-986e3f100e1a) : https://doi.org/10.15468/xykprp.
We noticed that the occurrenceIDs were changed. We have temporarily paused the ingestions of this dataset.

As you might already know, when an occurrence record has a new occurrenceID for a given dataset, our system considers it to be a new occurrence.
This means that it will be given a new gbifid and a new occurrence URL (like this one: https://www.gbif.org/occurrence/1252968762) and the old gbifid and URL will be deprecated.

In this case, this means that the occurrence URLs would be deprecated when ingesting the newest versions of these datasets.

We would like to check with you if those changes were intentional. Do you know if this is the case?
Please let us know, thanks! We are happy to resume the dataset ingestion.

Note that some users rely on those occurrence URLs and gbifids (like https://bionomia.net for example). In an attempt to improve
the stability of the occurrence URLs and gbifids, we have implemented a warning system to detect these type of changes in datasets (see this news item).
If the data publisher can provide us with a list of old and new occurrenceIDs per record, we can avoid the identifier and URL changes. Could that be an option?

Please let us know if you have any question. Thanks!

All the best,

</details>


You can skip/fix identifier validation using [the registry UI](https://registry.gbif.org/dataset/05776b2b-eda0-4a70-ba81-986e3f100e1a/ingestion-history).

**Comment by gbif-pipelines** [comment]
Identifier validation still  failing for the dataset [JOI - Herbário Joinvillea](https://registry.gbif.org/dataset/05776b2b-eda0-4a70-ba81-986e3f100e1a):
- Crawler attempt: 340
- Publishing organization: [Universidade da Região de Joinville](https://registry.gbif.org/organization/efe6e324-c6aa-4ed0-9693-80e7ba5bab12)
- Publishing country: BRAZIL
- Installation: [speciesLink Network / INCT-HVFF IPT](https://registry.gbif.org/installation/b38ff2b7-c8af-454e-b5af-ee760f0d5bca)
- Number of occurrences indexed for this dataset at the time of the issue: 18112
- Cause: GBIF IDs hit maximum allowed - 50%, duplicates - 100%, total records count 18153, absent records count 18153
- Pipelines execution steps: [http://api.gbif.org/v1/pipelines/history/execution/3072487/step](http://api.gbif.org/v1/pipelines/history/execution/3072487/step)
<details>
<summary>Publisher email</summary>

Hello,

I am contacting you from the GBIF Secretariat about a dataset published by the [JOI - Herbário Joinvillea](https://registry.gbif.org/dataset/05776b2b-eda0-4a70-ba81-986e3f100e1a) : https://doi.org/10.15468/xykprp.
We noticed that the occurrenceIDs were changed. We have temporarily paused the ingestions of this dataset.

As you might already know, when an occurrence record has a new occurrenceID for a given dataset, our system considers it to be a new occurrence.
This means that it will be given a new gbifid and a new occurrence URL (like this one: https://www.gbif.org/occurrence/1252968762) and the old gbifid and URL will be deprecated.

In this case, this means that the occurrence URLs would be deprecated when ingesting the newest versions of these datasets.

We would like to check with you if those changes were intentional. Do you know if this is the case?
Please let us know, thanks! We are happy to resume the dataset ingestion.

Note that some users rely on those occurrence URLs and gbifids (like https://bionomia.net for example). In an attempt to improve
the stability of the occurrence URLs and gbifids, we have implemented a warning system to detect these type of changes in datasets (see this news item).
If the data publisher can provide us with a list of old and new occurrenceIDs per record, we can avoid the identifier and URL changes. Could that be an option?

Please let us know if you have any question. Thanks!

All the best,

</details>


You can skip/fix identifier validation using [the registry UI](https://registry.gbif.org/dataset/05776b2b-eda0-4a70-ba81-986e3f100e1a/ingestion-history).

**Comment by jhnwllr** [comment]
Closing because lack of response from publisher.
