### ISSUE TITLE
Identifiers validation failed for dataset CFU of pink-pigmented facultative methylotrophs per gramm leaf fresh weight

### ISSUE THREAD

**Issue by gbif-pipelines** [gbif/ingestion-management#183]
Identifier validation failed for the dataset [CFU of pink-pigmented facultative methylotrophs per gramm leaf fresh weight](https://registry.gbif.org/dataset/b60b46be-25ba-470a-8675-849d896dbe65):
- Crawler attempt: 287
- Publishing organization: [Biodiversity Exploratories](https://registry.gbif.org/organization/541c2668-9391-4479-b90f-fe90b365f33b)
- Publishing country: GERMANY
- Installation: [Biodiversity Exploratories HTTP installation](https://registry.gbif.org/installation/708736d8-ee11-4d9e-bbcd-3e68967143a7)
- Number of occurrences indexed for this dataset at the time of the issue: 66
- Cause: GBIF IDs hit maximum allowed - 50%, duplicates - 100%, total records count 66, absent records count 66
- Pipelines execution steps: [http://api.gbif.org/v1/pipelines/history/execution/3085326/step](http://api.gbif.org/v1/pipelines/history/execution/3085326/step)
<details>
<summary>Publisher email</summary>

Hello,

I am contacting you from the GBIF Secretariat about a dataset published by the [CFU of pink-pigmented facultative methylotrophs per gramm leaf fresh weight](https://registry.gbif.org/dataset/b60b46be-25ba-470a-8675-849d896dbe65) : https://doi.org/10.15468/2ftmey.
We noticed that the occurrenceIDs were changed. We have temporarily paused the ingestions of this dataset.

As you might already know, when an occurrence record has a new occurrenceID for a given dataset, our system considers it to be a new occurrence.
This means that it will be given a new gbifid and a new occurrence URL (like this one: https://www.gbif.org/occurrence/1252968762) and the old gbifid and URL will be deprecated.

In this case, this means that the occurrence URLs would be deprecated when ingesting the newest versions of these datasets.

We would like to check with you if those changes were intentional. Do you know if this is the case?
Please let us know, thanks! We are happy to resume the dataset ingestion.

Note that some users rely on those occurrence URLs and gbifids (like https://bionomia.net for example). In an attempt to improve
the stability of the occurrence URLs and gbifids, we have implemented a warning system to detect these type of changes in datasets (see this news item).
If the data publisher can provide us with a list of old and new occurrenceIDs per record, we can avoid the identifier and URL changes. Could that be an option?

Please let us know if you have any question. Thanks!

All the best,

</details>

You can skip/fix identifier validation using [the registry UI](https://registry.gbif.org/dataset/b60b46be-25ba-470a-8675-849d896dbe65/ingestion-history).

**Comment by ktotsum** [comment]
There was no change of the IDs and this happened due to the wrong link on their repository. Data ingestion was successful on 2023-08-21.
