### ISSUE TITLE
Identifiers validation failed for dataset UCR - University of California, Riverside Herbarium - Vascular Plants

### ISSUE THREAD

**Issue by gbif-pipelines** [gbif/ingestion-management#19]
Identifier validation failed for the dataset [UCR - University of California, Riverside Herbarium - Vascular Plants](https://registry.gbif.org/dataset/e523cf2d-4fc2-48d8-aa75-80ecbc90b3f5):
- Crawler attempt: 208
- Publishing organization: [University of California Riverside](https://registry.gbif.org/organization/53e59855-7653-4d3e-87cc-162021713823)
- Publishing country: UNITED_STATES
- Installation: [Consortium of California Herbaria, CCH2 Portal](https://registry.gbif.org/installation/cb27a4ab-3360-4cf5-b5de-48a06a9c47ae)
- Number of occurrences indexed for this dataset at the time of the issue: 275289
- Cause: GBIF IDs hit maximum allowed - 50%, duplicates - 52%, total records count 459, absent records count 237
- Step metrics: 
```

```

- Pipelines execution steps: [http://api.gbif.org/v1/pipelines/history/execution/3042401/step](http://api.gbif.org/v1/pipelines/history/execution/3042401/step)
<details>
<summary>Publisher email</summary>

Hello,

I am contacting you from the GBIF Secretariat about a dataset published by the [UCR - University of California, Riverside Herbarium - Vascular Plants](https://registry.gbif.org/dataset/e523cf2d-4fc2-48d8-aa75-80ecbc90b3f5) : https://doi.org/10.15468/ai1kou.
We noticed that the occurrenceIDs were changed. We have temporarily paused the ingestions of this dataset.

As you might already know, when an occurrence record has a new occurrenceID for a given dataset, our system considers it to be a new occurrence.
This means that it will be given a new gbifid and a new occurrence URL (like this one: https://www.gbif.org/occurrence/1252968762) and the old gbifid and URL will be deprecated.

In this case, this means that the occurrence URLs would be deprecated when ingesting the newest versions of these datasets.

We would like to check with you if those changes were intentional. Do you know if this is the case?
Please let us know, thanks! We are happy to resume the dataset ingestion.

Note that some users rely on those occurrence URLs and gbifids (like https://bionomia.net for example). In an attempt to improve
the stability of the occurrence URLs and gbifids, we have implemented a warning system to detect these type of changes in datasets (see this news item).
If the data publisher can provide us with a list of old and new occurrenceIDs per record, we can avoid the identifier and URL changes. Could that be an option?

Please let us know if you have any question. Thanks!

All the best,

</details>

You can skip/fix identifier validation using [the registry UI](https://registry.gbif.org/dataset/e523cf2d-4fc2-48d8-aa75-80ecbc90b3f5/ingestion-history).

**Comment by gbif-pipelines** [comment]
Identifier validation still  failing for the dataset [UCR - University of California, Riverside Herbarium - Vascular Plants](https://registry.gbif.org/dataset/e523cf2d-4fc2-48d8-aa75-80ecbc90b3f5):
- Crawler attempt: 208
- Publishing organization: [University of California Riverside](https://registry.gbif.org/organization/53e59855-7653-4d3e-87cc-162021713823)
- Publishing country: UNITED_STATES
- Installation: [Consortium of California Herbaria, CCH2 Portal](https://registry.gbif.org/installation/cb27a4ab-3360-4cf5-b5de-48a06a9c47ae)
- Number of occurrences indexed for this dataset at the time of the issue: 275289
- Cause: GBIF IDs hit maximum allowed - 50%, duplicates - 52%, total records count 459, absent records count 237
- Step metrics: 
```

```

- Pipelines execution steps: [http://api.gbif.org/v1/pipelines/history/execution/3042591/step](http://api.gbif.org/v1/pipelines/history/execution/3042591/step)
<details>
<summary>Publisher email</summary>

Hello,

I am contacting you from the GBIF Secretariat about a dataset published by the [UCR - University of California, Riverside Herbarium - Vascular Plants](https://registry.gbif.org/dataset/e523cf2d-4fc2-48d8-aa75-80ecbc90b3f5) : https://doi.org/10.15468/ai1kou.
We noticed that the occurrenceIDs were changed. We have temporarily paused the ingestions of this dataset.

As you might already know, when an occurrence record has a new occurrenceID for a given dataset, our system considers it to be a new occurrence.
This means that it will be given a new gbifid and a new occurrence URL (like this one: https://www.gbif.org/occurrence/1252968762) and the old gbifid and URL will be deprecated.

In this case, this means that the occurrence URLs would be deprecated when ingesting the newest versions of these datasets.

We would like to check with you if those changes were intentional. Do you know if this is the case?
Please let us know, thanks! We are happy to resume the dataset ingestion.

Note that some users rely on those occurrence URLs and gbifids (like https://bionomia.net for example). In an attempt to improve
the stability of the occurrence URLs and gbifids, we have implemented a warning system to detect these type of changes in datasets (see this news item).
If the data publisher can provide us with a list of old and new occurrenceIDs per record, we can avoid the identifier and URL changes. Could that be an option?

Please let us know if you have any question. Thanks!

All the best,

</details>


You can skip/fix identifier validation using [the registry UI](https://registry.gbif.org/dataset/e523cf2d-4fc2-48d8-aa75-80ecbc90b3f5/ingestion-history).

**Comment by jhnwllr** [comment]
Looks like the records were deleted...

**Comment by jhnwllr** [comment]
There was a deletion event but then it looks like the publisher has corrected it.
