### ISSUE TITLE
Identifiers validation failed for dataset Zooplankton Bongo Net Data from the 2019 and 2020 Gulf of Alaska International Year of the Salmon Expeditions

### ISSUE THREAD

**Issue by gbif-pipelines** [gbif/ingestion-management#20]
Identifier validation failed for the dataset [Zooplankton Bongo Net Data from the 2019 and 2020 Gulf of Alaska International Year of the Salmon Expeditions](https://registry.gbif.org/dataset/d80c46be-b600-44d5-9758-ef5159d40002):
- Crawler attempt: 88
- Publishing organization: [Hakai Institute](https://registry.gbif.org/organization/55897143-3f69-42f1-810d-ae94b55fde24)
- Publishing country: CANADA
- Installation: [OBIS Canada](https://registry.gbif.org/installation/5ff1c992-5c84-40aa-bd9a-c1743a870c32)
- Number of occurrences indexed for this dataset at the time of the issue: 8980
- Cause: GBIF IDs hit maximum allowed - 50%, duplicates - 100%, total records count 7942, absent records count 7942
- Step metrics: 
```

```

- Pipelines execution steps: [http://api.gbif.org/v1/pipelines/history/execution/3042623/step](http://api.gbif.org/v1/pipelines/history/execution/3042623/step)
<details>
<summary>Publisher email</summary>

Hello,

I am contacting you from the GBIF Secretariat about a dataset published by the [Zooplankton Bongo Net Data from the 2019 and 2020 Gulf of Alaska International Year of the Salmon Expeditions](https://registry.gbif.org/dataset/d80c46be-b600-44d5-9758-ef5159d40002) : https://doi.org/10.21966/7cmt-ca72.
We noticed that the occurrenceIDs were changed. We have temporarily paused the ingestions of this dataset.

As you might already know, when an occurrence record has a new occurrenceID for a given dataset, our system considers it to be a new occurrence.
This means that it will be given a new gbifid and a new occurrence URL (like this one: https://www.gbif.org/occurrence/1252968762) and the old gbifid and URL will be deprecated.

In this case, this means that the occurrence URLs would be deprecated when ingesting the newest versions of these datasets.

We would like to check with you if those changes were intentional. Do you know if this is the case?
Please let us know, thanks! We are happy to resume the dataset ingestion.

Note that some users rely on those occurrence URLs and gbifids (like https://bionomia.net for example). In an attempt to improve
the stability of the occurrence URLs and gbifids, we have implemented a warning system to detect these type of changes in datasets (see this news item).
If the data publisher can provide us with a list of old and new occurrenceIDs per record, we can avoid the identifier and URL changes. Could that be an option?

Please let us know if you have any question. Thanks!

All the best,

</details>

You can skip/fix identifier validation using [the registry UI](https://registry.gbif.org/dataset/d80c46be-b600-44d5-9758-ef5159d40002/ingestion-history).

**Comment by jhnwllr** [comment]
Was contacted on 07-18-2023.

**Comment by jhnwllr** [comment]
Closing because lack of response from publisher and is OBIS.
