### ISSUE TITLE
Identifiers validation failed for dataset Happywhale - Humpback Whale in South Atlantic Ocean

### ISSUE THREAD

**Issue by gbif-pipelines** [gbif/ingestion-management#23]
Identifier validation failed for the dataset [Happywhale - Humpback Whale in South Atlantic Ocean](https://registry.gbif.org/dataset/e1dddb82-f1c0-4553-aa2e-1fd414658d01):
- Crawler attempt: 129
- Publishing organization: [OBIS-SEAMAP](https://registry.gbif.org/organization/67b2263f-6990-4d9d-b32b-20aa72ef4fbc)
- Publishing country: UNITED_STATES
- Installation: [OBIS-SEAMAP IPT](https://registry.gbif.org/installation/beeeddea-c02a-43d5-aec7-b534daca34d6)
- Number of occurrences indexed for this dataset at the time of the issue: 2352
- Cause: GBIF IDs hit maximum allowed - 50%, duplicates - 56%, total records count 5375, absent records count 3002
- Step metrics: 
```

```

- Pipelines execution steps: [http://api.gbif.org/v1/pipelines/history/execution/3044511/step](http://api.gbif.org/v1/pipelines/history/execution/3044511/step)
<details>
<summary>Publisher email</summary>

Hello,

I am contacting you from the GBIF Secretariat about a dataset published by the [Happywhale - Humpback Whale in South Atlantic Ocean](https://registry.gbif.org/dataset/e1dddb82-f1c0-4553-aa2e-1fd414658d01) : https://doi.org/10.15468/v6r8s9.
We noticed that the occurrenceIDs were changed. We have temporarily paused the ingestions of this dataset.

As you might already know, when an occurrence record has a new occurrenceID for a given dataset, our system considers it to be a new occurrence.
This means that it will be given a new gbifid and a new occurrence URL (like this one: https://www.gbif.org/occurrence/1252968762) and the old gbifid and URL will be deprecated.

In this case, this means that the occurrence URLs would be deprecated when ingesting the newest versions of these datasets.

We would like to check with you if those changes were intentional. Do you know if this is the case?
Please let us know, thanks! We are happy to resume the dataset ingestion.

Note that some users rely on those occurrence URLs and gbifids (like https://bionomia.net for example). In an attempt to improve
the stability of the occurrence URLs and gbifids, we have implemented a warning system to detect these type of changes in datasets (see this news item).
If the data publisher can provide us with a list of old and new occurrenceIDs per record, we can avoid the identifier and URL changes. Could that be an option?

Please let us know if you have any question. Thanks!

All the best,

</details>

You can skip/fix identifier validation using [the registry UI](https://registry.gbif.org/dataset/e1dddb82-f1c0-4553-aa2e-1fd414658d01/ingestion-history).

**Comment by gbif-pipelines** [comment]
Identifier validation still  failing for the dataset [Happywhale - Humpback Whale in South Atlantic Ocean](https://registry.gbif.org/dataset/e1dddb82-f1c0-4553-aa2e-1fd414658d01):
- Crawler attempt: 135
- Publishing organization: [OBIS-SEAMAP](https://registry.gbif.org/organization/67b2263f-6990-4d9d-b32b-20aa72ef4fbc)
- Publishing country: UNITED_STATES
- Installation: [OBIS-SEAMAP IPT](https://registry.gbif.org/installation/beeeddea-c02a-43d5-aec7-b534daca34d6)
- Number of occurrences indexed for this dataset at the time of the issue: 2352
- Cause: GBIF IDs hit maximum allowed - 50%, duplicates - 58%, total records count 5640, absent records count 3273
- Pipelines execution steps: [http://api.gbif.org/v1/pipelines/history/execution/3087104/step](http://api.gbif.org/v1/pipelines/history/execution/3087104/step)
<details>
<summary>Publisher email</summary>

Hello,

I am contacting you from the GBIF Secretariat about a dataset published by the [Happywhale - Humpback Whale in South Atlantic Ocean](https://registry.gbif.org/dataset/e1dddb82-f1c0-4553-aa2e-1fd414658d01) : https://doi.org/10.15468/v6r8s9.
We noticed that the occurrenceIDs were changed. We have temporarily paused the ingestions of this dataset.

As you might already know, when an occurrence record has a new occurrenceID for a given dataset, our system considers it to be a new occurrence.
This means that it will be given a new gbifid and a new occurrence URL (like this one: https://www.gbif.org/occurrence/1252968762) and the old gbifid and URL will be deprecated.

In this case, this means that the occurrence URLs would be deprecated when ingesting the newest versions of these datasets.

We would like to check with you if those changes were intentional. Do you know if this is the case?
Please let us know, thanks! We are happy to resume the dataset ingestion.

Note that some users rely on those occurrence URLs and gbifids (like https://bionomia.net for example). In an attempt to improve
the stability of the occurrence URLs and gbifids, we have implemented a warning system to detect these type of changes in datasets (see this news item).
If the data publisher can provide us with a list of old and new occurrenceIDs per record, we can avoid the identifier and URL changes. Could that be an option?

Please let us know if you have any question. Thanks!

All the best,

</details>


You can skip/fix identifier validation using [the registry UI](https://registry.gbif.org/dataset/e1dddb82-f1c0-4553-aa2e-1fd414658d01/ingestion-history).

**Comment by gbif-pipelines** [comment]
Identifier validation still  failing for the dataset [Happywhale - Humpback Whale in South Atlantic Ocean](https://registry.gbif.org/dataset/e1dddb82-f1c0-4553-aa2e-1fd414658d01):
- Crawler attempt: 140
- Publishing organization: [OBIS-SEAMAP](https://registry.gbif.org/organization/67b2263f-6990-4d9d-b32b-20aa72ef4fbc)
- Publishing country: UNITED_STATES
- Installation: [OBIS-SEAMAP IPT](https://registry.gbif.org/installation/beeeddea-c02a-43d5-aec7-b534daca34d6)
- Number of occurrences indexed for this dataset at the time of the issue: 2352
- Cause: GBIF ID problems exceed 50% threshold: 59% duplicates; 5797 total records; 3429 absent records
- Pipelines execution steps: [http://api.gbif.org/v1/pipelines/history/execution/3265334/step](http://api.gbif.org/v1/pipelines/history/execution/3265334/step)
<details>
<summary>Publisher email</summary>

Hello,

I am contacting you from the GBIF Secretariat about a dataset published by the [Happywhale - Humpback Whale in South Atlantic Ocean](https://registry.gbif.org/dataset/e1dddb82-f1c0-4553-aa2e-1fd414658d01) : https://doi.org/10.15468/v6r8s9.
We noticed that the occurrenceIDs were changed. We have temporarily paused the ingestions of this dataset.

As you might already know, when an occurrence record has a new occurrenceID for a given dataset, our system considers it to be a new occurrence.
This means that it will be given a new gbifid and a new occurrence URL (like this one: https://www.gbif.org/occurrence/1252968762) and the old gbifid and URL will be deprecated.

In this case, this means that the occurrence URLs would be deprecated when ingesting the newest versions of these datasets.

We would like to check with you if those changes were intentional. Do you know if this is the case?
Please let us know, thanks! We are happy to resume the dataset ingestion.

Note that some users rely on those occurrence URLs and gbifids (like https://bionomia.net for example). In an attempt to improve
the stability of the occurrence URLs and gbifids, we have implemented a warning system to detect these type of changes in datasets (see this news item).
If the data publisher can provide us with a list of old and new occurrenceIDs per record, we can avoid the identifier and URL changes. Could that be an option?

Please let us know if you have any question. Thanks!

All the best,

</details>


You can skip/fix identifier validation using [the registry UI](https://registry.gbif.org/dataset/e1dddb82-f1c0-4553-aa2e-1fd414658d01/ingestion-history).

**Comment by jhnwllr** [comment]
This is OBIS? Should we let it through? 
@ManonGros

**Comment by ManonGros** [comment]
Yes let's do that. I have added the labels to the repo, see "resumes ingestion with no change".

**Comment by jhnwllr** [comment]
It's two months old so I am closing.
