### ISSUE TITLE
Identifiers validation failed for dataset Colección de Anélidos del Museo de Historia Natural Marina de Colombia - Makuriwa (Invemar)

### ISSUE THREAD

**Issue by gbif-pipelines** [gbif/ingestion-management#24]
Identifier validation failed for the dataset [Colección de Anélidos del Museo de Historia Natural Marina de Colombia - Makuriwa (Invemar)](https://registry.gbif.org/dataset/1641e2af-0532-4a7b-b300-3177a0a4a65d):
- Crawler attempt: 114
- Publishing organization: [Instituto de Investigaciones Marinas y Costeras - Invemar](https://registry.gbif.org/organization/f072f648-b8a4-47a0-9e1c-89d790645b5a)
- Publishing country: COLOMBIA
- Installation: [Datos sobre Biodiversidad Marino Costera de Colombia](https://registry.gbif.org/installation/73ebc470-17bd-4130-a880-1be5cfb16e4d)
- Number of occurrences indexed for this dataset at the time of the issue: 258
- Cause: GBIF IDs hit maximum allowed - 50%, duplicates - 100%, total records count 7059, absent records count 7059
- Step metrics: 
```

```

- Pipelines execution steps: [http://api.gbif.org/v1/pipelines/history/execution/3045688/step](http://api.gbif.org/v1/pipelines/history/execution/3045688/step)
<details>
<summary>Publisher email</summary>

Hello,

I am contacting you from the GBIF Secretariat about a dataset published by the [Colección de Anélidos del Museo de Historia Natural Marina de Colombia - Makuriwa (Invemar)](https://registry.gbif.org/dataset/1641e2af-0532-4a7b-b300-3177a0a4a65d) : https://doi.org/10.15472/ssc1ui.
We noticed that the occurrenceIDs were changed. We have temporarily paused the ingestions of this dataset.

As you might already know, when an occurrence record has a new occurrenceID for a given dataset, our system considers it to be a new occurrence.
This means that it will be given a new gbifid and a new occurrence URL (like this one: https://www.gbif.org/occurrence/1252968762) and the old gbifid and URL will be deprecated.

In this case, this means that the occurrence URLs would be deprecated when ingesting the newest versions of these datasets.

We would like to check with you if those changes were intentional. Do you know if this is the case?
Please let us know, thanks! We are happy to resume the dataset ingestion.

Note that some users rely on those occurrence URLs and gbifids (like https://bionomia.net for example). In an attempt to improve
the stability of the occurrence URLs and gbifids, we have implemented a warning system to detect these type of changes in datasets (see this news item).
If the data publisher can provide us with a list of old and new occurrenceIDs per record, we can avoid the identifier and URL changes. Could that be an option?

Please let us know if you have any question. Thanks!

All the best,

</details>

You can skip/fix identifier validation using [the registry UI](https://registry.gbif.org/dataset/1641e2af-0532-4a7b-b300-3177a0a4a65d/ingestion-history).

**Comment by jhnwllr** [comment]
Ran `pipelines-gbif-id-migrator` on  `1641e2af-0532-4a7b-b300-3177a0a4a65d` with file provided by publishers.
