### ISSUE TITLE
Identifiers validation failed for dataset Description of vegetation plots with Iris aphylla L. in European Russia

### ISSUE THREAD

**Issue by gbif-pipelines** [gbif/ingestion-management#25]
Identifier validation failed for the dataset [Description of vegetation plots with Iris aphylla L. in European Russia](https://registry.gbif.org/dataset/514dc3dd-4723-48a6-a219-8a9ea062a537):
- Crawler attempt: 147
- Publishing organization: [Institute of Geography, Russian Academy of Sciences](https://registry.gbif.org/organization/148dd300-d3cc-4004-a3d8-a7745673dac8)
- Publishing country: RUSSIAN_FEDERATION
- Installation: [Russian GBIF IPT](https://registry.gbif.org/installation/7743c35d-adbd-4ca6-a185-193a7a8d2684)
- Number of occurrences indexed for this dataset at the time of the issue: 5198
- Cause: GBIF IDs hit maximum allowed - 50%, duplicates - 66%, total records count 14003, absent records count 9301
- Step metrics: 
```

```

- Pipelines execution steps: [http://api.gbif.org/v1/pipelines/history/execution/3053365/step](http://api.gbif.org/v1/pipelines/history/execution/3053365/step)
<details>
<summary>Publisher email</summary>

Hello,

I am contacting you from the GBIF Secretariat about a dataset published by the [Description of vegetation plots with Iris aphylla L. in European Russia](https://registry.gbif.org/dataset/514dc3dd-4723-48a6-a219-8a9ea062a537) : https://doi.org/10.15468/hw7dhs.
We noticed that the occurrenceIDs were changed. We have temporarily paused the ingestions of this dataset.

As you might already know, when an occurrence record has a new occurrenceID for a given dataset, our system considers it to be a new occurrence.
This means that it will be given a new gbifid and a new occurrence URL (like this one: https://www.gbif.org/occurrence/1252968762) and the old gbifid and URL will be deprecated.

In this case, this means that the occurrence URLs would be deprecated when ingesting the newest versions of these datasets.

We would like to check with you if those changes were intentional. Do you know if this is the case?
Please let us know, thanks! We are happy to resume the dataset ingestion.

Note that some users rely on those occurrence URLs and gbifids (like https://bionomia.net for example). In an attempt to improve
the stability of the occurrence URLs and gbifids, we have implemented a warning system to detect these type of changes in datasets (see this news item).
If the data publisher can provide us with a list of old and new occurrenceIDs per record, we can avoid the identifier and URL changes. Could that be an option?

Please let us know if you have any question. Thanks!

All the best,

</details>

You can skip/fix identifier validation using [the registry UI](https://registry.gbif.org/dataset/514dc3dd-4723-48a6-a219-8a9ea062a537/ingestion-history).

**Comment by ktotsum** [comment]
This was intentional due to the increase of records according to the IPT comment.
http://gbif.ru:8080/ipt/resource?r=plots_with_iris_aphylla_in_european_russia
