### ISSUE TITLE
Identifiers validation failed for dataset Museo de Entomología Escuela Superior Politécnica de Chimborazo

### ISSUE THREAD

**Issue by gbif-pipelines** [gbif/ingestion-management#26]
Identifier validation failed for the dataset [Museo de Entomología Escuela Superior Politécnica de Chimborazo](https://registry.gbif.org/dataset/10db4545-973a-4574-931a-8f5659e48849):
- Crawler attempt: 71
- Publishing organization: [Museo de Entomología de la Escuela Superior Politécnica de Chimborazo](https://registry.gbif.org/organization/db2057d9-faf5-4fe1-a4c9-12b84a7fce80)
- Publishing country: ECUADOR
- Installation: [GBIF Ecuador - MAATE](https://registry.gbif.org/installation/9df8109c-684d-416b-819b-7bc09adc500b)
- Number of occurrences indexed for this dataset at the time of the issue: 1059
- Cause: GBIF IDs hit maximum allowed - 50%, duplicates - 100%, total records count 2102, absent records count 2102
- Pipelines execution steps: [http://api.gbif.org/v1/pipelines/history/execution/3061569/step](http://api.gbif.org/v1/pipelines/history/execution/3061569/step)
<details>
<summary>Publisher email</summary>

Hello,

I am contacting you from the GBIF Secretariat about a dataset published by the [Museo de Entomología Escuela Superior Politécnica de Chimborazo](https://registry.gbif.org/dataset/10db4545-973a-4574-931a-8f5659e48849) : https://doi.org/10.15468/8zkfnz.
We noticed that the occurrenceIDs were changed. We have temporarily paused the ingestions of this dataset.

As you might already know, when an occurrence record has a new occurrenceID for a given dataset, our system considers it to be a new occurrence.
This means that it will be given a new gbifid and a new occurrence URL (like this one: https://www.gbif.org/occurrence/1252968762) and the old gbifid and URL will be deprecated.

In this case, this means that the occurrence URLs would be deprecated when ingesting the newest versions of these datasets.

We would like to check with you if those changes were intentional. Do you know if this is the case?
Please let us know, thanks! We are happy to resume the dataset ingestion.

Note that some users rely on those occurrence URLs and gbifids (like https://bionomia.net for example). In an attempt to improve
the stability of the occurrence URLs and gbifids, we have implemented a warning system to detect these type of changes in datasets (see this news item).
If the data publisher can provide us with a list of old and new occurrenceIDs per record, we can avoid the identifier and URL changes. Could that be an option?

Please let us know if you have any question. Thanks!

All the best,

</details>

You can skip/fix identifier validation using [the registry UI](https://registry.gbif.org/dataset/10db4545-973a-4574-931a-8f5659e48849/ingestion-history).

**Comment by jhnwllr** [comment]
new ids:  
ESPOCH:ECESPOCH:009002
ESPOCH:ECESPOCH:008511
ESPOCH:ECESPOCH:000016
ESPOCH:ECESPOCH:000132
ESPOCH:ECESPOCH:000669
ESPOCH:ECESPOCH:000076
ESPOCH:ECESPOCH:009145
ESPOCH:ECESPOCH:008248
ESPOCH:ECESPOCH:008927
ESPOCH:ECESPOCH:000607
current ids: 

id sample:  
ESPOCH:ESPOCHME:000342
ESPOCH:ESPOCHME:001036
ESPOCH:ESPOCHME:000129
ESPOCH:ESPOCHME:000473
ESPOCH:ESPOCHME:000217
ESPOCH:ESPOCHME:000561
ESPOCH:ESPOCHME:001015
ESPOCH:ESPOCHME:000204
ESPOCH:ESPOCHME:000219
ESPOCH:ESPOCHME:000409

Closing because of lack of response from publisher even though it seems like an easy fix.
