### ISSUE TITLE
Identifiers validation failed for dataset Time series of zooplankton abundance of the South Florida Program / Sanctuaries Marine Biodiversity Observation Network programs

### ISSUE THREAD

**Issue by gbif-pipelines** [gbif/ingestion-management#27]
Identifier validation failed for the dataset [Time series of zooplankton abundance of the South Florida Program / Sanctuaries Marine Biodiversity Observation Network programs](https://registry.gbif.org/dataset/ec0d2fe8-21b1-4ab1-8b91-67873e8ca912):
- Crawler attempt: 169
- Publishing organization: [United States Geological Survey](https://registry.gbif.org/organization/c3ad790a-d426-4ac1-8e32-da61f81f0117)
- Publishing country: UNITED_STATES
- Installation: [Ocean Biodiversity Information System USA - OBIS-USA](https://registry.gbif.org/installation/a9c3f3b6-1f98-49c3-ba50-7e6aa1c9de59)
- Number of occurrences indexed for this dataset at the time of the issue: 767
- Cause: GBIF IDs hit maximum allowed - 50%, duplicates - 100%, total records count 2296, absent records count 2296
- Pipelines execution steps: [http://api.gbif.org/v1/pipelines/history/execution/3061621/step](http://api.gbif.org/v1/pipelines/history/execution/3061621/step)
<details>
<summary>Publisher email</summary>

Hello,

I am contacting you from the GBIF Secretariat about a dataset published by the [Time series of zooplankton abundance of the South Florida Program / Sanctuaries Marine Biodiversity Observation Network programs](https://registry.gbif.org/dataset/ec0d2fe8-21b1-4ab1-8b91-67873e8ca912) : https://doi.org/10.15468/buqg4u.
We noticed that the occurrenceIDs were changed. We have temporarily paused the ingestions of this dataset.

As you might already know, when an occurrence record has a new occurrenceID for a given dataset, our system considers it to be a new occurrence.
This means that it will be given a new gbifid and a new occurrence URL (like this one: https://www.gbif.org/occurrence/1252968762) and the old gbifid and URL will be deprecated.

In this case, this means that the occurrence URLs would be deprecated when ingesting the newest versions of these datasets.

We would like to check with you if those changes were intentional. Do you know if this is the case?
Please let us know, thanks! We are happy to resume the dataset ingestion.

Note that some users rely on those occurrence URLs and gbifids (like https://bionomia.net for example). In an attempt to improve
the stability of the occurrence URLs and gbifids, we have implemented a warning system to detect these type of changes in datasets (see this news item).
If the data publisher can provide us with a list of old and new occurrenceIDs per record, we can avoid the identifier and URL changes. Could that be an option?

Please let us know if you have any question. Thanks!

All the best,

</details>

You can skip/fix identifier validation using [the registry UI](https://registry.gbif.org/dataset/ec0d2fe8-21b1-4ab1-8b91-67873e8ca912/ingestion-history).

**Comment by ahahn-gbif** [comment]
Occurrence ID change permitted through on request of the Node manager ("The occurrenceIDs have changed but they have put in place a method for keeping them stable going forward."), email via helpdesk
