### ISSUE TITLE
Identifiers validation failed for dataset Auckland Museum Land Vertebrates Collection

### ISSUE THREAD

**Issue by gbif-pipelines** [gbif/ingestion-management#3]
Identifier validation failed for the dataset [Auckland Museum Land Vertebrates Collection](https://registry.gbif.org/dataset/aad97542-a068-449d-adb3-a8e937f64cb4):
- Crawler attempt: 288
- Publishing organization: [Auckland War Memorial Museum](https://registry.gbif.org/organization/32e82a64-c9b4-4b2f-9fbd-d446309b973f)
- Publishing country: NEW_ZEALAND
- Installation: [Auckland War Memorial Museum](https://registry.gbif.org/installation/58f76e14-f21d-4c3b-9c20-e14c006b7d3f)
- Number of occurrences indexed for this dataset at the time of the issue: 20065
- Cause: GBIF IDs hit maximum allowed - 50%, duplicates - 100%, total records count 19850, absent records count 19850
- Step metrics: 
```

```

- Pipelines execution steps: [http://api.gbif.org/v1/pipelines/history/execution/3028540/step](http://api.gbif.org/v1/pipelines/history/execution/3028540/step)
<details>
<summary>Publisher email</summary>

Hello,

I am contacting you from the GBIF Secretariat about a dataset published by the [Auckland Museum Land Vertebrates Collection](https://registry.gbif.org/dataset/aad97542-a068-449d-adb3-a8e937f64cb4) : https://doi.org/10.15468/xmpo2s.
We noticed that the occurrenceIDs were changed. We have temporarily paused the ingestions of this dataset.

As you might already know, when an occurrence record has a new occurrenceID for a given dataset, our system considers it to be a new occurrence.
This means that it will be given a new gbifid and a new occurrence URL (like this one: https://www.gbif.org/occurrence/1252968762) and the old gbifid and URL will be deprecated.

In this case, this means that the occurrence URLs would be deprecated when ingesting the newest versions of these datasets.

We would like to check with you if those changes were intentional. Do you know if this is the case?
Please let us know, thanks! We are happy to resume the dataset ingestion.

Note that some users rely on those occurrence URLs and gbifids (like https://bionomia.net for example). In an attempt to improve
the stability of the occurrence URLs and gbifids, we have implemented a warning system to detect these type of changes in datasets (see this news item).
If the data publisher can provide us with a list of old and new occurrenceIDs per record, we can avoid the identifier and URL changes. Could that be an option?

Please let us know if you have any question. Thanks!

All the best,

</details>

You can skip/fix identifier validation using [the registry UI](https://registry.gbif.org/dataset/aad97542-a068-449d-adb3-a8e937f64cb4/ingestion-history).

**Comment by gbif-pipelines** [comment]
Identifier validation still  failing for the dataset [Auckland Museum Land Vertebrates Collection](https://registry.gbif.org/dataset/aad97542-a068-449d-adb3-a8e937f64cb4):
- Crawler attempt: 288
- Publishing organization: [Auckland War Memorial Museum](https://registry.gbif.org/organization/32e82a64-c9b4-4b2f-9fbd-d446309b973f)
- Publishing country: NEW_ZEALAND
- Installation: [Auckland War Memorial Museum](https://registry.gbif.org/installation/58f76e14-f21d-4c3b-9c20-e14c006b7d3f)
- Number of occurrences indexed for this dataset at the time of the issue: 20065
- Cause: GBIF IDs hit maximum allowed - 50%, duplicates - 100%, total records count 19850, absent records count 19850
- Step metrics: 
```

```

- Pipelines execution steps: [http://api.gbif.org/v1/pipelines/history/execution/3028542/step](http://api.gbif.org/v1/pipelines/history/execution/3028542/step)
<details>
<summary>Publisher email</summary>

Hello,

I am contacting you from the GBIF Secretariat about a dataset published by the [Auckland Museum Land Vertebrates Collection](https://registry.gbif.org/dataset/aad97542-a068-449d-adb3-a8e937f64cb4) : https://doi.org/10.15468/xmpo2s.
We noticed that the occurrenceIDs were changed. We have temporarily paused the ingestions of this dataset.

As you might already know, when an occurrence record has a new occurrenceID for a given dataset, our system considers it to be a new occurrence.
This means that it will be given a new gbifid and a new occurrence URL (like this one: https://www.gbif.org/occurrence/1252968762) and the old gbifid and URL will be deprecated.

In this case, this means that the occurrence URLs would be deprecated when ingesting the newest versions of these datasets.

We would like to check with you if those changes were intentional. Do you know if this is the case?
Please let us know, thanks! We are happy to resume the dataset ingestion.

Note that some users rely on those occurrence URLs and gbifids (like https://bionomia.net for example). In an attempt to improve
the stability of the occurrence URLs and gbifids, we have implemented a warning system to detect these type of changes in datasets (see this news item).
If the data publisher can provide us with a list of old and new occurrenceIDs per record, we can avoid the identifier and URL changes. Could that be an option?

Please let us know if you have any question. Thanks!

All the best,

</details>


You can skip/fix identifier validation using [the registry UI](https://registry.gbif.org/dataset/aad97542-a068-449d-adb3-a8e937f64cb4/ingestion-history).

**Comment by ktotsum** [comment]
The endpoint is updated and accessible. The dataset has been successfully ingested after the identifier migration.
