### ISSUE TITLE
Identifiers validation failed for dataset LUSC - Herbário de Lages da Universidade do Estado de Santa Catarina

### ISSUE THREAD

**Issue by gbif-pipelines** [gbif/ingestion-management#30]
Identifier validation failed for the dataset [LUSC - Herbário de Lages da Universidade do Estado de Santa Catarina](https://registry.gbif.org/dataset/65d98c1d-a081-4b40-bc4b-81eae69a48e6):
- Crawler attempt: 391
- Publishing organization: [Universidade do Estado de Santa Catarina](https://registry.gbif.org/organization/d6541129-2940-44c0-baa1-ed6be2066df0)
- Publishing country: BRAZIL
- Installation: [speciesLink Network / INCT-HVFF IPT](https://registry.gbif.org/installation/b38ff2b7-c8af-454e-b5af-ee760f0d5bca)
- Number of occurrences indexed for this dataset at the time of the issue: 8583
- Cause: GBIF IDs hit maximum allowed - 50%, duplicates - 100%, total records count 8637, absent records count 8637
- Pipelines execution steps: [http://api.gbif.org/v1/pipelines/history/execution/3061993/step](http://api.gbif.org/v1/pipelines/history/execution/3061993/step)
<details>
<summary>Publisher email</summary>

Hello,

I am contacting you from the GBIF Secretariat about a dataset published by the [LUSC - Herbário de Lages da Universidade do Estado de Santa Catarina](https://registry.gbif.org/dataset/65d98c1d-a081-4b40-bc4b-81eae69a48e6) : https://doi.org/10.15468/xtjdqw.
We noticed that the occurrenceIDs were changed. We have temporarily paused the ingestions of this dataset.

As you might already know, when an occurrence record has a new occurrenceID for a given dataset, our system considers it to be a new occurrence.
This means that it will be given a new gbifid and a new occurrence URL (like this one: https://www.gbif.org/occurrence/1252968762) and the old gbifid and URL will be deprecated.

In this case, this means that the occurrence URLs would be deprecated when ingesting the newest versions of these datasets.

We would like to check with you if those changes were intentional. Do you know if this is the case?
Please let us know, thanks! We are happy to resume the dataset ingestion.

Note that some users rely on those occurrence URLs and gbifids (like https://bionomia.net for example). In an attempt to improve
the stability of the occurrence URLs and gbifids, we have implemented a warning system to detect these type of changes in datasets (see this news item).
If the data publisher can provide us with a list of old and new occurrenceIDs per record, we can avoid the identifier and URL changes. Could that be an option?

Please let us know if you have any question. Thanks!

All the best,

</details>

You can skip/fix identifier validation using [the registry UI](https://registry.gbif.org/dataset/65d98c1d-a081-4b40-bc4b-81eae69a48e6/ingestion-history).

**Comment by gbif-pipelines** [comment]
Identifier validation still  failing for the dataset [LUSC - Herbário de Lages da Universidade do Estado de Santa Catarina](https://registry.gbif.org/dataset/65d98c1d-a081-4b40-bc4b-81eae69a48e6):
- Crawler attempt: 392
- Publishing organization: [Universidade do Estado de Santa Catarina](https://registry.gbif.org/organization/d6541129-2940-44c0-baa1-ed6be2066df0)
- Publishing country: BRAZIL
- Installation: [speciesLink Network / INCT-HVFF IPT](https://registry.gbif.org/installation/b38ff2b7-c8af-454e-b5af-ee760f0d5bca)
- Number of occurrences indexed for this dataset at the time of the issue: 8583
- Cause: GBIF IDs hit maximum allowed - 50%, duplicates - 100%, total records count 8637, absent records count 8637
- Pipelines execution steps: [http://api.gbif.org/v1/pipelines/history/execution/3072401/step](http://api.gbif.org/v1/pipelines/history/execution/3072401/step)
<details>
<summary>Publisher email</summary>

Hello,

I am contacting you from the GBIF Secretariat about a dataset published by the [LUSC - Herbário de Lages da Universidade do Estado de Santa Catarina](https://registry.gbif.org/dataset/65d98c1d-a081-4b40-bc4b-81eae69a48e6) : https://doi.org/10.15468/xtjdqw.
We noticed that the occurrenceIDs were changed. We have temporarily paused the ingestions of this dataset.

As you might already know, when an occurrence record has a new occurrenceID for a given dataset, our system considers it to be a new occurrence.
This means that it will be given a new gbifid and a new occurrence URL (like this one: https://www.gbif.org/occurrence/1252968762) and the old gbifid and URL will be deprecated.

In this case, this means that the occurrence URLs would be deprecated when ingesting the newest versions of these datasets.

We would like to check with you if those changes were intentional. Do you know if this is the case?
Please let us know, thanks! We are happy to resume the dataset ingestion.

Note that some users rely on those occurrence URLs and gbifids (like https://bionomia.net for example). In an attempt to improve
the stability of the occurrence URLs and gbifids, we have implemented a warning system to detect these type of changes in datasets (see this news item).
If the data publisher can provide us with a list of old and new occurrenceIDs per record, we can avoid the identifier and URL changes. Could that be an option?

Please let us know if you have any question. Thanks!

All the best,

</details>


You can skip/fix identifier validation using [the registry UI](https://registry.gbif.org/dataset/65d98c1d-a081-4b40-bc4b-81eae69a48e6/ingestion-history).

**Comment by gbif-pipelines** [comment]
Identifier validation still  failing for the dataset [LUSC - Herbário de Lages da Universidade do Estado de Santa Catarina](https://registry.gbif.org/dataset/65d98c1d-a081-4b40-bc4b-81eae69a48e6):
- Crawler attempt: 393
- Publishing organization: [Universidade do Estado de Santa Catarina](https://registry.gbif.org/organization/d6541129-2940-44c0-baa1-ed6be2066df0)
- Publishing country: BRAZIL
- Installation: [speciesLink Network / INCT-HVFF IPT](https://registry.gbif.org/installation/b38ff2b7-c8af-454e-b5af-ee760f0d5bca)
- Number of occurrences indexed for this dataset at the time of the issue: 8583
- Cause: GBIF IDs hit maximum allowed - 50%, duplicates - 100%, total records count 8637, absent records count 8637
- Pipelines execution steps: [http://api.gbif.org/v1/pipelines/history/execution/3083212/step](http://api.gbif.org/v1/pipelines/history/execution/3083212/step)
<details>
<summary>Publisher email</summary>

Hello,

I am contacting you from the GBIF Secretariat about a dataset published by the [LUSC - Herbário de Lages da Universidade do Estado de Santa Catarina](https://registry.gbif.org/dataset/65d98c1d-a081-4b40-bc4b-81eae69a48e6) : https://doi.org/10.15468/xtjdqw.
We noticed that the occurrenceIDs were changed. We have temporarily paused the ingestions of this dataset.

As you might already know, when an occurrence record has a new occurrenceID for a given dataset, our system considers it to be a new occurrence.
This means that it will be given a new gbifid and a new occurrence URL (like this one: https://www.gbif.org/occurrence/1252968762) and the old gbifid and URL will be deprecated.

In this case, this means that the occurrence URLs would be deprecated when ingesting the newest versions of these datasets.

We would like to check with you if those changes were intentional. Do you know if this is the case?
Please let us know, thanks! We are happy to resume the dataset ingestion.

Note that some users rely on those occurrence URLs and gbifids (like https://bionomia.net for example). In an attempt to improve
the stability of the occurrence URLs and gbifids, we have implemented a warning system to detect these type of changes in datasets (see this news item).
If the data publisher can provide us with a list of old and new occurrenceIDs per record, we can avoid the identifier and URL changes. Could that be an option?

Please let us know if you have any question. Thanks!

All the best,

</details>


You can skip/fix identifier validation using [the registry UI](https://registry.gbif.org/dataset/65d98c1d-a081-4b40-bc4b-81eae69a48e6/ingestion-history).

**Comment by gbif-pipelines** [comment]
Identifier validation still  failing for the dataset [LUSC - Herbário de Lages da Universidade do Estado de Santa Catarina](https://registry.gbif.org/dataset/65d98c1d-a081-4b40-bc4b-81eae69a48e6):
- Crawler attempt: 394
- Publishing organization: [Universidade do Estado de Santa Catarina](https://registry.gbif.org/organization/d6541129-2940-44c0-baa1-ed6be2066df0)
- Publishing country: BRAZIL
- Installation: [speciesLink Network / INCT-HVFF IPT](https://registry.gbif.org/installation/b38ff2b7-c8af-454e-b5af-ee760f0d5bca)
- Number of occurrences indexed for this dataset at the time of the issue: 8583
- Cause: GBIF IDs hit maximum allowed - 50%, duplicates - 100%, total records count 8637, absent records count 8637
- Pipelines execution steps: [http://api.gbif.org/v1/pipelines/history/execution/3095445/step](http://api.gbif.org/v1/pipelines/history/execution/3095445/step)
<details>
<summary>Publisher email</summary>

Hello,

I am contacting you from the GBIF Secretariat about a dataset published by the [LUSC - Herbário de Lages da Universidade do Estado de Santa Catarina](https://registry.gbif.org/dataset/65d98c1d-a081-4b40-bc4b-81eae69a48e6) : https://doi.org/10.15468/xtjdqw.
We noticed that the occurrenceIDs were changed. We have temporarily paused the ingestions of this dataset.

As you might already know, when an occurrence record has a new occurrenceID for a given dataset, our system considers it to be a new occurrence.
This means that it will be given a new gbifid and a new occurrence URL (like this one: https://www.gbif.org/occurrence/1252968762) and the old gbifid and URL will be deprecated.

In this case, this means that the occurrence URLs would be deprecated when ingesting the newest versions of these datasets.

We would like to check with you if those changes were intentional. Do you know if this is the case?
Please let us know, thanks! We are happy to resume the dataset ingestion.

Note that some users rely on those occurrence URLs and gbifids (like https://bionomia.net for example). In an attempt to improve
the stability of the occurrence URLs and gbifids, we have implemented a warning system to detect these type of changes in datasets (see this news item).
If the data publisher can provide us with a list of old and new occurrenceIDs per record, we can avoid the identifier and URL changes. Could that be an option?

Please let us know if you have any question. Thanks!

All the best,

</details>


You can skip/fix identifier validation using [the registry UI](https://registry.gbif.org/dataset/65d98c1d-a081-4b40-bc4b-81eae69a48e6/ingestion-history).

**Comment by gbif-pipelines** [comment]
Identifier validation still  failing for the dataset [LUSC - Herbário de Lages da Universidade do Estado de Santa Catarina](https://registry.gbif.org/dataset/65d98c1d-a081-4b40-bc4b-81eae69a48e6):
- Crawler attempt: 395
- Publishing organization: [Universidade do Estado de Santa Catarina](https://registry.gbif.org/organization/d6541129-2940-44c0-baa1-ed6be2066df0)
- Publishing country: BRAZIL
- Installation: [speciesLink Network / INCT-HVFF IPT](https://registry.gbif.org/installation/b38ff2b7-c8af-454e-b5af-ee760f0d5bca)
- Number of occurrences indexed for this dataset at the time of the issue: 8583
- Cause: GBIF IDs hit maximum allowed - 50%, duplicates - 100%, total records count 8637, absent records count 8637
- Pipelines execution steps: [http://api.gbif.org/v1/pipelines/history/execution/3107687/step](http://api.gbif.org/v1/pipelines/history/execution/3107687/step)
<details>
<summary>Publisher email</summary>

Hello,

I am contacting you from the GBIF Secretariat about a dataset published by the [LUSC - Herbário de Lages da Universidade do Estado de Santa Catarina](https://registry.gbif.org/dataset/65d98c1d-a081-4b40-bc4b-81eae69a48e6) : https://doi.org/10.15468/xtjdqw.
We noticed that the occurrenceIDs were changed. We have temporarily paused the ingestions of this dataset.

As you might already know, when an occurrence record has a new occurrenceID for a given dataset, our system considers it to be a new occurrence.
This means that it will be given a new gbifid and a new occurrence URL (like this one: https://www.gbif.org/occurrence/1252968762) and the old gbifid and URL will be deprecated.

In this case, this means that the occurrence URLs would be deprecated when ingesting the newest versions of these datasets.

We would like to check with you if those changes were intentional. Do you know if this is the case?
Please let us know, thanks! We are happy to resume the dataset ingestion.

Note that some users rely on those occurrence URLs and gbifids (like https://bionomia.net for example). In an attempt to improve
the stability of the occurrence URLs and gbifids, we have implemented a warning system to detect these type of changes in datasets (see this news item).
If the data publisher can provide us with a list of old and new occurrenceIDs per record, we can avoid the identifier and URL changes. Could that be an option?

Please let us know if you have any question. Thanks!

All the best,

</details>


You can skip/fix identifier validation using [the registry UI](https://registry.gbif.org/dataset/65d98c1d-a081-4b40-bc4b-81eae69a48e6/ingestion-history).

**Comment by gbif-pipelines** [comment]
Identifier validation still  failing for the dataset [LUSC - Herbário de Lages da Universidade do Estado de Santa Catarina](https://registry.gbif.org/dataset/65d98c1d-a081-4b40-bc4b-81eae69a48e6):
- Crawler attempt: 398
- Publishing organization: [Universidade do Estado de Santa Catarina](https://registry.gbif.org/organization/d6541129-2940-44c0-baa1-ed6be2066df0)
- Publishing country: BRAZIL
- Installation: [speciesLink Network / INCT-HVFF IPT](https://registry.gbif.org/installation/b38ff2b7-c8af-454e-b5af-ee760f0d5bca)
- Number of occurrences indexed for this dataset at the time of the issue: 8583
- Cause: GBIF ID problems exceed 50% threshold: 100% duplicates; 8637 total records; 8637 absent records
- Pipelines execution steps: [http://api.gbif.org/v1/pipelines/history/execution/3265543/step](http://api.gbif.org/v1/pipelines/history/execution/3265543/step)
<details>
<summary>Publisher email</summary>

Hello,

I am contacting you from the GBIF Secretariat about a dataset published by the [LUSC - Herbário de Lages da Universidade do Estado de Santa Catarina](https://registry.gbif.org/dataset/65d98c1d-a081-4b40-bc4b-81eae69a48e6) : https://doi.org/10.15468/xtjdqw.
We noticed that the occurrenceIDs were changed. We have temporarily paused the ingestions of this dataset.

As you might already know, when an occurrence record has a new occurrenceID for a given dataset, our system considers it to be a new occurrence.
This means that it will be given a new gbifid and a new occurrence URL (like this one: https://www.gbif.org/occurrence/1252968762) and the old gbifid and URL will be deprecated.

In this case, this means that the occurrence URLs would be deprecated when ingesting the newest versions of these datasets.

We would like to check with you if those changes were intentional. Do you know if this is the case?
Please let us know, thanks! We are happy to resume the dataset ingestion.

Note that some users rely on those occurrence URLs and gbifids (like https://bionomia.net for example). In an attempt to improve
the stability of the occurrence URLs and gbifids, we have implemented a warning system to detect these type of changes in datasets (see this news item).
If the data publisher can provide us with a list of old and new occurrenceIDs per record, we can avoid the identifier and URL changes. Could that be an option?

Please let us know if you have any question. Thanks!

All the best,

</details>


You can skip/fix identifier validation using [the registry UI](https://registry.gbif.org/dataset/65d98c1d-a081-4b40-bc4b-81eae69a48e6/ingestion-history).

**Comment by gbif-pipelines** [comment]
Identifier validation still  failing for the dataset [LUSC - Herbário de Lages da Universidade do Estado de Santa Catarina](https://registry.gbif.org/dataset/65d98c1d-a081-4b40-bc4b-81eae69a48e6):
- Crawler attempt: 399
- Publishing organization: [Universidade do Estado de Santa Catarina](https://registry.gbif.org/organization/d6541129-2940-44c0-baa1-ed6be2066df0)
- Publishing country: BRAZIL
- Installation: [speciesLink Network / INCT-HVFF IPT](https://registry.gbif.org/installation/b38ff2b7-c8af-454e-b5af-ee760f0d5bca)
- Number of occurrences indexed for this dataset at the time of the issue: 8583
- Cause: GBIF ID problems exceed 50% threshold: 100% duplicates; 8637 total records; 8637 absent records
- Pipelines execution steps: [http://api.gbif.org/v1/pipelines/history/execution/3309441/step](http://api.gbif.org/v1/pipelines/history/execution/3309441/step)
<details>
<summary>Publisher email</summary>

Hello,

I am contacting you from the GBIF Secretariat about a dataset published by the [LUSC - Herbário de Lages da Universidade do Estado de Santa Catarina](https://registry.gbif.org/dataset/65d98c1d-a081-4b40-bc4b-81eae69a48e6) : https://doi.org/10.15468/xtjdqw.
We noticed that the occurrenceIDs were changed. We have temporarily paused the ingestions of this dataset.

As you might already know, when an occurrence record has a new occurrenceID for a given dataset, our system considers it to be a new occurrence.
This means that it will be given a new gbifid and a new occurrence URL (like this one: https://www.gbif.org/occurrence/1252968762) and the old gbifid and URL will be deprecated.

In this case, this means that the occurrence URLs would be deprecated when ingesting the newest versions of these datasets.

We would like to check with you if those changes were intentional. Do you know if this is the case?
Please let us know, thanks! We are happy to resume the dataset ingestion.

Note that some users rely on those occurrence URLs and gbifids (like https://bionomia.net for example). In an attempt to improve
the stability of the occurrence URLs and gbifids, we have implemented a warning system to detect these type of changes in datasets (see this news item).
If the data publisher can provide us with a list of old and new occurrenceIDs per record, we can avoid the identifier and URL changes. Could that be an option?

Please let us know if you have any question. Thanks!

All the best,

</details>


You can skip/fix identifier validation using [the registry UI](https://registry.gbif.org/dataset/65d98c1d-a081-4b40-bc4b-81eae69a48e6/ingestion-history).

**Comment by jhnwllr** [comment]
This issue was closed with a script because it was older than two months, please re-open if you think this is incorrect.
