### ISSUE TITLE
Identifiers validation failed for dataset VIES-Fungi - Herbário Central da Universidade Federal do Espírito Santo - Coleção de Fungos

### ISSUE THREAD

**Issue by gbif-pipelines** [gbif/ingestion-management#31]
Identifier validation failed for the dataset [VIES-Fungi - Herbário Central da Universidade Federal do Espírito Santo - Coleção de Fungos](https://registry.gbif.org/dataset/6a4e55d7-4468-4ad8-a5d5-f9ca5d6fa41e):
- Crawler attempt: 225
- Publishing organization: [Universidade Federal do Espírito Santo](https://registry.gbif.org/organization/503e9b26-09b5-4c40-b42a-bb476319a8ad)
- Publishing country: BRAZIL
- Installation: [speciesLink Network / INCT-HVFF IPT](https://registry.gbif.org/installation/b38ff2b7-c8af-454e-b5af-ee760f0d5bca)
- Number of occurrences indexed for this dataset at the time of the issue: 1556
- Cause: GBIF IDs hit maximum allowed - 50%, duplicates - 100%, total records count 1556, absent records count 1556
- Pipelines execution steps: [http://api.gbif.org/v1/pipelines/history/execution/3062001/step](http://api.gbif.org/v1/pipelines/history/execution/3062001/step)
<details>
<summary>Publisher email</summary>

Hello,

I am contacting you from the GBIF Secretariat about a dataset published by the [VIES-Fungi - Herbário Central da Universidade Federal do Espírito Santo - Coleção de Fungos](https://registry.gbif.org/dataset/6a4e55d7-4468-4ad8-a5d5-f9ca5d6fa41e) : https://doi.org/10.15468/k6spx1.
We noticed that the occurrenceIDs were changed. We have temporarily paused the ingestions of this dataset.

As you might already know, when an occurrence record has a new occurrenceID for a given dataset, our system considers it to be a new occurrence.
This means that it will be given a new gbifid and a new occurrence URL (like this one: https://www.gbif.org/occurrence/1252968762) and the old gbifid and URL will be deprecated.

In this case, this means that the occurrence URLs would be deprecated when ingesting the newest versions of these datasets.

We would like to check with you if those changes were intentional. Do you know if this is the case?
Please let us know, thanks! We are happy to resume the dataset ingestion.

Note that some users rely on those occurrence URLs and gbifids (like https://bionomia.net for example). In an attempt to improve
the stability of the occurrence URLs and gbifids, we have implemented a warning system to detect these type of changes in datasets (see this news item).
If the data publisher can provide us with a list of old and new occurrenceIDs per record, we can avoid the identifier and URL changes. Could that be an option?

Please let us know if you have any question. Thanks!

All the best,

</details>

You can skip/fix identifier validation using [the registry UI](https://registry.gbif.org/dataset/6a4e55d7-4468-4ad8-a5d5-f9ca5d6fa41e/ingestion-history).

**Comment by gbif-pipelines** [comment]
Identifier validation still  failing for the dataset [VIES-Fungi - Herbário Central da Universidade Federal do Espírito Santo - Coleção de Fungos](https://registry.gbif.org/dataset/6a4e55d7-4468-4ad8-a5d5-f9ca5d6fa41e):
- Crawler attempt: 225
- Publishing organization: [Universidade Federal do Espírito Santo](https://registry.gbif.org/organization/503e9b26-09b5-4c40-b42a-bb476319a8ad)
- Publishing country: BRAZIL
- Installation: [speciesLink Network / INCT-HVFF IPT](https://registry.gbif.org/installation/b38ff2b7-c8af-454e-b5af-ee760f0d5bca)
- Number of occurrences indexed for this dataset at the time of the issue: 1556
- Cause: GBIF IDs hit maximum allowed - 50%, duplicates - 100%, total records count 1556, absent records count 1556
- Pipelines execution steps: [http://api.gbif.org/v1/pipelines/history/execution/3062044/step](http://api.gbif.org/v1/pipelines/history/execution/3062044/step)
<details>
<summary>Publisher email</summary>

Hello,

I am contacting you from the GBIF Secretariat about a dataset published by the [VIES-Fungi - Herbário Central da Universidade Federal do Espírito Santo - Coleção de Fungos](https://registry.gbif.org/dataset/6a4e55d7-4468-4ad8-a5d5-f9ca5d6fa41e) : https://doi.org/10.15468/k6spx1.
We noticed that the occurrenceIDs were changed. We have temporarily paused the ingestions of this dataset.

As you might already know, when an occurrence record has a new occurrenceID for a given dataset, our system considers it to be a new occurrence.
This means that it will be given a new gbifid and a new occurrence URL (like this one: https://www.gbif.org/occurrence/1252968762) and the old gbifid and URL will be deprecated.

In this case, this means that the occurrence URLs would be deprecated when ingesting the newest versions of these datasets.

We would like to check with you if those changes were intentional. Do you know if this is the case?
Please let us know, thanks! We are happy to resume the dataset ingestion.

Note that some users rely on those occurrence URLs and gbifids (like https://bionomia.net for example). In an attempt to improve
the stability of the occurrence URLs and gbifids, we have implemented a warning system to detect these type of changes in datasets (see this news item).
If the data publisher can provide us with a list of old and new occurrenceIDs per record, we can avoid the identifier and URL changes. Could that be an option?

Please let us know if you have any question. Thanks!

All the best,

</details>


You can skip/fix identifier validation using [the registry UI](https://registry.gbif.org/dataset/6a4e55d7-4468-4ad8-a5d5-f9ca5d6fa41e/ingestion-history).

**Comment by gbif-pipelines** [comment]
Identifier validation still  failing for the dataset [VIES-Fungi - Herbário Central da Universidade Federal do Espírito Santo - Coleção de Fungos](https://registry.gbif.org/dataset/6a4e55d7-4468-4ad8-a5d5-f9ca5d6fa41e):
- Crawler attempt: 226
- Publishing organization: [Universidade Federal do Espírito Santo](https://registry.gbif.org/organization/503e9b26-09b5-4c40-b42a-bb476319a8ad)
- Publishing country: BRAZIL
- Installation: [speciesLink Network / INCT-HVFF IPT](https://registry.gbif.org/installation/b38ff2b7-c8af-454e-b5af-ee760f0d5bca)
- Number of occurrences indexed for this dataset at the time of the issue: 1556
- Cause: GBIF IDs hit maximum allowed - 50%, duplicates - 100%, total records count 1556, absent records count 1556
- Pipelines execution steps: [http://api.gbif.org/v1/pipelines/history/execution/3072353/step](http://api.gbif.org/v1/pipelines/history/execution/3072353/step)
<details>
<summary>Publisher email</summary>

Hello,

I am contacting you from the GBIF Secretariat about a dataset published by the [VIES-Fungi - Herbário Central da Universidade Federal do Espírito Santo - Coleção de Fungos](https://registry.gbif.org/dataset/6a4e55d7-4468-4ad8-a5d5-f9ca5d6fa41e) : https://doi.org/10.15468/k6spx1.
We noticed that the occurrenceIDs were changed. We have temporarily paused the ingestions of this dataset.

As you might already know, when an occurrence record has a new occurrenceID for a given dataset, our system considers it to be a new occurrence.
This means that it will be given a new gbifid and a new occurrence URL (like this one: https://www.gbif.org/occurrence/1252968762) and the old gbifid and URL will be deprecated.

In this case, this means that the occurrence URLs would be deprecated when ingesting the newest versions of these datasets.

We would like to check with you if those changes were intentional. Do you know if this is the case?
Please let us know, thanks! We are happy to resume the dataset ingestion.

Note that some users rely on those occurrence URLs and gbifids (like https://bionomia.net for example). In an attempt to improve
the stability of the occurrence URLs and gbifids, we have implemented a warning system to detect these type of changes in datasets (see this news item).
If the data publisher can provide us with a list of old and new occurrenceIDs per record, we can avoid the identifier and URL changes. Could that be an option?

Please let us know if you have any question. Thanks!

All the best,

</details>


You can skip/fix identifier validation using [the registry UI](https://registry.gbif.org/dataset/6a4e55d7-4468-4ad8-a5d5-f9ca5d6fa41e/ingestion-history).

**Comment by gbif-pipelines** [comment]
Identifier validation still  failing for the dataset [VIES-Fungi - Herbário Central da Universidade Federal do Espírito Santo - Coleção de Fungos](https://registry.gbif.org/dataset/6a4e55d7-4468-4ad8-a5d5-f9ca5d6fa41e):
- Crawler attempt: 228
- Publishing organization: [Universidade Federal do Espírito Santo](https://registry.gbif.org/organization/503e9b26-09b5-4c40-b42a-bb476319a8ad)
- Publishing country: BRAZIL
- Installation: [speciesLink Network / INCT-HVFF IPT](https://registry.gbif.org/installation/b38ff2b7-c8af-454e-b5af-ee760f0d5bca)
- Number of occurrences indexed for this dataset at the time of the issue: 1556
- Cause: GBIF IDs hit maximum allowed - 50%, duplicates - 100%, total records count 1556, absent records count 1556
- Pipelines execution steps: [http://api.gbif.org/v1/pipelines/history/execution/3095401/step](http://api.gbif.org/v1/pipelines/history/execution/3095401/step)
<details>
<summary>Publisher email</summary>

Hello,

I am contacting you from the GBIF Secretariat about a dataset published by the [VIES-Fungi - Herbário Central da Universidade Federal do Espírito Santo - Coleção de Fungos](https://registry.gbif.org/dataset/6a4e55d7-4468-4ad8-a5d5-f9ca5d6fa41e) : https://doi.org/10.15468/k6spx1.
We noticed that the occurrenceIDs were changed. We have temporarily paused the ingestions of this dataset.

As you might already know, when an occurrence record has a new occurrenceID for a given dataset, our system considers it to be a new occurrence.
This means that it will be given a new gbifid and a new occurrence URL (like this one: https://www.gbif.org/occurrence/1252968762) and the old gbifid and URL will be deprecated.

In this case, this means that the occurrence URLs would be deprecated when ingesting the newest versions of these datasets.

We would like to check with you if those changes were intentional. Do you know if this is the case?
Please let us know, thanks! We are happy to resume the dataset ingestion.

Note that some users rely on those occurrence URLs and gbifids (like https://bionomia.net for example). In an attempt to improve
the stability of the occurrence URLs and gbifids, we have implemented a warning system to detect these type of changes in datasets (see this news item).
If the data publisher can provide us with a list of old and new occurrenceIDs per record, we can avoid the identifier and URL changes. Could that be an option?

Please let us know if you have any question. Thanks!

All the best,

</details>


You can skip/fix identifier validation using [the registry UI](https://registry.gbif.org/dataset/6a4e55d7-4468-4ad8-a5d5-f9ca5d6fa41e/ingestion-history).

**Comment by gbif-pipelines** [comment]
Identifier validation still  failing for the dataset [VIES-Fungi - Herbário Central da Universidade Federal do Espírito Santo - Coleção de Fungos](https://registry.gbif.org/dataset/6a4e55d7-4468-4ad8-a5d5-f9ca5d6fa41e):
- Crawler attempt: 229
- Publishing organization: [Universidade Federal do Espírito Santo](https://registry.gbif.org/organization/503e9b26-09b5-4c40-b42a-bb476319a8ad)
- Publishing country: BRAZIL
- Installation: [speciesLink Network / INCT-HVFF IPT](https://registry.gbif.org/installation/b38ff2b7-c8af-454e-b5af-ee760f0d5bca)
- Number of occurrences indexed for this dataset at the time of the issue: 1556
- Cause: GBIF IDs hit maximum allowed - 50%, duplicates - 100%, total records count 1556, absent records count 1556
- Pipelines execution steps: [http://api.gbif.org/v1/pipelines/history/execution/3107627/step](http://api.gbif.org/v1/pipelines/history/execution/3107627/step)
<details>
<summary>Publisher email</summary>

Hello,

I am contacting you from the GBIF Secretariat about a dataset published by the [VIES-Fungi - Herbário Central da Universidade Federal do Espírito Santo - Coleção de Fungos](https://registry.gbif.org/dataset/6a4e55d7-4468-4ad8-a5d5-f9ca5d6fa41e) : https://doi.org/10.15468/k6spx1.
We noticed that the occurrenceIDs were changed. We have temporarily paused the ingestions of this dataset.

As you might already know, when an occurrence record has a new occurrenceID for a given dataset, our system considers it to be a new occurrence.
This means that it will be given a new gbifid and a new occurrence URL (like this one: https://www.gbif.org/occurrence/1252968762) and the old gbifid and URL will be deprecated.

In this case, this means that the occurrence URLs would be deprecated when ingesting the newest versions of these datasets.

We would like to check with you if those changes were intentional. Do you know if this is the case?
Please let us know, thanks! We are happy to resume the dataset ingestion.

Note that some users rely on those occurrence URLs and gbifids (like https://bionomia.net for example). In an attempt to improve
the stability of the occurrence URLs and gbifids, we have implemented a warning system to detect these type of changes in datasets (see this news item).
If the data publisher can provide us with a list of old and new occurrenceIDs per record, we can avoid the identifier and URL changes. Could that be an option?

Please let us know if you have any question. Thanks!

All the best,

</details>


You can skip/fix identifier validation using [the registry UI](https://registry.gbif.org/dataset/6a4e55d7-4468-4ad8-a5d5-f9ca5d6fa41e/ingestion-history).

**Comment by gbif-pipelines** [comment]
Identifier validation still  failing for the dataset [VIES-Fungi - Herbário Central da Universidade Federal do Espírito Santo - Coleção de Fungos](https://registry.gbif.org/dataset/6a4e55d7-4468-4ad8-a5d5-f9ca5d6fa41e):
- Crawler attempt: 230
- Publishing organization: [Universidade Federal do Espírito Santo](https://registry.gbif.org/organization/503e9b26-09b5-4c40-b42a-bb476319a8ad)
- Publishing country: BRAZIL
- Installation: [speciesLink Network / INCT-HVFF IPT](https://registry.gbif.org/installation/b38ff2b7-c8af-454e-b5af-ee760f0d5bca)
- Number of occurrences indexed for this dataset at the time of the issue: 1556
- Cause: GBIF ID problems exceed 50% threshold: 100% duplicates; 1556 total records; 1556 absent records
- Pipelines execution steps: [http://api.gbif.org/v1/pipelines/history/execution/3182046/step](http://api.gbif.org/v1/pipelines/history/execution/3182046/step)
<details>
<summary>Publisher email</summary>

Hello,

I am contacting you from the GBIF Secretariat about a dataset published by the [VIES-Fungi - Herbário Central da Universidade Federal do Espírito Santo - Coleção de Fungos](https://registry.gbif.org/dataset/6a4e55d7-4468-4ad8-a5d5-f9ca5d6fa41e) : https://doi.org/10.15468/k6spx1.
We noticed that the occurrenceIDs were changed. We have temporarily paused the ingestions of this dataset.

As you might already know, when an occurrence record has a new occurrenceID for a given dataset, our system considers it to be a new occurrence.
This means that it will be given a new gbifid and a new occurrence URL (like this one: https://www.gbif.org/occurrence/1252968762) and the old gbifid and URL will be deprecated.

In this case, this means that the occurrence URLs would be deprecated when ingesting the newest versions of these datasets.

We would like to check with you if those changes were intentional. Do you know if this is the case?
Please let us know, thanks! We are happy to resume the dataset ingestion.

Note that some users rely on those occurrence URLs and gbifids (like https://bionomia.net for example). In an attempt to improve
the stability of the occurrence URLs and gbifids, we have implemented a warning system to detect these type of changes in datasets (see this news item).
If the data publisher can provide us with a list of old and new occurrenceIDs per record, we can avoid the identifier and URL changes. Could that be an option?

Please let us know if you have any question. Thanks!

All the best,

</details>


You can skip/fix identifier validation using [the registry UI](https://registry.gbif.org/dataset/6a4e55d7-4468-4ad8-a5d5-f9ca5d6fa41e/ingestion-history).

**Comment by gbif-pipelines** [comment]
Identifier validation still  failing for the dataset [VIES-Fungi - Herbário Central da Universidade Federal do Espírito Santo - Coleção de Fungos](https://registry.gbif.org/dataset/6a4e55d7-4468-4ad8-a5d5-f9ca5d6fa41e):
- Crawler attempt: 231
- Publishing organization: [Universidade Federal do Espírito Santo](https://registry.gbif.org/organization/503e9b26-09b5-4c40-b42a-bb476319a8ad)
- Publishing country: BRAZIL
- Installation: [speciesLink Network / INCT-HVFF IPT](https://registry.gbif.org/installation/b38ff2b7-c8af-454e-b5af-ee760f0d5bca)
- Number of occurrences indexed for this dataset at the time of the issue: 1556
- Cause: GBIF ID problems exceed 50% threshold: 100% duplicates; 1556 total records; 1556 absent records
- Pipelines execution steps: [http://api.gbif.org/v1/pipelines/history/execution/3255922/step](http://api.gbif.org/v1/pipelines/history/execution/3255922/step)
<details>
<summary>Publisher email</summary>

Hello,

I am contacting you from the GBIF Secretariat about a dataset published by the [VIES-Fungi - Herbário Central da Universidade Federal do Espírito Santo - Coleção de Fungos](https://registry.gbif.org/dataset/6a4e55d7-4468-4ad8-a5d5-f9ca5d6fa41e) : https://doi.org/10.15468/k6spx1.
We noticed that the occurrenceIDs were changed. We have temporarily paused the ingestions of this dataset.

As you might already know, when an occurrence record has a new occurrenceID for a given dataset, our system considers it to be a new occurrence.
This means that it will be given a new gbifid and a new occurrence URL (like this one: https://www.gbif.org/occurrence/1252968762) and the old gbifid and URL will be deprecated.

In this case, this means that the occurrence URLs would be deprecated when ingesting the newest versions of these datasets.

We would like to check with you if those changes were intentional. Do you know if this is the case?
Please let us know, thanks! We are happy to resume the dataset ingestion.

Note that some users rely on those occurrence URLs and gbifids (like https://bionomia.net for example). In an attempt to improve
the stability of the occurrence URLs and gbifids, we have implemented a warning system to detect these type of changes in datasets (see this news item).
If the data publisher can provide us with a list of old and new occurrenceIDs per record, we can avoid the identifier and URL changes. Could that be an option?

Please let us know if you have any question. Thanks!

All the best,

</details>


You can skip/fix identifier validation using [the registry UI](https://registry.gbif.org/dataset/6a4e55d7-4468-4ad8-a5d5-f9ca5d6fa41e/ingestion-history).

**Comment by gbif-pipelines** [comment]
Identifier validation still  failing for the dataset [VIES-Fungi - Herbário Central da Universidade Federal do Espírito Santo - Coleção de Fungos](https://registry.gbif.org/dataset/6a4e55d7-4468-4ad8-a5d5-f9ca5d6fa41e):
- Crawler attempt: 232
- Publishing organization: [Universidade Federal do Espírito Santo](https://registry.gbif.org/organization/503e9b26-09b5-4c40-b42a-bb476319a8ad)
- Publishing country: BRAZIL
- Installation: [speciesLink Network / INCT-HVFF IPT](https://registry.gbif.org/installation/b38ff2b7-c8af-454e-b5af-ee760f0d5bca)
- Number of occurrences indexed for this dataset at the time of the issue: 1556
- Cause: GBIF ID problems exceed 50% threshold: 100% duplicates; 1556 total records; 1556 absent records
- Pipelines execution steps: [http://api.gbif.org/v1/pipelines/history/execution/3265422/step](http://api.gbif.org/v1/pipelines/history/execution/3265422/step)
<details>
<summary>Publisher email</summary>

Hello,

I am contacting you from the GBIF Secretariat about a dataset published by the [VIES-Fungi - Herbário Central da Universidade Federal do Espírito Santo - Coleção de Fungos](https://registry.gbif.org/dataset/6a4e55d7-4468-4ad8-a5d5-f9ca5d6fa41e) : https://doi.org/10.15468/k6spx1.
We noticed that the occurrenceIDs were changed. We have temporarily paused the ingestions of this dataset.

As you might already know, when an occurrence record has a new occurrenceID for a given dataset, our system considers it to be a new occurrence.
This means that it will be given a new gbifid and a new occurrence URL (like this one: https://www.gbif.org/occurrence/1252968762) and the old gbifid and URL will be deprecated.

In this case, this means that the occurrence URLs would be deprecated when ingesting the newest versions of these datasets.

We would like to check with you if those changes were intentional. Do you know if this is the case?
Please let us know, thanks! We are happy to resume the dataset ingestion.

Note that some users rely on those occurrence URLs and gbifids (like https://bionomia.net for example). In an attempt to improve
the stability of the occurrence URLs and gbifids, we have implemented a warning system to detect these type of changes in datasets (see this news item).
If the data publisher can provide us with a list of old and new occurrenceIDs per record, we can avoid the identifier and URL changes. Could that be an option?

Please let us know if you have any question. Thanks!

All the best,

</details>


You can skip/fix identifier validation using [the registry UI](https://registry.gbif.org/dataset/6a4e55d7-4468-4ad8-a5d5-f9ca5d6fa41e/ingestion-history).

**Comment by gbif-pipelines** [comment]
Identifier validation still  failing for the dataset [VIES-Fungi - Herbário Central da Universidade Federal do Espírito Santo - Coleção de Fungos](https://registry.gbif.org/dataset/6a4e55d7-4468-4ad8-a5d5-f9ca5d6fa41e):
- Crawler attempt: 233
- Publishing organization: [Universidade Federal do Espírito Santo](https://registry.gbif.org/organization/503e9b26-09b5-4c40-b42a-bb476319a8ad)
- Publishing country: BRAZIL
- Installation: [speciesLink Network / INCT-HVFF IPT](https://registry.gbif.org/installation/b38ff2b7-c8af-454e-b5af-ee760f0d5bca)
- Number of occurrences indexed for this dataset at the time of the issue: 1556
- Cause: GBIF ID problems exceed 50% threshold: 100% duplicates; 1556 total records; 1556 absent records
- Pipelines execution steps: [http://api.gbif.org/v1/pipelines/history/execution/3309366/step](http://api.gbif.org/v1/pipelines/history/execution/3309366/step)
<details>
<summary>Publisher email</summary>

Hello,

I am contacting you from the GBIF Secretariat about a dataset published by the [VIES-Fungi - Herbário Central da Universidade Federal do Espírito Santo - Coleção de Fungos](https://registry.gbif.org/dataset/6a4e55d7-4468-4ad8-a5d5-f9ca5d6fa41e) : https://doi.org/10.15468/k6spx1.
We noticed that the occurrenceIDs were changed. We have temporarily paused the ingestions of this dataset.

As you might already know, when an occurrence record has a new occurrenceID for a given dataset, our system considers it to be a new occurrence.
This means that it will be given a new gbifid and a new occurrence URL (like this one: https://www.gbif.org/occurrence/1252968762) and the old gbifid and URL will be deprecated.

In this case, this means that the occurrence URLs would be deprecated when ingesting the newest versions of these datasets.

We would like to check with you if those changes were intentional. Do you know if this is the case?
Please let us know, thanks! We are happy to resume the dataset ingestion.

Note that some users rely on those occurrence URLs and gbifids (like https://bionomia.net for example). In an attempt to improve
the stability of the occurrence URLs and gbifids, we have implemented a warning system to detect these type of changes in datasets (see this news item).
If the data publisher can provide us with a list of old and new occurrenceIDs per record, we can avoid the identifier and URL changes. Could that be an option?

Please let us know if you have any question. Thanks!

All the best,

</details>


You can skip/fix identifier validation using [the registry UI](https://registry.gbif.org/dataset/6a4e55d7-4468-4ad8-a5d5-f9ca5d6fa41e/ingestion-history).

**Comment by jhnwllr** [comment]
This issue was closed with a script because it was older than two months, please re-open if you think this is incorrect.
