### ISSUE TITLE
Identifiers validation failed for dataset North Carolina Rehabilitated Sea Turtle Monitoring Project (aggregated per 1-degree cell)

### ISSUE THREAD

**Issue by gbif-pipelines** [gbif/ingestion-management#39]
Identifier validation failed for the dataset [North Carolina Rehabilitated Sea Turtle Monitoring Project (aggregated per 1-degree cell)](https://registry.gbif.org/dataset/e080cae8-4d98-434d-a644-a36e7d3ba9d1):
- Crawler attempt: 112
- Publishing organization: [OBIS-SEAMAP](https://registry.gbif.org/organization/67b2263f-6990-4d9d-b32b-20aa72ef4fbc)
- Publishing country: UNITED_STATES
- Installation: [OBIS-SEAMAP IPT](https://registry.gbif.org/installation/beeeddea-c02a-43d5-aec7-b534daca34d6)
- Number of occurrences indexed for this dataset at the time of the issue: 17
- Cause: GBIF IDs hit maximum allowed - 50%, duplicates - 100%, total records count 17, absent records count 17
- Pipelines execution steps: [http://api.gbif.org/v1/pipelines/history/execution/3067119/step](http://api.gbif.org/v1/pipelines/history/execution/3067119/step)
<details>
<summary>Publisher email</summary>

Hello,

I am contacting you from the GBIF Secretariat about a dataset published by the [North Carolina Rehabilitated Sea Turtle Monitoring Project (aggregated per 1-degree cell)](https://registry.gbif.org/dataset/e080cae8-4d98-434d-a644-a36e7d3ba9d1) : https://doi.org/10.15468/c65k23.
We noticed that the occurrenceIDs were changed. We have temporarily paused the ingestions of this dataset.

As you might already know, when an occurrence record has a new occurrenceID for a given dataset, our system considers it to be a new occurrence.
This means that it will be given a new gbifid and a new occurrence URL (like this one: https://www.gbif.org/occurrence/1252968762) and the old gbifid and URL will be deprecated.

In this case, this means that the occurrence URLs would be deprecated when ingesting the newest versions of these datasets.

We would like to check with you if those changes were intentional. Do you know if this is the case?
Please let us know, thanks! We are happy to resume the dataset ingestion.

Note that some users rely on those occurrence URLs and gbifids (like https://bionomia.net for example). In an attempt to improve
the stability of the occurrence URLs and gbifids, we have implemented a warning system to detect these type of changes in datasets (see this news item).
If the data publisher can provide us with a list of old and new occurrenceIDs per record, we can avoid the identifier and URL changes. Could that be an option?

Please let us know if you have any question. Thanks!

All the best,

</details>

You can skip/fix identifier validation using [the registry UI](https://registry.gbif.org/dataset/e080cae8-4d98-434d-a644-a36e7d3ba9d1/ingestion-history).

**Comment by ManonGros** [comment]
The data was aggregated, we were told in the past to not check those as the IDs will change every update.
I added the tag and ingested the dataset.
