### ISSUE TITLE
Identifiers validation failed for dataset Conopidae of Ireland

### ISSUE THREAD

**Issue by gbif-pipelines** [gbif/ingestion-management#4]
Identifier validation failed for the dataset [Conopidae of Ireland](https://registry.gbif.org/dataset/7e225289-7c61-498a-bbcc-9995685b9abc):
- Crawler attempt: 232
- Publishing organization: [National Biodiversity Data Centre](https://registry.gbif.org/organization/d2b97690-bfd6-11de-b279-d52977ace833)
- Publishing country: IRELAND
- Installation: [HTTP Installation](https://registry.gbif.org/installation/99672740-f762-11e1-a439-00145eb45e9a)
- Number of occurrences indexed for this dataset at the time of the issue: 153
- Cause: GBIF IDs hit maximum allowed - 50%, duplicates - 77%, total records count 496, absent records count 380
- Step metrics: 
```

```

- Pipelines execution steps: [http://api.gbif.org/v1/pipelines/history/execution/3028633/step](http://api.gbif.org/v1/pipelines/history/execution/3028633/step)
<details>
<summary>Publisher email</summary>

Hello,

I am contacting you from the GBIF Secretariat about a dataset published by the [Conopidae of Ireland](https://registry.gbif.org/dataset/7e225289-7c61-498a-bbcc-9995685b9abc) : https://doi.org/10.15468/zkazip.
We noticed that the occurrenceIDs were changed. We have temporarily paused the ingestions of this dataset.

As you might already know, when an occurrence record has a new occurrenceID for a given dataset, our system considers it to be a new occurrence.
This means that it will be given a new gbifid and a new occurrence URL (like this one: https://www.gbif.org/occurrence/1252968762) and the old gbifid and URL will be deprecated.

In this case, this means that the occurrence URLs would be deprecated when ingesting the newest versions of these datasets.

We would like to check with you if those changes were intentional. Do you know if this is the case?
Please let us know, thanks! We are happy to resume the dataset ingestion.

Note that some users rely on those occurrence URLs and gbifids (like https://bionomia.net for example). In an attempt to improve
the stability of the occurrence URLs and gbifids, we have implemented a warning system to detect these type of changes in datasets (see this news item).
If the data publisher can provide us with a list of old and new occurrenceIDs per record, we can avoid the identifier and URL changes. Could that be an option?

Please let us know if you have any question. Thanks!

All the best,

</details>

You can skip/fix identifier validation using [the registry UI](https://registry.gbif.org/dataset/7e225289-7c61-498a-bbcc-9995685b9abc/ingestion-history).

**Comment by ManonGros** [comment]
Allowed failed identifiers
