### ISSUE TITLE
Identifiers validation failed for dataset Ashmore Reef Marine Park Environmental Assessment 2019 - Shorebird and Seabird counts

### ISSUE THREAD

**Issue by gbif-pipelines** [gbif/ingestion-management#464]
Identifier validation failed for the dataset [Ashmore Reef Marine Park Environmental Assessment 2019 - Shorebird and Seabird counts](https://registry.gbif.org/dataset/fa30c197-111f-457d-b775-e7c824952c88):
- Crawler attempt: 3
- Publishing organization: [CSIRO National Collections and Marine Infrastructure (NCMI) Information and Data Centre (IDC)](https://registry.gbif.org/organization/5fa89f68-9af0-4a0d-8998-ea39695c1db9)
- Publishing country: AUSTRALIA
- Installation: [CSIRO NCMI IDC / OBIS Australia](https://registry.gbif.org/installation/729a7375-b120-4e4f-bb81-ad9badcca81b)
- Number of occurrences indexed for this dataset at the time of the issue: 3335
- Cause: GBIF IDs hit maximum allowed - 50%, duplicates - 100%, total records count 84, absent records count 84
- Pipelines execution steps: [http://api.gbif.org/v1/pipelines/history/execution/3097964/step](http://api.gbif.org/v1/pipelines/history/execution/3097964/step)
<details>
<summary>Publisher email</summary>

Hello,

I am contacting you from the GBIF Secretariat about a dataset published by the [Ashmore Reef Marine Park Environmental Assessment 2019 - Shorebird and Seabird counts](https://registry.gbif.org/dataset/fa30c197-111f-457d-b775-e7c824952c88) : https://doi.org/10.25919/dgzt-t965.
We noticed that the occurrenceIDs were changed. We have temporarily paused the ingestions of this dataset.

As you might already know, when an occurrence record has a new occurrenceID for a given dataset, our system considers it to be a new occurrence.
This means that it will be given a new gbifid and a new occurrence URL (like this one: https://www.gbif.org/occurrence/1252968762) and the old gbifid and URL will be deprecated.

In this case, this means that the occurrence URLs would be deprecated when ingesting the newest versions of these datasets.

We would like to check with you if those changes were intentional. Do you know if this is the case?
Please let us know, thanks! We are happy to resume the dataset ingestion.

Note that some users rely on those occurrence URLs and gbifids (like https://bionomia.net for example). In an attempt to improve
the stability of the occurrence URLs and gbifids, we have implemented a warning system to detect these type of changes in datasets (see this news item).
If the data publisher can provide us with a list of old and new occurrenceIDs per record, we can avoid the identifier and URL changes. Could that be an option?

Please let us know if you have any question. Thanks!

All the best,

</details>

You can skip/fix identifier validation using [the registry UI](https://registry.gbif.org/dataset/fa30c197-111f-457d-b775-e7c824952c88/ingestion-history).

**Comment by gbif-pipelines** [comment]
Identifier validation still  failing for the dataset [Ashmore Reef Marine Park Environmental Assessment 2019 - Shorebird and Seabird counts](https://registry.gbif.org/dataset/fa30c197-111f-457d-b775-e7c824952c88):
- Crawler attempt: 4
- Publishing organization: [CSIRO National Collections and Marine Infrastructure (NCMI) Information and Data Centre (IDC)](https://registry.gbif.org/organization/5fa89f68-9af0-4a0d-8998-ea39695c1db9)
- Publishing country: AUSTRALIA
- Installation: [CSIRO NCMI IDC / OBIS Australia](https://registry.gbif.org/installation/729a7375-b120-4e4f-bb81-ad9badcca81b)
- Number of occurrences indexed for this dataset at the time of the issue: 3335
- Cause: GBIF IDs hit maximum allowed - 50%, duplicates - 100%, total records count 88, absent records count 88
- Pipelines execution steps: [http://api.gbif.org/v1/pipelines/history/execution/3099087/step](http://api.gbif.org/v1/pipelines/history/execution/3099087/step)
<details>
<summary>Publisher email</summary>

Hello,

I am contacting you from the GBIF Secretariat about a dataset published by the [Ashmore Reef Marine Park Environmental Assessment 2019 - Shorebird and Seabird counts](https://registry.gbif.org/dataset/fa30c197-111f-457d-b775-e7c824952c88) : https://doi.org/10.25919/dgzt-t965.
We noticed that the occurrenceIDs were changed. We have temporarily paused the ingestions of this dataset.

As you might already know, when an occurrence record has a new occurrenceID for a given dataset, our system considers it to be a new occurrence.
This means that it will be given a new gbifid and a new occurrence URL (like this one: https://www.gbif.org/occurrence/1252968762) and the old gbifid and URL will be deprecated.

In this case, this means that the occurrence URLs would be deprecated when ingesting the newest versions of these datasets.

We would like to check with you if those changes were intentional. Do you know if this is the case?
Please let us know, thanks! We are happy to resume the dataset ingestion.

Note that some users rely on those occurrence URLs and gbifids (like https://bionomia.net for example). In an attempt to improve
the stability of the occurrence URLs and gbifids, we have implemented a warning system to detect these type of changes in datasets (see this news item).
If the data publisher can provide us with a list of old and new occurrenceIDs per record, we can avoid the identifier and URL changes. Could that be an option?

Please let us know if you have any question. Thanks!

All the best,

</details>


You can skip/fix identifier validation using [the registry UI](https://registry.gbif.org/dataset/fa30c197-111f-457d-b775-e7c824952c88/ingestion-history).

**Comment by ktotsum** [comment]
ID changes were intentional due to fixing the dataset link. Data ingestion was successful on 2023-08-22.
