### ISSUE TITLE
Identifiers validation failed for dataset Colección Paleontológica Invertebrados e Icnología - IPGP CONICET - Argentina

### ISSUE THREAD

**Issue by gbif-pipelines** [gbif/ingestion-management#465]
Identifier validation failed for the dataset [Colección Paleontológica Invertebrados e Icnología - IPGP CONICET - Argentina](https://registry.gbif.org/dataset/02c8848f-a20e-4436-bc56-d067c7681b04):
- Crawler attempt: 54
- Publishing organization: [CCT CONICET-CENPAT Centro Científico Tecnológico](https://registry.gbif.org/organization/b62390e0-0e35-11d9-8431-b8a03c50a862)
- Publishing country: ARGENTINA
- Installation: [IPT CENPAT-CONICET](https://registry.gbif.org/installation/30cdb869-126c-44df-b1f2-6e06ea98e889)
- Number of occurrences indexed for this dataset at the time of the issue: 544
- Cause: GBIF IDs hit maximum allowed - 50%, duplicates - 100%, total records count 813, absent records count 813
- Pipelines execution steps: [http://api.gbif.org/v1/pipelines/history/execution/3099099/step](http://api.gbif.org/v1/pipelines/history/execution/3099099/step)
<details>
<summary>Publisher email</summary>

Hello,

I am contacting you from the GBIF Secretariat about a dataset published by the [Colección Paleontológica Invertebrados e Icnología - IPGP CONICET - Argentina](https://registry.gbif.org/dataset/02c8848f-a20e-4436-bc56-d067c7681b04) : https://doi.org/10.15468/obcc3l.
We noticed that the occurrenceIDs were changed. We have temporarily paused the ingestions of this dataset.

As you might already know, when an occurrence record has a new occurrenceID for a given dataset, our system considers it to be a new occurrence.
This means that it will be given a new gbifid and a new occurrence URL (like this one: https://www.gbif.org/occurrence/1252968762) and the old gbifid and URL will be deprecated.

In this case, this means that the occurrence URLs would be deprecated when ingesting the newest versions of these datasets.

We would like to check with you if those changes were intentional. Do you know if this is the case?
Please let us know, thanks! We are happy to resume the dataset ingestion.

Note that some users rely on those occurrence URLs and gbifids (like https://bionomia.net for example). In an attempt to improve
the stability of the occurrence URLs and gbifids, we have implemented a warning system to detect these type of changes in datasets (see this news item).
If the data publisher can provide us with a list of old and new occurrenceIDs per record, we can avoid the identifier and URL changes. Could that be an option?

Please let us know if you have any question. Thanks!

All the best,

</details>

You can skip/fix identifier validation using [the registry UI](https://registry.gbif.org/dataset/02c8848f-a20e-4436-bc56-d067c7681b04/ingestion-history).

**Comment by gbif-pipelines** [comment]
Identifier validation still  failing for the dataset [Colección Paleontológica Invertebrados e Icnología - IPGP CONICET - Argentina](https://registry.gbif.org/dataset/02c8848f-a20e-4436-bc56-d067c7681b04):
- Crawler attempt: 55
- Publishing organization: [CCT CONICET-CENPAT Centro Científico Tecnológico](https://registry.gbif.org/organization/b62390e0-0e35-11d9-8431-b8a03c50a862)
- Publishing country: ARGENTINA
- Installation: [IPT CENPAT-CONICET](https://registry.gbif.org/installation/30cdb869-126c-44df-b1f2-6e06ea98e889)
- Number of occurrences indexed for this dataset at the time of the issue: 544
- Cause: GBIF ID problems exceed 50% threshold: 100% duplicates; 813 total records; 813 absent records
- Pipelines execution steps: [http://api.gbif.org/v1/pipelines/history/execution/3170721/step](http://api.gbif.org/v1/pipelines/history/execution/3170721/step)
<details>
<summary>Publisher email</summary>

Hello,

I am contacting you from the GBIF Secretariat about a dataset published by the [Colección Paleontológica Invertebrados e Icnología - IPGP CONICET - Argentina](https://registry.gbif.org/dataset/02c8848f-a20e-4436-bc56-d067c7681b04) : https://doi.org/10.15468/obcc3l.
We noticed that the occurrenceIDs were changed. We have temporarily paused the ingestions of this dataset.

As you might already know, when an occurrence record has a new occurrenceID for a given dataset, our system considers it to be a new occurrence.
This means that it will be given a new gbifid and a new occurrence URL (like this one: https://www.gbif.org/occurrence/1252968762) and the old gbifid and URL will be deprecated.

In this case, this means that the occurrence URLs would be deprecated when ingesting the newest versions of these datasets.

We would like to check with you if those changes were intentional. Do you know if this is the case?
Please let us know, thanks! We are happy to resume the dataset ingestion.

Note that some users rely on those occurrence URLs and gbifids (like https://bionomia.net for example). In an attempt to improve
the stability of the occurrence URLs and gbifids, we have implemented a warning system to detect these type of changes in datasets (see this news item).
If the data publisher can provide us with a list of old and new occurrenceIDs per record, we can avoid the identifier and URL changes. Could that be an option?

Please let us know if you have any question. Thanks!

All the best,

</details>


You can skip/fix identifier validation using [the registry UI](https://registry.gbif.org/dataset/02c8848f-a20e-4436-bc56-d067c7681b04/ingestion-history).

**Comment by gbif-pipelines** [comment]
Identifier validation still  failing for the dataset [Colección Paleontológica Invertebrados e Icnología - IPGP CONICET - Argentina](https://registry.gbif.org/dataset/02c8848f-a20e-4436-bc56-d067c7681b04):
- Crawler attempt: 56
- Publishing organization: [CCT CONICET-CENPAT Centro Científico Tecnológico](https://registry.gbif.org/organization/b62390e0-0e35-11d9-8431-b8a03c50a862)
- Publishing country: ARGENTINA
- Installation: [IPT CENPAT-CONICET](https://registry.gbif.org/installation/30cdb869-126c-44df-b1f2-6e06ea98e889)
- Number of occurrences indexed for this dataset at the time of the issue: 544
- Cause: GBIF ID problems exceed 50% threshold: 100% duplicates; 813 total records; 813 absent records
- Pipelines execution steps: [http://api.gbif.org/v1/pipelines/history/execution/3170804/step](http://api.gbif.org/v1/pipelines/history/execution/3170804/step)
<details>
<summary>Publisher email</summary>

Hello,

I am contacting you from the GBIF Secretariat about a dataset published by the [Colección Paleontológica Invertebrados e Icnología - IPGP CONICET - Argentina](https://registry.gbif.org/dataset/02c8848f-a20e-4436-bc56-d067c7681b04) : https://doi.org/10.15468/obcc3l.
We noticed that the occurrenceIDs were changed. We have temporarily paused the ingestions of this dataset.

As you might already know, when an occurrence record has a new occurrenceID for a given dataset, our system considers it to be a new occurrence.
This means that it will be given a new gbifid and a new occurrence URL (like this one: https://www.gbif.org/occurrence/1252968762) and the old gbifid and URL will be deprecated.

In this case, this means that the occurrence URLs would be deprecated when ingesting the newest versions of these datasets.

We would like to check with you if those changes were intentional. Do you know if this is the case?
Please let us know, thanks! We are happy to resume the dataset ingestion.

Note that some users rely on those occurrence URLs and gbifids (like https://bionomia.net for example). In an attempt to improve
the stability of the occurrence URLs and gbifids, we have implemented a warning system to detect these type of changes in datasets (see this news item).
If the data publisher can provide us with a list of old and new occurrenceIDs per record, we can avoid the identifier and URL changes. Could that be an option?

Please let us know if you have any question. Thanks!

All the best,

</details>


You can skip/fix identifier validation using [the registry UI](https://registry.gbif.org/dataset/02c8848f-a20e-4436-bc56-d067c7681b04/ingestion-history).

**Comment by ktotsum** [comment]
resumed the ingestion as no response from the publisher
