### ISSUE TITLE
Identifiers validation failed for dataset Colección  de moldes endocraneanos del CENPAT

### ISSUE THREAD

**Issue by gbif-pipelines** [gbif/ingestion-management#466]
Identifier validation failed for the dataset [Colección  de moldes endocraneanos del CENPAT](https://registry.gbif.org/dataset/b78dc638-1dde-43b4-a4cb-1e7e8ba2f185):
- Crawler attempt: 293
- Publishing organization: [CCT CONICET-CENPAT Centro Científico Tecnológico](https://registry.gbif.org/organization/b62390e0-0e35-11d9-8431-b8a03c50a862)
- Publishing country: ARGENTINA
- Installation: [IPT CENPAT-CONICET](https://registry.gbif.org/installation/30cdb869-126c-44df-b1f2-6e06ea98e889)
- Number of occurrences indexed for this dataset at the time of the issue: 146
- Cause: GBIF IDs hit maximum allowed - 50%, duplicates - 100%, total records count 149, absent records count 149
- Pipelines execution steps: [http://api.gbif.org/v1/pipelines/history/execution/3099122/step](http://api.gbif.org/v1/pipelines/history/execution/3099122/step)
<details>
<summary>Publisher email</summary>

Hello,

I am contacting you from the GBIF Secretariat about a dataset published by the [Colección  de moldes endocraneanos del CENPAT](https://registry.gbif.org/dataset/b78dc638-1dde-43b4-a4cb-1e7e8ba2f185) : https://doi.org/10.15468/2ynl0h.
We noticed that the occurrenceIDs were changed. We have temporarily paused the ingestions of this dataset.

As you might already know, when an occurrence record has a new occurrenceID for a given dataset, our system considers it to be a new occurrence.
This means that it will be given a new gbifid and a new occurrence URL (like this one: https://www.gbif.org/occurrence/1252968762) and the old gbifid and URL will be deprecated.

In this case, this means that the occurrence URLs would be deprecated when ingesting the newest versions of these datasets.

We would like to check with you if those changes were intentional. Do you know if this is the case?
Please let us know, thanks! We are happy to resume the dataset ingestion.

Note that some users rely on those occurrence URLs and gbifids (like https://bionomia.net for example). In an attempt to improve
the stability of the occurrence URLs and gbifids, we have implemented a warning system to detect these type of changes in datasets (see this news item).
If the data publisher can provide us with a list of old and new occurrenceIDs per record, we can avoid the identifier and URL changes. Could that be an option?

Please let us know if you have any question. Thanks!

All the best,

</details>

You can skip/fix identifier validation using [the registry UI](https://registry.gbif.org/dataset/b78dc638-1dde-43b4-a4cb-1e7e8ba2f185/ingestion-history).

**Comment by ktotsum** [comment]
Investigating because the ingestion stopped at "VERBATIM_TO_INTERPRETED" after allowing id changes.

**Comment by gbif-pipelines** [comment]
Identifier validation still  failing for the dataset [Colección  de moldes endocraneanos del CENPAT](https://registry.gbif.org/dataset/b78dc638-1dde-43b4-a4cb-1e7e8ba2f185):
- Crawler attempt: 294
- Publishing organization: [CCT CONICET-CENPAT Centro Científico Tecnológico](https://registry.gbif.org/organization/b62390e0-0e35-11d9-8431-b8a03c50a862)
- Publishing country: ARGENTINA
- Installation: [IPT CENPAT-CONICET](https://registry.gbif.org/installation/30cdb869-126c-44df-b1f2-6e06ea98e889)
- Number of occurrences indexed for this dataset at the time of the issue: 146
- Cause: GBIF ID problems exceed 50% threshold: 100% duplicates; 149 total records; 149 absent records
- Pipelines execution steps: [http://api.gbif.org/v1/pipelines/history/execution/3389423/step](http://api.gbif.org/v1/pipelines/history/execution/3389423/step)

```
New IDs sample:


```


```
Old IDs sample:

0482B52F-86A3-43FA-B4FC-03A95C49574E
0530F641-AE7E-4C78-B5E4-099468ECDC98
05926E4C-7C20-446F-8BC9-3E2BE1153E9D
05B50060-50B7-4976-95A1-009AF737A499
08CB6B5D-1B0A-4525-8868-5CA1581D3A98
0B2E3C13-35DC-459D-8153-67E23E3740A9
0B8B29E3-ECE1-4FEC-B8DB-6E76EB447599
0D1B8A4D-5548-449A-A827-1B1B7C1C4EF3
0DE99457-D0AD-46A3-A1F8-BEA997789EDB
0E1C5198-AA94-456B-A423-FD3E46955DEA
```

<details>
<summary>Publisher email</summary>

Hello,

I am contacting you from the GBIF Secretariat about a dataset published by the [Colección  de moldes endocraneanos del CENPAT](https://registry.gbif.org/dataset/b78dc638-1dde-43b4-a4cb-1e7e8ba2f185) : https://doi.org/10.15468/2ynl0h.
We noticed that the occurrenceIDs were changed. We have temporarily paused the ingestions of this dataset.

As you might already know, when an occurrence record has a new occurrenceID for a given dataset, our system considers it to be a new occurrence.
This means that it will be given a new gbifid and a new occurrence URL (like this one: https://www.gbif.org/occurrence/1252968762) and the old gbifid and URL will be deprecated.

In this case, this means that the occurrence URLs would be deprecated when ingesting the newest versions of these datasets.

We would like to check with you if those changes were intentional. Do you know if this is the case?
Please let us know, thanks! We are happy to resume the dataset ingestion.

Note that some users rely on those occurrence URLs and gbifids (like https://bionomia.net for example). In an attempt to improve
the stability of the occurrence URLs and gbifids, we have implemented a warning system to detect these type of changes in datasets (see this news item).
If the data publisher can provide us with a list of old and new occurrenceIDs per record, we can avoid the identifier and URL changes. Could that be an option?

Please let us know if you have any question. Thanks!

All the best,

</details>


You can skip/fix identifier validation using [the registry UI](https://registry.gbif.org/dataset/b78dc638-1dde-43b4-a4cb-1e7e8ba2f185/ingestion-history).

**Comment by ktotsum** [comment]
The dataset has been updated after fixing a technical bug (some internal files were missing).
