### ISSUE TITLE
Identifiers validation failed for dataset DVPR - Herbário da Universidade Tecnológica Federal do Paraná - Dois Vizinhos

### ISSUE THREAD

**Issue by gbif-pipelines** [gbif/ingestion-management#6]
Identifier validation failed for the dataset [DVPR - Herbário da Universidade Tecnológica Federal do Paraná - Dois Vizinhos](https://registry.gbif.org/dataset/0ec3229f-2b53-484e-817a-de8ceb1fce2b):
- Crawler attempt: 383
- Publishing organization: [Universidade Tecnológica Federal do Paraná - Campus Dois Vizinhos](https://registry.gbif.org/organization/cc8ec135-6ade-4a8e-8b31-475dc1d3c433)
- Publishing country: BRAZIL
- Installation: [speciesLink Network / INCT-HVFF IPT](https://registry.gbif.org/installation/b38ff2b7-c8af-454e-b5af-ee760f0d5bca)
- Number of occurrences indexed for this dataset at the time of the issue: 6788
- Cause: GBIF IDs hit maximum allowed - 50%, duplicates - 100%, total records count 6788, absent records count 6788
- Step metrics: 
```

```

- Pipelines execution steps: [http://api.gbif.org/v1/pipelines/history/execution/3029560/step](http://api.gbif.org/v1/pipelines/history/execution/3029560/step)
<details>
<summary>Publisher email</summary>

Hello,

I am contacting you from the GBIF Secretariat about a dataset published by the [DVPR - Herbário da Universidade Tecnológica Federal do Paraná - Dois Vizinhos](https://registry.gbif.org/dataset/0ec3229f-2b53-484e-817a-de8ceb1fce2b) : https://doi.org/10.15468/utbo2g.
We noticed that the occurrenceIDs were changed. We have temporarily paused the ingestions of this dataset.

As you might already know, when an occurrence record has a new occurrenceID for a given dataset, our system considers it to be a new occurrence.
This means that it will be given a new gbifid and a new occurrence URL (like this one: https://www.gbif.org/occurrence/1252968762) and the old gbifid and URL will be deprecated.

In this case, this means that the occurrence URLs would be deprecated when ingesting the newest versions of these datasets.

We would like to check with you if those changes were intentional. Do you know if this is the case?
Please let us know, thanks! We are happy to resume the dataset ingestion.

Note that some users rely on those occurrence URLs and gbifids (like https://bionomia.net for example). In an attempt to improve
the stability of the occurrence URLs and gbifids, we have implemented a warning system to detect these type of changes in datasets (see this news item).
If the data publisher can provide us with a list of old and new occurrenceIDs per record, we can avoid the identifier and URL changes. Could that be an option?

Please let us know if you have any question. Thanks!

All the best,

</details>

You can skip/fix identifier validation using [the registry UI](https://registry.gbif.org/dataset/0ec3229f-2b53-484e-817a-de8ceb1fce2b/ingestion-history).

**Comment by gbif-pipelines** [comment]
Identifier validation still  failing for the dataset [DVPR - Herbário da Universidade Tecnológica Federal do Paraná - Dois Vizinhos](https://registry.gbif.org/dataset/0ec3229f-2b53-484e-817a-de8ceb1fce2b):
- Crawler attempt: 385
- Publishing organization: [Universidade Tecnológica Federal do Paraná - Campus Dois Vizinhos](https://registry.gbif.org/organization/cc8ec135-6ade-4a8e-8b31-475dc1d3c433)
- Publishing country: BRAZIL
- Installation: [speciesLink Network / INCT-HVFF IPT](https://registry.gbif.org/installation/b38ff2b7-c8af-454e-b5af-ee760f0d5bca)
- Number of occurrences indexed for this dataset at the time of the issue: 6788
- Cause: GBIF IDs hit maximum allowed - 50%, duplicates - 100%, total records count 6788, absent records count 6788
- Step metrics: 
```

```

- Pipelines execution steps: [http://api.gbif.org/v1/pipelines/history/execution/3043073/step](http://api.gbif.org/v1/pipelines/history/execution/3043073/step)
<details>
<summary>Publisher email</summary>

Hello,

I am contacting you from the GBIF Secretariat about a dataset published by the [DVPR - Herbário da Universidade Tecnológica Federal do Paraná - Dois Vizinhos](https://registry.gbif.org/dataset/0ec3229f-2b53-484e-817a-de8ceb1fce2b) : https://doi.org/10.15468/utbo2g.
We noticed that the occurrenceIDs were changed. We have temporarily paused the ingestions of this dataset.

As you might already know, when an occurrence record has a new occurrenceID for a given dataset, our system considers it to be a new occurrence.
This means that it will be given a new gbifid and a new occurrence URL (like this one: https://www.gbif.org/occurrence/1252968762) and the old gbifid and URL will be deprecated.

In this case, this means that the occurrence URLs would be deprecated when ingesting the newest versions of these datasets.

We would like to check with you if those changes were intentional. Do you know if this is the case?
Please let us know, thanks! We are happy to resume the dataset ingestion.

Note that some users rely on those occurrence URLs and gbifids (like https://bionomia.net for example). In an attempt to improve
the stability of the occurrence URLs and gbifids, we have implemented a warning system to detect these type of changes in datasets (see this news item).
If the data publisher can provide us with a list of old and new occurrenceIDs per record, we can avoid the identifier and URL changes. Could that be an option?

Please let us know if you have any question. Thanks!

All the best,

</details>


You can skip/fix identifier validation using [the registry UI](https://registry.gbif.org/dataset/0ec3229f-2b53-484e-817a-de8ceb1fce2b/ingestion-history).

**Comment by gbif-pipelines** [comment]
Identifier validation still  failing for the dataset [DVPR - Herbário da Universidade Tecnológica Federal do Paraná - Dois Vizinhos](https://registry.gbif.org/dataset/0ec3229f-2b53-484e-817a-de8ceb1fce2b):
- Crawler attempt: 387
- Publishing organization: [Universidade Tecnológica Federal do Paraná - Campus Dois Vizinhos](https://registry.gbif.org/organization/cc8ec135-6ade-4a8e-8b31-475dc1d3c433)
- Publishing country: BRAZIL
- Installation: [speciesLink Network / INCT-HVFF IPT](https://registry.gbif.org/installation/b38ff2b7-c8af-454e-b5af-ee760f0d5bca)
- Number of occurrences indexed for this dataset at the time of the issue: 6788
- Cause: GBIF IDs hit maximum allowed - 50%, duplicates - 100%, total records count 6788, absent records count 6788
- Pipelines execution steps: [http://api.gbif.org/v1/pipelines/history/execution/3062490/step](http://api.gbif.org/v1/pipelines/history/execution/3062490/step)
<details>
<summary>Publisher email</summary>

Hello,

I am contacting you from the GBIF Secretariat about a dataset published by the [DVPR - Herbário da Universidade Tecnológica Federal do Paraná - Dois Vizinhos](https://registry.gbif.org/dataset/0ec3229f-2b53-484e-817a-de8ceb1fce2b) : https://doi.org/10.15468/utbo2g.
We noticed that the occurrenceIDs were changed. We have temporarily paused the ingestions of this dataset.

As you might already know, when an occurrence record has a new occurrenceID for a given dataset, our system considers it to be a new occurrence.
This means that it will be given a new gbifid and a new occurrence URL (like this one: https://www.gbif.org/occurrence/1252968762) and the old gbifid and URL will be deprecated.

In this case, this means that the occurrence URLs would be deprecated when ingesting the newest versions of these datasets.

We would like to check with you if those changes were intentional. Do you know if this is the case?
Please let us know, thanks! We are happy to resume the dataset ingestion.

Note that some users rely on those occurrence URLs and gbifids (like https://bionomia.net for example). In an attempt to improve
the stability of the occurrence URLs and gbifids, we have implemented a warning system to detect these type of changes in datasets (see this news item).
If the data publisher can provide us with a list of old and new occurrenceIDs per record, we can avoid the identifier and URL changes. Could that be an option?

Please let us know if you have any question. Thanks!

All the best,

</details>


You can skip/fix identifier validation using [the registry UI](https://registry.gbif.org/dataset/0ec3229f-2b53-484e-817a-de8ceb1fce2b/ingestion-history).

**Comment by gbif-pipelines** [comment]
Identifier validation still  failing for the dataset [DVPR - Herbário da Universidade Tecnológica Federal do Paraná - Dois Vizinhos](https://registry.gbif.org/dataset/0ec3229f-2b53-484e-817a-de8ceb1fce2b):
- Crawler attempt: 388
- Publishing organization: [Universidade Tecnológica Federal do Paraná - Campus Dois Vizinhos](https://registry.gbif.org/organization/cc8ec135-6ade-4a8e-8b31-475dc1d3c433)
- Publishing country: BRAZIL
- Installation: [speciesLink Network / INCT-HVFF IPT](https://registry.gbif.org/installation/b38ff2b7-c8af-454e-b5af-ee760f0d5bca)
- Number of occurrences indexed for this dataset at the time of the issue: 6788
- Cause: GBIF IDs hit maximum allowed - 50%, duplicates - 100%, total records count 6788, absent records count 6788
- Pipelines execution steps: [http://api.gbif.org/v1/pipelines/history/execution/3073825/step](http://api.gbif.org/v1/pipelines/history/execution/3073825/step)
<details>
<summary>Publisher email</summary>

Hello,

I am contacting you from the GBIF Secretariat about a dataset published by the [DVPR - Herbário da Universidade Tecnológica Federal do Paraná - Dois Vizinhos](https://registry.gbif.org/dataset/0ec3229f-2b53-484e-817a-de8ceb1fce2b) : https://doi.org/10.15468/utbo2g.
We noticed that the occurrenceIDs were changed. We have temporarily paused the ingestions of this dataset.

As you might already know, when an occurrence record has a new occurrenceID for a given dataset, our system considers it to be a new occurrence.
This means that it will be given a new gbifid and a new occurrence URL (like this one: https://www.gbif.org/occurrence/1252968762) and the old gbifid and URL will be deprecated.

In this case, this means that the occurrence URLs would be deprecated when ingesting the newest versions of these datasets.

We would like to check with you if those changes were intentional. Do you know if this is the case?
Please let us know, thanks! We are happy to resume the dataset ingestion.

Note that some users rely on those occurrence URLs and gbifids (like https://bionomia.net for example). In an attempt to improve
the stability of the occurrence URLs and gbifids, we have implemented a warning system to detect these type of changes in datasets (see this news item).
If the data publisher can provide us with a list of old and new occurrenceIDs per record, we can avoid the identifier and URL changes. Could that be an option?

Please let us know if you have any question. Thanks!

All the best,

</details>


You can skip/fix identifier validation using [the registry UI](https://registry.gbif.org/dataset/0ec3229f-2b53-484e-817a-de8ceb1fce2b/ingestion-history).

**Comment by ktotsum** [comment]
The dataset was successfully ingested after the new version (1.101) was published on 2023-08-06.
http://ipt1.cria.org.br/ipt/resource?r=dvpr
