### ISSUE TITLE
Identifiers validation failed for dataset Coleção de Mastozoologia do Museu de História Natural Capão da Imbuia

### ISSUE THREAD

**Issue by gbif-pipelines** [gbif/ingestion-management#698]
Identifier validation failed for the dataset [Coleção de Mastozoologia do Museu de História Natural Capão da Imbuia](https://registry.gbif.org/dataset/0dfeb21c-5cfa-4bc8-8efd-bfd3f8968d45):
- Crawler attempt: 7
- Publishing organization: [Museu de História Natural Capão da Imbuia](https://registry.gbif.org/organization/02a23c15-0df3-4bae-9524-11622114e0c9)
- Publishing country: BRAZIL
- Installation: [IPT Taxonline - Rede Paranaense de Coleções Biológicas](https://registry.gbif.org/installation/f129364a-33f3-4f3d-a41a-35073cf22b16)
- Number of occurrences indexed for this dataset at the time of the issue: 6683
- Cause: GBIF ID problems exceed 50% threshold: 100% duplicates; 7438 total records; 7438 absent records
- Pipelines execution steps: [http://api.gbif.org/v1/pipelines/history/execution/3169903/step](http://api.gbif.org/v1/pipelines/history/execution/3169903/step)
<details>
<summary>Publisher email</summary>

Hello,

I am contacting you from the GBIF Secretariat about a dataset published by the [Coleção de Mastozoologia do Museu de História Natural Capão da Imbuia](https://registry.gbif.org/dataset/0dfeb21c-5cfa-4bc8-8efd-bfd3f8968d45) : https://doi.org/10.15468/34kj28.
We noticed that the occurrenceIDs were changed. We have temporarily paused the ingestions of this dataset.

As you might already know, when an occurrence record has a new occurrenceID for a given dataset, our system considers it to be a new occurrence.
This means that it will be given a new gbifid and a new occurrence URL (like this one: https://www.gbif.org/occurrence/1252968762) and the old gbifid and URL will be deprecated.

In this case, this means that the occurrence URLs would be deprecated when ingesting the newest versions of these datasets.

We would like to check with you if those changes were intentional. Do you know if this is the case?
Please let us know, thanks! We are happy to resume the dataset ingestion.

Note that some users rely on those occurrence URLs and gbifids (like https://bionomia.net for example). In an attempt to improve
the stability of the occurrence URLs and gbifids, we have implemented a warning system to detect these type of changes in datasets (see this news item).
If the data publisher can provide us with a list of old and new occurrenceIDs per record, we can avoid the identifier and URL changes. Could that be an option?

Please let us know if you have any question. Thanks!

All the best,

</details>

You can skip/fix identifier validation using [the registry UI](https://registry.gbif.org/dataset/0dfeb21c-5cfa-4bc8-8efd-bfd3f8968d45/ingestion-history).

**Comment by gbif-pipelines** [comment]
Identifier validation still  failing for the dataset [Coleção de Mastozoologia do Museu de História Natural Capão da Imbuia](https://registry.gbif.org/dataset/0dfeb21c-5cfa-4bc8-8efd-bfd3f8968d45):
- Crawler attempt: 7
- Publishing organization: [Museu de História Natural Capão da Imbuia](https://registry.gbif.org/organization/02a23c15-0df3-4bae-9524-11622114e0c9)
- Publishing country: BRAZIL
- Installation: [IPT Taxonline - Rede Paranaense de Coleções Biológicas](https://registry.gbif.org/installation/f129364a-33f3-4f3d-a41a-35073cf22b16)
- Number of occurrences indexed for this dataset at the time of the issue: 6683
- Cause: GBIF ID problems exceed 50% threshold: 100% duplicates; 7438 total records; 7438 absent records
- Pipelines execution steps: [http://api.gbif.org/v1/pipelines/history/execution/3170492/step](http://api.gbif.org/v1/pipelines/history/execution/3170492/step)
<details>
<summary>Publisher email</summary>

Hello,

I am contacting you from the GBIF Secretariat about a dataset published by the [Coleção de Mastozoologia do Museu de História Natural Capão da Imbuia](https://registry.gbif.org/dataset/0dfeb21c-5cfa-4bc8-8efd-bfd3f8968d45) : https://doi.org/10.15468/34kj28.
We noticed that the occurrenceIDs were changed. We have temporarily paused the ingestions of this dataset.

As you might already know, when an occurrence record has a new occurrenceID for a given dataset, our system considers it to be a new occurrence.
This means that it will be given a new gbifid and a new occurrence URL (like this one: https://www.gbif.org/occurrence/1252968762) and the old gbifid and URL will be deprecated.

In this case, this means that the occurrence URLs would be deprecated when ingesting the newest versions of these datasets.

We would like to check with you if those changes were intentional. Do you know if this is the case?
Please let us know, thanks! We are happy to resume the dataset ingestion.

Note that some users rely on those occurrence URLs and gbifids (like https://bionomia.net for example). In an attempt to improve
the stability of the occurrence URLs and gbifids, we have implemented a warning system to detect these type of changes in datasets (see this news item).
If the data publisher can provide us with a list of old and new occurrenceIDs per record, we can avoid the identifier and URL changes. Could that be an option?

Please let us know if you have any question. Thanks!

All the best,

</details>


You can skip/fix identifier validation using [the registry UI](https://registry.gbif.org/dataset/0dfeb21c-5cfa-4bc8-8efd-bfd3f8968d45/ingestion-history).

**Comment by ktotsum** [comment]
Contacted the user from helpdesk on 2023-05-23. No action has been taken since then but the dataset was ingested successfully on 2023-08-28.
