### ISSUE TITLE
Identifiers validation failed for dataset Equinodermos de la Colección de Referencia de Biología Marina de la Universidad del Valle (CRBMeq-UV)

### ISSUE THREAD

**Issue by gbif-pipelines** [gbif/ingestion-management#699]
Identifier validation failed for the dataset [Equinodermos de la Colección de Referencia de Biología Marina de la Universidad del Valle (CRBMeq-UV)](https://registry.gbif.org/dataset/03a84058-3571-46c8-837f-efd412152734):
- Crawler attempt: 250
- Publishing organization: [Universidad del Valle](https://registry.gbif.org/organization/85be57ed-f187-49c9-b7ff-eaa622e06217)
- Publishing country: COLOMBIA
- Installation: [Datos sobre Biodiversidad de Colombia](https://registry.gbif.org/installation/68845aab-a453-4816-b36d-a3ec8455deb0)
- Number of occurrences indexed for this dataset at the time of the issue: 295
- Cause: GBIF ID problems exceed 50% threshold: 58% duplicates; 624 total records; 361 absent records
- Pipelines execution steps: [http://api.gbif.org/v1/pipelines/history/execution/3170619/step](http://api.gbif.org/v1/pipelines/history/execution/3170619/step)
<details>
<summary>Publisher email</summary>

Hello,

I am contacting you from the GBIF Secretariat about a dataset published by the [Equinodermos de la Colección de Referencia de Biología Marina de la Universidad del Valle (CRBMeq-UV)](https://registry.gbif.org/dataset/03a84058-3571-46c8-837f-efd412152734) : https://doi.org/10.15472/lywq4k.
We noticed that the occurrenceIDs were changed. We have temporarily paused the ingestions of this dataset.

As you might already know, when an occurrence record has a new occurrenceID for a given dataset, our system considers it to be a new occurrence.
This means that it will be given a new gbifid and a new occurrence URL (like this one: https://www.gbif.org/occurrence/1252968762) and the old gbifid and URL will be deprecated.

In this case, this means that the occurrence URLs would be deprecated when ingesting the newest versions of these datasets.

We would like to check with you if those changes were intentional. Do you know if this is the case?
Please let us know, thanks! We are happy to resume the dataset ingestion.

Note that some users rely on those occurrence URLs and gbifids (like https://bionomia.net for example). In an attempt to improve
the stability of the occurrence URLs and gbifids, we have implemented a warning system to detect these type of changes in datasets (see this news item).
If the data publisher can provide us with a list of old and new occurrenceIDs per record, we can avoid the identifier and URL changes. Could that be an option?

Please let us know if you have any question. Thanks!

All the best,

</details>

You can skip/fix identifier validation using [the registry UI](https://registry.gbif.org/dataset/03a84058-3571-46c8-837f-efd412152734/ingestion-history).

**Comment by gbif-pipelines** [comment]
Identifier validation still  failing for the dataset [Equinodermos de la Colección de Referencia de Biología Marina de la Universidad del Valle (CRBMeq-UV)](https://registry.gbif.org/dataset/03a84058-3571-46c8-837f-efd412152734):
- Crawler attempt: 250
- Publishing organization: [Universidad del Valle](https://registry.gbif.org/organization/85be57ed-f187-49c9-b7ff-eaa622e06217)
- Publishing country: COLOMBIA
- Installation: [Datos sobre Biodiversidad de Colombia](https://registry.gbif.org/installation/68845aab-a453-4816-b36d-a3ec8455deb0)
- Number of occurrences indexed for this dataset at the time of the issue: 295
- Cause: GBIF ID problems exceed 50% threshold: 58% duplicates; 624 total records; 361 absent records
- Pipelines execution steps: [http://api.gbif.org/v1/pipelines/history/execution/3389451/step](http://api.gbif.org/v1/pipelines/history/execution/3389451/step)

```
New IDs sample:

UNIVALLE:CRBMeq-UV:1984-002
UNIVALLE:CRBMeq-UV:1984-012
UNIVALLE:CRBMeq-UV:1984-031
UNIVALLE:CRBMeq-UV:1984-010
UNIVALLE:CRBMeq-UV:1983-021
UNIVALLE:CRBMeq-UV:1984-028
UNIVALLE:CRBMeq-UV:1984-025
UNIVALLE:CRBMeq-UV:1983-002
UNIVALLE:CRBMeq-UV:1984-003
UNIVALLE:CRBMeq-UV:1987-003
```


```
Old IDs sample:

UNIVALLE:CRBMeq-UV:1977-002
UNIVALLE:CRBMeq-UV:1978-008
UNIVALLE:CRBMeq-UV:2011-001
UNIVALLE:CRBMeq-UV:2011-002
UNIVALLE:CRBMeq-UV:2011-003
UNIVALLE:CRBMeq-UV:2010-001
UNIVALLE:CRBMeq-UV:2010-002
UNIVALLE:CRBMeq-UV:2009-021
UNIVALLE:CRBMeq-UV:2012-001
UNIVALLE:CRBMeq-UV:1980-009
```

<details>
<summary>Publisher email</summary>

Hello,

I am contacting you from the GBIF Secretariat about a dataset published by the [Equinodermos de la Colección de Referencia de Biología Marina de la Universidad del Valle (CRBMeq-UV)](https://registry.gbif.org/dataset/03a84058-3571-46c8-837f-efd412152734) : https://doi.org/10.15472/lywq4k.
We noticed that the occurrenceIDs were changed. We have temporarily paused the ingestions of this dataset.

As you might already know, when an occurrence record has a new occurrenceID for a given dataset, our system considers it to be a new occurrence.
This means that it will be given a new gbifid and a new occurrence URL (like this one: https://www.gbif.org/occurrence/1252968762) and the old gbifid and URL will be deprecated.

In this case, this means that the occurrence URLs would be deprecated when ingesting the newest versions of these datasets.

We would like to check with you if those changes were intentional. Do you know if this is the case?
Please let us know, thanks! We are happy to resume the dataset ingestion.

Note that some users rely on those occurrence URLs and gbifids (like https://bionomia.net for example). In an attempt to improve
the stability of the occurrence URLs and gbifids, we have implemented a warning system to detect these type of changes in datasets (see this news item).
If the data publisher can provide us with a list of old and new occurrenceIDs per record, we can avoid the identifier and URL changes. Could that be an option?

Please let us know if you have any question. Thanks!

All the best,

</details>


You can skip/fix identifier validation using [the registry UI](https://registry.gbif.org/dataset/03a84058-3571-46c8-837f-efd412152734/ingestion-history).

**Comment by ktotsum** [comment]
The dataset has been updated after fixing a technical bug (some internal files were missing).
