### ISSUE TITLE
Identifiers validation failed for dataset Auckland Museum NZ Marine Collection

### ISSUE THREAD

**Issue by gbif-pipelines** [gbif/ingestion-management#806]
Identifier validation failed for the dataset [Auckland Museum NZ Marine Collection](https://registry.gbif.org/dataset/e2980e63-d152-4219-8c1e-0ffdef3ea6aa):
- Crawler attempt: 384
- Publishing organization: [Auckland War Memorial Museum](https://registry.gbif.org/organization/32e82a64-c9b4-4b2f-9fbd-d446309b973f)
- Publishing country: NEW_ZEALAND
- Installation: [Auckland War Memorial Museum](https://registry.gbif.org/installation/58f76e14-f21d-4c3b-9c20-e14c006b7d3f)
- Number of occurrences indexed for this dataset at the time of the issue: 20414
- Cause: GBIF ID problems exceed 50% threshold: 90% duplicates; 48974 total records; 44011 absent records
- Pipelines execution steps: [http://api.gbif.org/v1/pipelines/history/execution/3173103/step](http://api.gbif.org/v1/pipelines/history/execution/3173103/step)
<details>
<summary>Publisher email</summary>

Hello,

I am contacting you from the GBIF Secretariat about a dataset published by the [Auckland Museum NZ Marine Collection](https://registry.gbif.org/dataset/e2980e63-d152-4219-8c1e-0ffdef3ea6aa) : https://doi.org/10.15468/plyefd.
We noticed that the occurrenceIDs were changed. We have temporarily paused the ingestions of this dataset.

As you might already know, when an occurrence record has a new occurrenceID for a given dataset, our system considers it to be a new occurrence.
This means that it will be given a new gbifid and a new occurrence URL (like this one: https://www.gbif.org/occurrence/1252968762) and the old gbifid and URL will be deprecated.

In this case, this means that the occurrence URLs would be deprecated when ingesting the newest versions of these datasets.

We would like to check with you if those changes were intentional. Do you know if this is the case?
Please let us know, thanks! We are happy to resume the dataset ingestion.

Note that some users rely on those occurrence URLs and gbifids (like https://bionomia.net for example). In an attempt to improve
the stability of the occurrence URLs and gbifids, we have implemented a warning system to detect these type of changes in datasets (see this news item).
If the data publisher can provide us with a list of old and new occurrenceIDs per record, we can avoid the identifier and URL changes. Could that be an option?

Please let us know if you have any question. Thanks!

All the best,

</details>

You can skip/fix identifier validation using [the registry UI](https://registry.gbif.org/dataset/e2980e63-d152-4219-8c1e-0ffdef3ea6aa/ingestion-history).

**Comment by ktotsum** [comment]
We asked questions on the list of old/new occurrenceIDs list that we received from the publisher on 2023-09-08.

**Comment by ktotsum** [comment]
@ManonGros Could you follow up on this case? Maybe we could migrate just 618 records and resume the rest.
