### ISSUE TITLE
Identifiers validation failed for dataset Biological records of potentially host plants of mexican wild bees identified from iNaturalist

### ISSUE THREAD

**Issue by gbif-pipelines** [gbif/ingestion-management#808]
Identifier validation failed for the dataset [Biological records of potentially host plants of mexican wild bees identified from iNaturalist](https://registry.gbif.org/dataset/e1e1e05e-a239-49aa-9e10-94b81cf63b7f):
- Crawler attempt: 76
- Publishing organization: [Comisión nacional para el conocimiento y uso de la biodiversidad](https://registry.gbif.org/organization/ff90b050-c256-11db-b71b-b8a03c50a862)
- Publishing country: MEXICO
- Installation: [IPTCONABIO](https://registry.gbif.org/installation/e081c7d7-2dab-42fd-94c4-9f275767fe7d)
- Number of occurrences indexed for this dataset at the time of the issue: 4532
- Cause: GBIF ID problems exceed 50% threshold: 100% duplicates; 4532 total records; 4532 absent records
- Pipelines execution steps: [http://api.gbif.org/v1/pipelines/history/execution/3181073/step](http://api.gbif.org/v1/pipelines/history/execution/3181073/step)
<details>
<summary>Publisher email</summary>

Hello,

I am contacting you from the GBIF Secretariat about a dataset published by the [Biological records of potentially host plants of mexican wild bees identified from iNaturalist](https://registry.gbif.org/dataset/e1e1e05e-a239-49aa-9e10-94b81cf63b7f) : https://doi.org/10.15468/m4r9h2.
We noticed that the occurrenceIDs were changed. We have temporarily paused the ingestions of this dataset.

As you might already know, when an occurrence record has a new occurrenceID for a given dataset, our system considers it to be a new occurrence.
This means that it will be given a new gbifid and a new occurrence URL (like this one: https://www.gbif.org/occurrence/1252968762) and the old gbifid and URL will be deprecated.

In this case, this means that the occurrence URLs would be deprecated when ingesting the newest versions of these datasets.

We would like to check with you if those changes were intentional. Do you know if this is the case?
Please let us know, thanks! We are happy to resume the dataset ingestion.

Note that some users rely on those occurrence URLs and gbifids (like https://bionomia.net for example). In an attempt to improve
the stability of the occurrence URLs and gbifids, we have implemented a warning system to detect these type of changes in datasets (see this news item).
If the data publisher can provide us with a list of old and new occurrenceIDs per record, we can avoid the identifier and URL changes. Could that be an option?

Please let us know if you have any question. Thanks!

All the best,

</details>

You can skip/fix identifier validation using [the registry UI](https://registry.gbif.org/dataset/e1e1e05e-a239-49aa-9e10-94b81cf63b7f/ingestion-history).

**Comment by gbif-pipelines** [comment]
Identifier validation still  failing for the dataset [Biological records of potentially host plants of mexican wild bees identified from iNaturalist](https://registry.gbif.org/dataset/e1e1e05e-a239-49aa-9e10-94b81cf63b7f):
- Crawler attempt: 77
- Publishing organization: [Comisión nacional para el conocimiento y uso de la biodiversidad](https://registry.gbif.org/organization/ff90b050-c256-11db-b71b-b8a03c50a862)
- Publishing country: MEXICO
- Installation: [IPTCONABIO](https://registry.gbif.org/installation/e081c7d7-2dab-42fd-94c4-9f275767fe7d)
- Number of occurrences indexed for this dataset at the time of the issue: 4532
- Cause: GBIF ID problems exceed 50% threshold: 100% duplicates; 4532 total records; 4532 absent records
- Pipelines execution steps: [http://api.gbif.org/v1/pipelines/history/execution/3191485/step](http://api.gbif.org/v1/pipelines/history/execution/3191485/step)
<details>
<summary>Publisher email</summary>

Hello,

I am contacting you from the GBIF Secretariat about a dataset published by the [Biological records of potentially host plants of mexican wild bees identified from iNaturalist](https://registry.gbif.org/dataset/e1e1e05e-a239-49aa-9e10-94b81cf63b7f) : https://doi.org/10.15468/m4r9h2.
We noticed that the occurrenceIDs were changed. We have temporarily paused the ingestions of this dataset.

As you might already know, when an occurrence record has a new occurrenceID for a given dataset, our system considers it to be a new occurrence.
This means that it will be given a new gbifid and a new occurrence URL (like this one: https://www.gbif.org/occurrence/1252968762) and the old gbifid and URL will be deprecated.

In this case, this means that the occurrence URLs would be deprecated when ingesting the newest versions of these datasets.

We would like to check with you if those changes were intentional. Do you know if this is the case?
Please let us know, thanks! We are happy to resume the dataset ingestion.

Note that some users rely on those occurrence URLs and gbifids (like https://bionomia.net for example). In an attempt to improve
the stability of the occurrence URLs and gbifids, we have implemented a warning system to detect these type of changes in datasets (see this news item).
If the data publisher can provide us with a list of old and new occurrenceIDs per record, we can avoid the identifier and URL changes. Could that be an option?

Please let us know if you have any question. Thanks!

All the best,

</details>


You can skip/fix identifier validation using [the registry UI](https://registry.gbif.org/dataset/e1e1e05e-a239-49aa-9e10-94b81cf63b7f/ingestion-history).

**Comment by jhnwllr** [comment]
Has occurrenceIds with dashes, meaning the bulk download because it was length 32 instead of 36 characters. 


new ids:  
75fbee05-3fa1-4976-8296-3e786468627c
73b3c75a-605a-46da-8905-21805f5a144f
24082667-e88c-4596-902d-7e292462f6a6
8aaf9cb3-e167-4a9f-8ba5-4872301be92c
f90e36b8-ea79-4a3d-a718-74c897c509e4
1f14ab2d-f590-46cd-b510-de09f92bac3c
f4783d62-be87-4975-ba39-b7632594cddd
0a3d7521-05fe-4585-947b-93ee55b35873
54c2d11c-931e-4732-bc58-80d0957b74f6
2ae6007d-dba3-4762-a2cc-64a2ead42a91
current ids: 

id sample:  
cb0ad00c-59ef-4f5e-95d5-617d43d0b57d
5e5fb1d1-383e-4fa5-b9c1-182ed41c7203
9d2a6e7c-0dec-4a93-803e-418a3ef50ab1
f69058ca-6204-4830-b1fa-d8b36eb36ed7
ee9df5ad-049c-496a-91af-77d3f5b8c8c7
95e2b030-17ea-44d6-a460-1625b56ec182
d547df11-237c-410c-9d96-2f7d35471ede
81daac2b-6c25-4c8b-b3bb-5f4a6a95da93
7a836a7a-3039-4dcb-bd33-2bc530aadcab
2589b19f-45bb-46c2-81fe-7cb5d45723da

**Comment by gbif-pipelines** [comment]
Identifier validation still  failing for the dataset [Biological records of potentially host plants of mexican wild bees identified from iNaturalist](https://registry.gbif.org/dataset/e1e1e05e-a239-49aa-9e10-94b81cf63b7f):
- Crawler attempt: 79
- Publishing organization: [Comisión nacional para el conocimiento y uso de la biodiversidad](https://registry.gbif.org/organization/ff90b050-c256-11db-b71b-b8a03c50a862)
- Publishing country: MEXICO
- Installation: [IPTCONABIO](https://registry.gbif.org/installation/e081c7d7-2dab-42fd-94c4-9f275767fe7d)
- Number of occurrences indexed for this dataset at the time of the issue: 4532
- Cause: GBIF ID problems exceed 50% threshold: 100% duplicates; 4532 total records; 4532 absent records
- Pipelines execution steps: [http://api.gbif.org/v1/pipelines/history/execution/3273545/step](http://api.gbif.org/v1/pipelines/history/execution/3273545/step)
<details>
<summary>Publisher email</summary>

Hello,

I am contacting you from the GBIF Secretariat about a dataset published by the [Biological records of potentially host plants of mexican wild bees identified from iNaturalist](https://registry.gbif.org/dataset/e1e1e05e-a239-49aa-9e10-94b81cf63b7f) : https://doi.org/10.15468/m4r9h2.
We noticed that the occurrenceIDs were changed. We have temporarily paused the ingestions of this dataset.

As you might already know, when an occurrence record has a new occurrenceID for a given dataset, our system considers it to be a new occurrence.
This means that it will be given a new gbifid and a new occurrence URL (like this one: https://www.gbif.org/occurrence/1252968762) and the old gbifid and URL will be deprecated.

In this case, this means that the occurrence URLs would be deprecated when ingesting the newest versions of these datasets.

We would like to check with you if those changes were intentional. Do you know if this is the case?
Please let us know, thanks! We are happy to resume the dataset ingestion.

Note that some users rely on those occurrence URLs and gbifids (like https://bionomia.net for example). In an attempt to improve
the stability of the occurrence URLs and gbifids, we have implemented a warning system to detect these type of changes in datasets (see this news item).
If the data publisher can provide us with a list of old and new occurrenceIDs per record, we can avoid the identifier and URL changes. Could that be an option?

Please let us know if you have any question. Thanks!

All the best,

</details>


You can skip/fix identifier validation using [the registry UI](https://registry.gbif.org/dataset/e1e1e05e-a239-49aa-9e10-94b81cf63b7f/ingestion-history).

**Comment by jhnwllr** [comment]
Id checks skipped because publisher wants to keep the new ids.
