### ISSUE TITLE
Identifiers validation failed for dataset Biological Collection of National Taiwan Museum, Taipei, Taiwan

### ISSUE THREAD

**Issue by gbif-pipelines** [gbif/ingestion-management#811]
Identifier validation failed for the dataset [Biological Collection of National Taiwan Museum, Taipei, Taiwan](https://registry.gbif.org/dataset/24f1ac6a-8f1d-4d23-8453-e5ce18bff54c):
- Crawler attempt: 54
- Publishing organization: [National Taiwan Museum](https://registry.gbif.org/organization/c57cd401-ff9e-43bd-9403-089b88a97dea)
- Publishing country: TAIWAN
- Installation: [TaiBIF IPT](https://registry.gbif.org/installation/08eefeeb-e20f-4482-8e0f-f218547e2f50)
- Number of occurrences indexed for this dataset at the time of the issue: 23346
- Cause: GBIF ID problems exceed 50% threshold: 66% duplicates; 68001 total records; 44656 absent records
- Pipelines execution steps: [http://api.gbif.org/v1/pipelines/history/execution/3181860/step](http://api.gbif.org/v1/pipelines/history/execution/3181860/step)
<details>
<summary>Publisher email</summary>

Hello,

I am contacting you from the GBIF Secretariat about a dataset published by the [Biological Collection of National Taiwan Museum, Taipei, Taiwan](https://registry.gbif.org/dataset/24f1ac6a-8f1d-4d23-8453-e5ce18bff54c) : https://doi.org/10.15468/fxzm63.
We noticed that the occurrenceIDs were changed. We have temporarily paused the ingestions of this dataset.

As you might already know, when an occurrence record has a new occurrenceID for a given dataset, our system considers it to be a new occurrence.
This means that it will be given a new gbifid and a new occurrence URL (like this one: https://www.gbif.org/occurrence/1252968762) and the old gbifid and URL will be deprecated.

In this case, this means that the occurrence URLs would be deprecated when ingesting the newest versions of these datasets.

We would like to check with you if those changes were intentional. Do you know if this is the case?
Please let us know, thanks! We are happy to resume the dataset ingestion.

Note that some users rely on those occurrence URLs and gbifids (like https://bionomia.net for example). In an attempt to improve
the stability of the occurrence URLs and gbifids, we have implemented a warning system to detect these type of changes in datasets (see this news item).
If the data publisher can provide us with a list of old and new occurrenceIDs per record, we can avoid the identifier and URL changes. Could that be an option?

Please let us know if you have any question. Thanks!

All the best,

</details>

You can skip/fix identifier validation using [the registry UI](https://registry.gbif.org/dataset/24f1ac6a-8f1d-4d23-8453-e5ce18bff54c/ingestion-history).

**Comment by gbif-pipelines** [comment]
Identifier validation still  failing for the dataset [Biological Collection of National Taiwan Museum, Taipei, Taiwan](https://registry.gbif.org/dataset/24f1ac6a-8f1d-4d23-8453-e5ce18bff54c):
- Crawler attempt: 55
- Publishing organization: [National Taiwan Museum](https://registry.gbif.org/organization/c57cd401-ff9e-43bd-9403-089b88a97dea)
- Publishing country: TAIWAN
- Installation: [TaiBIF IPT](https://registry.gbif.org/installation/08eefeeb-e20f-4482-8e0f-f218547e2f50)
- Number of occurrences indexed for this dataset at the time of the issue: 23346
- Cause: GBIF ID problems exceed 50% threshold: 66% duplicates; 68001 total records; 44656 absent records
- Pipelines execution steps: [http://api.gbif.org/v1/pipelines/history/execution/3182427/step](http://api.gbif.org/v1/pipelines/history/execution/3182427/step)
<details>
<summary>Publisher email</summary>

Hello,

I am contacting you from the GBIF Secretariat about a dataset published by the [Biological Collection of National Taiwan Museum, Taipei, Taiwan](https://registry.gbif.org/dataset/24f1ac6a-8f1d-4d23-8453-e5ce18bff54c) : https://doi.org/10.15468/fxzm63.
We noticed that the occurrenceIDs were changed. We have temporarily paused the ingestions of this dataset.

As you might already know, when an occurrence record has a new occurrenceID for a given dataset, our system considers it to be a new occurrence.
This means that it will be given a new gbifid and a new occurrence URL (like this one: https://www.gbif.org/occurrence/1252968762) and the old gbifid and URL will be deprecated.

In this case, this means that the occurrence URLs would be deprecated when ingesting the newest versions of these datasets.

We would like to check with you if those changes were intentional. Do you know if this is the case?
Please let us know, thanks! We are happy to resume the dataset ingestion.

Note that some users rely on those occurrence URLs and gbifids (like https://bionomia.net for example). In an attempt to improve
the stability of the occurrence URLs and gbifids, we have implemented a warning system to detect these type of changes in datasets (see this news item).
If the data publisher can provide us with a list of old and new occurrenceIDs per record, we can avoid the identifier and URL changes. Could that be an option?

Please let us know if you have any question. Thanks!

All the best,

</details>


You can skip/fix identifier validation using [the registry UI](https://registry.gbif.org/dataset/24f1ac6a-8f1d-4d23-8453-e5ce18bff54c/ingestion-history).

**Comment by ktotsum** [comment]
Resumed the data ingestion because the identifiers did not change between the old and the new records for the existing records. The issue was created due to the increase of data by 3 times.
https://ipt.taibif.tw/resource?r=ntm-bio-collection&v=1.5
