### ISSUE TITLE
Identifiers validation failed for dataset Programa de fotomonitoreo de objetos de conservación y amenazas en el Sistema Nacional de Áreas Silvestres Protegidas del Estado (SNASPE)

### ISSUE THREAD

**Issue by gbif-pipelines** [gbif/ingestion-management#812]
Identifier validation failed for the dataset [Programa de fotomonitoreo de objetos de conservación y amenazas en el Sistema Nacional de Áreas Silvestres Protegidas del Estado (SNASPE)](https://registry.gbif.org/dataset/9f7ed5a4-f73a-4d74-b0be-cef5bd700a37):
- Crawler attempt: 95
- Publishing organization: [Corporación Nacional Forestal](https://registry.gbif.org/organization/6568c9e4-fdc6-4d73-a7ea-2d1bf44fcd61)
- Publishing country: CHILE
- Installation: [IPT v.2.3.2](https://registry.gbif.org/installation/faeb021c-ab9f-4c80-9587-3749a8f6fb23)
- Number of occurrences indexed for this dataset at the time of the issue: 217775
- Cause: GBIF ID problems exceed 50% threshold: 79% duplicates; 612187 total records; 483304 absent records
- Pipelines execution steps: [http://api.gbif.org/v1/pipelines/history/execution/3182010/step](http://api.gbif.org/v1/pipelines/history/execution/3182010/step)
<details>
<summary>Publisher email</summary>

Hello,

I am contacting you from the GBIF Secretariat about a dataset published by the [Programa de fotomonitoreo de objetos de conservación y amenazas en el Sistema Nacional de Áreas Silvestres Protegidas del Estado (SNASPE)](https://registry.gbif.org/dataset/9f7ed5a4-f73a-4d74-b0be-cef5bd700a37) : https://doi.org/10.15468/gwjq89.
We noticed that the occurrenceIDs were changed. We have temporarily paused the ingestions of this dataset.

As you might already know, when an occurrence record has a new occurrenceID for a given dataset, our system considers it to be a new occurrence.
This means that it will be given a new gbifid and a new occurrence URL (like this one: https://www.gbif.org/occurrence/1252968762) and the old gbifid and URL will be deprecated.

In this case, this means that the occurrence URLs would be deprecated when ingesting the newest versions of these datasets.

We would like to check with you if those changes were intentional. Do you know if this is the case?
Please let us know, thanks! We are happy to resume the dataset ingestion.

Note that some users rely on those occurrence URLs and gbifids (like https://bionomia.net for example). In an attempt to improve
the stability of the occurrence URLs and gbifids, we have implemented a warning system to detect these type of changes in datasets (see this news item).
If the data publisher can provide us with a list of old and new occurrenceIDs per record, we can avoid the identifier and URL changes. Could that be an option?

Please let us know if you have any question. Thanks!

All the best,

</details>

You can skip/fix identifier validation using [the registry UI](https://registry.gbif.org/dataset/9f7ed5a4-f73a-4d74-b0be-cef5bd700a37/ingestion-history).

**Comment by gbif-pipelines** [comment]
Identifier validation still  failing for the dataset [Programa de fotomonitoreo de objetos de conservación y amenazas en el Sistema Nacional de Áreas Protegidas (SNAP)](https://registry.gbif.org/dataset/9f7ed5a4-f73a-4d74-b0be-cef5bd700a37):
- Crawler attempt: 96
- Publishing organization: [Corporación Nacional Forestal](https://registry.gbif.org/organization/6568c9e4-fdc6-4d73-a7ea-2d1bf44fcd61)
- Publishing country: CHILE
- Installation: [IPT v.2.3.2](https://registry.gbif.org/installation/faeb021c-ab9f-4c80-9587-3749a8f6fb23)
- Number of occurrences indexed for this dataset at the time of the issue: 217775
- Cause: GBIF ID problems exceed 50% threshold: 79% duplicates; 612187 total records; 483304 absent records
- Pipelines execution steps: [http://api.gbif.org/v1/pipelines/history/execution/3182142/step](http://api.gbif.org/v1/pipelines/history/execution/3182142/step)
<details>
<summary>Publisher email</summary>

Hello,

I am contacting you from the GBIF Secretariat about a dataset published by the [Programa de fotomonitoreo de objetos de conservación y amenazas en el Sistema Nacional de Áreas Protegidas (SNAP)](https://registry.gbif.org/dataset/9f7ed5a4-f73a-4d74-b0be-cef5bd700a37) : https://doi.org/10.15468/gwjq89.
We noticed that the occurrenceIDs were changed. We have temporarily paused the ingestions of this dataset.

As you might already know, when an occurrence record has a new occurrenceID for a given dataset, our system considers it to be a new occurrence.
This means that it will be given a new gbifid and a new occurrence URL (like this one: https://www.gbif.org/occurrence/1252968762) and the old gbifid and URL will be deprecated.

In this case, this means that the occurrence URLs would be deprecated when ingesting the newest versions of these datasets.

We would like to check with you if those changes were intentional. Do you know if this is the case?
Please let us know, thanks! We are happy to resume the dataset ingestion.

Note that some users rely on those occurrence URLs and gbifids (like https://bionomia.net for example). In an attempt to improve
the stability of the occurrence URLs and gbifids, we have implemented a warning system to detect these type of changes in datasets (see this news item).
If the data publisher can provide us with a list of old and new occurrenceIDs per record, we can avoid the identifier and URL changes. Could that be an option?

Please let us know if you have any question. Thanks!

All the best,

</details>


You can skip/fix identifier validation using [the registry UI](https://registry.gbif.org/dataset/9f7ed5a4-f73a-4d74-b0be-cef5bd700a37/ingestion-history).

**Comment by ktotsum** [comment]
Identifier migration was conducted before the dataset was published (helpdesk email: Technical Consultations - Chile). This issue was created because the number of records increased by 3 times.
