### ISSUE TITLE
Identifiers validation failed for dataset NEON breeding landbird point counts

### ISSUE THREAD

**Issue by gbif-pipelines** [gbif/ingestion-management#816]
Identifier validation failed for the dataset [NEON breeding landbird point counts](https://registry.gbif.org/dataset/516eb7c0-3586-4dfc-bc18-c1fc1e765b7f):
- Crawler attempt: 89
- Publishing organization: [National Ecological Observatory Network](https://registry.gbif.org/organization/e794e60e-e558-4549-99f8-cfb241cdce24)
- Publishing country: UNITED_STATES
- Installation: [USGS GBIF-US IPT](https://registry.gbif.org/installation/394c0f8e-8b5e-4fbc-b942-568a4a267032)
- Number of occurrences indexed for this dataset at the time of the issue: 151139
- Cause: GBIF ID problems exceed 50% threshold: 100% duplicates; 227981 total records; 227981 absent records
- Pipelines execution steps: [http://api.gbif.org/v1/pipelines/history/execution/3182492/step](http://api.gbif.org/v1/pipelines/history/execution/3182492/step)
<details>
<summary>Publisher email</summary>

Hello,

I am contacting you from the GBIF Secretariat about a dataset published by the [NEON breeding landbird point counts](https://registry.gbif.org/dataset/516eb7c0-3586-4dfc-bc18-c1fc1e765b7f) : https://doi.org/10.15468/3vd2zk.
We noticed that the occurrenceIDs were changed. We have temporarily paused the ingestions of this dataset.

As you might already know, when an occurrence record has a new occurrenceID for a given dataset, our system considers it to be a new occurrence.
This means that it will be given a new gbifid and a new occurrence URL (like this one: https://www.gbif.org/occurrence/1252968762) and the old gbifid and URL will be deprecated.

In this case, this means that the occurrence URLs would be deprecated when ingesting the newest versions of these datasets.

We would like to check with you if those changes were intentional. Do you know if this is the case?
Please let us know, thanks! We are happy to resume the dataset ingestion.

Note that some users rely on those occurrence URLs and gbifids (like https://bionomia.net for example). In an attempt to improve
the stability of the occurrence URLs and gbifids, we have implemented a warning system to detect these type of changes in datasets (see this news item).
If the data publisher can provide us with a list of old and new occurrenceIDs per record, we can avoid the identifier and URL changes. Could that be an option?

Please let us know if you have any question. Thanks!

All the best,

</details>

You can skip/fix identifier validation using [the registry UI](https://registry.gbif.org/dataset/516eb7c0-3586-4dfc-bc18-c1fc1e765b7f/ingestion-history).

**Comment by ktotsum** [comment]
The dataset was ingested after the migration of identifiers provided by the data provider. occurrenceIDs change every time for this observation dataset so we suggest skipping identifier validation from next time.

**Comment by ktotsum** [comment]
We have set a tag to skip occurrencIDs check on request from the data provider.
