### ISSUE TITLE
Identifiers validation failed for dataset Kenai National Wildlife Refuge Aquatic Invasive Fish Surveys

### ISSUE THREAD

**Issue by gbif-pipelines** [gbif/ingestion-management#818]
Identifier validation failed for the dataset [Kenai National Wildlife Refuge Aquatic Invasive Fish Surveys](https://registry.gbif.org/dataset/b88e40a8-c39e-4f8f-962a-7f6d93a977a4):
- Crawler attempt: 21
- Publishing organization: [United States Fish and Wildlife Service](https://registry.gbif.org/organization/f8dbeca7-3131-41ab-872f-bfad71041f3f)
- Publishing country: UNITED_STATES
- Installation: [USGS GBIF-US IPT](https://registry.gbif.org/installation/394c0f8e-8b5e-4fbc-b942-568a4a267032)
- Number of occurrences indexed for this dataset at the time of the issue: 198
- Cause: GBIF ID problems exceed 50% threshold: 67% duplicates; 238 total records; 159 absent records
- Pipelines execution steps: [http://api.gbif.org/v1/pipelines/history/execution/3182801/step](http://api.gbif.org/v1/pipelines/history/execution/3182801/step)
<details>
<summary>Publisher email</summary>

Hello,

I am contacting you from the GBIF Secretariat about a dataset published by the [Kenai National Wildlife Refuge Aquatic Invasive Fish Surveys](https://registry.gbif.org/dataset/b88e40a8-c39e-4f8f-962a-7f6d93a977a4) : https://doi.org/10.15468/kzw2j5.
We noticed that the occurrenceIDs were changed. We have temporarily paused the ingestions of this dataset.

As you might already know, when an occurrence record has a new occurrenceID for a given dataset, our system considers it to be a new occurrence.
This means that it will be given a new gbifid and a new occurrence URL (like this one: https://www.gbif.org/occurrence/1252968762) and the old gbifid and URL will be deprecated.

In this case, this means that the occurrence URLs would be deprecated when ingesting the newest versions of these datasets.

We would like to check with you if those changes were intentional. Do you know if this is the case?
Please let us know, thanks! We are happy to resume the dataset ingestion.

Note that some users rely on those occurrence URLs and gbifids (like https://bionomia.net for example). In an attempt to improve
the stability of the occurrence URLs and gbifids, we have implemented a warning system to detect these type of changes in datasets (see this news item).
If the data publisher can provide us with a list of old and new occurrenceIDs per record, we can avoid the identifier and URL changes. Could that be an option?

Please let us know if you have any question. Thanks!

All the best,

</details>

You can skip/fix identifier validation using [the registry UI](https://registry.gbif.org/dataset/b88e40a8-c39e-4f8f-962a-7f6d93a977a4/ingestion-history).

**Comment by ktotsum** [comment]
The dataset was ingested successfully on 2023-09-03 without manual data processing from helpdesk.
