### ISSUE TITLE
Identifiers validation failed for dataset Registros biológicos de plantas con potencial actividad giardicida aplicando la zoofarmacognosia en el municipio de Solano, departamento de Caquetá

### ISSUE THREAD

**Issue by gbif-pipelines** [gbif/ingestion-management#820]
Identifier validation failed for the dataset [Registros biológicos de plantas con potencial actividad giardicida aplicando la zoofarmacognosia en el municipio de Solano, departamento de Caquetá](https://registry.gbif.org/dataset/bf77c333-4c4d-4e0c-b9b9-cfa50b7e17ae):
- Crawler attempt: 41
- Publishing organization: [Universidad del Magdalena](https://registry.gbif.org/organization/30ff48bd-4dd1-429d-a5a5-348c8e5fbfb1)
- Publishing country: COLOMBIA
- Installation: [Datos sobre Biodiversidad de Colombia](https://registry.gbif.org/installation/68845aab-a453-4816-b36d-a3ec8455deb0)
- Number of occurrences indexed for this dataset at the time of the issue: 4
- Cause: GBIF ID problems exceed 50% threshold: 100% duplicates; 74 total records; 74 absent records
- Pipelines execution steps: [http://api.gbif.org/v1/pipelines/history/execution/3255794/step](http://api.gbif.org/v1/pipelines/history/execution/3255794/step)
<details>
<summary>Publisher email</summary>

Hello,

I am contacting you from the GBIF Secretariat about a dataset published by the [Registros biológicos de plantas con potencial actividad giardicida aplicando la zoofarmacognosia en el municipio de Solano, departamento de Caquetá](https://registry.gbif.org/dataset/bf77c333-4c4d-4e0c-b9b9-cfa50b7e17ae) : https://doi.org/10.15472/j7msrp.
We noticed that the occurrenceIDs were changed. We have temporarily paused the ingestions of this dataset.

As you might already know, when an occurrence record has a new occurrenceID for a given dataset, our system considers it to be a new occurrence.
This means that it will be given a new gbifid and a new occurrence URL (like this one: https://www.gbif.org/occurrence/1252968762) and the old gbifid and URL will be deprecated.

In this case, this means that the occurrence URLs would be deprecated when ingesting the newest versions of these datasets.

We would like to check with you if those changes were intentional. Do you know if this is the case?
Please let us know, thanks! We are happy to resume the dataset ingestion.

Note that some users rely on those occurrence URLs and gbifids (like https://bionomia.net for example). In an attempt to improve
the stability of the occurrence URLs and gbifids, we have implemented a warning system to detect these type of changes in datasets (see this news item).
If the data publisher can provide us with a list of old and new occurrenceIDs per record, we can avoid the identifier and URL changes. Could that be an option?

Please let us know if you have any question. Thanks!

All the best,

</details>

You can skip/fix identifier validation using [the registry UI](https://registry.gbif.org/dataset/bf77c333-4c4d-4e0c-b9b9-cfa50b7e17ae/ingestion-history).

**Comment by ManonGros** [comment]
Hello again @RicardoOrtizG @EstebanMH-SiB, this other dataset was paused by the GBIF ingestion system because all occurrenceIDs were changed: https://ipt.biodiversidad.co/sib/resource?r=unimagdalena_plantas_zoofarmacognosia
Would it be possible to check this one as well?

PS: let me know if you prefer be contacted by email.

**Comment by EstebanMH-SiB** [comment]
Hello @ManonGros, in this one we can just reindex the dataset, originally there were just 4 records and the new actualization added 71 and deleted 3 of the original that are no longer part of this dataset. 

PS: Github issues are fine and in that way we can follow all ingestion issues

**Comment by ManonGros** [comment]
great, thanks @EstebanMH-SiB! I have resumed the dataset ingestion. You can see all the datasets currently paused because of a change of occurrenceID here: https://github.com/gbif/ingestion-management/labels/Country%20COLOMBIA
