### ISSUE TITLE
Identifiers validation failed for dataset Biodiversidad asociada al Área de perforación exploratoria - VIM46

### ISSUE THREAD

**Issue by gbif-pipelines** [gbif/ingestion-management#821]
Identifier validation failed for the dataset [Biodiversidad asociada al Área de perforación exploratoria - VIM46](https://registry.gbif.org/dataset/1a017764-ffb6-4880-801f-27e209a1f7e0):
- Crawler attempt: 22
- Publishing organization: [Frontera Energy Colombia Corp](https://registry.gbif.org/organization/591b93c8-b83c-45a4-8c8d-85728347a56c)
- Publishing country: COLOMBIA
- Installation: [Datos sobre Biodiversidad de Colombia](https://registry.gbif.org/installation/68845aab-a453-4816-b36d-a3ec8455deb0)
- Number of occurrences indexed for this dataset at the time of the issue: 6189
- Cause: GBIF ID problems exceed 50% threshold: 72% duplicates; 6258 total records; 4530 absent records
- Pipelines execution steps: [http://api.gbif.org/v1/pipelines/history/execution/3255796/step](http://api.gbif.org/v1/pipelines/history/execution/3255796/step)
<details>
<summary>Publisher email</summary>

Hello,

I am contacting you from the GBIF Secretariat about a dataset published by the [Biodiversidad asociada al Área de perforación exploratoria - VIM46](https://registry.gbif.org/dataset/1a017764-ffb6-4880-801f-27e209a1f7e0) : https://doi.org/10.15472/wzmpjt.
We noticed that the occurrenceIDs were changed. We have temporarily paused the ingestions of this dataset.

As you might already know, when an occurrence record has a new occurrenceID for a given dataset, our system considers it to be a new occurrence.
This means that it will be given a new gbifid and a new occurrence URL (like this one: https://www.gbif.org/occurrence/1252968762) and the old gbifid and URL will be deprecated.

In this case, this means that the occurrence URLs would be deprecated when ingesting the newest versions of these datasets.

We would like to check with you if those changes were intentional. Do you know if this is the case?
Please let us know, thanks! We are happy to resume the dataset ingestion.

Note that some users rely on those occurrence URLs and gbifids (like https://bionomia.net for example). In an attempt to improve
the stability of the occurrence URLs and gbifids, we have implemented a warning system to detect these type of changes in datasets (see this news item).
If the data publisher can provide us with a list of old and new occurrenceIDs per record, we can avoid the identifier and URL changes. Could that be an option?

Please let us know if you have any question. Thanks!

All the best,

</details>

You can skip/fix identifier validation using [the registry UI](https://registry.gbif.org/dataset/1a017764-ffb6-4880-801f-27e209a1f7e0/ingestion-history).

**Comment by ManonGros** [comment]
Hi @RicardoOrtizG @EstebanMH-SiB, the following dataset was paused by the GBIF ingestion system because 72% of the occurrenceIDs were changed: https://ipt.biodiversidad.co/sib/resource?r=fronteraenergy_vim46
Do you know if this was intentional? Should we let this dataset be ingested?

Let me know, thanks!

**Comment by gbif-pipelines** [comment]
Identifier validation still  failing for the dataset [Biodiversidad asociada al Área de perforación exploratoria - VIM46](https://registry.gbif.org/dataset/1a017764-ffb6-4880-801f-27e209a1f7e0):
- Crawler attempt: 22
- Publishing organization: [Frontera Energy Colombia Corp](https://registry.gbif.org/organization/591b93c8-b83c-45a4-8c8d-85728347a56c)
- Publishing country: COLOMBIA
- Installation: [Datos sobre Biodiversidad de Colombia](https://registry.gbif.org/installation/68845aab-a453-4816-b36d-a3ec8455deb0)
- Number of occurrences indexed for this dataset at the time of the issue: 6189
- Cause: GBIF ID problems exceed 50% threshold: 72% duplicates; 6258 total records; 4530 absent records
- Pipelines execution steps: [http://api.gbif.org/v1/pipelines/history/execution/3270717/step](http://api.gbif.org/v1/pipelines/history/execution/3270717/step)
<details>
<summary>Publisher email</summary>

Hello,

I am contacting you from the GBIF Secretariat about a dataset published by the [Biodiversidad asociada al Área de perforación exploratoria - VIM46](https://registry.gbif.org/dataset/1a017764-ffb6-4880-801f-27e209a1f7e0) : https://doi.org/10.15472/wzmpjt.
We noticed that the occurrenceIDs were changed. We have temporarily paused the ingestions of this dataset.

As you might already know, when an occurrence record has a new occurrenceID for a given dataset, our system considers it to be a new occurrence.
This means that it will be given a new gbifid and a new occurrence URL (like this one: https://www.gbif.org/occurrence/1252968762) and the old gbifid and URL will be deprecated.

In this case, this means that the occurrence URLs would be deprecated when ingesting the newest versions of these datasets.

We would like to check with you if those changes were intentional. Do you know if this is the case?
Please let us know, thanks! We are happy to resume the dataset ingestion.

Note that some users rely on those occurrence URLs and gbifids (like https://bionomia.net for example). In an attempt to improve
the stability of the occurrence URLs and gbifids, we have implemented a warning system to detect these type of changes in datasets (see this news item).
If the data publisher can provide us with a list of old and new occurrenceIDs per record, we can avoid the identifier and URL changes. Could that be an option?

Please let us know if you have any question. Thanks!

All the best,

</details>


You can skip/fix identifier validation using [the registry UI](https://registry.gbif.org/dataset/1a017764-ffb6-4880-801f-27e209a1f7e0/ingestion-history).

**Comment by EstebanMH-SiB** [comment]
Hi @ManonGros I made the change hoping it will work, it was just a change in a tilde, from Epífitas to Epifitas and from Hidrobiología to Hidrobiologia. I share the list of all original occurrenceIDs and it's mapping to the new ones to continue with the ingestion process.

[ChangeOccurrenceID_Vim46.txt](https://github.com/gbif/ingestion-management/files/12674015/ChangeOccurrenceID_Vim46.txt)

Thanks for your help!

**Comment by ManonGros** [comment]
Thanks Esteban! I migrated the IDs and resumed the dataset ingestion.
