### ISSUE TITLE
Identifiers validation failed for dataset CM Vertebrate Paleontology Collection

### ISSUE THREAD

**Issue by gbif-pipelines** [gbif/ingestion-management#822]
Identifier validation failed for the dataset [CM Vertebrate Paleontology Collection](https://registry.gbif.org/dataset/6720aee6-2aad-446d-bb97-ba009d1b5666):
- Crawler attempt: 290
- Publishing organization: [Carnegie Museums](https://registry.gbif.org/organization/c1da06f0-580e-11dc-8a9e-b8a03c50a862)
- Publishing country: UNITED_STATES
- Installation: [IPT - Hosted by VertNet](https://registry.gbif.org/installation/a957a663-2f17-415f-b1c8-5cf6398df8ed)
- Number of occurrences indexed for this dataset at the time of the issue: 79254
- Cause: GBIF ID problems exceed 50% threshold: 100% duplicates; 84309 total records; 84309 absent records
- Pipelines execution steps: [http://api.gbif.org/v1/pipelines/history/execution/3255800/step](http://api.gbif.org/v1/pipelines/history/execution/3255800/step)
<details>
<summary>Publisher email</summary>

Hello,

I am contacting you from the GBIF Secretariat about a dataset published by the [CM Vertebrate Paleontology Collection](https://registry.gbif.org/dataset/6720aee6-2aad-446d-bb97-ba009d1b5666) : https://doi.org/10.15468/hw4khc.
We noticed that the occurrenceIDs were changed. We have temporarily paused the ingestions of this dataset.

As you might already know, when an occurrence record has a new occurrenceID for a given dataset, our system considers it to be a new occurrence.
This means that it will be given a new gbifid and a new occurrence URL (like this one: https://www.gbif.org/occurrence/1252968762) and the old gbifid and URL will be deprecated.

In this case, this means that the occurrence URLs would be deprecated when ingesting the newest versions of these datasets.

We would like to check with you if those changes were intentional. Do you know if this is the case?
Please let us know, thanks! We are happy to resume the dataset ingestion.

Note that some users rely on those occurrence URLs and gbifids (like https://bionomia.net for example). In an attempt to improve
the stability of the occurrence URLs and gbifids, we have implemented a warning system to detect these type of changes in datasets (see this news item).
If the data publisher can provide us with a list of old and new occurrenceIDs per record, we can avoid the identifier and URL changes. Could that be an option?

Please let us know if you have any question. Thanks!

All the best,

</details>

You can skip/fix identifier validation using [the registry UI](https://registry.gbif.org/dataset/6720aee6-2aad-446d-bb97-ba009d1b5666/ingestion-history).

**Comment by dbloom** [comment]
@ktotsum FYI - still working through the ID lists with the folks at the CM. Close to resolution.
