### ISSUE TITLE
Identifiers validation failed for dataset eButterfly Surveys

### ISSUE THREAD

**Issue by gbif-pipelines** [gbif/ingestion-management#823]
Identifier validation failed for the dataset [eButterfly Surveys](https://registry.gbif.org/dataset/cf3bdc30-370c-48d3-8fff-b587a39d72d6):
- Crawler attempt: 699
- Publishing organization: [Vermont Center for Ecostudies](https://registry.gbif.org/organization/b6d09100-919d-4026-b35b-22be3dae7156)
- Publishing country: UNITED_STATES
- Installation: [IPT of the Vermont Atlas of Life (VAL)](https://registry.gbif.org/installation/5ae8b93d-03d9-48f1-8334-f1f251d13f1f)
- Number of occurrences indexed for this dataset at the time of the issue: 523009
- Cause: Dataset has no API records, but 0% of IDs aren't new
- Pipelines execution steps: [http://api.gbif.org/v1/pipelines/history/execution/3255817/step](http://api.gbif.org/v1/pipelines/history/execution/3255817/step)
<details>
<summary>Publisher email</summary>

Hello,

I am contacting you from the GBIF Secretariat about a dataset published by the [eButterfly Surveys](https://registry.gbif.org/dataset/cf3bdc30-370c-48d3-8fff-b587a39d72d6) : https://doi.org/10.15468/ykxm8x.
We noticed that the occurrenceIDs were changed. We have temporarily paused the ingestions of this dataset.

As you might already know, when an occurrence record has a new occurrenceID for a given dataset, our system considers it to be a new occurrence.
This means that it will be given a new gbifid and a new occurrence URL (like this one: https://www.gbif.org/occurrence/1252968762) and the old gbifid and URL will be deprecated.

In this case, this means that the occurrence URLs would be deprecated when ingesting the newest versions of these datasets.

We would like to check with you if those changes were intentional. Do you know if this is the case?
Please let us know, thanks! We are happy to resume the dataset ingestion.

Note that some users rely on those occurrence URLs and gbifids (like https://bionomia.net for example). In an attempt to improve
the stability of the occurrence URLs and gbifids, we have implemented a warning system to detect these type of changes in datasets (see this news item).
If the data publisher can provide us with a list of old and new occurrenceIDs per record, we can avoid the identifier and URL changes. Could that be an option?

Please let us know if you have any question. Thanks!

All the best,

</details>

You can skip/fix identifier validation using [the registry UI](https://registry.gbif.org/dataset/cf3bdc30-370c-48d3-8fff-b587a39d72d6/ingestion-history).

**Comment by gbif-pipelines** [comment]
Identifier validation still  failing for the dataset [eButterfly Surveys](https://registry.gbif.org/dataset/cf3bdc30-370c-48d3-8fff-b587a39d72d6):
- Crawler attempt: 702
- Publishing organization: [Vermont Center for Ecostudies](https://registry.gbif.org/organization/b6d09100-919d-4026-b35b-22be3dae7156)
- Publishing country: UNITED_STATES
- Installation: [IPT of the Vermont Atlas of Life (VAL)](https://registry.gbif.org/installation/5ae8b93d-03d9-48f1-8334-f1f251d13f1f)
- Number of occurrences indexed for this dataset at the time of the issue: 0
- Cause: Dataset has no API records, but 0% of IDs aren't new
- Pipelines execution steps: [http://api.gbif.org/v1/pipelines/history/execution/3255929/step](http://api.gbif.org/v1/pipelines/history/execution/3255929/step)
<details>
<summary>Publisher email</summary>

Hello,

I am contacting you from the GBIF Secretariat about a dataset published by the [eButterfly Surveys](https://registry.gbif.org/dataset/cf3bdc30-370c-48d3-8fff-b587a39d72d6) : https://doi.org/10.15468/ykxm8x.
We noticed that the occurrenceIDs were changed. We have temporarily paused the ingestions of this dataset.

As you might already know, when an occurrence record has a new occurrenceID for a given dataset, our system considers it to be a new occurrence.
This means that it will be given a new gbifid and a new occurrence URL (like this one: https://www.gbif.org/occurrence/1252968762) and the old gbifid and URL will be deprecated.

In this case, this means that the occurrence URLs would be deprecated when ingesting the newest versions of these datasets.

We would like to check with you if those changes were intentional. Do you know if this is the case?
Please let us know, thanks! We are happy to resume the dataset ingestion.

Note that some users rely on those occurrence URLs and gbifids (like https://bionomia.net for example). In an attempt to improve
the stability of the occurrence URLs and gbifids, we have implemented a warning system to detect these type of changes in datasets (see this news item).
If the data publisher can provide us with a list of old and new occurrenceIDs per record, we can avoid the identifier and URL changes. Could that be an option?

Please let us know if you have any question. Thanks!

All the best,

</details>


You can skip/fix identifier validation using [the registry UI](https://registry.gbif.org/dataset/cf3bdc30-370c-48d3-8fff-b587a39d72d6/ingestion-history).

**Comment by gbif-pipelines** [comment]
Identifier validation still  failing for the dataset [eButterfly Surveys](https://registry.gbif.org/dataset/cf3bdc30-370c-48d3-8fff-b587a39d72d6):
- Crawler attempt: 703
- Publishing organization: [Vermont Center for Ecostudies](https://registry.gbif.org/organization/b6d09100-919d-4026-b35b-22be3dae7156)
- Publishing country: UNITED_STATES
- Installation: [IPT of the Vermont Atlas of Life (VAL)](https://registry.gbif.org/installation/5ae8b93d-03d9-48f1-8334-f1f251d13f1f)
- Number of occurrences indexed for this dataset at the time of the issue: 0
- Cause: Dataset has no API records, but 0% of IDs aren't new
- Pipelines execution steps: [http://api.gbif.org/v1/pipelines/history/execution/3256287/step](http://api.gbif.org/v1/pipelines/history/execution/3256287/step)
<details>
<summary>Publisher email</summary>

Hello,

I am contacting you from the GBIF Secretariat about a dataset published by the [eButterfly Surveys](https://registry.gbif.org/dataset/cf3bdc30-370c-48d3-8fff-b587a39d72d6) : https://doi.org/10.15468/ykxm8x.
We noticed that the occurrenceIDs were changed. We have temporarily paused the ingestions of this dataset.

As you might already know, when an occurrence record has a new occurrenceID for a given dataset, our system considers it to be a new occurrence.
This means that it will be given a new gbifid and a new occurrence URL (like this one: https://www.gbif.org/occurrence/1252968762) and the old gbifid and URL will be deprecated.

In this case, this means that the occurrence URLs would be deprecated when ingesting the newest versions of these datasets.

We would like to check with you if those changes were intentional. Do you know if this is the case?
Please let us know, thanks! We are happy to resume the dataset ingestion.

Note that some users rely on those occurrence URLs and gbifids (like https://bionomia.net for example). In an attempt to improve
the stability of the occurrence URLs and gbifids, we have implemented a warning system to detect these type of changes in datasets (see this news item).
If the data publisher can provide us with a list of old and new occurrenceIDs per record, we can avoid the identifier and URL changes. Could that be an option?

Please let us know if you have any question. Thanks!

All the best,

</details>


You can skip/fix identifier validation using [the registry UI](https://registry.gbif.org/dataset/cf3bdc30-370c-48d3-8fff-b587a39d72d6/ingestion-history).

**Comment by gbif-pipelines** [comment]
Identifier validation still  failing for the dataset [eButterfly Surveys](https://registry.gbif.org/dataset/cf3bdc30-370c-48d3-8fff-b587a39d72d6):
- Crawler attempt: 704
- Publishing organization: [Vermont Center for Ecostudies](https://registry.gbif.org/organization/b6d09100-919d-4026-b35b-22be3dae7156)
- Publishing country: UNITED_STATES
- Installation: [IPT of the Vermont Atlas of Life (VAL)](https://registry.gbif.org/installation/5ae8b93d-03d9-48f1-8334-f1f251d13f1f)
- Number of occurrences indexed for this dataset at the time of the issue: 0
- Cause: Dataset has no API records, but 0% of IDs aren't new
- Pipelines execution steps: [http://api.gbif.org/v1/pipelines/history/execution/3256360/step](http://api.gbif.org/v1/pipelines/history/execution/3256360/step)
<details>
<summary>Publisher email</summary>

Hello,

I am contacting you from the GBIF Secretariat about a dataset published by the [eButterfly Surveys](https://registry.gbif.org/dataset/cf3bdc30-370c-48d3-8fff-b587a39d72d6) : https://doi.org/10.15468/ykxm8x.
We noticed that the occurrenceIDs were changed. We have temporarily paused the ingestions of this dataset.

As you might already know, when an occurrence record has a new occurrenceID for a given dataset, our system considers it to be a new occurrence.
This means that it will be given a new gbifid and a new occurrence URL (like this one: https://www.gbif.org/occurrence/1252968762) and the old gbifid and URL will be deprecated.

In this case, this means that the occurrence URLs would be deprecated when ingesting the newest versions of these datasets.

We would like to check with you if those changes were intentional. Do you know if this is the case?
Please let us know, thanks! We are happy to resume the dataset ingestion.

Note that some users rely on those occurrence URLs and gbifids (like https://bionomia.net for example). In an attempt to improve
the stability of the occurrence URLs and gbifids, we have implemented a warning system to detect these type of changes in datasets (see this news item).
If the data publisher can provide us with a list of old and new occurrenceIDs per record, we can avoid the identifier and URL changes. Could that be an option?

Please let us know if you have any question. Thanks!

All the best,

</details>


You can skip/fix identifier validation using [the registry UI](https://registry.gbif.org/dataset/cf3bdc30-370c-48d3-8fff-b587a39d72d6/ingestion-history).

**Comment by gbif-pipelines** [comment]
Identifier validation still  failing for the dataset [eButterfly Surveys](https://registry.gbif.org/dataset/cf3bdc30-370c-48d3-8fff-b587a39d72d6):
- Crawler attempt: 706
- Publishing organization: [Vermont Center for Ecostudies](https://registry.gbif.org/organization/b6d09100-919d-4026-b35b-22be3dae7156)
- Publishing country: UNITED_STATES
- Installation: [IPT of the Vermont Atlas of Life (VAL)](https://registry.gbif.org/installation/5ae8b93d-03d9-48f1-8334-f1f251d13f1f)
- Number of occurrences indexed for this dataset at the time of the issue: 0
- Cause: Dataset has no API records, but 0% of IDs aren't new
- Pipelines execution steps: [http://api.gbif.org/v1/pipelines/history/execution/3256439/step](http://api.gbif.org/v1/pipelines/history/execution/3256439/step)
<details>
<summary>Publisher email</summary>

Hello,

I am contacting you from the GBIF Secretariat about a dataset published by the [eButterfly Surveys](https://registry.gbif.org/dataset/cf3bdc30-370c-48d3-8fff-b587a39d72d6) : https://doi.org/10.15468/ykxm8x.
We noticed that the occurrenceIDs were changed. We have temporarily paused the ingestions of this dataset.

As you might already know, when an occurrence record has a new occurrenceID for a given dataset, our system considers it to be a new occurrence.
This means that it will be given a new gbifid and a new occurrence URL (like this one: https://www.gbif.org/occurrence/1252968762) and the old gbifid and URL will be deprecated.

In this case, this means that the occurrence URLs would be deprecated when ingesting the newest versions of these datasets.

We would like to check with you if those changes were intentional. Do you know if this is the case?
Please let us know, thanks! We are happy to resume the dataset ingestion.

Note that some users rely on those occurrence URLs and gbifids (like https://bionomia.net for example). In an attempt to improve
the stability of the occurrence URLs and gbifids, we have implemented a warning system to detect these type of changes in datasets (see this news item).
If the data publisher can provide us with a list of old and new occurrenceIDs per record, we can avoid the identifier and URL changes. Could that be an option?

Please let us know if you have any question. Thanks!

All the best,

</details>


You can skip/fix identifier validation using [the registry UI](https://registry.gbif.org/dataset/cf3bdc30-370c-48d3-8fff-b587a39d72d6/ingestion-history).

**Comment by gbif-pipelines** [comment]
Identifier validation still  failing for the dataset [eButterfly Surveys](https://registry.gbif.org/dataset/cf3bdc30-370c-48d3-8fff-b587a39d72d6):
- Crawler attempt: 707
- Publishing organization: [Vermont Center for Ecostudies](https://registry.gbif.org/organization/b6d09100-919d-4026-b35b-22be3dae7156)
- Publishing country: UNITED_STATES
- Installation: [IPT of the Vermont Atlas of Life (VAL)](https://registry.gbif.org/installation/5ae8b93d-03d9-48f1-8334-f1f251d13f1f)
- Number of occurrences indexed for this dataset at the time of the issue: 0
- Cause: Dataset has no API records, but 0% of IDs aren't new
- Pipelines execution steps: [http://api.gbif.org/v1/pipelines/history/execution/3256863/step](http://api.gbif.org/v1/pipelines/history/execution/3256863/step)
<details>
<summary>Publisher email</summary>

Hello,

I am contacting you from the GBIF Secretariat about a dataset published by the [eButterfly Surveys](https://registry.gbif.org/dataset/cf3bdc30-370c-48d3-8fff-b587a39d72d6) : https://doi.org/10.15468/ykxm8x.
We noticed that the occurrenceIDs were changed. We have temporarily paused the ingestions of this dataset.

As you might already know, when an occurrence record has a new occurrenceID for a given dataset, our system considers it to be a new occurrence.
This means that it will be given a new gbifid and a new occurrence URL (like this one: https://www.gbif.org/occurrence/1252968762) and the old gbifid and URL will be deprecated.

In this case, this means that the occurrence URLs would be deprecated when ingesting the newest versions of these datasets.

We would like to check with you if those changes were intentional. Do you know if this is the case?
Please let us know, thanks! We are happy to resume the dataset ingestion.

Note that some users rely on those occurrence URLs and gbifids (like https://bionomia.net for example). In an attempt to improve
the stability of the occurrence URLs and gbifids, we have implemented a warning system to detect these type of changes in datasets (see this news item).
If the data publisher can provide us with a list of old and new occurrenceIDs per record, we can avoid the identifier and URL changes. Could that be an option?

Please let us know if you have any question. Thanks!

All the best,

</details>


You can skip/fix identifier validation using [the registry UI](https://registry.gbif.org/dataset/cf3bdc30-370c-48d3-8fff-b587a39d72d6/ingestion-history).

**Comment by ktotsum** [comment]
The dataset was ingested and there was no change of occurrenceIDs. The publisher replaced the data with a snapshot from older version (Sept. 1, 2023), published on IPT and then republished the latest version. We are uncertain of the error happened on the 8th of September, but we paused the data ingestion for all datasets for maintenance on that day.
