### ISSUE TITLE
Identifiers validation failed for dataset Bivalvia collection of Shirshov Institute of Oceanology, Laboratory of Ocean Benthic Fauna

### ISSUE THREAD

**Issue by gbif-pipelines** [gbif/ingestion-management#824]
Identifier validation failed for the dataset [Bivalvia collection of Shirshov Institute of Oceanology, Laboratory of Ocean Benthic Fauna](https://registry.gbif.org/dataset/d0632e0e-ae35-4387-9ddd-14113d2c4374):
- Crawler attempt: 45
- Publishing organization: [Shirshov Institute of Oceanology, Russian Academy of Sciences](https://registry.gbif.org/organization/9abe4949-29aa-450e-b767-b2788f66e04d)
- Publishing country: RUSSIAN_FEDERATION
- Installation: [Shirshov Institute of Oceanology IPT](https://registry.gbif.org/installation/da87027f-12b5-442f-b132-0f6f25acfd53)
- Number of occurrences indexed for this dataset at the time of the issue: 278
- Cause: GBIF ID problems exceed 50% threshold: 100% duplicates; 1227 total records; 1227 absent records
- Pipelines execution steps: [http://api.gbif.org/v1/pipelines/history/execution/3257079/step](http://api.gbif.org/v1/pipelines/history/execution/3257079/step)
<details>
<summary>Publisher email</summary>

Hello,

I am contacting you from the GBIF Secretariat about a dataset published by the [Bivalvia collection of Shirshov Institute of Oceanology, Laboratory of Ocean Benthic Fauna](https://registry.gbif.org/dataset/d0632e0e-ae35-4387-9ddd-14113d2c4374) : https://doi.org/10.15468/g7we9s.
We noticed that the occurrenceIDs were changed. We have temporarily paused the ingestions of this dataset.

As you might already know, when an occurrence record has a new occurrenceID for a given dataset, our system considers it to be a new occurrence.
This means that it will be given a new gbifid and a new occurrence URL (like this one: https://www.gbif.org/occurrence/1252968762) and the old gbifid and URL will be deprecated.

In this case, this means that the occurrence URLs would be deprecated when ingesting the newest versions of these datasets.

We would like to check with you if those changes were intentional. Do you know if this is the case?
Please let us know, thanks! We are happy to resume the dataset ingestion.

Note that some users rely on those occurrence URLs and gbifids (like https://bionomia.net for example). In an attempt to improve
the stability of the occurrence URLs and gbifids, we have implemented a warning system to detect these type of changes in datasets (see this news item).
If the data publisher can provide us with a list of old and new occurrenceIDs per record, we can avoid the identifier and URL changes. Could that be an option?

Please let us know if you have any question. Thanks!

All the best,

</details>

You can skip/fix identifier validation using [the registry UI](https://registry.gbif.org/dataset/d0632e0e-ae35-4387-9ddd-14113d2c4374/ingestion-history).

**Comment by gbif-pipelines** [comment]
Identifier validation still  failing for the dataset [Bivalvia collection of Shirshov Institute of Oceanology, Laboratory of Ocean Benthic Fauna](https://registry.gbif.org/dataset/d0632e0e-ae35-4387-9ddd-14113d2c4374):
- Crawler attempt: 46
- Publishing organization: [Shirshov Institute of Oceanology, Russian Academy of Sciences](https://registry.gbif.org/organization/9abe4949-29aa-450e-b767-b2788f66e04d)
- Publishing country: RUSSIAN_FEDERATION
- Installation: [Shirshov Institute of Oceanology IPT](https://registry.gbif.org/installation/da87027f-12b5-442f-b132-0f6f25acfd53)
- Number of occurrences indexed for this dataset at the time of the issue: 278
- Cause: GBIF ID problems exceed 50% threshold: 100% duplicates; 1227 total records; 1227 absent records
- Pipelines execution steps: [http://api.gbif.org/v1/pipelines/history/execution/3257214/step](http://api.gbif.org/v1/pipelines/history/execution/3257214/step)
<details>
<summary>Publisher email</summary>

Hello,

I am contacting you from the GBIF Secretariat about a dataset published by the [Bivalvia collection of Shirshov Institute of Oceanology, Laboratory of Ocean Benthic Fauna](https://registry.gbif.org/dataset/d0632e0e-ae35-4387-9ddd-14113d2c4374) : https://doi.org/10.15468/g7we9s.
We noticed that the occurrenceIDs were changed. We have temporarily paused the ingestions of this dataset.

As you might already know, when an occurrence record has a new occurrenceID for a given dataset, our system considers it to be a new occurrence.
This means that it will be given a new gbifid and a new occurrence URL (like this one: https://www.gbif.org/occurrence/1252968762) and the old gbifid and URL will be deprecated.

In this case, this means that the occurrence URLs would be deprecated when ingesting the newest versions of these datasets.

We would like to check with you if those changes were intentional. Do you know if this is the case?
Please let us know, thanks! We are happy to resume the dataset ingestion.

Note that some users rely on those occurrence URLs and gbifids (like https://bionomia.net for example). In an attempt to improve
the stability of the occurrence URLs and gbifids, we have implemented a warning system to detect these type of changes in datasets (see this news item).
If the data publisher can provide us with a list of old and new occurrenceIDs per record, we can avoid the identifier and URL changes. Could that be an option?

Please let us know if you have any question. Thanks!

All the best,

</details>


You can skip/fix identifier validation using [the registry UI](https://registry.gbif.org/dataset/d0632e0e-ae35-4387-9ddd-14113d2c4374/ingestion-history).

**Comment by gbif-pipelines** [comment]
Identifier validation still  failing for the dataset [Bivalvia collection of Shirshov Institute of Oceanology, Laboratory of Ocean Benthic Fauna](https://registry.gbif.org/dataset/d0632e0e-ae35-4387-9ddd-14113d2c4374):
- Crawler attempt: 47
- Publishing organization: [Shirshov Institute of Oceanology, Russian Academy of Sciences](https://registry.gbif.org/organization/9abe4949-29aa-450e-b767-b2788f66e04d)
- Publishing country: RUSSIAN_FEDERATION
- Installation: [Shirshov Institute of Oceanology IPT](https://registry.gbif.org/installation/da87027f-12b5-442f-b132-0f6f25acfd53)
- Number of occurrences indexed for this dataset at the time of the issue: 278
- Cause: GBIF ID problems exceed 50% threshold: 100% duplicates; 1227 total records; 1227 absent records
- Pipelines execution steps: [http://api.gbif.org/v1/pipelines/history/execution/3257803/step](http://api.gbif.org/v1/pipelines/history/execution/3257803/step)
<details>
<summary>Publisher email</summary>

Hello,

I am contacting you from the GBIF Secretariat about a dataset published by the [Bivalvia collection of Shirshov Institute of Oceanology, Laboratory of Ocean Benthic Fauna](https://registry.gbif.org/dataset/d0632e0e-ae35-4387-9ddd-14113d2c4374) : https://doi.org/10.15468/g7we9s.
We noticed that the occurrenceIDs were changed. We have temporarily paused the ingestions of this dataset.

As you might already know, when an occurrence record has a new occurrenceID for a given dataset, our system considers it to be a new occurrence.
This means that it will be given a new gbifid and a new occurrence URL (like this one: https://www.gbif.org/occurrence/1252968762) and the old gbifid and URL will be deprecated.

In this case, this means that the occurrence URLs would be deprecated when ingesting the newest versions of these datasets.

We would like to check with you if those changes were intentional. Do you know if this is the case?
Please let us know, thanks! We are happy to resume the dataset ingestion.

Note that some users rely on those occurrence URLs and gbifids (like https://bionomia.net for example). In an attempt to improve
the stability of the occurrence URLs and gbifids, we have implemented a warning system to detect these type of changes in datasets (see this news item).
If the data publisher can provide us with a list of old and new occurrenceIDs per record, we can avoid the identifier and URL changes. Could that be an option?

Please let us know if you have any question. Thanks!

All the best,

</details>


You can skip/fix identifier validation using [the registry UI](https://registry.gbif.org/dataset/d0632e0e-ae35-4387-9ddd-14113d2c4374/ingestion-history).

**Comment by ManonGros** [comment]
The publisher replied that the changes were intentional and I allowed the failed identifiers.
