### ISSUE TITLE
Identifiers validation failed for dataset V. N. Karazin Kharkiv National University herbarium (CWU), Department of Botany and Plant Ecology

### ISSUE THREAD

**Issue by gbif-pipelines** [gbif/ingestion-management#825]
Identifier validation failed for the dataset [V. N. Karazin Kharkiv National University herbarium (CWU), Department of Botany and Plant Ecology](https://registry.gbif.org/dataset/f0642098-7d83-403a-8ea3-8331f6c5b95d):
- Crawler attempt: 78
- Publishing organization: [V. N. Karazin Kharkiv National University](https://registry.gbif.org/organization/b835f634-e4ed-4d54-bbcf-e0e6344a8c88)
- Publishing country: UKRAINE
- Installation: [IPT Installation PlutoF Biodiversity Platform](https://registry.gbif.org/installation/5f02b486-8869-418b-88ba-1819001f1da7)
- Number of occurrences indexed for this dataset at the time of the issue: 138
- Cause: GBIF ID problems exceed 50% threshold: 99% duplicates; 894 total records; 886 absent records
- Pipelines execution steps: [http://api.gbif.org/v1/pipelines/history/execution/3257602/step](http://api.gbif.org/v1/pipelines/history/execution/3257602/step)
<details>
<summary>Publisher email</summary>

Hello,

I am contacting you from the GBIF Secretariat about a dataset published by the [V. N. Karazin Kharkiv National University herbarium (CWU), Department of Botany and Plant Ecology](https://registry.gbif.org/dataset/f0642098-7d83-403a-8ea3-8331f6c5b95d) : https://doi.org/10.15468/dgz2fh.
We noticed that the occurrenceIDs were changed. We have temporarily paused the ingestions of this dataset.

As you might already know, when an occurrence record has a new occurrenceID for a given dataset, our system considers it to be a new occurrence.
This means that it will be given a new gbifid and a new occurrence URL (like this one: https://www.gbif.org/occurrence/1252968762) and the old gbifid and URL will be deprecated.

In this case, this means that the occurrence URLs would be deprecated when ingesting the newest versions of these datasets.

We would like to check with you if those changes were intentional. Do you know if this is the case?
Please let us know, thanks! We are happy to resume the dataset ingestion.

Note that some users rely on those occurrence URLs and gbifids (like https://bionomia.net for example). In an attempt to improve
the stability of the occurrence URLs and gbifids, we have implemented a warning system to detect these type of changes in datasets (see this news item).
If the data publisher can provide us with a list of old and new occurrenceIDs per record, we can avoid the identifier and URL changes. Could that be an option?

Please let us know if you have any question. Thanks!

All the best,

</details>

You can skip/fix identifier validation using [the registry UI](https://registry.gbif.org/dataset/f0642098-7d83-403a-8ea3-8331f6c5b95d/ingestion-history).

**Comment by ManonGros** [comment]
The publisher said the occurrenceIDs are generated automatically by PlutoF and they cannot choose them. They asked to resume the dataset ingestion. So I allowed the failed identifiers.
