### ISSUE TITLE
Identifiers validation failed for dataset Surveys of long spined sea urchin (Centrostephanus rodgersii) and barrens habitat, Kent Group, Tasmania 2000

### ISSUE THREAD

**Issue by gbif-pipelines** [gbif/ingestion-management#826]
Identifier validation failed for the dataset [Surveys of long spined sea urchin (Centrostephanus rodgersii) and barrens habitat, Kent Group, Tasmania 2000](https://registry.gbif.org/dataset/82acb6ea-dacc-4e3b-abf5-5facf6cab77c):
- Crawler attempt: 1
- Publishing organization: [CSIRO National Collections and Marine Infrastructure (NCMI) Information and Data Centre (IDC)](https://registry.gbif.org/organization/5fa89f68-9af0-4a0d-8998-ea39695c1db9)
- Publishing country: AUSTRALIA
- Installation: [CSIRO NCMI IDC / OBIS Australia](https://registry.gbif.org/installation/729a7375-b120-4e4f-bb81-ad9badcca81b)
- Number of occurrences indexed for this dataset at the time of the issue: 0
- Cause: Dataset has no API records, but 51% of IDs aren't new
- Pipelines execution steps: [http://api.gbif.org/v1/pipelines/history/execution/3268932/step](http://api.gbif.org/v1/pipelines/history/execution/3268932/step)
<details>
<summary>Publisher email</summary>

Hello,

I am contacting you from the GBIF Secretariat about a dataset published by the [Surveys of long spined sea urchin (Centrostephanus rodgersii) and barrens habitat, Kent Group, Tasmania 2000](https://registry.gbif.org/dataset/82acb6ea-dacc-4e3b-abf5-5facf6cab77c) : https://doi.org/10.15468/yxqda7.
We noticed that the occurrenceIDs were changed. We have temporarily paused the ingestions of this dataset.

As you might already know, when an occurrence record has a new occurrenceID for a given dataset, our system considers it to be a new occurrence.
This means that it will be given a new gbifid and a new occurrence URL (like this one: https://www.gbif.org/occurrence/1252968762) and the old gbifid and URL will be deprecated.

In this case, this means that the occurrence URLs would be deprecated when ingesting the newest versions of these datasets.

We would like to check with you if those changes were intentional. Do you know if this is the case?
Please let us know, thanks! We are happy to resume the dataset ingestion.

Note that some users rely on those occurrence URLs and gbifids (like https://bionomia.net for example). In an attempt to improve
the stability of the occurrence URLs and gbifids, we have implemented a warning system to detect these type of changes in datasets (see this news item).
If the data publisher can provide us with a list of old and new occurrenceIDs per record, we can avoid the identifier and URL changes. Could that be an option?

Please let us know if you have any question. Thanks!

All the best,

</details>

You can skip/fix identifier validation using [the registry UI](https://registry.gbif.org/dataset/82acb6ea-dacc-4e3b-abf5-5facf6cab77c/ingestion-history).

**Comment by gbif-pipelines** [comment]
Identifier validation still  failing for the dataset [Surveys of long spined sea urchin (Centrostephanus rodgersii) and barrens habitat, Kent Group, Tasmania 2000](https://registry.gbif.org/dataset/82acb6ea-dacc-4e3b-abf5-5facf6cab77c):
- Crawler attempt: 1
- Publishing organization: [CSIRO National Collections and Marine Infrastructure (NCMI) Information and Data Centre (IDC)](https://registry.gbif.org/organization/5fa89f68-9af0-4a0d-8998-ea39695c1db9)
- Publishing country: AUSTRALIA
- Installation: [CSIRO NCMI IDC / OBIS Australia](https://registry.gbif.org/installation/729a7375-b120-4e4f-bb81-ad9badcca81b)
- Number of occurrences indexed for this dataset at the time of the issue: 0
- Cause: Dataset has no API records, but 51% of IDs aren't new
- Pipelines execution steps: [http://api.gbif.org/v1/pipelines/history/execution/3307652/step](http://api.gbif.org/v1/pipelines/history/execution/3307652/step)
<details>
<summary>Publisher email</summary>

Hello,

I am contacting you from the GBIF Secretariat about a dataset published by the [Surveys of long spined sea urchin (Centrostephanus rodgersii) and barrens habitat, Kent Group, Tasmania 2000](https://registry.gbif.org/dataset/82acb6ea-dacc-4e3b-abf5-5facf6cab77c) : https://doi.org/10.15468/yxqda7.
We noticed that the occurrenceIDs were changed. We have temporarily paused the ingestions of this dataset.

As you might already know, when an occurrence record has a new occurrenceID for a given dataset, our system considers it to be a new occurrence.
This means that it will be given a new gbifid and a new occurrence URL (like this one: https://www.gbif.org/occurrence/1252968762) and the old gbifid and URL will be deprecated.

In this case, this means that the occurrence URLs would be deprecated when ingesting the newest versions of these datasets.

We would like to check with you if those changes were intentional. Do you know if this is the case?
Please let us know, thanks! We are happy to resume the dataset ingestion.

Note that some users rely on those occurrence URLs and gbifids (like https://bionomia.net for example). In an attempt to improve
the stability of the occurrence URLs and gbifids, we have implemented a warning system to detect these type of changes in datasets (see this news item).
If the data publisher can provide us with a list of old and new occurrenceIDs per record, we can avoid the identifier and URL changes. Could that be an option?

Please let us know if you have any question. Thanks!

All the best,

</details>


You can skip/fix identifier validation using [the registry UI](https://registry.gbif.org/dataset/82acb6ea-dacc-4e3b-abf5-5facf6cab77c/ingestion-history).

**Comment by gbif-pipelines** [comment]
Identifier validation still  failing for the dataset [Surveys of long spined sea urchin (Centrostephanus rodgersii) and barrens habitat, Kent Group, Tasmania 2000](https://registry.gbif.org/dataset/82acb6ea-dacc-4e3b-abf5-5facf6cab77c):
- Crawler attempt: 14
- Publishing organization: [CSIRO National Collections and Marine Infrastructure (NCMI) Information and Data Centre (IDC)](https://registry.gbif.org/organization/5fa89f68-9af0-4a0d-8998-ea39695c1db9)
- Publishing country: AUSTRALIA
- Installation: [CSIRO NCMI IDC / OBIS Australia](https://registry.gbif.org/installation/729a7375-b120-4e4f-bb81-ad9badcca81b)
- Number of occurrences indexed for this dataset at the time of the issue: 0
- Cause: Dataset has no API records, but 51% of IDs aren't new
- Pipelines execution steps: [http://api.gbif.org/v1/pipelines/history/execution/3309228/step](http://api.gbif.org/v1/pipelines/history/execution/3309228/step)
<details>
<summary>Publisher email</summary>

Hello,

I am contacting you from the GBIF Secretariat about a dataset published by the [Surveys of long spined sea urchin (Centrostephanus rodgersii) and barrens habitat, Kent Group, Tasmania 2000](https://registry.gbif.org/dataset/82acb6ea-dacc-4e3b-abf5-5facf6cab77c) : https://doi.org/10.15468/yxqda7.
We noticed that the occurrenceIDs were changed. We have temporarily paused the ingestions of this dataset.

As you might already know, when an occurrence record has a new occurrenceID for a given dataset, our system considers it to be a new occurrence.
This means that it will be given a new gbifid and a new occurrence URL (like this one: https://www.gbif.org/occurrence/1252968762) and the old gbifid and URL will be deprecated.

In this case, this means that the occurrence URLs would be deprecated when ingesting the newest versions of these datasets.

We would like to check with you if those changes were intentional. Do you know if this is the case?
Please let us know, thanks! We are happy to resume the dataset ingestion.

Note that some users rely on those occurrence URLs and gbifids (like https://bionomia.net for example). In an attempt to improve
the stability of the occurrence URLs and gbifids, we have implemented a warning system to detect these type of changes in datasets (see this news item).
If the data publisher can provide us with a list of old and new occurrenceIDs per record, we can avoid the identifier and URL changes. Could that be an option?

Please let us know if you have any question. Thanks!

All the best,

</details>


You can skip/fix identifier validation using [the registry UI](https://registry.gbif.org/dataset/82acb6ea-dacc-4e3b-abf5-5facf6cab77c/ingestion-history).

**Comment by ktotsum** [comment]
This was a strange case as no change of occurrenceIDs and the dataset was last published in 2022. We allowed change of identifiers and resumed the ingestion.
