### ISSUE TITLE
Identifiers validation failed for dataset Epibenthos and demersal fish monitoring in function of dredge disposal monitoring in the Belgian part of the North Sea

### ISSUE THREAD

**Issue by gbif-pipelines** [gbif/ingestion-management#831]
Identifier validation failed for the dataset [Epibenthos and demersal fish monitoring in function of dredge disposal monitoring in the Belgian part of the North Sea](https://registry.gbif.org/dataset/e5306688-5202-45b9-b858-e4683f3ccfab):
- Crawler attempt: 318
- Publishing organization: [Flanders Research Institute for Agriculture, Fisheries and Food (ILVO)](https://registry.gbif.org/organization/ac07bb5e-8a5c-493f-b183-9d7ad8d54cff)
- Publishing country: BELGIUM
- Installation: [European Ocean Biodiversity Information System (EurOBIS)](https://registry.gbif.org/installation/f9df6cff-21d4-4d4b-8da4-eda454f5a086)
- Number of occurrences indexed for this dataset at the time of the issue: 6830
- Cause: GBIF ID problems exceed 50% threshold: 100% duplicates; 11229 total records; 11229 absent records
- Pipelines execution steps: [http://api.gbif.org/v1/pipelines/history/execution/3309869/step](http://api.gbif.org/v1/pipelines/history/execution/3309869/step)
<details>
<summary>Publisher email</summary>

Hello,

I am contacting you from the GBIF Secretariat about a dataset published by the [Epibenthos and demersal fish monitoring in function of dredge disposal monitoring in the Belgian part of the North Sea](https://registry.gbif.org/dataset/e5306688-5202-45b9-b858-e4683f3ccfab) : https://doi.org/10.14284/198.
We noticed that the occurrenceIDs were changed. We have temporarily paused the ingestions of this dataset.

As you might already know, when an occurrence record has a new occurrenceID for a given dataset, our system considers it to be a new occurrence.
This means that it will be given a new gbifid and a new occurrence URL (like this one: https://www.gbif.org/occurrence/1252968762) and the old gbifid and URL will be deprecated.

In this case, this means that the occurrence URLs would be deprecated when ingesting the newest versions of these datasets.

We would like to check with you if those changes were intentional. Do you know if this is the case?
Please let us know, thanks! We are happy to resume the dataset ingestion.

Note that some users rely on those occurrence URLs and gbifids (like https://bionomia.net for example). In an attempt to improve
the stability of the occurrence URLs and gbifids, we have implemented a warning system to detect these type of changes in datasets (see this news item).
If the data publisher can provide us with a list of old and new occurrenceIDs per record, we can avoid the identifier and URL changes. Could that be an option?

Please let us know if you have any question. Thanks!

All the best,

</details>

You can skip/fix identifier validation using [the registry UI](https://registry.gbif.org/dataset/e5306688-5202-45b9-b858-e4683f3ccfab/ingestion-history).

**Comment by jhnwllr** [comment]
Id checkes skipped because OBIS.
