### ISSUE TITLE
Identifiers validation failed for dataset UPCB - Herbário do Departamento de Botânica

### ISSUE THREAD

**Issue by gbif-pipelines** [gbif/ingestion-management#843]
Identifier validation failed for the dataset [UPCB - Herbário do Departamento de Botânica](https://registry.gbif.org/dataset/a51fa32f-831d-49d6-8b8a-c7b52ae65b3b):
- Crawler attempt: 383
- Publishing organization: [Universidade Federal do Paraná](https://registry.gbif.org/organization/f6e2efc9-42a3-47ea-99c6-3eda8d653cc9)
- Publishing country: BRAZIL
- Installation: [speciesLink Network / INCT-HVFF IPT](https://registry.gbif.org/installation/b38ff2b7-c8af-454e-b5af-ee760f0d5bca)
- Number of occurrences indexed for this dataset at the time of the issue: 102624
- Cause: GBIF ID problems exceed 5% threshold: 86% duplicates; 102714 total records; 88271 absent records
- Pipelines execution steps: [http://api.gbif.org/v1/pipelines/history/execution/3321198/step](http://api.gbif.org/v1/pipelines/history/execution/3321198/step)

```
New IDs sample:

BRA:FURB:UPCB:48079
BRA:FURB:UPCB:87643
BRA:FURB:UPCB:1683
BRA:FURB:UPCB:73026
BRA:FURB:UPCB:48302
BRA:FURB:UPCB:73027
BRA:FURB:UPCB:48301
BRA:FURB:UPCB:87640
BRA:FURB:UPCB:1697
BRA:FURB:UPCB:87641
```

```
Old IDs sample:

BRA:UFPR:UPCB:103886
BRA:UFPR:UPCB:104894
BRA:UFPR:UPCB:105207
BRA:UFPR:UPCB:105208
BRA:UFPR:UPCB:105209
BRA:UFPR:UPCB:105210
BRA:UFPR:UPCB:105211
BRA:UFPR:UPCB:105212
BRA:UFPR:UPCB:105213
BRA:UFPR:UPCB:105214
```

<details>
<summary>Publisher email</summary>

Hello,

I am contacting you from the GBIF Secretariat about a dataset published by the [UPCB - Herbário do Departamento de Botânica](https://registry.gbif.org/dataset/a51fa32f-831d-49d6-8b8a-c7b52ae65b3b) : https://doi.org/10.15468/udpvi1.
We noticed that the occurrenceIDs were changed. We have temporarily paused the ingestions of this dataset.

As you might already know, when an occurrence record has a new occurrenceID for a given dataset, our system considers it to be a new occurrence.
This means that it will be given a new gbifid and a new occurrence URL (like this one: https://www.gbif.org/occurrence/1252968762) and the old gbifid and URL will be deprecated.

In this case, this means that the occurrence URLs would be deprecated when ingesting the newest versions of these datasets.

We would like to check with you if those changes were intentional. Do you know if this is the case?
Please let us know, thanks! We are happy to resume the dataset ingestion.

Note that some users rely on those occurrence URLs and gbifids (like https://bionomia.net for example). In an attempt to improve
the stability of the occurrence URLs and gbifids, we have implemented a warning system to detect these type of changes in datasets (see this news item).
If the data publisher can provide us with a list of old and new occurrenceIDs per record, we can avoid the identifier and URL changes. Could that be an option?

Please let us know if you have any question. Thanks!

All the best,

</details>

You can skip/fix identifier validation using [the registry UI](https://registry.gbif.org/dataset/a51fa32f-831d-49d6-8b8a-c7b52ae65b3b/ingestion-history).

**Comment by gbif-pipelines** [comment]
Identifier validation still  failing for the dataset [UPCB - Herbário do Departamento de Botânica](https://registry.gbif.org/dataset/a51fa32f-831d-49d6-8b8a-c7b52ae65b3b):
- Crawler attempt: 384
- Publishing organization: [Universidade Federal do Paraná](https://registry.gbif.org/organization/f6e2efc9-42a3-47ea-99c6-3eda8d653cc9)
- Publishing country: BRAZIL
- Installation: [speciesLink Network / INCT-HVFF IPT](https://registry.gbif.org/installation/b38ff2b7-c8af-454e-b5af-ee760f0d5bca)
- Number of occurrences indexed for this dataset at the time of the issue: 102624
- Cause: GBIF ID problems exceed 50% threshold: 86% duplicates; 102714 total records; 88271 absent records
- Pipelines execution steps: [http://api.gbif.org/v1/pipelines/history/execution/3331141/step](http://api.gbif.org/v1/pipelines/history/execution/3331141/step)

```
New IDs sample:

BRA:FURB:UPCB:48079
BRA:FURB:UPCB:87643
BRA:FURB:UPCB:1683
BRA:FURB:UPCB:73026
BRA:FURB:UPCB:48302
BRA:FURB:UPCB:73027
BRA:FURB:UPCB:48301
BRA:FURB:UPCB:87640
BRA:FURB:UPCB:1697
BRA:FURB:UPCB:87641
```


```
Old IDs sample:

BRA:UFPR:UPCB:103886
BRA:UFPR:UPCB:104894
BRA:UFPR:UPCB:105207
BRA:UFPR:UPCB:105208
BRA:UFPR:UPCB:105209
BRA:UFPR:UPCB:105210
BRA:UFPR:UPCB:105211
BRA:UFPR:UPCB:105212
BRA:UFPR:UPCB:105213
BRA:UFPR:UPCB:105214
```

<details>
<summary>Publisher email</summary>

Hello,

I am contacting you from the GBIF Secretariat about a dataset published by the [UPCB - Herbário do Departamento de Botânica](https://registry.gbif.org/dataset/a51fa32f-831d-49d6-8b8a-c7b52ae65b3b) : https://doi.org/10.15468/udpvi1.
We noticed that the occurrenceIDs were changed. We have temporarily paused the ingestions of this dataset.

As you might already know, when an occurrence record has a new occurrenceID for a given dataset, our system considers it to be a new occurrence.
This means that it will be given a new gbifid and a new occurrence URL (like this one: https://www.gbif.org/occurrence/1252968762) and the old gbifid and URL will be deprecated.

In this case, this means that the occurrence URLs would be deprecated when ingesting the newest versions of these datasets.

We would like to check with you if those changes were intentional. Do you know if this is the case?
Please let us know, thanks! We are happy to resume the dataset ingestion.

Note that some users rely on those occurrence URLs and gbifids (like https://bionomia.net for example). In an attempt to improve
the stability of the occurrence URLs and gbifids, we have implemented a warning system to detect these type of changes in datasets (see this news item).
If the data publisher can provide us with a list of old and new occurrenceIDs per record, we can avoid the identifier and URL changes. Could that be an option?

Please let us know if you have any question. Thanks!

All the best,

</details>


You can skip/fix identifier validation using [the registry UI](https://registry.gbif.org/dataset/a51fa32f-831d-49d6-8b8a-c7b52ae65b3b/ingestion-history).

**Comment by gbif-pipelines** [comment]
Identifier validation still  failing for the dataset [UPCB - Herbário do Departamento de Botânica](https://registry.gbif.org/dataset/a51fa32f-831d-49d6-8b8a-c7b52ae65b3b):
- Crawler attempt: 385
- Publishing organization: [Universidade Federal do Paraná](https://registry.gbif.org/organization/f6e2efc9-42a3-47ea-99c6-3eda8d653cc9)
- Publishing country: BRAZIL
- Installation: [speciesLink Network / INCT-HVFF IPT](https://registry.gbif.org/installation/b38ff2b7-c8af-454e-b5af-ee760f0d5bca)
- Number of occurrences indexed for this dataset at the time of the issue: 102624
- Cause: GBIF ID problems exceed 50% threshold: 86% duplicates; 102714 total records; 88271 absent records
- Pipelines execution steps: [http://api.gbif.org/v1/pipelines/history/execution/3343222/step](http://api.gbif.org/v1/pipelines/history/execution/3343222/step)

```
New IDs sample:

BRA:FURB:UPCB:48079
BRA:FURB:UPCB:87643
BRA:FURB:UPCB:1683
BRA:FURB:UPCB:73026
BRA:FURB:UPCB:48302
BRA:FURB:UPCB:73027
BRA:FURB:UPCB:48301
BRA:FURB:UPCB:87640
BRA:FURB:UPCB:1697
BRA:FURB:UPCB:87641
```


```
Old IDs sample:

BRA:UFPR:UPCB:103886
BRA:UFPR:UPCB:104894
BRA:UFPR:UPCB:105207
BRA:UFPR:UPCB:105208
BRA:UFPR:UPCB:105209
BRA:UFPR:UPCB:105210
BRA:UFPR:UPCB:105211
BRA:UFPR:UPCB:105212
BRA:UFPR:UPCB:105213
BRA:UFPR:UPCB:105214
```

<details>
<summary>Publisher email</summary>

Hello,

I am contacting you from the GBIF Secretariat about a dataset published by the [UPCB - Herbário do Departamento de Botânica](https://registry.gbif.org/dataset/a51fa32f-831d-49d6-8b8a-c7b52ae65b3b) : https://doi.org/10.15468/udpvi1.
We noticed that the occurrenceIDs were changed. We have temporarily paused the ingestions of this dataset.

As you might already know, when an occurrence record has a new occurrenceID for a given dataset, our system considers it to be a new occurrence.
This means that it will be given a new gbifid and a new occurrence URL (like this one: https://www.gbif.org/occurrence/1252968762) and the old gbifid and URL will be deprecated.

In this case, this means that the occurrence URLs would be deprecated when ingesting the newest versions of these datasets.

We would like to check with you if those changes were intentional. Do you know if this is the case?
Please let us know, thanks! We are happy to resume the dataset ingestion.

Note that some users rely on those occurrence URLs and gbifids (like https://bionomia.net for example). In an attempt to improve
the stability of the occurrence URLs and gbifids, we have implemented a warning system to detect these type of changes in datasets (see this news item).
If the data publisher can provide us with a list of old and new occurrenceIDs per record, we can avoid the identifier and URL changes. Could that be an option?

Please let us know if you have any question. Thanks!

All the best,

</details>


You can skip/fix identifier validation using [the registry UI](https://registry.gbif.org/dataset/a51fa32f-831d-49d6-8b8a-c7b52ae65b3b/ingestion-history).

**Comment by gbif-pipelines** [comment]
Identifier validation still  failing for the dataset [UPCB - Herbário do Departamento de Botânica](https://registry.gbif.org/dataset/a51fa32f-831d-49d6-8b8a-c7b52ae65b3b):
- Crawler attempt: 386
- Publishing organization: [Universidade Federal do Paraná](https://registry.gbif.org/organization/f6e2efc9-42a3-47ea-99c6-3eda8d653cc9)
- Publishing country: BRAZIL
- Installation: [speciesLink Network / INCT-HVFF IPT](https://registry.gbif.org/installation/b38ff2b7-c8af-454e-b5af-ee760f0d5bca)
- Number of occurrences indexed for this dataset at the time of the issue: 102624
- Cause: GBIF ID problems exceed 50% threshold: 86% duplicates; 102714 total records; 88271 absent records
- Pipelines execution steps: [http://api.gbif.org/v1/pipelines/history/execution/3355489/step](http://api.gbif.org/v1/pipelines/history/execution/3355489/step)

```
New IDs sample:

BRA:FURB:UPCB:48079
BRA:FURB:UPCB:87643
BRA:FURB:UPCB:1683
BRA:FURB:UPCB:73026
BRA:FURB:UPCB:48302
BRA:FURB:UPCB:73027
BRA:FURB:UPCB:48301
BRA:FURB:UPCB:87640
BRA:FURB:UPCB:1697
BRA:FURB:UPCB:87641
```


```
Old IDs sample:

BRA:UFPR:UPCB:103886
BRA:UFPR:UPCB:104894
BRA:UFPR:UPCB:105207
BRA:UFPR:UPCB:105208
BRA:UFPR:UPCB:105209
BRA:UFPR:UPCB:105210
BRA:UFPR:UPCB:105211
BRA:UFPR:UPCB:105212
BRA:UFPR:UPCB:105213
BRA:UFPR:UPCB:105214
```

<details>
<summary>Publisher email</summary>

Hello,

I am contacting you from the GBIF Secretariat about a dataset published by the [UPCB - Herbário do Departamento de Botânica](https://registry.gbif.org/dataset/a51fa32f-831d-49d6-8b8a-c7b52ae65b3b) : https://doi.org/10.15468/udpvi1.
We noticed that the occurrenceIDs were changed. We have temporarily paused the ingestions of this dataset.

As you might already know, when an occurrence record has a new occurrenceID for a given dataset, our system considers it to be a new occurrence.
This means that it will be given a new gbifid and a new occurrence URL (like this one: https://www.gbif.org/occurrence/1252968762) and the old gbifid and URL will be deprecated.

In this case, this means that the occurrence URLs would be deprecated when ingesting the newest versions of these datasets.

We would like to check with you if those changes were intentional. Do you know if this is the case?
Please let us know, thanks! We are happy to resume the dataset ingestion.

Note that some users rely on those occurrence URLs and gbifids (like https://bionomia.net for example). In an attempt to improve
the stability of the occurrence URLs and gbifids, we have implemented a warning system to detect these type of changes in datasets (see this news item).
If the data publisher can provide us with a list of old and new occurrenceIDs per record, we can avoid the identifier and URL changes. Could that be an option?

Please let us know if you have any question. Thanks!

All the best,

</details>


You can skip/fix identifier validation using [the registry UI](https://registry.gbif.org/dataset/a51fa32f-831d-49d6-8b8a-c7b52ae65b3b/ingestion-history).

**Comment by gbif-pipelines** [comment]
Identifier validation still  failing for the dataset [UPCB - Herbário do Departamento de Botânica](https://registry.gbif.org/dataset/a51fa32f-831d-49d6-8b8a-c7b52ae65b3b):
- Crawler attempt: 387
- Publishing organization: [Universidade Federal do Paraná](https://registry.gbif.org/organization/f6e2efc9-42a3-47ea-99c6-3eda8d653cc9)
- Publishing country: BRAZIL
- Installation: [speciesLink Network / INCT-HVFF IPT](https://registry.gbif.org/installation/b38ff2b7-c8af-454e-b5af-ee760f0d5bca)
- Number of occurrences indexed for this dataset at the time of the issue: 102624
- Cause: GBIF ID problems exceed 50% threshold: 86% duplicates; 102714 total records; 88271 absent records
- Pipelines execution steps: [http://api.gbif.org/v1/pipelines/history/execution/3364939/step](http://api.gbif.org/v1/pipelines/history/execution/3364939/step)

```
New IDs sample:

BRA:FURB:UPCB:48079
BRA:FURB:UPCB:87643
BRA:FURB:UPCB:1683
BRA:FURB:UPCB:73026
BRA:FURB:UPCB:48302
BRA:FURB:UPCB:73027
BRA:FURB:UPCB:48301
BRA:FURB:UPCB:87640
BRA:FURB:UPCB:1697
BRA:FURB:UPCB:87641
```


```
Old IDs sample:

BRA:UFPR:UPCB:103886
BRA:UFPR:UPCB:104894
BRA:UFPR:UPCB:105207
BRA:UFPR:UPCB:105208
BRA:UFPR:UPCB:105209
BRA:UFPR:UPCB:105210
BRA:UFPR:UPCB:105211
BRA:UFPR:UPCB:105212
BRA:UFPR:UPCB:105213
BRA:UFPR:UPCB:105214
```

<details>
<summary>Publisher email</summary>

Hello,

I am contacting you from the GBIF Secretariat about a dataset published by the [UPCB - Herbário do Departamento de Botânica](https://registry.gbif.org/dataset/a51fa32f-831d-49d6-8b8a-c7b52ae65b3b) : https://doi.org/10.15468/udpvi1.
We noticed that the occurrenceIDs were changed. We have temporarily paused the ingestions of this dataset.

As you might already know, when an occurrence record has a new occurrenceID for a given dataset, our system considers it to be a new occurrence.
This means that it will be given a new gbifid and a new occurrence URL (like this one: https://www.gbif.org/occurrence/1252968762) and the old gbifid and URL will be deprecated.

In this case, this means that the occurrence URLs would be deprecated when ingesting the newest versions of these datasets.

We would like to check with you if those changes were intentional. Do you know if this is the case?
Please let us know, thanks! We are happy to resume the dataset ingestion.

Note that some users rely on those occurrence URLs and gbifids (like https://bionomia.net for example). In an attempt to improve
the stability of the occurrence URLs and gbifids, we have implemented a warning system to detect these type of changes in datasets (see this news item).
If the data publisher can provide us with a list of old and new occurrenceIDs per record, we can avoid the identifier and URL changes. Could that be an option?

Please let us know if you have any question. Thanks!

All the best,

</details>


You can skip/fix identifier validation using [the registry UI](https://registry.gbif.org/dataset/a51fa32f-831d-49d6-8b8a-c7b52ae65b3b/ingestion-history).

**Comment by gbif-pipelines** [comment]
Identifier validation still  failing for the dataset [UPCB - Herbário do Departamento de Botânica](https://registry.gbif.org/dataset/a51fa32f-831d-49d6-8b8a-c7b52ae65b3b):
- Crawler attempt: 388
- Publishing organization: [Universidade Federal do Paraná](https://registry.gbif.org/organization/f6e2efc9-42a3-47ea-99c6-3eda8d653cc9)
- Publishing country: BRAZIL
- Installation: [speciesLink Network / INCT-HVFF IPT](https://registry.gbif.org/installation/b38ff2b7-c8af-454e-b5af-ee760f0d5bca)
- Number of occurrences indexed for this dataset at the time of the issue: 102624
- Cause: GBIF ID problems exceed 50% threshold: 86% duplicates; 102714 total records; 88271 absent records
- Pipelines execution steps: [http://api.gbif.org/v1/pipelines/history/execution/3382598/step](http://api.gbif.org/v1/pipelines/history/execution/3382598/step)

```
New IDs sample:

BRA:FURB:UPCB:48079
BRA:FURB:UPCB:87643
BRA:FURB:UPCB:1683
BRA:FURB:UPCB:73026
BRA:FURB:UPCB:48302
BRA:FURB:UPCB:73027
BRA:FURB:UPCB:48301
BRA:FURB:UPCB:87640
BRA:FURB:UPCB:1697
BRA:FURB:UPCB:87641
```


```
Old IDs sample:

BRA:UFPR:UPCB:103886
BRA:UFPR:UPCB:104894
BRA:UFPR:UPCB:105207
BRA:UFPR:UPCB:105208
BRA:UFPR:UPCB:105209
BRA:UFPR:UPCB:105210
BRA:UFPR:UPCB:105211
BRA:UFPR:UPCB:105212
BRA:UFPR:UPCB:105213
BRA:UFPR:UPCB:105214
```

<details>
<summary>Publisher email</summary>

Hello,

I am contacting you from the GBIF Secretariat about a dataset published by the [UPCB - Herbário do Departamento de Botânica](https://registry.gbif.org/dataset/a51fa32f-831d-49d6-8b8a-c7b52ae65b3b) : https://doi.org/10.15468/udpvi1.
We noticed that the occurrenceIDs were changed. We have temporarily paused the ingestions of this dataset.

As you might already know, when an occurrence record has a new occurrenceID for a given dataset, our system considers it to be a new occurrence.
This means that it will be given a new gbifid and a new occurrence URL (like this one: https://www.gbif.org/occurrence/1252968762) and the old gbifid and URL will be deprecated.

In this case, this means that the occurrence URLs would be deprecated when ingesting the newest versions of these datasets.

We would like to check with you if those changes were intentional. Do you know if this is the case?
Please let us know, thanks! We are happy to resume the dataset ingestion.

Note that some users rely on those occurrence URLs and gbifids (like https://bionomia.net for example). In an attempt to improve
the stability of the occurrence URLs and gbifids, we have implemented a warning system to detect these type of changes in datasets (see this news item).
If the data publisher can provide us with a list of old and new occurrenceIDs per record, we can avoid the identifier and URL changes. Could that be an option?

Please let us know if you have any question. Thanks!

All the best,

</details>


You can skip/fix identifier validation using [the registry UI](https://registry.gbif.org/dataset/a51fa32f-831d-49d6-8b8a-c7b52ae65b3b/ingestion-history).

**Comment by gbif-pipelines** [comment]
Identifier validation still  failing for the dataset [UPCB - Herbário do Departamento de Botânica](https://registry.gbif.org/dataset/a51fa32f-831d-49d6-8b8a-c7b52ae65b3b):
- Crawler attempt: 389
- Publishing organization: [Universidade Federal do Paraná](https://registry.gbif.org/organization/f6e2efc9-42a3-47ea-99c6-3eda8d653cc9)
- Publishing country: BRAZIL
- Installation: [speciesLink Network / INCT-HVFF IPT](https://registry.gbif.org/installation/b38ff2b7-c8af-454e-b5af-ee760f0d5bca)
- Number of occurrences indexed for this dataset at the time of the issue: 102624
- Cause: GBIF ID problems exceed 50% threshold: 86% duplicates; 102714 total records; 88271 absent records
- Pipelines execution steps: [http://api.gbif.org/v1/pipelines/history/execution/3402600/step](http://api.gbif.org/v1/pipelines/history/execution/3402600/step)

```
New IDs sample:

BRA:FURB:UPCB:48079
BRA:FURB:UPCB:87643
BRA:FURB:UPCB:1683
BRA:FURB:UPCB:73026
BRA:FURB:UPCB:48302
BRA:FURB:UPCB:73027
BRA:FURB:UPCB:48301
BRA:FURB:UPCB:87640
BRA:FURB:UPCB:1697
BRA:FURB:UPCB:87641
```


```
Old IDs sample:

BRA:UFPR:UPCB:103886
BRA:UFPR:UPCB:104894
BRA:UFPR:UPCB:105207
BRA:UFPR:UPCB:105208
BRA:UFPR:UPCB:105209
BRA:UFPR:UPCB:105210
BRA:UFPR:UPCB:105211
BRA:UFPR:UPCB:105212
BRA:UFPR:UPCB:105213
BRA:UFPR:UPCB:105214
```

<details>
<summary>Publisher email</summary>

Hello,

I am contacting you from the GBIF Secretariat about a dataset published by the [UPCB - Herbário do Departamento de Botânica](https://registry.gbif.org/dataset/a51fa32f-831d-49d6-8b8a-c7b52ae65b3b) : https://doi.org/10.15468/udpvi1.
We noticed that the occurrenceIDs were changed. We have temporarily paused the ingestions of this dataset.

As you might already know, when an occurrence record has a new occurrenceID for a given dataset, our system considers it to be a new occurrence.
This means that it will be given a new gbifid and a new occurrence URL (like this one: https://www.gbif.org/occurrence/1252968762) and the old gbifid and URL will be deprecated.

In this case, this means that the occurrence URLs would be deprecated when ingesting the newest versions of these datasets.

We would like to check with you if those changes were intentional. Do you know if this is the case?
Please let us know, thanks! We are happy to resume the dataset ingestion.

Note that some users rely on those occurrence URLs and gbifids (like https://bionomia.net for example). In an attempt to improve
the stability of the occurrence URLs and gbifids, we have implemented a warning system to detect these type of changes in datasets (see this news item).
If the data publisher can provide us with a list of old and new occurrenceIDs per record, we can avoid the identifier and URL changes. Could that be an option?

Please let us know if you have any question. Thanks!

All the best,

</details>


You can skip/fix identifier validation using [the registry UI](https://registry.gbif.org/dataset/a51fa32f-831d-49d6-8b8a-c7b52ae65b3b/ingestion-history).

**Comment by gbif-pipelines** [comment]
Identifier validation still  failing for the dataset [UPCB - Herbário do Departamento de Botânica](https://registry.gbif.org/dataset/a51fa32f-831d-49d6-8b8a-c7b52ae65b3b):
- Crawler attempt: 390
- Publishing organization: [Universidade Federal do Paraná](https://registry.gbif.org/organization/f6e2efc9-42a3-47ea-99c6-3eda8d653cc9)
- Publishing country: BRAZIL
- Installation: [speciesLink Network / INCT-HVFF IPT](https://registry.gbif.org/installation/b38ff2b7-c8af-454e-b5af-ee760f0d5bca)
- Number of occurrences indexed for this dataset at the time of the issue: 102624
- Cause: GBIF ID problems exceed 50% threshold: 86% duplicates; 102714 total records; 88271 absent records
- Pipelines execution steps: [http://api.gbif.org/v1/pipelines/history/execution/3412720/step](http://api.gbif.org/v1/pipelines/history/execution/3412720/step)

```
New IDs sample:

BRA:FURB:UPCB:48079
BRA:FURB:UPCB:87643
BRA:FURB:UPCB:1683
BRA:FURB:UPCB:73026
BRA:FURB:UPCB:48302
BRA:FURB:UPCB:73027
BRA:FURB:UPCB:48301
BRA:FURB:UPCB:87640
BRA:FURB:UPCB:1697
BRA:FURB:UPCB:87641
```


```
Old IDs sample:

BRA:UFPR:UPCB:103886
BRA:UFPR:UPCB:104894
BRA:UFPR:UPCB:105207
BRA:UFPR:UPCB:105208
BRA:UFPR:UPCB:105209
BRA:UFPR:UPCB:105210
BRA:UFPR:UPCB:105211
BRA:UFPR:UPCB:105212
BRA:UFPR:UPCB:105213
BRA:UFPR:UPCB:105214
```

<details>
<summary>Publisher email</summary>

Hello,

I am contacting you from the GBIF Secretariat about a dataset published by the [UPCB - Herbário do Departamento de Botânica](https://registry.gbif.org/dataset/a51fa32f-831d-49d6-8b8a-c7b52ae65b3b) : https://doi.org/10.15468/udpvi1.
We noticed that the occurrenceIDs were changed. We have temporarily paused the ingestions of this dataset.

As you might already know, when an occurrence record has a new occurrenceID for a given dataset, our system considers it to be a new occurrence.
This means that it will be given a new gbifid and a new occurrence URL (like this one: https://www.gbif.org/occurrence/1252968762) and the old gbifid and URL will be deprecated.

In this case, this means that the occurrence URLs would be deprecated when ingesting the newest versions of these datasets.

We would like to check with you if those changes were intentional. Do you know if this is the case?
Please let us know, thanks! We are happy to resume the dataset ingestion.

Note that some users rely on those occurrence URLs and gbifids (like https://bionomia.net for example). In an attempt to improve
the stability of the occurrence URLs and gbifids, we have implemented a warning system to detect these type of changes in datasets (see this news item).
If the data publisher can provide us with a list of old and new occurrenceIDs per record, we can avoid the identifier and URL changes. Could that be an option?

Please let us know if you have any question. Thanks!

All the best,

</details>


You can skip/fix identifier validation using [the registry UI](https://registry.gbif.org/dataset/a51fa32f-831d-49d6-8b8a-c7b52ae65b3b/ingestion-history).

**Comment by gbif-pipelines** [comment]
Identifier validation still  failing for the dataset [UPCB - Herbário do Departamento de Botânica](https://registry.gbif.org/dataset/a51fa32f-831d-49d6-8b8a-c7b52ae65b3b):
- Crawler attempt: 391
- Publishing organization: [Universidade Federal do Paraná](https://registry.gbif.org/organization/f6e2efc9-42a3-47ea-99c6-3eda8d653cc9)
- Publishing country: BRAZIL
- Installation: [speciesLink Network / INCT-HVFF IPT](https://registry.gbif.org/installation/b38ff2b7-c8af-454e-b5af-ee760f0d5bca)
- Number of occurrences indexed for this dataset at the time of the issue: 102624
- Cause: GBIF ID problems exceed 50% threshold: 86% duplicates; 102714 total records; 88271 absent records
- Pipelines execution steps: [http://api.gbif.org/v1/pipelines/history/execution/3424410/step](http://api.gbif.org/v1/pipelines/history/execution/3424410/step)

```
New IDs sample:

BRA:FURB:UPCB:48079
BRA:FURB:UPCB:87643
BRA:FURB:UPCB:1683
BRA:FURB:UPCB:73026
BRA:FURB:UPCB:48302
BRA:FURB:UPCB:73027
BRA:FURB:UPCB:48301
BRA:FURB:UPCB:87640
BRA:FURB:UPCB:1697
BRA:FURB:UPCB:87641
```


```
Old IDs sample:

BRA:UFPR:UPCB:103886
BRA:UFPR:UPCB:104894
BRA:UFPR:UPCB:105207
BRA:UFPR:UPCB:105208
BRA:UFPR:UPCB:105209
BRA:UFPR:UPCB:105210
BRA:UFPR:UPCB:105211
BRA:UFPR:UPCB:105212
BRA:UFPR:UPCB:105213
BRA:UFPR:UPCB:105214
```

<details>
<summary>Publisher email</summary>

Hello,

I am contacting you from the GBIF Secretariat about a dataset published by the [UPCB - Herbário do Departamento de Botânica](https://registry.gbif.org/dataset/a51fa32f-831d-49d6-8b8a-c7b52ae65b3b) : https://doi.org/10.15468/udpvi1.
We noticed that the occurrenceIDs were changed. We have temporarily paused the ingestions of this dataset.

As you might already know, when an occurrence record has a new occurrenceID for a given dataset, our system considers it to be a new occurrence.
This means that it will be given a new gbifid and a new occurrence URL (like this one: https://www.gbif.org/occurrence/1252968762) and the old gbifid and URL will be deprecated.

In this case, this means that the occurrence URLs would be deprecated when ingesting the newest versions of these datasets.

We would like to check with you if those changes were intentional. Do you know if this is the case?
Please let us know, thanks! We are happy to resume the dataset ingestion.

Note that some users rely on those occurrence URLs and gbifids (like https://bionomia.net for example). In an attempt to improve
the stability of the occurrence URLs and gbifids, we have implemented a warning system to detect these type of changes in datasets (see this news item).
If the data publisher can provide us with a list of old and new occurrenceIDs per record, we can avoid the identifier and URL changes. Could that be an option?

Please let us know if you have any question. Thanks!

All the best,

</details>


You can skip/fix identifier validation using [the registry UI](https://registry.gbif.org/dataset/a51fa32f-831d-49d6-8b8a-c7b52ae65b3b/ingestion-history).

**Comment by jhnwllr** [comment]
Since this is an old issue, with no response, I am resuming id checks.
