### ISSUE TITLE
Identifiers validation failed for dataset UNM Earth Sciences Collection (Arctos)

### ISSUE THREAD

**Issue by gbif-pipelines** [gbif/ingestion-management#844]
Identifier validation failed for the dataset [UNM Earth Sciences Collection (Arctos)](https://registry.gbif.org/dataset/2ea6a803-fcf8-4733-9171-23e3edc59624):
- Crawler attempt: 344
- Publishing organization: [University of New Mexico Paleontology Collections (UNMP)](https://registry.gbif.org/organization/e6e2dcf4-60c4-4b16-abea-557a3f89f2aa)
- Publishing country: UNITED_STATES
- Installation: [IPT - Hosted by VertNet](https://registry.gbif.org/installation/a957a663-2f17-415f-b1c8-5cf6398df8ed)
- Number of occurrences indexed for this dataset at the time of the issue: 1548
- Cause: GBIF ID problems exceed 5% threshold: 100% duplicates; 3397 total records; 3397 absent records
- Pipelines execution steps: [http://api.gbif.org/v1/pipelines/history/execution/3321372/step](http://api.gbif.org/v1/pipelines/history/execution/3321372/step)

```
New IDs sample:

http://arctos.database.museum/guid/UNM:Geol:1676?seid=6097144
http://arctos.database.museum/guid/UNM:Geol:1731?seid=6097195
http://arctos.database.museum/guid/UNM:Geol:1737?seid=6097200
http://arctos.database.museum/guid/UNM:Geol:1772?seid=6097239
http://arctos.database.museum/guid/UNM:Geol:1732?seid=6097252
http://arctos.database.museum/guid/UNM:Geol:205?seid=6097266
http://arctos.database.museum/guid/UNM:Geol:16?seid=6097283
http://arctos.database.museum/guid/UNM:Geol:334?seid=6097300
http://arctos.database.museum/guid/UNM:Geol:1733?seid=6097302
http://arctos.database.museum/guid/UNM:Geol:2232?seid=6097303
http://arctos.database.museum/guid/UNM:Geol:494?seid=6097308
http://arctos.database.museum/guid/UNM:Geol:496?seid=6097310
http://arctos.database.museum/guid/UNM:Geol:497?seid=6097311
http://arctos.database.museum/guid/UNM:Geol:812?seid=6097366
http://arctos.database.museum/guid/UNM:Geol:916?seid=6097382
http://arctos.database.museum/guid/UNM:Geol:918?seid=6097384
http://arctos.database.museum/guid/UNM:Geol:11?seid=6097407
http://arctos.database.museum/guid/UNM:Geol:13?seid=6097409
http://arctos.database.museum/guid/UNM:Geol:31?seid=6097420



```

```
Old IDs sample:

http://arctos.database.museum/guid/UNM:Paleo:10258?seid=4003879
http://arctos.database.museum/guid/UNM:Paleo:10263?seid=4003881
http://arctos.database.museum/guid/UNM:Paleo:1660?seid=4001519
http://arctos.database.museum/guid/UNM:Paleo:1804?seid=4001520
http://arctos.database.museum/guid/UNM:Paleo:1992?seid=4003874
http://arctos.database.museum/guid/UNM:Paleo:4463?seid=4003878
http://arctos.database.museum/guid/UNM:Paleo:6056?seid=4001526
http://arctos.database.museum/guid/UNM:Paleo:6058?seid=4001527
http://arctos.database.museum/guid/UNM:Paleo:844?seid=4003872
http://arctos.database.museum/guid/UNM:Paleo:13200?seid=4045076
```

<details>
<summary>Publisher email</summary>

Hello,

I am contacting you from the GBIF Secretariat about a dataset published by the [UNM Earth Sciences Collection (Arctos)](https://registry.gbif.org/dataset/2ea6a803-fcf8-4733-9171-23e3edc59624) : https://doi.org/10.15468/s7se8x.
We noticed that the occurrenceIDs were changed. We have temporarily paused the ingestions of this dataset.

As you might already know, when an occurrence record has a new occurrenceID for a given dataset, our system considers it to be a new occurrence.
This means that it will be given a new gbifid and a new occurrence URL (like this one: https://www.gbif.org/occurrence/1252968762) and the old gbifid and URL will be deprecated.

In this case, this means that the occurrence URLs would be deprecated when ingesting the newest versions of these datasets.

We would like to check with you if those changes were intentional. Do you know if this is the case?
Please let us know, thanks! We are happy to resume the dataset ingestion.

Note that some users rely on those occurrence URLs and gbifids (like https://bionomia.net for example). In an attempt to improve
the stability of the occurrence URLs and gbifids, we have implemented a warning system to detect these type of changes in datasets (see this news item).
If the data publisher can provide us with a list of old and new occurrenceIDs per record, we can avoid the identifier and URL changes. Could that be an option?

Please let us know if you have any question. Thanks!

All the best,

</details>

You can skip/fix identifier validation using [the registry UI](https://registry.gbif.org/dataset/2ea6a803-fcf8-4733-9171-23e3edc59624/ingestion-history).

**Comment by ManonGros** [comment]
Hi @dbloom, this is the repository we use to get notification for datasets with paused because of occurrenceID changes. The occurrenceID for the dataset titled "UNM Earth Sciences Collection (Arctos)" (http://ipt.vertnet.org:8080/ipt/resource?r=unm_es) have been changed.

Should we go ahead and resume the dataset ingestion? Let us know, thanks!

As a side note, you can see the datasets hosted by VerNet that are currently paused here: https://github.com/gbif/ingestion-management/labels/inst%3A%20a957a663-2f17-415f-b1c8-5cf6398df8ed

Would you rather be notified by email or is tagging you on GitHub easier to keep an overview? Let us know, thanks!

**Comment by dbloom** [comment]
Thanks @ManonGros This was operator error on my part. I have republished with the correct IDs. Please resume ingestion if it is still on hold.

**Comment by gbif-pipelines** [comment]
Identifier validation still  failing for the dataset [UNM Earth Sciences Collection (Arctos)](https://registry.gbif.org/dataset/2ea6a803-fcf8-4733-9171-23e3edc59624):
- Crawler attempt: 345
- Publishing organization: [University of New Mexico Paleontology Collections (UNMP)](https://registry.gbif.org/organization/e6e2dcf4-60c4-4b16-abea-557a3f89f2aa)
- Publishing country: UNITED_STATES
- Installation: [IPT - Hosted by VertNet](https://registry.gbif.org/installation/a957a663-2f17-415f-b1c8-5cf6398df8ed)
- Number of occurrences indexed for this dataset at the time of the issue: 1548
- Cause: GBIF ID problems exceed 5% threshold: 100% duplicates; 3397 total records; 3397 absent records
- Pipelines execution steps: [http://api.gbif.org/v1/pipelines/history/execution/3324187/step](http://api.gbif.org/v1/pipelines/history/execution/3324187/step)

```
New IDs sample:


```


```
Old IDs sample:

http://arctos.database.museum/guid/UNM:Paleo:10258?seid=4003879
http://arctos.database.museum/guid/UNM:Paleo:10263?seid=4003881
http://arctos.database.museum/guid/UNM:Paleo:1660?seid=4001519
http://arctos.database.museum/guid/UNM:Paleo:1804?seid=4001520
http://arctos.database.museum/guid/UNM:Paleo:1992?seid=4003874
http://arctos.database.museum/guid/UNM:Paleo:4463?seid=4003878
http://arctos.database.museum/guid/UNM:Paleo:6056?seid=4001526
http://arctos.database.museum/guid/UNM:Paleo:6058?seid=4001527
http://arctos.database.museum/guid/UNM:Paleo:844?seid=4003872
http://arctos.database.museum/guid/UNM:Paleo:13200?seid=4045076
```

<details>
<summary>Publisher email</summary>

Hello,

I am contacting you from the GBIF Secretariat about a dataset published by the [UNM Earth Sciences Collection (Arctos)](https://registry.gbif.org/dataset/2ea6a803-fcf8-4733-9171-23e3edc59624) : https://doi.org/10.15468/s7se8x.
We noticed that the occurrenceIDs were changed. We have temporarily paused the ingestions of this dataset.

As you might already know, when an occurrence record has a new occurrenceID for a given dataset, our system considers it to be a new occurrence.
This means that it will be given a new gbifid and a new occurrence URL (like this one: https://www.gbif.org/occurrence/1252968762) and the old gbifid and URL will be deprecated.

In this case, this means that the occurrence URLs would be deprecated when ingesting the newest versions of these datasets.

We would like to check with you if those changes were intentional. Do you know if this is the case?
Please let us know, thanks! We are happy to resume the dataset ingestion.

Note that some users rely on those occurrence URLs and gbifids (like https://bionomia.net for example). In an attempt to improve
the stability of the occurrence URLs and gbifids, we have implemented a warning system to detect these type of changes in datasets (see this news item).
If the data publisher can provide us with a list of old and new occurrenceIDs per record, we can avoid the identifier and URL changes. Could that be an option?

Please let us know if you have any question. Thanks!

All the best,

</details>


You can skip/fix identifier validation using [the registry UI](https://registry.gbif.org/dataset/2ea6a803-fcf8-4733-9171-23e3edc59624/ingestion-history).

**Comment by dbloom** [comment]
@ManonGros This doesn't make sense to me.

The DwC-A produced by the IPT contains 3397 occurrenceIDs, no duplicates. The direct database linkage, when refreshed, shows the same. the Attached is the occurrence.txt. What am I missing here?
[occurrence.txt](https://github.com/gbif/ingestion-management/files/12821740/occurrence.txt)

**Comment by ManonGros** [comment]
Hi @dbloom this is because the current version of the data we have has occurrenceIDs like `http://arctos.database.museum/guid/UNM:Paleo:10258?seid=4003879` but the archive generated has new occurrenceIDs like `http://arctos.database.museum/guid/UNM:Geol:1563?seid=6096887`. One noticeable difference is the `Paleo` vs `Geol` in the URL but I am not sure that's the only ones.
I am happy to go ahead and resume the dataset ingestion in order to get the new occurrenceID. We just want to make sure the change in occurrenceID isn't a mistake.

**Comment by dbloom** [comment]
@ManonGros It was my error a second time with this one. This is bound to happen when Arctos has both UMN:Geol and UNM:Paleo. I have corrected this dataset so that it is now using the correct ArctosID (Paleo) This should also correct the record count and return it to 1548.

I have published it once again. Hopefully this will make the validator happy.

**Comment by ManonGros** [comment]
Thanks @dbloom! The ingestion went through.
Note that if the identifiers need to be changed in a future update, it is ok, just let us know and we will let the dataset go through.
