### ISSUE TITLE
Identifiers validation failed for dataset University of Cincinnati, Margaret H. Fulford Herbarium - Vascular Plants

### ISSUE THREAD

**Issue by gbif-pipelines** [gbif/ingestion-management#847]
Identifier validation failed for the dataset [University of Cincinnati, Margaret H. Fulford Herbarium - Vascular Plants](https://registry.gbif.org/dataset/0f6a3163-4efb-47ab-a4f1-2f548098665f):
- Crawler attempt: 124
- Publishing organization: [Margaret H. Fulford Herbarium, University of Cincinnati (CINC)](https://registry.gbif.org/organization/925267b2-870b-409e-8a81-d044d6eb6c2f)
- Publishing country: UNITED_STATES
- Installation: [SEINet Portal Network](https://registry.gbif.org/installation/ac2ad091-91eb-482d-a73f-061744da5dbf)
- Number of occurrences indexed for this dataset at the time of the issue: 16420
- Cause: GBIF ID problems exceed 5% threshold: 10% duplicates; 18202 total records; 1878 absent records
- Pipelines execution steps: [http://api.gbif.org/v1/pipelines/history/execution/3321795/step](http://api.gbif.org/v1/pipelines/history/execution/3321795/step)

```
New IDs sample:

31432522
31431200
31432523
31417359
31432530
31431208
31432532
31432531
31432525
31432524
```

```
Old IDs sample:

187a267a-122a-49ad-93b8-dfed23db9202
3e3244b9-ffb9-41f5-ad3d-ce193b4f4898
cef590fb-4cbb-4b3c-90a3-967d86f5cbfc
c9251f7a-e18f-4360-a422-5832abd528bd
13f8b87a-1a60-4fd5-8fac-111a64f35809
4065c304-cbe4-4313-a220-37a0b62c7aaa
c92c9cd4-d665-4ef6-ab86-404f7bac206b
c43f678a-e083-4a72-a2d0-c40bc432ea81
d1945de8-c3f8-4a4a-b7ca-3afdd76e7820
7eca32b7-7816-4a21-8157-2412ad282267
```

<details>
<summary>Publisher email</summary>

Hello,

I am contacting you from the GBIF Secretariat about a dataset published by the [University of Cincinnati, Margaret H. Fulford Herbarium - Vascular Plants](https://registry.gbif.org/dataset/0f6a3163-4efb-47ab-a4f1-2f548098665f) : https://doi.org/10.15468/bhgpmq.
We noticed that the occurrenceIDs were changed. We have temporarily paused the ingestions of this dataset.

As you might already know, when an occurrence record has a new occurrenceID for a given dataset, our system considers it to be a new occurrence.
This means that it will be given a new gbifid and a new occurrence URL (like this one: https://www.gbif.org/occurrence/1252968762) and the old gbifid and URL will be deprecated.

In this case, this means that the occurrence URLs would be deprecated when ingesting the newest versions of these datasets.

We would like to check with you if those changes were intentional. Do you know if this is the case?
Please let us know, thanks! We are happy to resume the dataset ingestion.

Note that some users rely on those occurrence URLs and gbifids (like https://bionomia.net for example). In an attempt to improve
the stability of the occurrence URLs and gbifids, we have implemented a warning system to detect these type of changes in datasets (see this news item).
If the data publisher can provide us with a list of old and new occurrenceIDs per record, we can avoid the identifier and URL changes. Could that be an option?

Please let us know if you have any question. Thanks!

All the best,

</details>

You can skip/fix identifier validation using [the registry UI](https://registry.gbif.org/dataset/0f6a3163-4efb-47ab-a4f1-2f548098665f/ingestion-history).

**Comment by jhnwllr** [comment]
This dataset was flagged because of a bug in the id checker.
