### ISSUE TITLE
Identifiers validation failed for dataset University of Cincinnati, Margaret H. Fulford Herbarium - Bryophytes

### ISSUE THREAD

**Issue by gbif-pipelines** [gbif/ingestion-management#848]
Identifier validation failed for the dataset [University of Cincinnati, Margaret H. Fulford Herbarium - Bryophytes](https://registry.gbif.org/dataset/6cfce8da-c177-4790-b038-1202dd33e9d7):
- Crawler attempt: 129
- Publishing organization: [Margaret H. Fulford Herbarium, University of Cincinnati (CINC)](https://registry.gbif.org/organization/925267b2-870b-409e-8a81-d044d6eb6c2f)
- Publishing country: UNITED_STATES
- Installation: [Consortium of North American Bryophyte Herbaria](https://registry.gbif.org/installation/f14b8ea2-5f17-466c-89c4-61f2a0ac425a)
- Number of occurrences indexed for this dataset at the time of the issue: 53819
- Cause: GBIF ID problems exceed 5% threshold: 8% duplicates; 58365 total records; 4548 absent records
- Pipelines execution steps: [http://api.gbif.org/v1/pipelines/history/execution/3321811/step](http://api.gbif.org/v1/pipelines/history/execution/3321811/step)

```
New IDs sample:

3651434
3651430
4217046
4217041
4217047
4217048
4217049
3651435
4217043
3651433
```

```
Old IDs sample:

f3434fee-d7df-4acc-82db-f287b17b339c
fc4ae9fc-7542-4528-96ed-0fef3b879f65
ef71e73d-859e-4223-a08d-a05a4b23879e
8ab2e45a-e112-4eae-9627-76fe4734055d
ab1d8f4e-304f-4a5c-9c2a-3bb2fc7fa31d
c3af0c0e-561b-420b-ba4c-c0b494801217
fcdea0f3-b579-48d5-9a98-3041f095f446
fb841572-7db6-4fd1-ab5c-2a238718d49f
edb69430-b9a2-4938-a103-c7ea89ec6ced
6cb7e24c-58fa-47c6-92ff-807f6b22031b
```

<details>
<summary>Publisher email</summary>

Hello,

I am contacting you from the GBIF Secretariat about a dataset published by the [University of Cincinnati, Margaret H. Fulford Herbarium - Bryophytes](https://registry.gbif.org/dataset/6cfce8da-c177-4790-b038-1202dd33e9d7) : https://doi.org/10.15468/xkca3p.
We noticed that the occurrenceIDs were changed. We have temporarily paused the ingestions of this dataset.

As you might already know, when an occurrence record has a new occurrenceID for a given dataset, our system considers it to be a new occurrence.
This means that it will be given a new gbifid and a new occurrence URL (like this one: https://www.gbif.org/occurrence/1252968762) and the old gbifid and URL will be deprecated.

In this case, this means that the occurrence URLs would be deprecated when ingesting the newest versions of these datasets.

We would like to check with you if those changes were intentional. Do you know if this is the case?
Please let us know, thanks! We are happy to resume the dataset ingestion.

Note that some users rely on those occurrence URLs and gbifids (like https://bionomia.net for example). In an attempt to improve
the stability of the occurrence URLs and gbifids, we have implemented a warning system to detect these type of changes in datasets (see this news item).
If the data publisher can provide us with a list of old and new occurrenceIDs per record, we can avoid the identifier and URL changes. Could that be an option?

Please let us know if you have any question. Thanks!

All the best,

</details>

You can skip/fix identifier validation using [the registry UI](https://registry.gbif.org/dataset/6cfce8da-c177-4790-b038-1202dd33e9d7/ingestion-history).

**Comment by gbif-pipelines** [comment]
Identifier validation still  failing for the dataset [University of Cincinnati, Margaret H. Fulford Herbarium - Bryophytes](https://registry.gbif.org/dataset/6cfce8da-c177-4790-b038-1202dd33e9d7):
- Crawler attempt: 130
- Publishing organization: [Margaret H. Fulford Herbarium, University of Cincinnati (CINC)](https://registry.gbif.org/organization/925267b2-870b-409e-8a81-d044d6eb6c2f)
- Publishing country: UNITED_STATES
- Installation: [Consortium of North American Bryophyte Herbaria](https://registry.gbif.org/installation/f14b8ea2-5f17-466c-89c4-61f2a0ac425a)
- Number of occurrences indexed for this dataset at the time of the issue: 53819
- Cause: GBIF ID problems exceed 5% threshold: 8% duplicates; 58372 total records; 4555 absent records
- Pipelines execution steps: [http://api.gbif.org/v1/pipelines/history/execution/3323165/step](http://api.gbif.org/v1/pipelines/history/execution/3323165/step)

```
New IDs sample:

3651434
3651430
4217046
4217041
4217047
4217048
4217049
3651435
4217043
3651433
```


```
Old IDs sample:

f3434fee-d7df-4acc-82db-f287b17b339c
fc4ae9fc-7542-4528-96ed-0fef3b879f65
ef71e73d-859e-4223-a08d-a05a4b23879e
8ab2e45a-e112-4eae-9627-76fe4734055d
ab1d8f4e-304f-4a5c-9c2a-3bb2fc7fa31d
c3af0c0e-561b-420b-ba4c-c0b494801217
fcdea0f3-b579-48d5-9a98-3041f095f446
fb841572-7db6-4fd1-ab5c-2a238718d49f
edb69430-b9a2-4938-a103-c7ea89ec6ced
6cb7e24c-58fa-47c6-92ff-807f6b22031b
```

<details>
<summary>Publisher email</summary>

Hello,

I am contacting you from the GBIF Secretariat about a dataset published by the [University of Cincinnati, Margaret H. Fulford Herbarium - Bryophytes](https://registry.gbif.org/dataset/6cfce8da-c177-4790-b038-1202dd33e9d7) : https://doi.org/10.15468/xkca3p.
We noticed that the occurrenceIDs were changed. We have temporarily paused the ingestions of this dataset.

As you might already know, when an occurrence record has a new occurrenceID for a given dataset, our system considers it to be a new occurrence.
This means that it will be given a new gbifid and a new occurrence URL (like this one: https://www.gbif.org/occurrence/1252968762) and the old gbifid and URL will be deprecated.

In this case, this means that the occurrence URLs would be deprecated when ingesting the newest versions of these datasets.

We would like to check with you if those changes were intentional. Do you know if this is the case?
Please let us know, thanks! We are happy to resume the dataset ingestion.

Note that some users rely on those occurrence URLs and gbifids (like https://bionomia.net for example). In an attempt to improve
the stability of the occurrence URLs and gbifids, we have implemented a warning system to detect these type of changes in datasets (see this news item).
If the data publisher can provide us with a list of old and new occurrenceIDs per record, we can avoid the identifier and URL changes. Could that be an option?

Please let us know if you have any question. Thanks!

All the best,

</details>


You can skip/fix identifier validation using [the registry UI](https://registry.gbif.org/dataset/6cfce8da-c177-4790-b038-1202dd33e9d7/ingestion-history).

**Comment by jhnwllr** [comment]
This dataset was flagged because of a bug in the id checker.
