### ISSUE TITLE
Identifiers validation failed for dataset Dermaptera in the icipe collection

### ISSUE THREAD

**Issue by gbif-pipelines** [gbif/ingestion-management#853]
Identifier validation failed for the dataset [Dermaptera in the icipe collection](https://registry.gbif.org/dataset/b9fd03c9-29f6-4498-b3b4-0afa92b48534):
- Crawler attempt: 294
- Publishing organization: [International Centre for Insect Physiology and Ecology](https://registry.gbif.org/organization/43c1d5e0-0a24-11dd-953d-b8a03c50a862)
- Publishing country: UNKNOWN
- Installation: [ICIPE IPT](https://registry.gbif.org/installation/ed98fa0a-fc11-4517-9bd0-981b7e7c2ec7)
- Number of occurrences indexed for this dataset at the time of the issue: 154
- Cause: GBIF ID problems exceed 50% threshold: 100% duplicates; 154 total records; 154 absent records
- Pipelines execution steps: [http://api.gbif.org/v1/pipelines/history/execution/3331338/step](http://api.gbif.org/v1/pipelines/history/execution/3331338/step)

```
New IDs sample:


```

```
Old IDs sample:


```

<details>
<summary>Publisher email</summary>

Hello,

I am contacting you from the GBIF Secretariat about a dataset published by the [Dermaptera in the icipe collection](https://registry.gbif.org/dataset/b9fd03c9-29f6-4498-b3b4-0afa92b48534) : https://doi.org/10.15468/gfbto2.
We noticed that the occurrenceIDs were changed. We have temporarily paused the ingestions of this dataset.

As you might already know, when an occurrence record has a new occurrenceID for a given dataset, our system considers it to be a new occurrence.
This means that it will be given a new gbifid and a new occurrence URL (like this one: https://www.gbif.org/occurrence/1252968762) and the old gbifid and URL will be deprecated.

In this case, this means that the occurrence URLs would be deprecated when ingesting the newest versions of these datasets.

We would like to check with you if those changes were intentional. Do you know if this is the case?
Please let us know, thanks! We are happy to resume the dataset ingestion.

Note that some users rely on those occurrence URLs and gbifids (like https://bionomia.net for example). In an attempt to improve
the stability of the occurrence URLs and gbifids, we have implemented a warning system to detect these type of changes in datasets (see this news item).
If the data publisher can provide us with a list of old and new occurrenceIDs per record, we can avoid the identifier and URL changes. Could that be an option?

Please let us know if you have any question. Thanks!

All the best,

</details>

You can skip/fix identifier validation using [the registry UI](https://registry.gbif.org/dataset/b9fd03c9-29f6-4498-b3b4-0afa92b48534/ingestion-history).

**Comment by gbif-pipelines** [comment]
Identifier validation still  failing for the dataset [Dermaptera in the icipe collection](https://registry.gbif.org/dataset/b9fd03c9-29f6-4498-b3b4-0afa92b48534):
- Crawler attempt: 295
- Publishing organization: [International Centre for Insect Physiology and Ecology](https://registry.gbif.org/organization/43c1d5e0-0a24-11dd-953d-b8a03c50a862)
- Publishing country: UNKNOWN
- Installation: [ICIPE IPT](https://registry.gbif.org/installation/ed98fa0a-fc11-4517-9bd0-981b7e7c2ec7)
- Number of occurrences indexed for this dataset at the time of the issue: 154
- Cause: GBIF ID problems exceed 50% threshold: 100% duplicates; 154 total records; 154 absent records
- Pipelines execution steps: [http://api.gbif.org/v1/pipelines/history/execution/3331420/step](http://api.gbif.org/v1/pipelines/history/execution/3331420/step)

```
New IDs sample:


```


```
Old IDs sample:


```

<details>
<summary>Publisher email</summary>

Hello,

I am contacting you from the GBIF Secretariat about a dataset published by the [Dermaptera in the icipe collection](https://registry.gbif.org/dataset/b9fd03c9-29f6-4498-b3b4-0afa92b48534) : https://doi.org/10.60798/qoaus1.
We noticed that the occurrenceIDs were changed. We have temporarily paused the ingestions of this dataset.

As you might already know, when an occurrence record has a new occurrenceID for a given dataset, our system considers it to be a new occurrence.
This means that it will be given a new gbifid and a new occurrence URL (like this one: https://www.gbif.org/occurrence/1252968762) and the old gbifid and URL will be deprecated.

In this case, this means that the occurrence URLs would be deprecated when ingesting the newest versions of these datasets.

We would like to check with you if those changes were intentional. Do you know if this is the case?
Please let us know, thanks! We are happy to resume the dataset ingestion.

Note that some users rely on those occurrence URLs and gbifids (like https://bionomia.net for example). In an attempt to improve
the stability of the occurrence URLs and gbifids, we have implemented a warning system to detect these type of changes in datasets (see this news item).
If the data publisher can provide us with a list of old and new occurrenceIDs per record, we can avoid the identifier and URL changes. Could that be an option?

Please let us know if you have any question. Thanks!

All the best,

</details>


You can skip/fix identifier validation using [the registry UI](https://registry.gbif.org/dataset/b9fd03c9-29f6-4498-b3b4-0afa92b48534/ingestion-history).

**Comment by ahahn-gbif** [comment]
Migration from a TAPIR dataset to IPT. Released for ID change
