### ISSUE TITLE
Identifiers validation failed for dataset Happywhale - Humpback Whale in South Atlantic Ocean

### ISSUE THREAD

**Issue by gbif-pipelines** [gbif/ingestion-management#856]
Identifier validation failed for the dataset [Happywhale - Humpback Whale in South Atlantic Ocean](https://registry.gbif.org/dataset/e1dddb82-f1c0-4553-aa2e-1fd414658d01):
- Crawler attempt: 145
- Publishing organization: [OBIS-SEAMAP](https://registry.gbif.org/organization/67b2263f-6990-4d9d-b32b-20aa72ef4fbc)
- Publishing country: UNITED_STATES
- Installation: [OBIS-SEAMAP IPT](https://registry.gbif.org/installation/beeeddea-c02a-43d5-aec7-b534daca34d6)
- Number of occurrences indexed for this dataset at the time of the issue: 2352
- Cause: GBIF ID problems exceed 50% threshold: 61% duplicates; 6002 total records; 3632 absent records
- Pipelines execution steps: [http://api.gbif.org/v1/pipelines/history/execution/3343776/step](http://api.gbif.org/v1/pipelines/history/execution/3343776/step)

```
New IDs sample:

166918
8607
162978
20131
288454
8608
288451
228517
288453
289879
```

```
Old IDs sample:

270051
270052
270053
270247
270292
270293
270295
270323
270324
270348
```

<details>
<summary>Publisher email</summary>

Hello,

I am contacting you from the GBIF Secretariat about a dataset published by the [Happywhale - Humpback Whale in South Atlantic Ocean](https://registry.gbif.org/dataset/e1dddb82-f1c0-4553-aa2e-1fd414658d01) : https://doi.org/10.15468/v6r8s9.
We noticed that the occurrenceIDs were changed. We have temporarily paused the ingestions of this dataset.

As you might already know, when an occurrence record has a new occurrenceID for a given dataset, our system considers it to be a new occurrence.
This means that it will be given a new gbifid and a new occurrence URL (like this one: https://www.gbif.org/occurrence/1252968762) and the old gbifid and URL will be deprecated.

In this case, this means that the occurrence URLs would be deprecated when ingesting the newest versions of these datasets.

We would like to check with you if those changes were intentional. Do you know if this is the case?
Please let us know, thanks! We are happy to resume the dataset ingestion.

Note that some users rely on those occurrence URLs and gbifids (like https://bionomia.net for example). In an attempt to improve
the stability of the occurrence URLs and gbifids, we have implemented a warning system to detect these type of changes in datasets (see this news item).
If the data publisher can provide us with a list of old and new occurrenceIDs per record, we can avoid the identifier and URL changes. Could that be an option?

Please let us know if you have any question. Thanks!

All the best,

</details>

You can skip/fix identifier validation using [the registry UI](https://registry.gbif.org/dataset/e1dddb82-f1c0-4553-aa2e-1fd414658d01/ingestion-history).

**Comment by ktotsum** [comment]
Contacted the publisher on 2023-06-19 by helpdesk.
