### ISSUE TITLE
Identifiers validation failed for dataset Institut Botanic de Barcelona (IBB, CSIC-Ajuntament de Barcelona), BC-Lichenotheca

### ISSUE THREAD

**Issue by gbif-pipelines** [gbif/ingestion-management#858]
Identifier validation failed for the dataset [Institut Botanic de Barcelona (IBB, CSIC-Ajuntament de Barcelona), BC-Lichenotheca](https://registry.gbif.org/dataset/6aeebd1a-c3ad-4bc5-bdfe-24de0e2e9052):
- Crawler attempt: 313
- Publishing organization: [Institut Botànic de Barcelona (CSIC-Ajuntament de Barcelona)](https://registry.gbif.org/organization/6f3ccc65-0a54-4e65-ae7e-13b92d618e7c)
- Publishing country: SPAIN
- Installation: [GBIF Spain IPT](https://registry.gbif.org/installation/2a3f6a56-7591-4f05-8c4c-a1bb77aa4ea6)
- Number of occurrences indexed for this dataset at the time of the issue: 6495
- Cause: GBIF ID problems exceed 50% threshold: 60% duplicates; 9778 total records; 5865 absent records
- Pipelines execution steps: [http://api.gbif.org/v1/pipelines/history/execution/3347987/step](http://api.gbif.org/v1/pipelines/history/execution/3347987/step)

```
New IDs sample:

f9fca74f-3b81-4ec4-9e2e-ec5fee0ea6bc
5ebcc52d-325c-4809-9b29-a875ac6aab71
d50f8c17-bfdc-4a5b-8298-4b9264e1fea0
78ba3695-b5e0-485a-a87f-6d0584035fab
a4b49319-c5b4-497f-9f39-ac8d1f2017ec
7fe05ae6-6a78-4419-bc78-526a6150a49b
76aec2e5-9983-4d6d-b606-c0355a873cc2
0657caac-5855-44e9-8cdc-24fc4e67be7a
05f43f24-a0c5-422d-849e-c36392c9f646
057ddb5e-ed72-4508-a0fc-8148fd1cb4cf
```

```
Old IDs sample:

F52BBB32-D5AA-4D73-B2C3-0F073F328647
F54519C2-DB8C-4773-A2C1-0A07285DE796
F5E5976D-D9A1-48E0-94C0-95F34868DA84
F6617F7C-8AF7-4756-A593-C14C603DDCB5
F6CEAD56-4C69-4940-862C-06B4B1587B2D
F7173621-8797-4056-A84B-065FCCECE16B
F774EA4F-8783-4DCD-86F7-758C236869D6
F87F815F-540E-455D-BCC8-A2E2A9E877F5
F882B191-3260-4C33-BF14-608D38DF6DD8
F8C5EDFF-1BB7-4F34-B2B4-5B78E7714516
```

<details>
<summary>Publisher email</summary>

Hello,

I am contacting you from the GBIF Secretariat about a dataset published by the [Institut Botanic de Barcelona (IBB, CSIC-Ajuntament de Barcelona), BC-Lichenotheca](https://registry.gbif.org/dataset/6aeebd1a-c3ad-4bc5-bdfe-24de0e2e9052) : https://doi.org/10.15468/dgecw5.
We noticed that the occurrenceIDs were changed. We have temporarily paused the ingestions of this dataset.

As you might already know, when an occurrence record has a new occurrenceID for a given dataset, our system considers it to be a new occurrence.
This means that it will be given a new gbifid and a new occurrence URL (like this one: https://www.gbif.org/occurrence/1252968762) and the old gbifid and URL will be deprecated.

In this case, this means that the occurrence URLs would be deprecated when ingesting the newest versions of these datasets.

We would like to check with you if those changes were intentional. Do you know if this is the case?
Please let us know, thanks! We are happy to resume the dataset ingestion.

Note that some users rely on those occurrence URLs and gbifids (like https://bionomia.net for example). In an attempt to improve
the stability of the occurrence URLs and gbifids, we have implemented a warning system to detect these type of changes in datasets (see this news item).
If the data publisher can provide us with a list of old and new occurrenceIDs per record, we can avoid the identifier and URL changes. Could that be an option?

Please let us know if you have any question. Thanks!

All the best,

</details>

You can skip/fix identifier validation using [the registry UI](https://registry.gbif.org/dataset/6aeebd1a-c3ad-4bc5-bdfe-24de0e2e9052/ingestion-history).

**Comment by ktotsum** [comment]
@ManonGros Could you follow up on this case? It has been nearly 2 months since the last contact. Katia is in touch with the publisher to follow up for this case and we are waiting for a reply about a possible migration.

**Comment by gbif-pipelines** [comment]
Identifier validation still  failing for the dataset [Institut Botanic de Barcelona (IBB, CSIC-Ajuntament de Barcelona), BC-Lichenotheca](https://registry.gbif.org/dataset/6aeebd1a-c3ad-4bc5-bdfe-24de0e2e9052):
- Crawler attempt: 324
- Publishing organization: [Institut Botànic de Barcelona (CSIC-CMCNB)](https://registry.gbif.org/organization/6f3ccc65-0a54-4e65-ae7e-13b92d618e7c)
- Publishing country: SPAIN
- Installation: [GBIF Spain IPT](https://registry.gbif.org/installation/2a3f6a56-7591-4f05-8c4c-a1bb77aa4ea6)
- Number of occurrences indexed for this dataset at the time of the issue: 6495
- Cause: GBIF ID problems exceed 50% threshold: 60% duplicates; 9778 total records; 5865 absent records
- Pipelines execution steps: [http://api.gbif.org/v1/pipelines/history/execution/3501837/step](http://api.gbif.org/v1/pipelines/history/execution/3501837/step)

```
New IDs sample:

f9fca74f-3b81-4ec4-9e2e-ec5fee0ea6bc
5ebcc52d-325c-4809-9b29-a875ac6aab71
d50f8c17-bfdc-4a5b-8298-4b9264e1fea0
78ba3695-b5e0-485a-a87f-6d0584035fab
a4b49319-c5b4-497f-9f39-ac8d1f2017ec
7fe05ae6-6a78-4419-bc78-526a6150a49b
76aec2e5-9983-4d6d-b606-c0355a873cc2
0657caac-5855-44e9-8cdc-24fc4e67be7a
05f43f24-a0c5-422d-849e-c36392c9f646
057ddb5e-ed72-4508-a0fc-8148fd1cb4cf
```


```
Old IDs sample:

F52BBB32-D5AA-4D73-B2C3-0F073F328647
F54519C2-DB8C-4773-A2C1-0A07285DE796
F5E5976D-D9A1-48E0-94C0-95F34868DA84
F6617F7C-8AF7-4756-A593-C14C603DDCB5
F6CEAD56-4C69-4940-862C-06B4B1587B2D
F7173621-8797-4056-A84B-065FCCECE16B
F774EA4F-8783-4DCD-86F7-758C236869D6
F87F815F-540E-455D-BCC8-A2E2A9E877F5
F882B191-3260-4C33-BF14-608D38DF6DD8
F8C5EDFF-1BB7-4F34-B2B4-5B78E7714516
```

<details>
<summary>Publisher email</summary>

Hello,

I am contacting you from the GBIF Secretariat about a dataset published by the [Institut Botanic de Barcelona (IBB, CSIC-Ajuntament de Barcelona), BC-Lichenotheca](https://registry.gbif.org/dataset/6aeebd1a-c3ad-4bc5-bdfe-24de0e2e9052) : https://doi.org/10.15468/dgecw5.
We noticed that the occurrenceIDs were changed. We have temporarily paused the ingestions of this dataset.

As you might already know, when an occurrence record has a new occurrenceID for a given dataset, our system considers it to be a new occurrence.
This means that it will be given a new gbifid and a new occurrence URL (like this one: https://www.gbif.org/occurrence/1252968762) and the old gbifid and URL will be deprecated.

In this case, this means that the occurrence URLs would be deprecated when ingesting the newest versions of these datasets.

We would like to check with you if those changes were intentional. Do you know if this is the case?
Please let us know, thanks! We are happy to resume the dataset ingestion.

Note that some users rely on those occurrence URLs and gbifids (like https://bionomia.net for example). In an attempt to improve
the stability of the occurrence URLs and gbifids, we have implemented a warning system to detect these type of changes in datasets (see this news item).
If the data publisher can provide us with a list of old and new occurrenceIDs per record, we can avoid the identifier and URL changes. Could that be an option?

Please let us know if you have any question. Thanks!

All the best,

</details>


You can skip/fix identifier validation using [the registry UI](https://registry.gbif.org/dataset/6aeebd1a-c3ad-4bc5-bdfe-24de0e2e9052/ingestion-history).

**Comment by ManonGros** [comment]
I have migrated a number of occurrences to other datasets based on the files that the node sent. However, the new occurrenceIDs were not included in the file.

**Comment by gbif-pipelines** [comment]
Identifier validation still  failing for the dataset [Institut Botanic de Barcelona (IBB, CSIC-Ajuntament de Barcelona), BC-Lichenotheca](https://registry.gbif.org/dataset/6aeebd1a-c3ad-4bc5-bdfe-24de0e2e9052):
- Crawler attempt: 324
- Publishing organization: [Institut Botànic de Barcelona (CSIC-CMCNB)](https://registry.gbif.org/organization/6f3ccc65-0a54-4e65-ae7e-13b92d618e7c)
- Publishing country: SPAIN
- Installation: [GBIF Spain IPT](https://registry.gbif.org/installation/2a3f6a56-7591-4f05-8c4c-a1bb77aa4ea6)
- Number of occurrences indexed for this dataset at the time of the issue: 6495
- Cause: GBIF ID problems exceed 50% threshold: 60% duplicates; 9778 total records; 5865 absent records
- Pipelines execution steps: [http://api.gbif.org/v1/pipelines/history/execution/3522981/step](http://api.gbif.org/v1/pipelines/history/execution/3522981/step)

```
New IDs sample:

f9fca74f-3b81-4ec4-9e2e-ec5fee0ea6bc
5ebcc52d-325c-4809-9b29-a875ac6aab71
d50f8c17-bfdc-4a5b-8298-4b9264e1fea0
78ba3695-b5e0-485a-a87f-6d0584035fab
a4b49319-c5b4-497f-9f39-ac8d1f2017ec
7fe05ae6-6a78-4419-bc78-526a6150a49b
76aec2e5-9983-4d6d-b606-c0355a873cc2
0657caac-5855-44e9-8cdc-24fc4e67be7a
05f43f24-a0c5-422d-849e-c36392c9f646
057ddb5e-ed72-4508-a0fc-8148fd1cb4cf
```


```
Old IDs sample:

F52BBB32-D5AA-4D73-B2C3-0F073F328647
F54519C2-DB8C-4773-A2C1-0A07285DE796
F5E5976D-D9A1-48E0-94C0-95F34868DA84
F6617F7C-8AF7-4756-A593-C14C603DDCB5
F6CEAD56-4C69-4940-862C-06B4B1587B2D
F7173621-8797-4056-A84B-065FCCECE16B
F774EA4F-8783-4DCD-86F7-758C236869D6
F87F815F-540E-455D-BCC8-A2E2A9E877F5
F882B191-3260-4C33-BF14-608D38DF6DD8
F8C5EDFF-1BB7-4F34-B2B4-5B78E7714516
```

<details>
<summary>Publisher email</summary>

Hello,

I am contacting you from the GBIF Secretariat about a dataset published by the [Institut Botanic de Barcelona (IBB, CSIC-Ajuntament de Barcelona), BC-Lichenotheca](https://registry.gbif.org/dataset/6aeebd1a-c3ad-4bc5-bdfe-24de0e2e9052) : https://doi.org/10.15468/dgecw5.
We noticed that the occurrenceIDs were changed. We have temporarily paused the ingestions of this dataset.

As you might already know, when an occurrence record has a new occurrenceID for a given dataset, our system considers it to be a new occurrence.
This means that it will be given a new gbifid and a new occurrence URL (like this one: https://www.gbif.org/occurrence/1252968762) and the old gbifid and URL will be deprecated.

In this case, this means that the occurrence URLs would be deprecated when ingesting the newest versions of these datasets.

We would like to check with you if those changes were intentional. Do you know if this is the case?
Please let us know, thanks! We are happy to resume the dataset ingestion.

Note that some users rely on those occurrence URLs and gbifids (like https://bionomia.net for example). In an attempt to improve
the stability of the occurrence URLs and gbifids, we have implemented a warning system to detect these type of changes in datasets (see this news item).
If the data publisher can provide us with a list of old and new occurrenceIDs per record, we can avoid the identifier and URL changes. Could that be an option?

Please let us know if you have any question. Thanks!

All the best,

</details>


You can skip/fix identifier validation using [the registry UI](https://registry.gbif.org/dataset/6aeebd1a-c3ad-4bc5-bdfe-24de0e2e9052/ingestion-history).

**Comment by ManonGros** [comment]
I let the identifiers go through to fix the duplicated GBIFID issue.
