### ISSUE TITLE
Identifiers validation failed for dataset Mammal collection (TSZM) The Arctic University Museum of Norway

### ISSUE THREAD

**Issue by gbif-pipelines** [gbif/ingestion-management#859]
Identifier validation failed for the dataset [Mammal collection (TSZM) The Arctic University Museum of Norway](https://registry.gbif.org/dataset/92272f64-30e8-4d9d-80bc-c79465d4e667):
- Crawler attempt: 6
- Publishing organization: [UiT The Arctic University of Norway](https://registry.gbif.org/organization/689b40c4-ff31-4cd0-83a5-a7a828f1cd92)
- Publishing country: NORWAY
- Installation: [GBIF.no](https://registry.gbif.org/installation/c4e83f8a-f24c-4573-a197-f085ca242917)
- Number of occurrences indexed for this dataset at the time of the issue: 2653
- Cause: GBIF ID problems exceed 50% threshold: 100% duplicates; 2653 total records; 2653 absent records
- Pipelines execution steps: [http://api.gbif.org/v1/pipelines/history/execution/3355785/step](http://api.gbif.org/v1/pipelines/history/execution/3355785/step)

```
New IDs sample:


```

```
Old IDs sample:

urn:catalog:TSZP:2647
urn:catalog:TSZP:2648
urn:catalog:TSZP:2650
urn:catalog:TSZP:2625
urn:catalog:TSZP:2626
urn:catalog:TSZP:2627
urn:catalog:TSZP:2628
urn:catalog:TSZP:2629
urn:catalog:TSZP:2525
urn:catalog:TSZP:2563
```

<details>
<summary>Publisher email</summary>

Hello,

I am contacting you from the GBIF Secretariat about a dataset published by the [Mammal collection (TSZM) The Arctic University Museum of Norway](https://registry.gbif.org/dataset/92272f64-30e8-4d9d-80bc-c79465d4e667) : https://doi.org/10.15468/6c89re.
We noticed that the occurrenceIDs were changed. We have temporarily paused the ingestions of this dataset.

As you might already know, when an occurrence record has a new occurrenceID for a given dataset, our system considers it to be a new occurrence.
This means that it will be given a new gbifid and a new occurrence URL (like this one: https://www.gbif.org/occurrence/1252968762) and the old gbifid and URL will be deprecated.

In this case, this means that the occurrence URLs would be deprecated when ingesting the newest versions of these datasets.

We would like to check with you if those changes were intentional. Do you know if this is the case?
Please let us know, thanks! We are happy to resume the dataset ingestion.

Note that some users rely on those occurrence URLs and gbifids (like https://bionomia.net for example). In an attempt to improve
the stability of the occurrence URLs and gbifids, we have implemented a warning system to detect these type of changes in datasets (see this news item).
If the data publisher can provide us with a list of old and new occurrenceIDs per record, we can avoid the identifier and URL changes. Could that be an option?

Please let us know if you have any question. Thanks!

All the best,

</details>

You can skip/fix identifier validation using [the registry UI](https://registry.gbif.org/dataset/92272f64-30e8-4d9d-80bc-c79465d4e667/ingestion-history).

**Comment by ktotsum** [comment]
updates of collectionCode in occurrenceIDs
e.g., from urn:catalog:TSZP:2647 to urn:catalog:TSZM:2647
