### ISSUE TITLE
Identifiers validation failed for dataset Colección ictiológica de referencia de la Universidad del Valle

### ISSUE THREAD

**Issue by gbif-pipelines** [gbif/ingestion-management#890]
Identifier validation failed for the dataset [Colección ictiológica de referencia de la Universidad del Valle](https://registry.gbif.org/dataset/e760ba8b-f487-46ae-91a2-526fe72bbe1c):
- Crawler attempt: 34
- Publishing organization: [Universidad del Valle](https://registry.gbif.org/organization/85be57ed-f187-49c9-b7ff-eaa622e06217)
- Publishing country: COLOMBIA
- Installation: [Datos sobre Biodiversidad Marino Costera de Colombia](https://registry.gbif.org/installation/73ebc470-17bd-4130-a880-1be5cfb16e4d)
- Number of occurrences indexed for this dataset at the time of the issue: 500
- Cause: GBIF ID problems exceed 50% threshold: 83% duplicates; 2876 total records; 2378 absent records
- Pipelines execution steps: [http://api.gbif.org/v1/pipelines/history/execution/3364529/step](http://api.gbif.org/v1/pipelines/history/execution/3364529/step)

```
New IDs sample:

UNIVALLE:CIR-UV:019028
UNIVALLE:CIR-UV:011069
UNIVALLE:CIR-UV:011024
UNIVALLE:CIR-UV:010138
UNIVALLE:CIR-UV:019029
UNIVALLE:CIR-UV:010083
UNIVALLE:CIR-UV:010057
UNIVALLE:CIR-UV:010010
UNIVALLE:CIR-UV:011051
UNIVALLE:CIR-UV:011025
```

```
Old IDs sample:

UNIVALLE:CIR-UV:021195
UNIVALLE:CIR-UV:021082
UNIVALLE:CIR-UV:021088
UNIVALLE:CIR-UV:021090
UNIVALLE:CIR-UV:021092
UNIVALLE:CIR-UV:021093
UNIVALLE:CIR-UV:021105
UNIVALLE:CIR-UV:021107
UNIVALLE:CIR-UV:021124
UNIVALLE:CIR-UV:021125
```

<details>
<summary>Publisher email</summary>

Hello,

I am contacting you from the GBIF Secretariat about a dataset published by the [Colección ictiológica de referencia de la Universidad del Valle](https://registry.gbif.org/dataset/e760ba8b-f487-46ae-91a2-526fe72bbe1c) : https://doi.org/10.15472/9qdylr.
We noticed that the occurrenceIDs were changed. We have temporarily paused the ingestions of this dataset.

As you might already know, when an occurrence record has a new occurrenceID for a given dataset, our system considers it to be a new occurrence.
This means that it will be given a new gbifid and a new occurrence URL (like this one: https://www.gbif.org/occurrence/1252968762) and the old gbifid and URL will be deprecated.

In this case, this means that the occurrence URLs would be deprecated when ingesting the newest versions of these datasets.

We would like to check with you if those changes were intentional. Do you know if this is the case?
Please let us know, thanks! We are happy to resume the dataset ingestion.

Note that some users rely on those occurrence URLs and gbifids (like https://bionomia.net for example). In an attempt to improve
the stability of the occurrence URLs and gbifids, we have implemented a warning system to detect these type of changes in datasets (see this news item).
If the data publisher can provide us with a list of old and new occurrenceIDs per record, we can avoid the identifier and URL changes. Could that be an option?

Please let us know if you have any question. Thanks!

All the best,

</details>

You can skip/fix identifier validation using [the registry UI](https://registry.gbif.org/dataset/e760ba8b-f487-46ae-91a2-526fe72bbe1c/ingestion-history).

**Comment by ManonGros** [comment]
Thanks @EstebanMH-SiB I need to check with my colleague exactly why the dataset was paused. I think that we might not take into account the increase in the number of records when computing the percentage of changes.
