### ISSUE TITLE
Identifiers validation failed for dataset Línea base general de aves y mamíferos a través de cámaras trampa para el valle medio del Magdalena - VMM

### ISSUE THREAD

**Issue by EstebanMH-SiB** [gbif/ingestion-management#894]
Hi, I am creating this issues manually beacause [this dataset](https://registry.gbif.org/dataset/8e8a18e4-2609-4122-a574-a2fad3945866) have this problem in january when this repo was not available. We coud not recover the original occurrenceIDs so it should resume ingestion with new occurrenceIDs.

I hope I am allowed to created issues manually in this repo without all the proper tags and information. If not, sorry in advance hahaha

**Comment by ManonGros** [comment]
Thanks @EstebanMH-SiB !
Yes please feel free to add issues when they are missing. We have resumed the dataset ingestion.
