### ISSUE TITLE
Identifiers validation failed for dataset Línea base general de aves y mamíferos a través de cámaras trampa para el valle medio del Magdalena - VMM

### ISSUE THREAD

**Issue by gbif-pipelines** [gbif/ingestion-management#898]
Identifier validation failed for the dataset [Línea base general de aves y mamíferos a través de cámaras trampa para el valle medio del Magdalena - VMM](https://registry.gbif.org/dataset/8e8a18e4-2609-4122-a574-a2fad3945866):
- Crawler attempt: 85
- Publishing organization: [Instituto de Investigación de Recursos Biológicos Alexander von Humboldt](https://registry.gbif.org/organization/2a7e3080-28a9-11dd-97cd-b8a03c50a862)
- Publishing country: COLOMBIA
- Installation: [IPT IAvH](https://registry.gbif.org/installation/804b8dd0-07ac-4a30-bf92-3c1d862faf5e)
- Number of occurrences indexed for this dataset at the time of the issue: 16719
- Cause: GBIF ID problems exceed 50% threshold: 81% duplicates; 67556 total records; 54651 absent records
- Pipelines execution steps: [http://api.gbif.org/v1/pipelines/history/execution/3381555/step](http://api.gbif.org/v1/pipelines/history/execution/3381555/step)

```
New IDs sample:

IAvH:SSCPE-ANH:SANTANDER:AVESMAMMALIA:OBSERVACIONCONMAQUINA:I2D-BIO_2022_050:10601
IAvH:SSCPE-ANH:SANTANDER:AVESMAMMALIA:OBSERVACIONCONMAQUINA:I2D-BIO_2022_050:11930
IAvH:SSCPE-ANH:SANTANDER:AVESMAMMALIA:OBSERVACIONCONMAQUINA:I2D-BIO_2022_050:10602
IAvH:SSCPE-ANH:SANTANDER:AVESMAMMALIA:OBSERVACIONCONMAQUINA:I2D-BIO_2022_050:11931
IAvH:SSCPE-ANH:SANTANDER:AVESMAMMALIA:OBSERVACIONCONMAQUINA:I2D-BIO_2022_050:23910
IAvH:SSCPE-ANH:SANTANDER:AVESMAMMALIA:OBSERVACIONCONMAQUINA:I2D-BIO_2022_050:23912
IAvH:SSCPE-ANH:SANTANDER:AVESMAMMALIA:OBSERVACIONCONMAQUINA:I2D-BIO_2022_050:16440
IAvH:SSCPE-ANH:SANTANDER:AVESMAMMALIA:OBSERVACIONCONMAQUINA:I2D-BIO_2022_050:29755
IAvH:SSCPE-ANH:SANTANDER:AVESMAMMALIA:OBSERVACIONCONMAQUINA:I2D-BIO_2022_050:29753
IAvH:SSCPE-ANH:SANTANDER:AVESMAMMALIA:OBSERVACIONCONMAQUINA:I2D-BIO_2022_050:23942
```

```
Old IDs sample:

IAvH:SSCPE-ANH:SANTANDER:AVESMAMMALIA:OBSERVACIONCONMAQUINA:I2D-BIO_2022_050:11918
IAvH:SSCPE-ANH:SANTANDER:AVESMAMMALIA:OBSERVACIONCONMAQUINA:I2D-BIO_2022_050:11936
IAvH:SSCPE-ANH:SANTANDER:AVESMAMMALIA:OBSERVACIONCONMAQUINA:I2D-BIO_2022_050:11937
IAvH:SSCPE-ANH:SANTANDER:AVESMAMMALIA:OBSERVACIONCONMAQUINA:I2D-BIO_2022_050:11938
IAvH:SSCPE-ANH:SANTANDER:AVESMAMMALIA:OBSERVACIONCONMAQUINA:I2D-BIO_2022_050:11939
IAvH:SSCPE-ANH:SANTANDER:AVESMAMMALIA:OBSERVACIONCONMAQUINA:I2D-BIO_2022_050:11940
IAvH:SSCPE-ANH:SANTANDER:AVESMAMMALIA:OBSERVACIONCONMAQUINA:I2D-BIO_2022_050:11941
IAvH:SSCPE-ANH:SANTANDER:AVESMAMMALIA:OBSERVACIONCONMAQUINA:I2D-BIO_2022_050:11942
IAvH:SSCPE-ANH:SANTANDER:AVESMAMMALIA:OBSERVACIONCONMAQUINA:I2D-BIO_2022_050:12945
IAvH:SSCPE-ANH:SANTANDER:AVESMAMMALIA:OBSERVACIONCONMAQUINA:I2D-BIO_2022_050:1443
```

<details>
<summary>Publisher email</summary>

Hello,

I am contacting you from the GBIF Secretariat about a dataset published by the [Línea base general de aves y mamíferos a través de cámaras trampa para el valle medio del Magdalena - VMM](https://registry.gbif.org/dataset/8e8a18e4-2609-4122-a574-a2fad3945866) : https://doi.org/10.15472/bo1z8z.
We noticed that the occurrenceIDs were changed. We have temporarily paused the ingestions of this dataset.

As you might already know, when an occurrence record has a new occurrenceID for a given dataset, our system considers it to be a new occurrence.
This means that it will be given a new gbifid and a new occurrence URL (like this one: https://www.gbif.org/occurrence/1252968762) and the old gbifid and URL will be deprecated.

In this case, this means that the occurrence URLs would be deprecated when ingesting the newest versions of these datasets.

We would like to check with you if those changes were intentional. Do you know if this is the case?
Please let us know, thanks! We are happy to resume the dataset ingestion.

Note that some users rely on those occurrence URLs and gbifids (like https://bionomia.net for example). In an attempt to improve
the stability of the occurrence URLs and gbifids, we have implemented a warning system to detect these type of changes in datasets (see this news item).
If the data publisher can provide us with a list of old and new occurrenceIDs per record, we can avoid the identifier and URL changes. Could that be an option?

Please let us know if you have any question. Thanks!

All the best,

</details>

You can skip/fix identifier validation using [the registry UI](https://registry.gbif.org/dataset/8e8a18e4-2609-4122-a574-a2fad3945866/ingestion-history).

**Comment by ManonGros** [comment]
Related to https://github.com/gbif/ingestion-management/issues/894
