### ISSUE TITLE
Identifiers validation failed for dataset Colección Paleontológica Invertebrados e Icnología - IPGP CONICET - Argentina

### ISSUE THREAD

**Issue by gbif-pipelines** [gbif/ingestion-management#899]
Identifier validation failed for the dataset [Colección Paleontológica Invertebrados e Icnología - IPGP CONICET - Argentina](https://registry.gbif.org/dataset/02c8848f-a20e-4436-bc56-d067c7681b04):
- Crawler attempt: 67
- Publishing organization: [CCT CONICET-CENPAT Centro Científico Tecnológico](https://registry.gbif.org/organization/b62390e0-0e35-11d9-8431-b8a03c50a862)
- Publishing country: ARGENTINA
- Installation: [IPT CENPAT-CONICET](https://registry.gbif.org/installation/30cdb869-126c-44df-b1f2-6e06ea98e889)
- Number of occurrences indexed for this dataset at the time of the issue: 544
- Cause: GBIF ID problems exceed 50% threshold: 100% duplicates; 813 total records; 813 absent records
- Pipelines execution steps: [http://api.gbif.org/v1/pipelines/history/execution/3381657/step](http://api.gbif.org/v1/pipelines/history/execution/3381657/step)

```
New IDs sample:


```

```
Old IDs sample:

ee714041-af52-4b29-9c94-5c745265d3ce
254f236e-abc1-456a-9d81-0f454e1adf97
c1b63c88-ff3d-40aa-8248-9026c23c4d80
2891b573-2c83-4db3-a35c-377b6f31fc08
e546a45e-c380-457e-903e-9c5d95391aee
05d6760c-011b-4601-aebb-d614b85ca4bd
54bdfdc7-709e-4021-8301-c6ccfcedf0da
a9815b70-925c-4602-a389-2df0ed53836f
460616b5-a493-4520-b158-b0cd7193bcb9
a33bd352-2e8c-4a8d-ba0c-bef903f5e5a0
```

<details>
<summary>Publisher email</summary>

Hello,

I am contacting you from the GBIF Secretariat about a dataset published by the [Colección Paleontológica Invertebrados e Icnología - IPGP CONICET - Argentina](https://registry.gbif.org/dataset/02c8848f-a20e-4436-bc56-d067c7681b04) : https://doi.org/10.15468/obcc3l.
We noticed that the occurrenceIDs were changed. We have temporarily paused the ingestions of this dataset.

As you might already know, when an occurrence record has a new occurrenceID for a given dataset, our system considers it to be a new occurrence.
This means that it will be given a new gbifid and a new occurrence URL (like this one: https://www.gbif.org/occurrence/1252968762) and the old gbifid and URL will be deprecated.

In this case, this means that the occurrence URLs would be deprecated when ingesting the newest versions of these datasets.

We would like to check with you if those changes were intentional. Do you know if this is the case?
Please let us know, thanks! We are happy to resume the dataset ingestion.

Note that some users rely on those occurrence URLs and gbifids (like https://bionomia.net for example). In an attempt to improve
the stability of the occurrence URLs and gbifids, we have implemented a warning system to detect these type of changes in datasets (see this news item).
If the data publisher can provide us with a list of old and new occurrenceIDs per record, we can avoid the identifier and URL changes. Could that be an option?

Please let us know if you have any question. Thanks!

All the best,

</details>

You can skip/fix identifier validation using [the registry UI](https://registry.gbif.org/dataset/02c8848f-a20e-4436-bc56-d067c7681b04/ingestion-history).

**Comment by ktotsum** [comment]
this happened because of the forced ingestion from https://github.com/gbif/ingestion-management/issues/465
