### ISSUE TITLE
Identifiers validation failed for dataset HUTO - Herbário da Universidade de Tocantins

### ISSUE THREAD

**Issue by gbif-pipelines** [gbif/ingestion-management#9]
Identifier validation failed for the dataset [HUTO - Herbário da Universidade de Tocantins](https://registry.gbif.org/dataset/965b5ae5-7b2d-4155-a7ff-e9e496d70f90):
- Crawler attempt: 388
- Publishing organization: [Fundação Universidade do Tocantins](https://registry.gbif.org/organization/605d693a-f335-44fb-b6cf-3ac49842358e)
- Publishing country: BRAZIL
- Installation: [speciesLink Network / INCT-HVFF IPT](https://registry.gbif.org/installation/b38ff2b7-c8af-454e-b5af-ee760f0d5bca)
- Number of occurrences indexed for this dataset at the time of the issue: 8114
- Cause: GBIF IDs hit maximum allowed - 50%, duplicates - 100%, total records count 3, absent records count 3
- Step metrics: 
```

```

- Pipelines execution steps: [http://api.gbif.org/v1/pipelines/history/execution/3039378/step](http://api.gbif.org/v1/pipelines/history/execution/3039378/step)
<details>
<summary>Publisher email</summary>

Hello,

I am contacting you from the GBIF Secretariat about a dataset published by the [HUTO - Herbário da Universidade de Tocantins](https://registry.gbif.org/dataset/965b5ae5-7b2d-4155-a7ff-e9e496d70f90) : https://doi.org/10.15468/zhlmlh.
We noticed that the occurrenceIDs were changed. We have temporarily paused the ingestions of this dataset.

As you might already know, when an occurrence record has a new occurrenceID for a given dataset, our system considers it to be a new occurrence.
This means that it will be given a new gbifid and a new occurrence URL (like this one: https://www.gbif.org/occurrence/1252968762) and the old gbifid and URL will be deprecated.

In this case, this means that the occurrence URLs would be deprecated when ingesting the newest versions of these datasets.

We would like to check with you if those changes were intentional. Do you know if this is the case?
Please let us know, thanks! We are happy to resume the dataset ingestion.

Note that some users rely on those occurrence URLs and gbifids (like https://bionomia.net for example). In an attempt to improve
the stability of the occurrence URLs and gbifids, we have implemented a warning system to detect these type of changes in datasets (see this news item).
If the data publisher can provide us with a list of old and new occurrenceIDs per record, we can avoid the identifier and URL changes. Could that be an option?

Please let us know if you have any question. Thanks!

All the best,

</details>

You can skip/fix identifier validation using [the registry UI](https://registry.gbif.org/dataset/965b5ae5-7b2d-4155-a7ff-e9e496d70f90/ingestion-history).

**Comment by gbif-pipelines** [comment]
Identifier validation still  failing for the dataset [HUTO - Herbário da Universidade de Tocantins](https://registry.gbif.org/dataset/965b5ae5-7b2d-4155-a7ff-e9e496d70f90):
- Crawler attempt: 389
- Publishing organization: [Fundação Universidade do Tocantins](https://registry.gbif.org/organization/605d693a-f335-44fb-b6cf-3ac49842358e)
- Publishing country: BRAZIL
- Installation: [speciesLink Network / INCT-HVFF IPT](https://registry.gbif.org/installation/b38ff2b7-c8af-454e-b5af-ee760f0d5bca)
- Number of occurrences indexed for this dataset at the time of the issue: 8114
- Cause: GBIF IDs hit maximum allowed - 50%, duplicates - 100%, total records count 3, absent records count 3
- Step metrics: 
```

```

- Pipelines execution steps: [http://api.gbif.org/v1/pipelines/history/execution/3051802/step](http://api.gbif.org/v1/pipelines/history/execution/3051802/step)
<details>
<summary>Publisher email</summary>

Hello,

I am contacting you from the GBIF Secretariat about a dataset published by the [HUTO - Herbário da Universidade de Tocantins](https://registry.gbif.org/dataset/965b5ae5-7b2d-4155-a7ff-e9e496d70f90) : https://doi.org/10.15468/zhlmlh.
We noticed that the occurrenceIDs were changed. We have temporarily paused the ingestions of this dataset.

As you might already know, when an occurrence record has a new occurrenceID for a given dataset, our system considers it to be a new occurrence.
This means that it will be given a new gbifid and a new occurrence URL (like this one: https://www.gbif.org/occurrence/1252968762) and the old gbifid and URL will be deprecated.

In this case, this means that the occurrence URLs would be deprecated when ingesting the newest versions of these datasets.

We would like to check with you if those changes were intentional. Do you know if this is the case?
Please let us know, thanks! We are happy to resume the dataset ingestion.

Note that some users rely on those occurrence URLs and gbifids (like https://bionomia.net for example). In an attempt to improve
the stability of the occurrence URLs and gbifids, we have implemented a warning system to detect these type of changes in datasets (see this news item).
If the data publisher can provide us with a list of old and new occurrenceIDs per record, we can avoid the identifier and URL changes. Could that be an option?

Please let us know if you have any question. Thanks!

All the best,

</details>


You can skip/fix identifier validation using [the registry UI](https://registry.gbif.org/dataset/965b5ae5-7b2d-4155-a7ff-e9e496d70f90/ingestion-history).

**Comment by gbif-pipelines** [comment]
Identifier validation still  failing for the dataset [HUTO - Herbário da Universidade de Tocantins](https://registry.gbif.org/dataset/965b5ae5-7b2d-4155-a7ff-e9e496d70f90):
- Crawler attempt: 391
- Publishing organization: [Fundação Universidade do Tocantins](https://registry.gbif.org/organization/605d693a-f335-44fb-b6cf-3ac49842358e)
- Publishing country: BRAZIL
- Installation: [speciesLink Network / INCT-HVFF IPT](https://registry.gbif.org/installation/b38ff2b7-c8af-454e-b5af-ee760f0d5bca)
- Number of occurrences indexed for this dataset at the time of the issue: 8114
- Cause: GBIF IDs hit maximum allowed - 50%, duplicates - 100%, total records count 3, absent records count 3
- Pipelines execution steps: [http://api.gbif.org/v1/pipelines/history/execution/3061980/step](http://api.gbif.org/v1/pipelines/history/execution/3061980/step)
<details>
<summary>Publisher email</summary>

Hello,

I am contacting you from the GBIF Secretariat about a dataset published by the [HUTO - Herbário da Universidade de Tocantins](https://registry.gbif.org/dataset/965b5ae5-7b2d-4155-a7ff-e9e496d70f90) : https://doi.org/10.15468/zhlmlh.
We noticed that the occurrenceIDs were changed. We have temporarily paused the ingestions of this dataset.

As you might already know, when an occurrence record has a new occurrenceID for a given dataset, our system considers it to be a new occurrence.
This means that it will be given a new gbifid and a new occurrence URL (like this one: https://www.gbif.org/occurrence/1252968762) and the old gbifid and URL will be deprecated.

In this case, this means that the occurrence URLs would be deprecated when ingesting the newest versions of these datasets.

We would like to check with you if those changes were intentional. Do you know if this is the case?
Please let us know, thanks! We are happy to resume the dataset ingestion.

Note that some users rely on those occurrence URLs and gbifids (like https://bionomia.net for example). In an attempt to improve
the stability of the occurrence URLs and gbifids, we have implemented a warning system to detect these type of changes in datasets (see this news item).
If the data publisher can provide us with a list of old and new occurrenceIDs per record, we can avoid the identifier and URL changes. Could that be an option?

Please let us know if you have any question. Thanks!

All the best,

</details>


You can skip/fix identifier validation using [the registry UI](https://registry.gbif.org/dataset/965b5ae5-7b2d-4155-a7ff-e9e496d70f90/ingestion-history).

**Comment by jhnwllr** [comment]
Looks like the records were deleted.

**Comment by gbif-pipelines** [comment]
Identifier validation still  failing for the dataset [HUTO - Herbário da Universidade de Tocantins](https://registry.gbif.org/dataset/965b5ae5-7b2d-4155-a7ff-e9e496d70f90):
- Crawler attempt: 394
- Publishing organization: [Fundação Universidade do Tocantins](https://registry.gbif.org/organization/605d693a-f335-44fb-b6cf-3ac49842358e)
- Publishing country: BRAZIL
- Installation: [speciesLink Network / INCT-HVFF IPT](https://registry.gbif.org/installation/b38ff2b7-c8af-454e-b5af-ee760f0d5bca)
- Number of occurrences indexed for this dataset at the time of the issue: 8114
- Cause: GBIF IDs hit maximum allowed - 50%, duplicates - 100%, total records count 3, absent records count 3
- Pipelines execution steps: [http://api.gbif.org/v1/pipelines/history/execution/3095431/step](http://api.gbif.org/v1/pipelines/history/execution/3095431/step)
<details>
<summary>Publisher email</summary>

Hello,

I am contacting you from the GBIF Secretariat about a dataset published by the [HUTO - Herbário da Universidade de Tocantins](https://registry.gbif.org/dataset/965b5ae5-7b2d-4155-a7ff-e9e496d70f90) : https://doi.org/10.15468/zhlmlh.
We noticed that the occurrenceIDs were changed. We have temporarily paused the ingestions of this dataset.

As you might already know, when an occurrence record has a new occurrenceID for a given dataset, our system considers it to be a new occurrence.
This means that it will be given a new gbifid and a new occurrence URL (like this one: https://www.gbif.org/occurrence/1252968762) and the old gbifid and URL will be deprecated.

In this case, this means that the occurrence URLs would be deprecated when ingesting the newest versions of these datasets.

We would like to check with you if those changes were intentional. Do you know if this is the case?
Please let us know, thanks! We are happy to resume the dataset ingestion.

Note that some users rely on those occurrence URLs and gbifids (like https://bionomia.net for example). In an attempt to improve
the stability of the occurrence URLs and gbifids, we have implemented a warning system to detect these type of changes in datasets (see this news item).
If the data publisher can provide us with a list of old and new occurrenceIDs per record, we can avoid the identifier and URL changes. Could that be an option?

Please let us know if you have any question. Thanks!

All the best,

</details>


You can skip/fix identifier validation using [the registry UI](https://registry.gbif.org/dataset/965b5ae5-7b2d-4155-a7ff-e9e496d70f90/ingestion-history).

**Comment by gbif-pipelines** [comment]
Identifier validation still  failing for the dataset [HUTO - Herbário da Universidade de Tocantins](https://registry.gbif.org/dataset/965b5ae5-7b2d-4155-a7ff-e9e496d70f90):
- Crawler attempt: 395
- Publishing organization: [Fundação Universidade do Tocantins](https://registry.gbif.org/organization/605d693a-f335-44fb-b6cf-3ac49842358e)
- Publishing country: BRAZIL
- Installation: [speciesLink Network / INCT-HVFF IPT](https://registry.gbif.org/installation/b38ff2b7-c8af-454e-b5af-ee760f0d5bca)
- Number of occurrences indexed for this dataset at the time of the issue: 8114
- Cause: GBIF IDs hit maximum allowed - 50%, duplicates - 100%, total records count 3, absent records count 3
- Pipelines execution steps: [http://api.gbif.org/v1/pipelines/history/execution/3107679/step](http://api.gbif.org/v1/pipelines/history/execution/3107679/step)
<details>
<summary>Publisher email</summary>

Hello,

I am contacting you from the GBIF Secretariat about a dataset published by the [HUTO - Herbário da Universidade de Tocantins](https://registry.gbif.org/dataset/965b5ae5-7b2d-4155-a7ff-e9e496d70f90) : https://doi.org/10.15468/zhlmlh.
We noticed that the occurrenceIDs were changed. We have temporarily paused the ingestions of this dataset.

As you might already know, when an occurrence record has a new occurrenceID for a given dataset, our system considers it to be a new occurrence.
This means that it will be given a new gbifid and a new occurrence URL (like this one: https://www.gbif.org/occurrence/1252968762) and the old gbifid and URL will be deprecated.

In this case, this means that the occurrence URLs would be deprecated when ingesting the newest versions of these datasets.

We would like to check with you if those changes were intentional. Do you know if this is the case?
Please let us know, thanks! We are happy to resume the dataset ingestion.

Note that some users rely on those occurrence URLs and gbifids (like https://bionomia.net for example). In an attempt to improve
the stability of the occurrence URLs and gbifids, we have implemented a warning system to detect these type of changes in datasets (see this news item).
If the data publisher can provide us with a list of old and new occurrenceIDs per record, we can avoid the identifier and URL changes. Could that be an option?

Please let us know if you have any question. Thanks!

All the best,

</details>


You can skip/fix identifier validation using [the registry UI](https://registry.gbif.org/dataset/965b5ae5-7b2d-4155-a7ff-e9e496d70f90/ingestion-history).

**Comment by gbif-pipelines** [comment]
Identifier validation still  failing for the dataset [HUTO - Herbário da Universidade de Tocantins](https://registry.gbif.org/dataset/965b5ae5-7b2d-4155-a7ff-e9e496d70f90):
- Crawler attempt: 396
- Publishing organization: [Fundação Universidade do Tocantins](https://registry.gbif.org/organization/605d693a-f335-44fb-b6cf-3ac49842358e)
- Publishing country: BRAZIL
- Installation: [speciesLink Network / INCT-HVFF IPT](https://registry.gbif.org/installation/b38ff2b7-c8af-454e-b5af-ee760f0d5bca)
- Number of occurrences indexed for this dataset at the time of the issue: 8114
- Cause: GBIF ID problems exceed 50% threshold: 100% duplicates; 3 total records; 3 absent records
- Pipelines execution steps: [http://api.gbif.org/v1/pipelines/history/execution/3182077/step](http://api.gbif.org/v1/pipelines/history/execution/3182077/step)
<details>
<summary>Publisher email</summary>

Hello,

I am contacting you from the GBIF Secretariat about a dataset published by the [HUTO - Herbário da Universidade de Tocantins](https://registry.gbif.org/dataset/965b5ae5-7b2d-4155-a7ff-e9e496d70f90) : https://doi.org/10.15468/zhlmlh.
We noticed that the occurrenceIDs were changed. We have temporarily paused the ingestions of this dataset.

As you might already know, when an occurrence record has a new occurrenceID for a given dataset, our system considers it to be a new occurrence.
This means that it will be given a new gbifid and a new occurrence URL (like this one: https://www.gbif.org/occurrence/1252968762) and the old gbifid and URL will be deprecated.

In this case, this means that the occurrence URLs would be deprecated when ingesting the newest versions of these datasets.

We would like to check with you if those changes were intentional. Do you know if this is the case?
Please let us know, thanks! We are happy to resume the dataset ingestion.

Note that some users rely on those occurrence URLs and gbifids (like https://bionomia.net for example). In an attempt to improve
the stability of the occurrence URLs and gbifids, we have implemented a warning system to detect these type of changes in datasets (see this news item).
If the data publisher can provide us with a list of old and new occurrenceIDs per record, we can avoid the identifier and URL changes. Could that be an option?

Please let us know if you have any question. Thanks!

All the best,

</details>


You can skip/fix identifier validation using [the registry UI](https://registry.gbif.org/dataset/965b5ae5-7b2d-4155-a7ff-e9e496d70f90/ingestion-history).

**Comment by gbif-pipelines** [comment]
Identifier validation still  failing for the dataset [HUTO - Herbário da Universidade de Tocantins](https://registry.gbif.org/dataset/965b5ae5-7b2d-4155-a7ff-e9e496d70f90):
- Crawler attempt: 397
- Publishing organization: [Fundação Universidade do Tocantins](https://registry.gbif.org/organization/605d693a-f335-44fb-b6cf-3ac49842358e)
- Publishing country: BRAZIL
- Installation: [speciesLink Network / INCT-HVFF IPT](https://registry.gbif.org/installation/b38ff2b7-c8af-454e-b5af-ee760f0d5bca)
- Number of occurrences indexed for this dataset at the time of the issue: 8114
- Cause: GBIF ID problems exceed 50% threshold: 100% duplicates; 3 total records; 3 absent records
- Pipelines execution steps: [http://api.gbif.org/v1/pipelines/history/execution/3255998/step](http://api.gbif.org/v1/pipelines/history/execution/3255998/step)
<details>
<summary>Publisher email</summary>

Hello,

I am contacting you from the GBIF Secretariat about a dataset published by the [HUTO - Herbário da Universidade de Tocantins](https://registry.gbif.org/dataset/965b5ae5-7b2d-4155-a7ff-e9e496d70f90) : https://doi.org/10.15468/zhlmlh.
We noticed that the occurrenceIDs were changed. We have temporarily paused the ingestions of this dataset.

As you might already know, when an occurrence record has a new occurrenceID for a given dataset, our system considers it to be a new occurrence.
This means that it will be given a new gbifid and a new occurrence URL (like this one: https://www.gbif.org/occurrence/1252968762) and the old gbifid and URL will be deprecated.

In this case, this means that the occurrence URLs would be deprecated when ingesting the newest versions of these datasets.

We would like to check with you if those changes were intentional. Do you know if this is the case?
Please let us know, thanks! We are happy to resume the dataset ingestion.

Note that some users rely on those occurrence URLs and gbifids (like https://bionomia.net for example). In an attempt to improve
the stability of the occurrence URLs and gbifids, we have implemented a warning system to detect these type of changes in datasets (see this news item).
If the data publisher can provide us with a list of old and new occurrenceIDs per record, we can avoid the identifier and URL changes. Could that be an option?

Please let us know if you have any question. Thanks!

All the best,

</details>


You can skip/fix identifier validation using [the registry UI](https://registry.gbif.org/dataset/965b5ae5-7b2d-4155-a7ff-e9e496d70f90/ingestion-history).
