### ISSUE TITLE
Identifiers validation failed for dataset Seabirds in Norway - Estimated population sizes (SEAPOP)

### ISSUE THREAD

**Issue by gbif-pipelines** [gbif/ingestion-management#944]
Identifier validation failed for the dataset [Seabirds in Norway - Estimated population sizes (SEAPOP)](https://registry.gbif.org/dataset/9801530f-ab2f-4913-9050-d7239d12aed0):
- Crawler attempt: 299
- Publishing organization: [Norwegian Institute for Nature Research](https://registry.gbif.org/organization/46fec380-8e1d-11dd-8679-b8a03c50a862)
- Publishing country: NORWAY
- Installation: [NINA IPT service](https://registry.gbif.org/installation/e312f477-a9ba-485e-8c1c-700868a0bfb7)
- Number of occurrences indexed for this dataset at the time of the issue: 20191
- Cause: GBIF ID problems exceed 50% threshold: 100% duplicates; 20176 total records; 20176 absent records
- Pipelines execution steps: [http://api.gbif.org/v1/pipelines/history/execution/3412657/step](http://api.gbif.org/v1/pipelines/history/execution/3412657/step)

```
New IDs sample:


```

```
Old IDs sample:

17
12
15
1
25
18
8
7
5
20
```

<details>
<summary>Publisher email</summary>

Hello,

I am contacting you from the GBIF Secretariat about a dataset published by the [Seabirds in Norway - Estimated population sizes (SEAPOP)](https://registry.gbif.org/dataset/9801530f-ab2f-4913-9050-d7239d12aed0) : https://doi.org/10.15468/vomcvi.
We noticed that the occurrenceIDs were changed. We have temporarily paused the ingestions of this dataset.

As you might already know, when an occurrence record has a new occurrenceID for a given dataset, our system considers it to be a new occurrence.
This means that it will be given a new gbifid and a new occurrence URL (like this one: https://www.gbif.org/occurrence/1252968762) and the old gbifid and URL will be deprecated.

In this case, this means that the occurrence URLs would be deprecated when ingesting the newest versions of these datasets.

We would like to check with you if those changes were intentional. Do you know if this is the case?
Please let us know, thanks! We are happy to resume the dataset ingestion.

Note that some users rely on those occurrence URLs and gbifids (like https://bionomia.net for example). In an attempt to improve
the stability of the occurrence URLs and gbifids, we have implemented a warning system to detect these type of changes in datasets (see this news item).
If the data publisher can provide us with a list of old and new occurrenceIDs per record, we can avoid the identifier and URL changes. Could that be an option?

Please let us know if you have any question. Thanks!

All the best,

</details>

You can skip/fix identifier validation using [the registry UI](https://registry.gbif.org/dataset/9801530f-ab2f-4913-9050-d7239d12aed0/ingestion-history).

**Comment by ManonGros** [comment]
The observations are machine observation and the change of ID went from integers to actual identifiers like "1375C07C-77A9-44C5-A874-0003971A6EC8" so I believe the change was intentional and I doubt they will have documented to ID change.
