### ISSUE TITLE
Identifiers validation failed for dataset Occurrences of pinnipeds (Carnivora, Phocidae) in the Azores archipelago (Portugal)

### ISSUE THREAD

**Issue by gbif-pipelines** [gbif/ingestion-management#945]
Identifier validation failed for the dataset [Occurrences of pinnipeds (Carnivora, Phocidae) in the Azores archipelago (Portugal)](https://registry.gbif.org/dataset/ae7484b9-9372-4191-a0d6-384454a98895):
- Crawler attempt: 60
- Publishing organization: [Universidade dos Açores](https://registry.gbif.org/organization/0a80feca-b411-428a-a34e-c5c2fa07cdba)
- Publishing country: PORTUGAL
- Installation: [GBIF Portugal IPT](https://registry.gbif.org/installation/06d75b22-fc7a-42ff-a14f-65a25cd0f3ab)
- Number of occurrences indexed for this dataset at the time of the issue: 34
- Cause: GBIF ID problems exceed 50% threshold: 100% duplicates; 34 total records; 34 absent records
- Pipelines execution steps: [http://api.gbif.org/v1/pipelines/history/execution/3413235/step](http://api.gbif.org/v1/pipelines/history/execution/3413235/step)

```
New IDs sample:


```

```
Old IDs sample:

UAcAZBIOP-GBAspList-MarMalPhoc-RACA_22
UAcAZBIOP-GBAspList-MarMalPhoc-RACA_23
UAcAZBIOP-GBAspList-MarMalPhoc-RACA_24
UAcAZBIOP-GBAspList-MarMalPhoc-RACA_25
UAcAZBIOP-GBAspList-MarMalPhoc-RACA_20
UAcAZBIOP-GBAspList-MarMalPhoc-RACA_19
UAcAZBIOP-GBAspList-MarMalPhoc-RACA_16
UAcAZBIOP-GBAspList-MarMalPhoc-RACA_18
UAcAZBIOP-GBAspList-MarMalPhoc-RACA_15
UAcAZBIOP-GBAspList-MarMalPhoc-RACA_12
```

<details>
<summary>Publisher email</summary>

Hello,

I am contacting you from the GBIF Secretariat about a dataset published by the [Occurrences of pinnipeds (Carnivora, Phocidae) in the Azores archipelago (Portugal)](https://registry.gbif.org/dataset/ae7484b9-9372-4191-a0d6-384454a98895) : https://doi.org/10.15468/7amx5z.
We noticed that the occurrenceIDs were changed. We have temporarily paused the ingestions of this dataset.

As you might already know, when an occurrence record has a new occurrenceID for a given dataset, our system considers it to be a new occurrence.
This means that it will be given a new gbifid and a new occurrence URL (like this one: https://www.gbif.org/occurrence/1252968762) and the old gbifid and URL will be deprecated.

In this case, this means that the occurrence URLs would be deprecated when ingesting the newest versions of these datasets.

We would like to check with you if those changes were intentional. Do you know if this is the case?
Please let us know, thanks! We are happy to resume the dataset ingestion.

Note that some users rely on those occurrence URLs and gbifids (like https://bionomia.net for example). In an attempt to improve
the stability of the occurrence URLs and gbifids, we have implemented a warning system to detect these type of changes in datasets (see this news item).
If the data publisher can provide us with a list of old and new occurrenceIDs per record, we can avoid the identifier and URL changes. Could that be an option?

Please let us know if you have any question. Thanks!

All the best,

</details>

You can skip/fix identifier validation using [the registry UI](https://registry.gbif.org/dataset/ae7484b9-9372-4191-a0d6-384454a98895/ingestion-history).

**Comment by ManonGros** [comment]
From the IPT comments, it looks like the changes (which were made a year ago) were intentional: http://ipt.gbif.pt/ipt/resource?r=phocidae_azores
