### ISSUE TITLE
Identifiers validation failed for dataset Bongo Zooplankton Data from the R/V TINRO, NOAA Bell M. Shimada, F/V Northwest Explorer and R/V CCGS Sir John Franklin during the 2022 International Year of the Salmon Pan-Pacific Winter High Seas Expedition

### ISSUE THREAD

**Issue by gbif-pipelines** [gbif/ingestion-management#947]
Identifier validation failed for the dataset [Bongo Zooplankton Data from the R/V TINRO, NOAA Bell M. Shimada, F/V Northwest Explorer and R/V CCGS Sir John Franklin during the 2022 International Year of the Salmon Pan-Pacific Winter High Seas Expedition](https://registry.gbif.org/dataset/e45afc03-4897-4bdf-ade1-bc07198674e7):
- Crawler attempt: 54
- Publishing organization: [Hakai Institute](https://registry.gbif.org/organization/55897143-3f69-42f1-810d-ae94b55fde24)
- Publishing country: CANADA
- Installation: [OBIS Canada](https://registry.gbif.org/installation/5ff1c992-5c84-40aa-bd9a-c1743a870c32)
- Number of occurrences indexed for this dataset at the time of the issue: 6568
- Cause: GBIF ID problems exceed 50% threshold: 100% duplicates; 7006 total records; 7006 absent records
- Pipelines execution steps: [http://api.gbif.org/v1/pipelines/history/execution/3417340/step](http://api.gbif.org/v1/pipelines/history/execution/3417340/step)

```
New IDs sample:


```

```
Old IDs sample:

IYS2022-Shimada-4-10-Bongo-1-114
IYS2022-Shimada-4-10-Bongo-1-115
IYS2022-Shimada-4-10-Bongo-1-116
IYS2022-Shimada-4-10-Bongo-1-117
IYS2022-Shimada-4-10-Bongo-1-118
IYS2022-Shimada-4-10-Bongo-1-119
IYS2022-Shimada-4-10-Bongo-1-120
IYS2022-Shimada-4-10-Bongo-1-121
IYS2022-Shimada-4-10-Bongo-1-122
IYS2022-Shimada-4-10-Bongo-1-123
```

<details>
<summary>Publisher email</summary>

Hello,

I am contacting you from the GBIF Secretariat about a dataset published by the [Bongo Zooplankton Data from the R/V TINRO, NOAA Bell M. Shimada, F/V Northwest Explorer and R/V CCGS Sir John Franklin during the 2022 International Year of the Salmon Pan-Pacific Winter High Seas Expedition](https://registry.gbif.org/dataset/e45afc03-4897-4bdf-ade1-bc07198674e7) : https://doi.org/10.21966/ymv6-8024.
We noticed that the occurrenceIDs were changed. We have temporarily paused the ingestions of this dataset.

As you might already know, when an occurrence record has a new occurrenceID for a given dataset, our system considers it to be a new occurrence.
This means that it will be given a new gbifid and a new occurrence URL (like this one: https://www.gbif.org/occurrence/1252968762) and the old gbifid and URL will be deprecated.

In this case, this means that the occurrence URLs would be deprecated when ingesting the newest versions of these datasets.

We would like to check with you if those changes were intentional. Do you know if this is the case?
Please let us know, thanks! We are happy to resume the dataset ingestion.

Note that some users rely on those occurrence URLs and gbifids (like https://bionomia.net for example). In an attempt to improve
the stability of the occurrence URLs and gbifids, we have implemented a warning system to detect these type of changes in datasets (see this news item).
If the data publisher can provide us with a list of old and new occurrenceIDs per record, we can avoid the identifier and URL changes. Could that be an option?

Please let us know if you have any question. Thanks!

All the best,

</details>

You can skip/fix identifier validation using [the registry UI](https://registry.gbif.org/dataset/e45afc03-4897-4bdf-ade1-bc07198674e7/ingestion-history).

**Comment by ManonGros** [comment]
It doesn't look like they kept track of their samples, only the sampling events. I am letting the dataset be ingested.
