### ISSUE TITLE
Identifiers validation failed for dataset International Barcode of Life project (iBOL)

### ISSUE THREAD

**Issue by gbif-pipelines** [gbif/ingestion-management#952]
Identifier validation failed for the dataset [International Barcode of Life project (iBOL)](https://registry.gbif.org/dataset/040c5662-da76-4782-a48e-cdea1892d14c):
- Crawler attempt: 320
- Publishing organization: [The International Barcode of Life Consortium](https://registry.gbif.org/organization/b3bf3a83-1f68-4541-a03f-330d30d567f5)
- Publishing country: UNKNOWN
- Installation: [GBIF Hosted Datasets](https://registry.gbif.org/installation/fb5e4c2a-579c-434b-a446-3a665dd732ad)
- Number of occurrences indexed for this dataset at the time of the issue: 9763216
- Cause: GBIF ID problems exceed 50% threshold: 100% duplicates; 13931772 total records; 13931772 absent records
- Pipelines execution steps: [http://api.gbif.org/v1/pipelines/history/execution/3426727/step](http://api.gbif.org/v1/pipelines/history/execution/3426727/step)

```
New IDs sample:


```

```
Old IDs sample:

http://bins.boldsystems.org/index.php/Public_RecordView?processid=AUCER001-22
http://bins.boldsystems.org/index.php/Public_RecordView?processid=BCHYM19493-22
http://bins.boldsystems.org/index.php/Public_RecordView?processid=EUGCO361-22
http://bins.boldsystems.org/index.php/Public_RecordView?processid=EUGCO362-22
http://bins.boldsystems.org/index.php/Public_RecordView?processid=EUGCO363-22
http://bins.boldsystems.org/index.php/Public_RecordView?processid=EUGCO370-22
http://bins.boldsystems.org/index.php/Public_RecordView?processid=EUGCO371-22
http://bins.boldsystems.org/index.php/Public_RecordView?processid=EUGCO372-22
http://bins.boldsystems.org/index.php/Public_RecordView?processid=EUGCO453-22
http://bins.boldsystems.org/index.php/Public_RecordView?processid=EUGCO454-22
```

<details>
<summary>Publisher email</summary>

Hello,

I am contacting you from the GBIF Secretariat about a dataset published by the [International Barcode of Life project (iBOL)](https://registry.gbif.org/dataset/040c5662-da76-4782-a48e-cdea1892d14c) : https://doi.org/10.15468/inygc6.
We noticed that the occurrenceIDs were changed. We have temporarily paused the ingestions of this dataset.

As you might already know, when an occurrence record has a new occurrenceID for a given dataset, our system considers it to be a new occurrence.
This means that it will be given a new gbifid and a new occurrence URL (like this one: https://www.gbif.org/occurrence/1252968762) and the old gbifid and URL will be deprecated.

In this case, this means that the occurrence URLs would be deprecated when ingesting the newest versions of these datasets.

We would like to check with you if those changes were intentional. Do you know if this is the case?
Please let us know, thanks! We are happy to resume the dataset ingestion.

Note that some users rely on those occurrence URLs and gbifids (like https://bionomia.net for example). In an attempt to improve
the stability of the occurrence URLs and gbifids, we have implemented a warning system to detect these type of changes in datasets (see this news item).
If the data publisher can provide us with a list of old and new occurrenceIDs per record, we can avoid the identifier and URL changes. Could that be an option?

Please let us know if you have any question. Thanks!

All the best,

</details>

You can skip/fix identifier validation using [the registry UI](https://registry.gbif.org/dataset/040c5662-da76-4782-a48e-cdea1892d14c/ingestion-history).

**Comment by ManonGros** [comment]
Hi @thomasstjerne, it looks like the iBOL identifiers aren't the same as in the previous versions.

Actually, when downloading the file accessible from the endpoint, I have only got something called `dna.txt` which doesn't seem to have much else than some sequences.  Is it expected? Could you take a look?

**Comment by thomasstjerne** [comment]
Hi @ManonGros 
Yes, based on requests, I have moved away from full URIs as identifiers. These are instead given in `http://purl.org/dc/terms/references`

So that 
`http://bins.boldsystems.org/index.php/Public_RecordView?processid=AUCER001-22
http://bins.boldsystems.org/index.php/Public_RecordView?processid=BCHYM19493-22
http://bins.boldsystems.org/index.php/Public_RecordView?processid=EUGCO361-22
http://bins.boldsystems.org/index.php/Public_RecordView?processid=EUGCO362-22`

Will now be

```
AUCER001-22
BCHYM19493-22
EUGCO361-22
EUGCO362-22
```

There a full ingestion from the same endpoint available in UAT: https://www.gbif-uat.org/dataset/040c5662-da76-4782-a48e-cdea1892d14c

**Comment by gbif-pipelines** [comment]
Identifier validation still  failing for the dataset [International Barcode of Life project (iBOL)](https://registry.gbif.org/dataset/040c5662-da76-4782-a48e-cdea1892d14c):
- Crawler attempt: 322
- Publishing organization: [The International Barcode of Life Consortium](https://registry.gbif.org/organization/b3bf3a83-1f68-4541-a03f-330d30d567f5)
- Publishing country: UNKNOWN
- Installation: [GBIF Hosted Datasets](https://registry.gbif.org/installation/fb5e4c2a-579c-434b-a446-3a665dd732ad)
- Number of occurrences indexed for this dataset at the time of the issue: 9763216
- Cause: GBIF ID problems exceed 50% threshold: 100% duplicates; 16073128 total records; 16073128 absent records
- Pipelines execution steps: [http://api.gbif.org/v1/pipelines/history/execution/3457887/step](http://api.gbif.org/v1/pipelines/history/execution/3457887/step)

```
New IDs sample:


```


```
Old IDs sample:

http://bins.boldsystems.org/index.php/Public_RecordView?processid=AUCER001-22
http://bins.boldsystems.org/index.php/Public_RecordView?processid=BCHYM19493-22
http://bins.boldsystems.org/index.php/Public_RecordView?processid=EUGCO361-22
http://bins.boldsystems.org/index.php/Public_RecordView?processid=EUGCO362-22
http://bins.boldsystems.org/index.php/Public_RecordView?processid=EUGCO363-22
http://bins.boldsystems.org/index.php/Public_RecordView?processid=EUGCO370-22
http://bins.boldsystems.org/index.php/Public_RecordView?processid=EUGCO371-22
http://bins.boldsystems.org/index.php/Public_RecordView?processid=EUGCO372-22
http://bins.boldsystems.org/index.php/Public_RecordView?processid=EUGCO453-22
http://bins.boldsystems.org/index.php/Public_RecordView?processid=EUGCO454-22
```

<details>
<summary>Publisher email</summary>

Hello,

I am contacting you from the GBIF Secretariat about a dataset published by the [International Barcode of Life project (iBOL)](https://registry.gbif.org/dataset/040c5662-da76-4782-a48e-cdea1892d14c) : https://doi.org/10.15468/inygc6.
We noticed that the occurrenceIDs were changed. We have temporarily paused the ingestions of this dataset.

As you might already know, when an occurrence record has a new occurrenceID for a given dataset, our system considers it to be a new occurrence.
This means that it will be given a new gbifid and a new occurrence URL (like this one: https://www.gbif.org/occurrence/1252968762) and the old gbifid and URL will be deprecated.

In this case, this means that the occurrence URLs would be deprecated when ingesting the newest versions of these datasets.

We would like to check with you if those changes were intentional. Do you know if this is the case?
Please let us know, thanks! We are happy to resume the dataset ingestion.

Note that some users rely on those occurrence URLs and gbifids (like https://bionomia.net for example). In an attempt to improve
the stability of the occurrence URLs and gbifids, we have implemented a warning system to detect these type of changes in datasets (see this news item).
If the data publisher can provide us with a list of old and new occurrenceIDs per record, we can avoid the identifier and URL changes. Could that be an option?

Please let us know if you have any question. Thanks!

All the best,

</details>


You can skip/fix identifier validation using [the registry UI](https://registry.gbif.org/dataset/040c5662-da76-4782-a48e-cdea1892d14c/ingestion-history).

**Comment by ManonGros** [comment]
Thanks @dshorthouse I am working on it but it takes a lot of time for our script to run, I hope to be done today but the occurrences won't be back until next week.

**Comment by dshorthouse** [comment]
Thanks @ManonGros @thomasstjerne. I'll try again next week.

**Comment by ManonGros** [comment]
@dshorthouse I have migrated the identifiers but as Thomas mentioned, we have a decrease in 0.6 M occurrences so I assume a number of attribution will still be broken. I am sorry. Not sure if this can be fixed.

**Comment by dshorthouse** [comment]
Noted, @ManonGros. I assume the folks at iBOL have been made aware of the implications and have chosen to accept the outcome?

**Comment by ManonGros** [comment]
Thanks David, I hope we can fix it.
@thomasstjerne is there a way we could get back the iBOL occurrences?

**Comment by dshorthouse** [comment]
Thanks all for having a deeper look. I've retained the lost occurrences at GBIF's end for the upcoming refresh of data at Bionomia's end. But, unless they can be restored, this is merely a short term solution until the next refresh in a few weeks. Hope these can be recovered.

**Comment by thomasstjerne** [comment]
I have contacted the BOLD support by email about this.
