### ISSUE TITLE
Identifiers validation failed for dataset Ian Watkinson Lepidoptera Collection

### ISSUE THREAD

**Issue by gbif-pipelines** [gbif/ingestion-management#959]
Identifier validation failed for the dataset [Ian Watkinson Lepidoptera Collection](https://registry.gbif.org/dataset/d0fc71de-dba4-48d1-8103-26c10f983a28):
- Crawler attempt: 28
- Publishing organization: [Arizona State University Biocollections](https://registry.gbif.org/organization/814cdfb5-d4f8-4453-815f-ea5df98e76bf)
- Publishing country: UNITED_STATES
- Installation: [Ecdysis](https://registry.gbif.org/installation/3056a1fb-d172-4927-8f52-92246f9c768b)
- Number of occurrences indexed for this dataset at the time of the issue: 1
- Cause: GBIF ID problems exceed 50% threshold: 100% duplicates; 181 total records; 181 absent records
- Pipelines execution steps: [http://api.gbif.org/v1/pipelines/history/execution/3457994/step](http://api.gbif.org/v1/pipelines/history/execution/3457994/step)

```
New IDs sample:


```

```
Old IDs sample:

273be976-7d27-4fbb-af08-4450de553b00
```

<details>
<summary>Publisher email</summary>

Hello,

I am contacting you from the GBIF Secretariat about a dataset published by the [Ian Watkinson Lepidoptera Collection](https://registry.gbif.org/dataset/d0fc71de-dba4-48d1-8103-26c10f983a28) : https://doi.org/10.15468/c89mz7.
We noticed that the occurrenceIDs were changed. We have temporarily paused the ingestions of this dataset.

As you might already know, when an occurrence record has a new occurrenceID for a given dataset, our system considers it to be a new occurrence.
This means that it will be given a new gbifid and a new occurrence URL (like this one: https://www.gbif.org/occurrence/1252968762) and the old gbifid and URL will be deprecated.

In this case, this means that the occurrence URLs would be deprecated when ingesting the newest versions of these datasets.

We would like to check with you if those changes were intentional. Do you know if this is the case?
Please let us know, thanks! We are happy to resume the dataset ingestion.

Note that some users rely on those occurrence URLs and gbifids (like https://bionomia.net for example). In an attempt to improve
the stability of the occurrence URLs and gbifids, we have implemented a warning system to detect these type of changes in datasets (see this news item).
If the data publisher can provide us with a list of old and new occurrenceIDs per record, we can avoid the identifier and URL changes. Could that be an option?

Please let us know if you have any question. Thanks!

All the best,

</details>

You can skip/fix identifier validation using [the registry UI](https://registry.gbif.org/dataset/d0fc71de-dba4-48d1-8103-26c10f983a28/ingestion-history).

**Comment by ManonGros** [comment]
The data went from one record to 181. I let the ingestion through.
