### ISSUE TITLE
Identifiers validation failed for dataset Registros de ectoparásitos para la detección de patógenos emergentes (SARS-CoV-2) y re-emergentes (Rickettsias) en caninos procedentes del departamento de Santander

### ISSUE THREAD

**Issue by gbif-pipelines** [gbif/ingestion-management#966]
Identifier validation failed for the dataset [Registros de ectoparásitos para la detección de patógenos emergentes (SARS-CoV-2) y re-emergentes (Rickettsias) en caninos procedentes del departamento de Santander](https://registry.gbif.org/dataset/17e160c4-11ea-432e-95af-d65e84ec5953):
- Crawler attempt: 73
- Publishing organization: [Universidad de Santander - UDES](https://registry.gbif.org/organization/112087f6-a6c0-4cee-8441-387f900d34f9)
- Publishing country: COLOMBIA
- Installation: [Datos sobre Biodiversidad de Colombia](https://registry.gbif.org/installation/68845aab-a453-4816-b36d-a3ec8455deb0)
- Number of occurrences indexed for this dataset at the time of the issue: 17
- Cause: GBIF ID problems exceed 50% threshold: 100% duplicates; 151 total records; 151 absent records
- Pipelines execution steps: [http://api.gbif.org/v1/pipelines/history/execution/3468418/step](http://api.gbif.org/v1/pipelines/history/execution/3468418/step)

```
New IDs sample:


```

```
Old IDs sample:

UDES:EctoparásitosRickettsias:UDES65
UDES:EctoparásitosRickettsias:UDES66
UDES:EctoparásitosRickettsias:UDES67
UDES:EctoparásitosRickettsias:UDES68
UDES:EctoparásitosRickettsias:UDES69
UDES:EctoparásitosRickettsias:UDES70
UDES:EctoparásitosRickettsias:UDES71
UDES:EctoparásitosRickettsias:UDES72
UDES:EctoparásitosRickettsias:UDES73
UDES:EctoparásitosRickettsias:UDES74
```

<details>
<summary>Publisher email</summary>

Hello,

I am contacting you from the GBIF Secretariat about a dataset published by the [Registros de ectoparásitos para la detección de patógenos emergentes (SARS-CoV-2) y re-emergentes (Rickettsias) en caninos procedentes del departamento de Santander](https://registry.gbif.org/dataset/17e160c4-11ea-432e-95af-d65e84ec5953) : https://doi.org/10.15472/kbnkvn.
We noticed that the occurrenceIDs were changed. We have temporarily paused the ingestions of this dataset.

As you might already know, when an occurrence record has a new occurrenceID for a given dataset, our system considers it to be a new occurrence.
This means that it will be given a new gbifid and a new occurrence URL (like this one: https://www.gbif.org/occurrence/1252968762) and the old gbifid and URL will be deprecated.

In this case, this means that the occurrence URLs would be deprecated when ingesting the newest versions of these datasets.

We would like to check with you if those changes were intentional. Do you know if this is the case?
Please let us know, thanks! We are happy to resume the dataset ingestion.

Note that some users rely on those occurrence URLs and gbifids (like https://bionomia.net for example). In an attempt to improve
the stability of the occurrence URLs and gbifids, we have implemented a warning system to detect these type of changes in datasets (see this news item).
If the data publisher can provide us with a list of old and new occurrenceIDs per record, we can avoid the identifier and URL changes. Could that be an option?

Please let us know if you have any question. Thanks!

All the best,

</details>

You can skip/fix identifier validation using [the registry UI](https://registry.gbif.org/dataset/17e160c4-11ea-432e-95af-d65e84ec5953/ingestion-history).

**Comment by EstebanMH-SiB** [comment]
We did some small changes in a superscript dot, here is the file to map the old and new occurrenceIDs
[ChangeOccurrenceID_UDES_Ectoparasitos.txt](https://github.com/gbif/ingestion-management/files/13661316/ChangeOccurrenceID_UDES_Ectoparasitos.txt)

**Comment by gbif-pipelines** [comment]
Identifier validation still  failing for the dataset [Registros de ectoparásitos para la detección de patógenos emergentes (SARS-CoV-2) y re-emergentes (Rickettsias) en caninos procedentes del departamento de Santander](https://registry.gbif.org/dataset/17e160c4-11ea-432e-95af-d65e84ec5953):
- Crawler attempt: 74
- Publishing organization: [Universidad de Santander - UDES](https://registry.gbif.org/organization/112087f6-a6c0-4cee-8441-387f900d34f9)
- Publishing country: COLOMBIA
- Installation: [Datos sobre Biodiversidad de Colombia](https://registry.gbif.org/installation/68845aab-a453-4816-b36d-a3ec8455deb0)
- Number of occurrences indexed for this dataset at the time of the issue: 17
- Cause: GBIF ID problems exceed 50% threshold: 89% duplicates; 151 total records; 135 absent records
- Pipelines execution steps: [http://api.gbif.org/v1/pipelines/history/execution/3480026/step](http://api.gbif.org/v1/pipelines/history/execution/3480026/step)

```
New IDs sample:

UDES:EctoparasitosRickettsias:UDES75
UDES:EctoparasitosRickettsias:UDES70
UDES:EctoparasitosRickettsias:UDES74
UDES:EctoparasitosRickettsias:UDES77
UDES:EctoparasitosRickettsias:UDES73
UDES:EctoparasitosRickettsias:UDES71
UDES:EctoparasitosRickettsias:UDES72
UDES:EctoparasitosRickettsias:UDES81
UDES:EctoparasitosRickettsias:UDES66
UDES:EctoparasitosRickettsias:UDES69
```


```
Old IDs sample:

UDES:EctoparásitosRickettsias:UDES65
UDES:EctoparásitosRickettsias:UDES66
UDES:EctoparásitosRickettsias:UDES67
UDES:EctoparásitosRickettsias:UDES68
UDES:EctoparásitosRickettsias:UDES69
UDES:EctoparásitosRickettsias:UDES70
UDES:EctoparásitosRickettsias:UDES71
UDES:EctoparásitosRickettsias:UDES72
UDES:EctoparásitosRickettsias:UDES73
UDES:EctoparásitosRickettsias:UDES74
```

<details>
<summary>Publisher email</summary>

Hello,

I am contacting you from the GBIF Secretariat about a dataset published by the [Registros de ectoparásitos para la detección de patógenos emergentes (SARS-CoV-2) y re-emergentes (Rickettsias) en caninos procedentes del departamento de Santander](https://registry.gbif.org/dataset/17e160c4-11ea-432e-95af-d65e84ec5953) : https://doi.org/10.15472/kbnkvn.
We noticed that the occurrenceIDs were changed. We have temporarily paused the ingestions of this dataset.

As you might already know, when an occurrence record has a new occurrenceID for a given dataset, our system considers it to be a new occurrence.
This means that it will be given a new gbifid and a new occurrence URL (like this one: https://www.gbif.org/occurrence/1252968762) and the old gbifid and URL will be deprecated.

In this case, this means that the occurrence URLs would be deprecated when ingesting the newest versions of these datasets.

We would like to check with you if those changes were intentional. Do you know if this is the case?
Please let us know, thanks! We are happy to resume the dataset ingestion.

Note that some users rely on those occurrence URLs and gbifids (like https://bionomia.net for example). In an attempt to improve
the stability of the occurrence URLs and gbifids, we have implemented a warning system to detect these type of changes in datasets (see this news item).
If the data publisher can provide us with a list of old and new occurrenceIDs per record, we can avoid the identifier and URL changes. Could that be an option?

Please let us know if you have any question. Thanks!

All the best,

</details>


You can skip/fix identifier validation using [the registry UI](https://registry.gbif.org/dataset/17e160c4-11ea-432e-95af-d65e84ec5953/ingestion-history).

**Comment by gbif-pipelines** [comment]
Identifier validation still  failing for the dataset [Registros de ectoparásitos para la detección de patógenos emergentes (SARS-CoV-2) y re-emergentes (Rickettsias) en caninos procedentes del departamento de Santander](https://registry.gbif.org/dataset/17e160c4-11ea-432e-95af-d65e84ec5953):
- Crawler attempt: 75
- Publishing organization: [Universidad de Santander - UDES](https://registry.gbif.org/organization/112087f6-a6c0-4cee-8441-387f900d34f9)
- Publishing country: COLOMBIA
- Installation: [Datos sobre Biodiversidad de Colombia](https://registry.gbif.org/installation/68845aab-a453-4816-b36d-a3ec8455deb0)
- Number of occurrences indexed for this dataset at the time of the issue: 17
- Cause: GBIF ID problems exceed 50% threshold: 89% duplicates; 151 total records; 135 absent records
- Pipelines execution steps: [http://api.gbif.org/v1/pipelines/history/execution/3480027/step](http://api.gbif.org/v1/pipelines/history/execution/3480027/step)

```
New IDs sample:

UDES:EctoparasitosRickettsias:UDES75
UDES:EctoparasitosRickettsias:UDES70
UDES:EctoparasitosRickettsias:UDES74
UDES:EctoparasitosRickettsias:UDES77
UDES:EctoparasitosRickettsias:UDES73
UDES:EctoparasitosRickettsias:UDES71
UDES:EctoparasitosRickettsias:UDES72
UDES:EctoparasitosRickettsias:UDES81
UDES:EctoparasitosRickettsias:UDES66
UDES:EctoparasitosRickettsias:UDES69
```


```
Old IDs sample:

UDES:EctoparásitosRickettsias:UDES65
UDES:EctoparásitosRickettsias:UDES66
UDES:EctoparásitosRickettsias:UDES67
UDES:EctoparásitosRickettsias:UDES68
UDES:EctoparásitosRickettsias:UDES69
UDES:EctoparásitosRickettsias:UDES70
UDES:EctoparásitosRickettsias:UDES71
UDES:EctoparásitosRickettsias:UDES72
UDES:EctoparásitosRickettsias:UDES73
UDES:EctoparásitosRickettsias:UDES74
```

<details>
<summary>Publisher email</summary>

Hello,

I am contacting you from the GBIF Secretariat about a dataset published by the [Registros de ectoparásitos para la detección de patógenos emergentes (SARS-CoV-2) y re-emergentes (Rickettsias) en caninos procedentes del departamento de Santander](https://registry.gbif.org/dataset/17e160c4-11ea-432e-95af-d65e84ec5953) : https://doi.org/10.15472/kbnkvn.
We noticed that the occurrenceIDs were changed. We have temporarily paused the ingestions of this dataset.

As you might already know, when an occurrence record has a new occurrenceID for a given dataset, our system considers it to be a new occurrence.
This means that it will be given a new gbifid and a new occurrence URL (like this one: https://www.gbif.org/occurrence/1252968762) and the old gbifid and URL will be deprecated.

In this case, this means that the occurrence URLs would be deprecated when ingesting the newest versions of these datasets.

We would like to check with you if those changes were intentional. Do you know if this is the case?
Please let us know, thanks! We are happy to resume the dataset ingestion.

Note that some users rely on those occurrence URLs and gbifids (like https://bionomia.net for example). In an attempt to improve
the stability of the occurrence URLs and gbifids, we have implemented a warning system to detect these type of changes in datasets (see this news item).
If the data publisher can provide us with a list of old and new occurrenceIDs per record, we can avoid the identifier and URL changes. Could that be an option?

Please let us know if you have any question. Thanks!

All the best,

</details>


You can skip/fix identifier validation using [the registry UI](https://registry.gbif.org/dataset/17e160c4-11ea-432e-95af-d65e84ec5953/ingestion-history).

**Comment by ManonGros** [comment]
Thanks @EstebanMH-SiB !
I have migrated the identifiers using the file you sent (16 records) and let the ingestion go through for the new occurrences.
