### ISSUE TITLE
Identifiers validation failed for dataset Colección plantas vasculares del Herbario Reinaldo Espinosa (Herbario LOJA) de la Universidad Nacional de Loja

### ISSUE THREAD

**Issue by gbif-pipelines** [gbif/ingestion-management#971]
Identifier validation failed for the dataset [Colección plantas vasculares del Herbario Reinaldo Espinosa (Herbario LOJA) de la Universidad Nacional de Loja](https://registry.gbif.org/dataset/b5a8e29d-cd8c-4e04-90b2-422d900caab6):
- Crawler attempt: 39
- Publishing organization: [Herbario Reinado Espinosa (Herbario LOJA) de la Universidad Nacional de Loja](https://registry.gbif.org/organization/33d232b5-5cc2-4521-8bd6-121c5bb41c32)
- Publishing country: ECUADOR
- Installation: [GBIF Ecuador - MAATE](https://registry.gbif.org/installation/9df8109c-684d-416b-819b-7bc09adc500b)
- Number of occurrences indexed for this dataset at the time of the issue: 19961
- Cause: GBIF ID problems exceed 50% threshold: 55% duplicates; 43388 total records; 23889 absent records
- Pipelines execution steps: [http://api.gbif.org/v1/pipelines/history/execution/3472435/step](http://api.gbif.org/v1/pipelines/history/execution/3472435/step)

```
New IDs sample:

HLOJA-UNL:9635
HLOJA-UNL:8303
HLOJA-UNL:9634
HLOJA-UNL:15830
HLOJA-UNL:9637
HLOJA-UNL:8305
HLOJA-UNL:9636
HLOJA-UNL:8304
HLOJA-UNL:5612
HLOJA-UNL:6946
```

```
Old IDs sample:

HLOJA-UNL:18135
HLOJA-UNL:19235
HLOJA-UNL:19236
HLOJA-UNL:19248
HLOJA-UNL:19256
HLOJA-UNL:19258
HLOJA-UNL:19259
HLOJA-UNL:19260
HLOJA-UNL:19261
HLOJA-UNL:18914
```

<details>
<summary>Publisher email</summary>

Hello,

I am contacting you from the GBIF Secretariat about a dataset published by the [Colección plantas vasculares del Herbario Reinaldo Espinosa (Herbario LOJA) de la Universidad Nacional de Loja](https://registry.gbif.org/dataset/b5a8e29d-cd8c-4e04-90b2-422d900caab6) : https://doi.org/10.60545/u5ji5y.
We noticed that the occurrenceIDs were changed. We have temporarily paused the ingestions of this dataset.

As you might already know, when an occurrence record has a new occurrenceID for a given dataset, our system considers it to be a new occurrence.
This means that it will be given a new gbifid and a new occurrence URL (like this one: https://www.gbif.org/occurrence/1252968762) and the old gbifid and URL will be deprecated.

In this case, this means that the occurrence URLs would be deprecated when ingesting the newest versions of these datasets.

We would like to check with you if those changes were intentional. Do you know if this is the case?
Please let us know, thanks! We are happy to resume the dataset ingestion.

Note that some users rely on those occurrence URLs and gbifids (like https://bionomia.net for example). In an attempt to improve
the stability of the occurrence URLs and gbifids, we have implemented a warning system to detect these type of changes in datasets (see this news item).
If the data publisher can provide us with a list of old and new occurrenceIDs per record, we can avoid the identifier and URL changes. Could that be an option?

Please let us know if you have any question. Thanks!

All the best,

</details>

You can skip/fix identifier validation using [the registry UI](https://registry.gbif.org/dataset/b5a8e29d-cd8c-4e04-90b2-422d900caab6/ingestion-history).

**Comment by gbif-pipelines** [comment]
Identifier validation still  failing for the dataset [Colección plantas vasculares del Herbario Reinaldo Espinosa (Herbario LOJA) de la Universidad Nacional de Loja](https://registry.gbif.org/dataset/b5a8e29d-cd8c-4e04-90b2-422d900caab6):
- Crawler attempt: 39
- Publishing organization: [Herbario Reinado Espinosa (Herbario LOJA) de la Universidad Nacional de Loja](https://registry.gbif.org/organization/33d232b5-5cc2-4521-8bd6-121c5bb41c32)
- Publishing country: ECUADOR
- Installation: [GBIF Ecuador - MAATE](https://registry.gbif.org/installation/9df8109c-684d-416b-819b-7bc09adc500b)
- Number of occurrences indexed for this dataset at the time of the issue: 19961
- Cause: GBIF ID problems exceed 50% threshold: 55% duplicates; 43388 total records; 23889 absent records
- Pipelines execution steps: [http://api.gbif.org/v1/pipelines/history/execution/3472440/step](http://api.gbif.org/v1/pipelines/history/execution/3472440/step)

```
New IDs sample:

HLOJA-UNL:9635
HLOJA-UNL:8303
HLOJA-UNL:9634
HLOJA-UNL:15830
HLOJA-UNL:9637
HLOJA-UNL:8305
HLOJA-UNL:9636
HLOJA-UNL:8304
HLOJA-UNL:5612
HLOJA-UNL:6946
```


```
Old IDs sample:

HLOJA-UNL:18135
HLOJA-UNL:19235
HLOJA-UNL:19236
HLOJA-UNL:19248
HLOJA-UNL:19256
HLOJA-UNL:19258
HLOJA-UNL:19259
HLOJA-UNL:19260
HLOJA-UNL:19261
HLOJA-UNL:18914
```

<details>
<summary>Publisher email</summary>

Hello,

I am contacting you from the GBIF Secretariat about a dataset published by the [Colección plantas vasculares del Herbario Reinaldo Espinosa (Herbario LOJA) de la Universidad Nacional de Loja](https://registry.gbif.org/dataset/b5a8e29d-cd8c-4e04-90b2-422d900caab6) : https://doi.org/10.60545/u5ji5y.
We noticed that the occurrenceIDs were changed. We have temporarily paused the ingestions of this dataset.

As you might already know, when an occurrence record has a new occurrenceID for a given dataset, our system considers it to be a new occurrence.
This means that it will be given a new gbifid and a new occurrence URL (like this one: https://www.gbif.org/occurrence/1252968762) and the old gbifid and URL will be deprecated.

In this case, this means that the occurrence URLs would be deprecated when ingesting the newest versions of these datasets.

We would like to check with you if those changes were intentional. Do you know if this is the case?
Please let us know, thanks! We are happy to resume the dataset ingestion.

Note that some users rely on those occurrence URLs and gbifids (like https://bionomia.net for example). In an attempt to improve
the stability of the occurrence URLs and gbifids, we have implemented a warning system to detect these type of changes in datasets (see this news item).
If the data publisher can provide us with a list of old and new occurrenceIDs per record, we can avoid the identifier and URL changes. Could that be an option?

Please let us know if you have any question. Thanks!

All the best,

</details>


You can skip/fix identifier validation using [the registry UI](https://registry.gbif.org/dataset/b5a8e29d-cd8c-4e04-90b2-422d900caab6/ingestion-history).

**Comment by ManonGros** [comment]
@vechocho contacted us on helpdesk. I see that the dataset was paused because of an increase in the number of records > 50%. I have resumed the dataset ingestion and will close the issue now.
