### ISSUE TITLE
Identifiers validation failed for dataset NHMD Ornithology Collection

### ISSUE THREAD

**Issue by gbif-pipelines** [gbif/ingestion-management#972]
Identifier validation failed for the dataset [NHMD Ornithology Collection](https://registry.gbif.org/dataset/84dbaec2-f762-11e1-a439-00145eb45e9a):
- Crawler attempt: 281
- Publishing organization: [Zoological Museum, Natural History Museum of Denmark](https://registry.gbif.org/organization/456058db-f70b-4005-97ad-e08570cf0c56)
- Publishing country: DENMARK
- Installation: [DanBIF IPT at Aarhus University](https://registry.gbif.org/installation/6aca019f-ee9d-4088-859b-5a601d4b093f)
- Number of occurrences indexed for this dataset at the time of the issue: 70229
- Cause: GBIF ID problems exceed 50% threshold: 86% duplicates; 228359 total records; 195493 absent records
- Pipelines execution steps: [http://api.gbif.org/v1/pipelines/history/execution/3478476/step](http://api.gbif.org/v1/pipelines/history/execution/3478476/step)

```
New IDs sample:

a8a98926-69fa-471a-b76f-40373df2776a
fd8de365-55b0-4402-8894-2c9c6eaad3af
a06b1bfa-90ea-40a8-9056-d8dc088440a2
da4a7bed-541e-426b-b73e-4d426c341d33
8d0d8e7a-a8cd-4302-bcfc-d6d33cbdd2bb
0b595369-3f7b-4792-8ce6-685dec23ea3d
6b0c0129-541d-4650-b13b-c250b636bf9e
811689a3-4e20-4f77-bc83-e20411ba656a
9eed5cc0-3753-488e-8504-bd815c05e44b
136e3adb-48ad-4c14-aa3c-8789ee3178b1
```

```
Old IDs sample:

urn:catalog:ZMUC:Fisk:24788
urn:catalog:ZMUC:Fisk:24789
urn:catalog:ZMUC:Fisk:24781
urn:catalog:ZMUC:Fisk:60
urn:catalog:ZMUC:Fisk:24782
urn:catalog:ZMUC:Fisk:24783
urn:catalog:ZMUC:Fisk:61
urn:catalog:ZMUC:Fisk:24784
urn:catalog:ZMUC:Fisk:62
urn:catalog:ZMUC:Fisk:63
```

<details>
<summary>Publisher email</summary>

Hello,

I am contacting you from the GBIF Secretariat about a dataset published by the [NHMD Ornithology Collection](https://registry.gbif.org/dataset/84dbaec2-f762-11e1-a439-00145eb45e9a) : https://doi.org/10.15468/cs1ywg.
We noticed that the occurrenceIDs were changed. We have temporarily paused the ingestions of this dataset.

As you might already know, when an occurrence record has a new occurrenceID for a given dataset, our system considers it to be a new occurrence.
This means that it will be given a new gbifid and a new occurrence URL (like this one: https://www.gbif.org/occurrence/1252968762) and the old gbifid and URL will be deprecated.

In this case, this means that the occurrence URLs would be deprecated when ingesting the newest versions of these datasets.

We would like to check with you if those changes were intentional. Do you know if this is the case?
Please let us know, thanks! We are happy to resume the dataset ingestion.

Note that some users rely on those occurrence URLs and gbifids (like https://bionomia.net for example). In an attempt to improve
the stability of the occurrence URLs and gbifids, we have implemented a warning system to detect these type of changes in datasets (see this news item).
If the data publisher can provide us with a list of old and new occurrenceIDs per record, we can avoid the identifier and URL changes. Could that be an option?

Please let us know if you have any question. Thanks!

All the best,

</details>

You can skip/fix identifier validation using [the registry UI](https://registry.gbif.org/dataset/84dbaec2-f762-11e1-a439-00145eb45e9a/ingestion-history).

**Comment by gbif-pipelines** [comment]
Identifier validation still  failing for the dataset [NHMD Ichthyology Collection](https://registry.gbif.org/dataset/84dbaec2-f762-11e1-a439-00145eb45e9a):
- Crawler attempt: 283
- Publishing organization: [Zoological Museum, Natural History Museum of Denmark](https://registry.gbif.org/organization/456058db-f70b-4005-97ad-e08570cf0c56)
- Publishing country: DENMARK
- Installation: [DanBIF IPT at Aarhus University](https://registry.gbif.org/installation/6aca019f-ee9d-4088-859b-5a601d4b093f)
- Number of occurrences indexed for this dataset at the time of the issue: 70229
- Cause: GBIF ID problems exceed 50% threshold: 86% duplicates; 228359 total records; 195493 absent records
- Pipelines execution steps: [http://api.gbif.org/v1/pipelines/history/execution/3478544/step](http://api.gbif.org/v1/pipelines/history/execution/3478544/step)

```
New IDs sample:

6ae7c498-fbe2-42a3-9b82-b742bd29d437
f58e389c-f19e-4589-b5f2-d9bef251b239
3dcf2f04-241a-4f94-ae8f-57d76a019fb5
f67baa23-7deb-49b4-a836-247ff7a66715
99e228a8-cf75-47df-98c9-b627af90b1c1
c5175b59-b8b8-412f-b170-7a898aafede8
206e797d-b24c-49f8-b5fd-b9b1fe848078
86cdc5a3-1988-4b5a-b7cf-d6b803ad2094
d00d6b77-f8c3-4487-9ab7-70d268a1dd3e
8f6d4e54-8524-4649-9e50-c9318dd5f88d
```


```
Old IDs sample:

urn:catalog:ZMUC:Fisk:24788
urn:catalog:ZMUC:Fisk:24789
urn:catalog:ZMUC:Fisk:24781
urn:catalog:ZMUC:Fisk:60
urn:catalog:ZMUC:Fisk:24782
urn:catalog:ZMUC:Fisk:24783
urn:catalog:ZMUC:Fisk:61
urn:catalog:ZMUC:Fisk:24784
urn:catalog:ZMUC:Fisk:62
urn:catalog:ZMUC:Fisk:63
```

<details>
<summary>Publisher email</summary>

Hello,

I am contacting you from the GBIF Secretariat about a dataset published by the [NHMD Ichthyology Collection](https://registry.gbif.org/dataset/84dbaec2-f762-11e1-a439-00145eb45e9a) : https://doi.org/10.15468/cs1ywg.
We noticed that the occurrenceIDs were changed. We have temporarily paused the ingestions of this dataset.

As you might already know, when an occurrence record has a new occurrenceID for a given dataset, our system considers it to be a new occurrence.
This means that it will be given a new gbifid and a new occurrence URL (like this one: https://www.gbif.org/occurrence/1252968762) and the old gbifid and URL will be deprecated.

In this case, this means that the occurrence URLs would be deprecated when ingesting the newest versions of these datasets.

We would like to check with you if those changes were intentional. Do you know if this is the case?
Please let us know, thanks! We are happy to resume the dataset ingestion.

Note that some users rely on those occurrence URLs and gbifids (like https://bionomia.net for example). In an attempt to improve
the stability of the occurrence URLs and gbifids, we have implemented a warning system to detect these type of changes in datasets (see this news item).
If the data publisher can provide us with a list of old and new occurrenceIDs per record, we can avoid the identifier and URL changes. Could that be an option?

Please let us know if you have any question. Thanks!

All the best,

</details>


You can skip/fix identifier validation using [the registry UI](https://registry.gbif.org/dataset/84dbaec2-f762-11e1-a439-00145eb45e9a/ingestion-history).

**Comment by ktotsum** [comment]
We migrated identifiers for under a half (47%) of records and resumed the ingestion. Also the record count increased by nearly 3 times.

The endpoint was changed from IPT to Specify. The correct title of this dataset is "NHMD Ichthyology Collection" (the eml file was updated after this issue was created).

**Comment by ManonGros** [comment]
I migrated the last record.
