### ISSUE TITLE
Identifiers validation failed for dataset Fungus Collections at Staatliches Museum für Naturkunde Karlsruhe (Herbarium KR)

### ISSUE THREAD

**Issue by gbif-pipelines** [gbif/ingestion-management#974]
Identifier validation failed for the dataset [Fungus Collections at Staatliches Museum für Naturkunde Karlsruhe (Herbarium KR)](https://registry.gbif.org/dataset/61a9ca38-b62f-11e2-afcb-00145eb45e9a):
- Crawler attempt: 321
- Publishing organization: [Staatliche Naturwissenschaftliche Sammlungen Bayerns](https://registry.gbif.org/organization/0674aea0-a7e1-11d8-9534-b8a03c50a862)
- Publishing country: GERMANY
- Installation: [BioCASe Installation Staatliche Naturwissenschaftliche Sammlungen Bayerns](https://registry.gbif.org/installation/6038e54e-f762-11e1-a439-00145eb45e9a)
- Number of occurrences indexed for this dataset at the time of the issue: 0
- Cause: Dataset has no API records, but 22% of IDs aren't new
- Pipelines execution steps: [http://api.gbif.org/v1/pipelines/history/execution/3482094/step](http://api.gbif.org/v1/pipelines/history/execution/3482094/step)

```
New IDs sample:

urn:catalog:KR:SMNKfungicoll:KR-M-0014958 / 455939 / 21950
urn:catalog:KR:SMNKfungicoll:KR-M-0014962 / 455943 / 21954
urn:catalog:KR:SMNKfungicoll:KR-M-0014986 / 489213 / 21979
urn:catalog:KR:SMNKfungicoll:KR-M-0014988 / 455970 / 21981
urn:catalog:KR:SMNKfungicoll:KR-M-0014990 / 489217 / 21983
urn:catalog:KR:SMNKfungicoll:KR-M-0014993 / 455975 / 21986
urn:catalog:KR:SMNKfungicoll:KR-M-0015018 / 489245 / 22011
urn:catalog:KR:SMNKfungicoll:KR-M-0015019 / 456001 / 84506
urn:catalog:KR:SMNKfungicoll:KR-M-0055792 / 814371 / 304248
urn:catalog:KR:SMNKfungicoll:KR-M-0055788 / 814363 / 304244
```

```
Old IDs sample:


```

<details>
<summary>Publisher email</summary>

Hello,

I am contacting you from the GBIF Secretariat about a dataset published by the [Fungus Collections at Staatliches Museum für Naturkunde Karlsruhe (Herbarium KR)](https://registry.gbif.org/dataset/61a9ca38-b62f-11e2-afcb-00145eb45e9a) : https://doi.org/10.15468/0bhhip.
We noticed that the occurrenceIDs were changed. We have temporarily paused the ingestions of this dataset.

As you might already know, when an occurrence record has a new occurrenceID for a given dataset, our system considers it to be a new occurrence.
This means that it will be given a new gbifid and a new occurrence URL (like this one: https://www.gbif.org/occurrence/1252968762) and the old gbifid and URL will be deprecated.

In this case, this means that the occurrence URLs would be deprecated when ingesting the newest versions of these datasets.

We would like to check with you if those changes were intentional. Do you know if this is the case?
Please let us know, thanks! We are happy to resume the dataset ingestion.

Note that some users rely on those occurrence URLs and gbifids (like https://bionomia.net for example). In an attempt to improve
the stability of the occurrence URLs and gbifids, we have implemented a warning system to detect these type of changes in datasets (see this news item).
If the data publisher can provide us with a list of old and new occurrenceIDs per record, we can avoid the identifier and URL changes. Could that be an option?

Please let us know if you have any question. Thanks!

All the best,

</details>

You can skip/fix identifier validation using [the registry UI](https://registry.gbif.org/dataset/61a9ca38-b62f-11e2-afcb-00145eb45e9a/ingestion-history).

**Comment by ManonGros** [comment]
Same situation as here: https://github.com/gbif/ingestion-management/issues/976
