### ISSUE TITLE
Identifiers validation failed for dataset The Fungal Collection at the Senckenberg Museum für Naturkunde Görlitz

### ISSUE THREAD

**Issue by gbif-pipelines** [gbif/ingestion-management#975]
Identifier validation failed for the dataset [The Fungal Collection at the Senckenberg Museum für Naturkunde Görlitz](https://registry.gbif.org/dataset/7a2660bc-f762-11e1-a439-00145eb45e9a):
- Crawler attempt: 310
- Publishing organization: [Staatliche Naturwissenschaftliche Sammlungen Bayerns](https://registry.gbif.org/organization/0674aea0-a7e1-11d8-9534-b8a03c50a862)
- Publishing country: GERMANY
- Installation: [BioCASe Installation Staatliche Naturwissenschaftliche Sammlungen Bayerns](https://registry.gbif.org/installation/6038e54e-f762-11e1-a439-00145eb45e9a)
- Number of occurrences indexed for this dataset at the time of the issue: 0
- Cause: Dataset has no API records, but 1% of IDs aren't new
- Pipelines execution steps: [http://api.gbif.org/v1/pipelines/history/execution/3482096/step](http://api.gbif.org/v1/pipelines/history/execution/3482096/step)

```
New IDs sample:

http://id.snsb.info/snsb/collection/31536/42436/31095
http://id.snsb.info/snsb/collection/39290/55498/38849
http://id.snsb.info/snsb/collection/39698/56029/39257
http://id.snsb.info/snsb/collection/40020/56439/39579
http://id.snsb.info/snsb/collection/40663/57422/40222
http://id.snsb.info/snsb/collection/44538/64434/44097
http://id.snsb.info/snsb/collection/47022/68974/46581
http://id.snsb.info/snsb/collection/49366/73099/48925
http://id.snsb.info/snsb/collection/52070/77599/51629
http://id.snsb.info/snsb/collection/58235/89611/57794
```

```
Old IDs sample:


```

<details>
<summary>Publisher email</summary>

Hello,

I am contacting you from the GBIF Secretariat about a dataset published by the [The Fungal Collection at the Senckenberg Museum für Naturkunde Görlitz](https://registry.gbif.org/dataset/7a2660bc-f762-11e1-a439-00145eb45e9a) : https://doi.org/10.15468/fhmwzv.
We noticed that the occurrenceIDs were changed. We have temporarily paused the ingestions of this dataset.

As you might already know, when an occurrence record has a new occurrenceID for a given dataset, our system considers it to be a new occurrence.
This means that it will be given a new gbifid and a new occurrence URL (like this one: https://www.gbif.org/occurrence/1252968762) and the old gbifid and URL will be deprecated.

In this case, this means that the occurrence URLs would be deprecated when ingesting the newest versions of these datasets.

We would like to check with you if those changes were intentional. Do you know if this is the case?
Please let us know, thanks! We are happy to resume the dataset ingestion.

Note that some users rely on those occurrence URLs and gbifids (like https://bionomia.net for example). In an attempt to improve
the stability of the occurrence URLs and gbifids, we have implemented a warning system to detect these type of changes in datasets (see this news item).
If the data publisher can provide us with a list of old and new occurrenceIDs per record, we can avoid the identifier and URL changes. Could that be an option?

Please let us know if you have any question. Thanks!

All the best,

</details>

You can skip/fix identifier validation using [the registry UI](https://registry.gbif.org/dataset/7a2660bc-f762-11e1-a439-00145eb45e9a/ingestion-history).

**Comment by ManonGros** [comment]
Same situation as here: https://github.com/gbif/ingestion-management/issues/976
