### ISSUE TITLE
Identifiers validation failed for dataset The Spider Collection at the Staatliches Museum für Naturkunde Karlsruhe

### ISSUE THREAD

**Issue by gbif-pipelines** [gbif/ingestion-management#976]
Identifier validation failed for the dataset [The Spider Collection at the Staatliches Museum für Naturkunde Karlsruhe](https://registry.gbif.org/dataset/8277b324-f762-11e1-a439-00145eb45e9a):
- Crawler attempt: 325
- Publishing organization: [Staatliche Naturwissenschaftliche Sammlungen Bayerns](https://registry.gbif.org/organization/0674aea0-a7e1-11d8-9534-b8a03c50a862)
- Publishing country: GERMANY
- Installation: [BioCASe Installation Staatliche Naturwissenschaftliche Sammlungen Bayerns](https://registry.gbif.org/installation/6038e54e-f762-11e1-a439-00145eb45e9a)
- Number of occurrences indexed for this dataset at the time of the issue: 0
- Cause: Dataset has no API records, but 9% of IDs aren't new
- Pipelines execution steps: [http://api.gbif.org/v1/pipelines/history/execution/3482097/step](http://api.gbif.org/v1/pipelines/history/execution/3482097/step)

```
New IDs sample:

urn:catalog:SMNK:SMNKspidercoll:SMNK-ARA 13616 / 621691 / 136492
urn:catalog:SMNK:SMNKspidercoll:SMNK-ARA 12895 / 619106 / 134579
urn:catalog:SMNK:SMNKspidercoll:SMNK-ARA 13477 / 621462 / 136297
urn:catalog:SMNK:SMNKspidercoll:SMNK-ARA 12594 / 617377 / 133903
urn:catalog:SMNK:SMNKspidercoll:SMNK-ARA 13614 / 621687 / 136488
urn:catalog:SMNK:SMNKspidercoll:SMNK-ARA 12253 / 584794 / 104066
urn:catalog:SMNK:SMNKspidercoll:SMNK-ARA 13500 / 621498 / 136325
urn:catalog:SMNK:SMNKspidercoll:SMNK-ARA 12523 / 617243 / 133797
urn:catalog:SMNK:SMNKspidercoll:SMNK-ARA 12479 / 606115 / 124812
urn:catalog:SMNS:SMNKspidercoll:SMNK-ARA 08046 / 449948 / 89377
```

```
Old IDs sample:


```

<details>
<summary>Publisher email</summary>

Hello,

I am contacting you from the GBIF Secretariat about a dataset published by the [The Spider Collection at the Staatliches Museum für Naturkunde Karlsruhe](https://registry.gbif.org/dataset/8277b324-f762-11e1-a439-00145eb45e9a) : https://doi.org/10.15468/fmxx2i.
We noticed that the occurrenceIDs were changed. We have temporarily paused the ingestions of this dataset.

As you might already know, when an occurrence record has a new occurrenceID for a given dataset, our system considers it to be a new occurrence.
This means that it will be given a new gbifid and a new occurrence URL (like this one: https://www.gbif.org/occurrence/1252968762) and the old gbifid and URL will be deprecated.

In this case, this means that the occurrence URLs would be deprecated when ingesting the newest versions of these datasets.

We would like to check with you if those changes were intentional. Do you know if this is the case?
Please let us know, thanks! We are happy to resume the dataset ingestion.

Note that some users rely on those occurrence URLs and gbifids (like https://bionomia.net for example). In an attempt to improve
the stability of the occurrence URLs and gbifids, we have implemented a warning system to detect these type of changes in datasets (see this news item).
If the data publisher can provide us with a list of old and new occurrenceIDs per record, we can avoid the identifier and URL changes. Could that be an option?

Please let us know if you have any question. Thanks!

All the best,

</details>

You can skip/fix identifier validation using [the registry UI](https://registry.gbif.org/dataset/8277b324-f762-11e1-a439-00145eb45e9a/ingestion-history).

**Comment by ManonGros** [comment]
The occurrences were previously deleted because of an issue in BioCASE installation. The occurrences were added again now. Only 2,146 IDs were unknown to GBIF, it is very little. I let the dataset go through.
