### ISSUE TITLE
Identifiers validation failed for dataset Colección de Aves del Instituto de Investigación de Recursos Biológicos Alexander von Humboldt (IAvH-A)

### ISSUE THREAD

**Issue by gbif-pipelines** [gbif/ingestion-management#982]
Identifier validation failed for the dataset [Colección de Aves del Instituto de Investigación de Recursos Biológicos Alexander von Humboldt (IAvH-A)](https://registry.gbif.org/dataset/3bef6fb2-9a1f-4d8d-b5f3-d6d23885905c):
- Crawler attempt: 344
- Publishing organization: [Instituto de Investigación de Recursos Biológicos Alexander von Humboldt](https://registry.gbif.org/organization/2a7e3080-28a9-11dd-97cd-b8a03c50a862)
- Publishing country: COLOMBIA
- Installation: [IPT IAvH](https://registry.gbif.org/installation/804b8dd0-07ac-4a30-bf92-3c1d862faf5e)
- Number of occurrences indexed for this dataset at the time of the issue: 15839
- Cause: GBIF ID problems exceed 50% threshold: 100% duplicates; 34192 total records; 34192 absent records
- Pipelines execution steps: [http://api.gbif.org/v1/pipelines/history/execution/3492253/step](http://api.gbif.org/v1/pipelines/history/execution/3492253/step)

```
New IDs sample:


```

```
Old IDs sample:

IAvH:COLECCIONES:AVES:IAvH-A-17179
IAvH:COLECCIONES:AVES:IAvH-A-17294
IAvH:COLECCIONES:AVES:IAvH-A-17178
IAvH:COLECCIONES:AVES:IAvH-A-17295
IAvH:COLECCIONES:AVES:IAvH-A-17296
IAvH:COLECCIONES:AVES:IAvH-A-17297
IAvH:COLECCIONES:AVES:IAvH-A-17298
IAvH:COLECCIONES:AVES:IAvH-A-17299
IAvH:COLECCIONES:AVES:IAvH-A-17300
IAvH:COLECCIONES:AVES:IAvH-A-17301
```

<details>
<summary>Publisher email</summary>

Hello,

I am contacting you from the GBIF Secretariat about a dataset published by the [Colección de Aves del Instituto de Investigación de Recursos Biológicos Alexander von Humboldt (IAvH-A)](https://registry.gbif.org/dataset/3bef6fb2-9a1f-4d8d-b5f3-d6d23885905c) : https://doi.org/10.15472/maeoiz.
We noticed that the occurrenceIDs were changed. We have temporarily paused the ingestions of this dataset.

As you might already know, when an occurrence record has a new occurrenceID for a given dataset, our system considers it to be a new occurrence.
This means that it will be given a new gbifid and a new occurrence URL (like this one: https://www.gbif.org/occurrence/1252968762) and the old gbifid and URL will be deprecated.

In this case, this means that the occurrence URLs would be deprecated when ingesting the newest versions of these datasets.

We would like to check with you if those changes were intentional. Do you know if this is the case?
Please let us know, thanks! We are happy to resume the dataset ingestion.

Note that some users rely on those occurrence URLs and gbifids (like https://bionomia.net for example). In an attempt to improve
the stability of the occurrence URLs and gbifids, we have implemented a warning system to detect these type of changes in datasets (see this news item).
If the data publisher can provide us with a list of old and new occurrenceIDs per record, we can avoid the identifier and URL changes. Could that be an option?

Please let us know if you have any question. Thanks!

All the best,

</details>

You can skip/fix identifier validation using [the registry UI](https://registry.gbif.org/dataset/3bef6fb2-9a1f-4d8d-b5f3-d6d23885905c/ingestion-history).

**Comment by gbif-pipelines** [comment]
Identifier validation still  failing for the dataset [Colección de Aves del Instituto de Investigación de Recursos Biológicos Alexander von Humboldt (IAvH-A)](https://registry.gbif.org/dataset/3bef6fb2-9a1f-4d8d-b5f3-d6d23885905c):
- Crawler attempt: 345
- Publishing organization: [Instituto de Investigación de Recursos Biológicos Alexander von Humboldt](https://registry.gbif.org/organization/2a7e3080-28a9-11dd-97cd-b8a03c50a862)
- Publishing country: COLOMBIA
- Installation: [IPT IAvH](https://registry.gbif.org/installation/804b8dd0-07ac-4a30-bf92-3c1d862faf5e)
- Number of occurrences indexed for this dataset at the time of the issue: 15839
- Cause: GBIF ID problems exceed 50% threshold: 100% duplicates; 34192 total records; 34192 absent records
- Pipelines execution steps: [http://api.gbif.org/v1/pipelines/history/execution/3492927/step](http://api.gbif.org/v1/pipelines/history/execution/3492927/step)

```
New IDs sample:


```


```
Old IDs sample:

IAvH:COLECCIONES:AVES:IAvH-A-17179
IAvH:COLECCIONES:AVES:IAvH-A-17294
IAvH:COLECCIONES:AVES:IAvH-A-17178
IAvH:COLECCIONES:AVES:IAvH-A-17295
IAvH:COLECCIONES:AVES:IAvH-A-17296
IAvH:COLECCIONES:AVES:IAvH-A-17297
IAvH:COLECCIONES:AVES:IAvH-A-17298
IAvH:COLECCIONES:AVES:IAvH-A-17299
IAvH:COLECCIONES:AVES:IAvH-A-17300
IAvH:COLECCIONES:AVES:IAvH-A-17301
```

<details>
<summary>Publisher email</summary>

Hello,

I am contacting you from the GBIF Secretariat about a dataset published by the [Colección de Aves del Instituto de Investigación de Recursos Biológicos Alexander von Humboldt (IAvH-A)](https://registry.gbif.org/dataset/3bef6fb2-9a1f-4d8d-b5f3-d6d23885905c) : https://doi.org/10.15472/maeoiz.
We noticed that the occurrenceIDs were changed. We have temporarily paused the ingestions of this dataset.

As you might already know, when an occurrence record has a new occurrenceID for a given dataset, our system considers it to be a new occurrence.
This means that it will be given a new gbifid and a new occurrence URL (like this one: https://www.gbif.org/occurrence/1252968762) and the old gbifid and URL will be deprecated.

In this case, this means that the occurrence URLs would be deprecated when ingesting the newest versions of these datasets.

We would like to check with you if those changes were intentional. Do you know if this is the case?
Please let us know, thanks! We are happy to resume the dataset ingestion.

Note that some users rely on those occurrence URLs and gbifids (like https://bionomia.net for example). In an attempt to improve
the stability of the occurrence URLs and gbifids, we have implemented a warning system to detect these type of changes in datasets (see this news item).
If the data publisher can provide us with a list of old and new occurrenceIDs per record, we can avoid the identifier and URL changes. Could that be an option?

Please let us know if you have any question. Thanks!

All the best,

</details>


You can skip/fix identifier validation using [the registry UI](https://registry.gbif.org/dataset/3bef6fb2-9a1f-4d8d-b5f3-d6d23885905c/ingestion-history).

**Comment by gbif-pipelines** [comment]
Identifier validation still  failing for the dataset [Colección de Aves del Instituto de Investigación de Recursos Biológicos Alexander von Humboldt (IAvH-A)](https://registry.gbif.org/dataset/3bef6fb2-9a1f-4d8d-b5f3-d6d23885905c):
- Crawler attempt: 346
- Publishing organization: [Instituto de Investigación de Recursos Biológicos Alexander von Humboldt](https://registry.gbif.org/organization/2a7e3080-28a9-11dd-97cd-b8a03c50a862)
- Publishing country: COLOMBIA
- Installation: [IPT IAvH](https://registry.gbif.org/installation/804b8dd0-07ac-4a30-bf92-3c1d862faf5e)
- Number of occurrences indexed for this dataset at the time of the issue: 15839
- Cause: GBIF ID problems exceed 50% threshold: 100% duplicates; 34192 total records; 34192 absent records
- Pipelines execution steps: [http://api.gbif.org/v1/pipelines/history/execution/3492930/step](http://api.gbif.org/v1/pipelines/history/execution/3492930/step)

```
New IDs sample:


```


```
Old IDs sample:

IAvH:COLECCIONES:AVES:IAvH-A-17179
IAvH:COLECCIONES:AVES:IAvH-A-17294
IAvH:COLECCIONES:AVES:IAvH-A-17178
IAvH:COLECCIONES:AVES:IAvH-A-17295
IAvH:COLECCIONES:AVES:IAvH-A-17296
IAvH:COLECCIONES:AVES:IAvH-A-17297
IAvH:COLECCIONES:AVES:IAvH-A-17298
IAvH:COLECCIONES:AVES:IAvH-A-17299
IAvH:COLECCIONES:AVES:IAvH-A-17300
IAvH:COLECCIONES:AVES:IAvH-A-17301
```

<details>
<summary>Publisher email</summary>

Hello,

I am contacting you from the GBIF Secretariat about a dataset published by the [Colección de Aves del Instituto de Investigación de Recursos Biológicos Alexander von Humboldt (IAvH-A)](https://registry.gbif.org/dataset/3bef6fb2-9a1f-4d8d-b5f3-d6d23885905c) : https://doi.org/10.15472/maeoiz.
We noticed that the occurrenceIDs were changed. We have temporarily paused the ingestions of this dataset.

As you might already know, when an occurrence record has a new occurrenceID for a given dataset, our system considers it to be a new occurrence.
This means that it will be given a new gbifid and a new occurrence URL (like this one: https://www.gbif.org/occurrence/1252968762) and the old gbifid and URL will be deprecated.

In this case, this means that the occurrence URLs would be deprecated when ingesting the newest versions of these datasets.

We would like to check with you if those changes were intentional. Do you know if this is the case?
Please let us know, thanks! We are happy to resume the dataset ingestion.

Note that some users rely on those occurrence URLs and gbifids (like https://bionomia.net for example). In an attempt to improve
the stability of the occurrence URLs and gbifids, we have implemented a warning system to detect these type of changes in datasets (see this news item).
If the data publisher can provide us with a list of old and new occurrenceIDs per record, we can avoid the identifier and URL changes. Could that be an option?

Please let us know if you have any question. Thanks!

All the best,

</details>


You can skip/fix identifier validation using [the registry UI](https://registry.gbif.org/dataset/3bef6fb2-9a1f-4d8d-b5f3-d6d23885905c/ingestion-history).

**Comment by gbif-pipelines** [comment]
Identifier validation still  failing for the dataset [Colección de Aves del Instituto de Investigación de Recursos Biológicos Alexander von Humboldt (IAvH-A)](https://registry.gbif.org/dataset/3bef6fb2-9a1f-4d8d-b5f3-d6d23885905c):
- Crawler attempt: 347
- Publishing organization: [Instituto de Investigación de Recursos Biológicos Alexander von Humboldt](https://registry.gbif.org/organization/2a7e3080-28a9-11dd-97cd-b8a03c50a862)
- Publishing country: COLOMBIA
- Installation: [IPT IAvH](https://registry.gbif.org/installation/804b8dd0-07ac-4a30-bf92-3c1d862faf5e)
- Number of occurrences indexed for this dataset at the time of the issue: 15839
- Cause: GBIF ID problems exceed 50% threshold: 100% duplicates; 16889 total records; 16889 absent records
- Pipelines execution steps: [http://api.gbif.org/v1/pipelines/history/execution/3492931/step](http://api.gbif.org/v1/pipelines/history/execution/3492931/step)

```
New IDs sample:


```


```
Old IDs sample:

IAvH:COLECCIONES:AVES:IAvH-A-17179
IAvH:COLECCIONES:AVES:IAvH-A-17294
IAvH:COLECCIONES:AVES:IAvH-A-17178
IAvH:COLECCIONES:AVES:IAvH-A-17295
IAvH:COLECCIONES:AVES:IAvH-A-17296
IAvH:COLECCIONES:AVES:IAvH-A-17297
IAvH:COLECCIONES:AVES:IAvH-A-17298
IAvH:COLECCIONES:AVES:IAvH-A-17299
IAvH:COLECCIONES:AVES:IAvH-A-17300
IAvH:COLECCIONES:AVES:IAvH-A-17301
```

<details>
<summary>Publisher email</summary>

Hello,

I am contacting you from the GBIF Secretariat about a dataset published by the [Colección de Aves del Instituto de Investigación de Recursos Biológicos Alexander von Humboldt (IAvH-A)](https://registry.gbif.org/dataset/3bef6fb2-9a1f-4d8d-b5f3-d6d23885905c) : https://doi.org/10.15472/maeoiz.
We noticed that the occurrenceIDs were changed. We have temporarily paused the ingestions of this dataset.

As you might already know, when an occurrence record has a new occurrenceID for a given dataset, our system considers it to be a new occurrence.
This means that it will be given a new gbifid and a new occurrence URL (like this one: https://www.gbif.org/occurrence/1252968762) and the old gbifid and URL will be deprecated.

In this case, this means that the occurrence URLs would be deprecated when ingesting the newest versions of these datasets.

We would like to check with you if those changes were intentional. Do you know if this is the case?
Please let us know, thanks! We are happy to resume the dataset ingestion.

Note that some users rely on those occurrence URLs and gbifids (like https://bionomia.net for example). In an attempt to improve
the stability of the occurrence URLs and gbifids, we have implemented a warning system to detect these type of changes in datasets (see this news item).
If the data publisher can provide us with a list of old and new occurrenceIDs per record, we can avoid the identifier and URL changes. Could that be an option?

Please let us know if you have any question. Thanks!

All the best,

</details>


You can skip/fix identifier validation using [the registry UI](https://registry.gbif.org/dataset/3bef6fb2-9a1f-4d8d-b5f3-d6d23885905c/ingestion-history).

**Comment by gbif-pipelines** [comment]
Identifier validation still  failing for the dataset [Colección de Aves del Instituto de Investigación de Recursos Biológicos Alexander von Humboldt (IAvH-A)](https://registry.gbif.org/dataset/3bef6fb2-9a1f-4d8d-b5f3-d6d23885905c):
- Crawler attempt: 348
- Publishing organization: [Instituto de Investigación de Recursos Biológicos Alexander von Humboldt](https://registry.gbif.org/organization/2a7e3080-28a9-11dd-97cd-b8a03c50a862)
- Publishing country: COLOMBIA
- Installation: [IPT IAvH](https://registry.gbif.org/installation/804b8dd0-07ac-4a30-bf92-3c1d862faf5e)
- Number of occurrences indexed for this dataset at the time of the issue: 15839
- Cause: GBIF ID problems exceed 50% threshold: 100% duplicates; 34192 total records; 34192 absent records
- Pipelines execution steps: [http://api.gbif.org/v1/pipelines/history/execution/3492933/step](http://api.gbif.org/v1/pipelines/history/execution/3492933/step)

```
New IDs sample:


```


```
Old IDs sample:

IAvH:COLECCIONES:AVES:IAvH-A-17179
IAvH:COLECCIONES:AVES:IAvH-A-17294
IAvH:COLECCIONES:AVES:IAvH-A-17178
IAvH:COLECCIONES:AVES:IAvH-A-17295
IAvH:COLECCIONES:AVES:IAvH-A-17296
IAvH:COLECCIONES:AVES:IAvH-A-17297
IAvH:COLECCIONES:AVES:IAvH-A-17298
IAvH:COLECCIONES:AVES:IAvH-A-17299
IAvH:COLECCIONES:AVES:IAvH-A-17300
IAvH:COLECCIONES:AVES:IAvH-A-17301
```

<details>
<summary>Publisher email</summary>

Hello,

I am contacting you from the GBIF Secretariat about a dataset published by the [Colección de Aves del Instituto de Investigación de Recursos Biológicos Alexander von Humboldt (IAvH-A)](https://registry.gbif.org/dataset/3bef6fb2-9a1f-4d8d-b5f3-d6d23885905c) : https://doi.org/10.15472/maeoiz.
We noticed that the occurrenceIDs were changed. We have temporarily paused the ingestions of this dataset.

As you might already know, when an occurrence record has a new occurrenceID for a given dataset, our system considers it to be a new occurrence.
This means that it will be given a new gbifid and a new occurrence URL (like this one: https://www.gbif.org/occurrence/1252968762) and the old gbifid and URL will be deprecated.

In this case, this means that the occurrence URLs would be deprecated when ingesting the newest versions of these datasets.

We would like to check with you if those changes were intentional. Do you know if this is the case?
Please let us know, thanks! We are happy to resume the dataset ingestion.

Note that some users rely on those occurrence URLs and gbifids (like https://bionomia.net for example). In an attempt to improve
the stability of the occurrence URLs and gbifids, we have implemented a warning system to detect these type of changes in datasets (see this news item).
If the data publisher can provide us with a list of old and new occurrenceIDs per record, we can avoid the identifier and URL changes. Could that be an option?

Please let us know if you have any question. Thanks!

All the best,

</details>


You can skip/fix identifier validation using [the registry UI](https://registry.gbif.org/dataset/3bef6fb2-9a1f-4d8d-b5f3-d6d23885905c/ingestion-history).

**Comment by ManonGros** [comment]
Hi @EstebanMH-SiB it looks like this dataset (https://ipt.biodiversidad.co/iavh/resource?r=aves_iavh) ingestion was paused because all the identifiers changed. Could you take a look and let us know if we should resume the dataset ingestion? Thanks!

**Comment by EstebanMH-SiB** [comment]
Hi @ManonGros , thank you very much for letting us know. The most likely scenario is that we can recover the original IDs, but it will take a while because we need to have a meeting with the publisher to avoid this in the future. So once we have sorted it out I will let you know, thanks!

**Comment by gbif-pipelines** [comment]
Identifier validation still  failing for the dataset [Colección de Aves del Instituto de Investigación de Recursos Biológicos Alexander von Humboldt (IAvH-A)](https://registry.gbif.org/dataset/3bef6fb2-9a1f-4d8d-b5f3-d6d23885905c):
- Crawler attempt: 350
- Publishing organization: [Instituto de Investigación de Recursos Biológicos Alexander von Humboldt](https://registry.gbif.org/organization/2a7e3080-28a9-11dd-97cd-b8a03c50a862)
- Publishing country: COLOMBIA
- Installation: [IPT IAvH](https://registry.gbif.org/installation/804b8dd0-07ac-4a30-bf92-3c1d862faf5e)
- Number of occurrences indexed for this dataset at the time of the issue: 15839
- Cause: GBIF ID problems exceed 50% threshold: 100% duplicates; 17303 total records; 17303 absent records
- Pipelines execution steps: [http://api.gbif.org/v1/pipelines/history/execution/3515137/step](http://api.gbif.org/v1/pipelines/history/execution/3515137/step)

```
New IDs sample:


```


```
Old IDs sample:

IAvH:COLECCIONES:AVES:IAvH-A-17179
IAvH:COLECCIONES:AVES:IAvH-A-17294
IAvH:COLECCIONES:AVES:IAvH-A-17178
IAvH:COLECCIONES:AVES:IAvH-A-17295
IAvH:COLECCIONES:AVES:IAvH-A-17296
IAvH:COLECCIONES:AVES:IAvH-A-17297
IAvH:COLECCIONES:AVES:IAvH-A-17298
IAvH:COLECCIONES:AVES:IAvH-A-17299
IAvH:COLECCIONES:AVES:IAvH-A-17300
IAvH:COLECCIONES:AVES:IAvH-A-17301
```

<details>
<summary>Publisher email</summary>

Hello,

I am contacting you from the GBIF Secretariat about a dataset published by the [Colección de Aves del Instituto de Investigación de Recursos Biológicos Alexander von Humboldt (IAvH-A)](https://registry.gbif.org/dataset/3bef6fb2-9a1f-4d8d-b5f3-d6d23885905c) : https://doi.org/10.15472/maeoiz.
We noticed that the occurrenceIDs were changed. We have temporarily paused the ingestions of this dataset.

As you might already know, when an occurrence record has a new occurrenceID for a given dataset, our system considers it to be a new occurrence.
This means that it will be given a new gbifid and a new occurrence URL (like this one: https://www.gbif.org/occurrence/1252968762) and the old gbifid and URL will be deprecated.

In this case, this means that the occurrence URLs would be deprecated when ingesting the newest versions of these datasets.

We would like to check with you if those changes were intentional. Do you know if this is the case?
Please let us know, thanks! We are happy to resume the dataset ingestion.

Note that some users rely on those occurrence URLs and gbifids (like https://bionomia.net for example). In an attempt to improve
the stability of the occurrence URLs and gbifids, we have implemented a warning system to detect these type of changes in datasets (see this news item).
If the data publisher can provide us with a list of old and new occurrenceIDs per record, we can avoid the identifier and URL changes. Could that be an option?

Please let us know if you have any question. Thanks!

All the best,

</details>


You can skip/fix identifier validation using [the registry UI](https://registry.gbif.org/dataset/3bef6fb2-9a1f-4d8d-b5f3-d6d23885905c/ingestion-history).

**Comment by gbif-pipelines** [comment]
Identifier validation still  failing for the dataset [Colección de Aves del Instituto de Investigación de Recursos Biológicos Alexander von Humboldt (IAvH-A)](https://registry.gbif.org/dataset/3bef6fb2-9a1f-4d8d-b5f3-d6d23885905c):
- Crawler attempt: 376
- Publishing organization: [Instituto de Investigación de Recursos Biológicos Alexander von Humboldt](https://registry.gbif.org/organization/2a7e3080-28a9-11dd-97cd-b8a03c50a862)
- Publishing country: COLOMBIA
- Installation: [IPT IAvH](https://registry.gbif.org/installation/804b8dd0-07ac-4a30-bf92-3c1d862faf5e)
- Number of occurrences indexed for this dataset at the time of the issue: 15839
- Cause: GBIF ID problems exceed 50% threshold: 100% duplicates; 17303 total records; 17303 absent records
- Pipelines execution steps: [http://api.gbif.org/v1/pipelines/history/execution/3997581/step](http://api.gbif.org/v1/pipelines/history/execution/3997581/step)

```
New IDs sample:


```


```
Old IDs sample:

IAvH:COLECCIONES:AVES:IAvH-A-17179
IAvH:COLECCIONES:AVES:IAvH-A-17294
IAvH:COLECCIONES:AVES:IAvH-A-17178
IAvH:COLECCIONES:AVES:IAvH-A-17295
IAvH:COLECCIONES:AVES:IAvH-A-17296
IAvH:COLECCIONES:AVES:IAvH-A-17297
IAvH:COLECCIONES:AVES:IAvH-A-17298
IAvH:COLECCIONES:AVES:IAvH-A-17299
IAvH:COLECCIONES:AVES:IAvH-A-17300
IAvH:COLECCIONES:AVES:IAvH-A-17301
```

<details>
<summary>Publisher email</summary>

Hello,

I am contacting you from the GBIF Secretariat about a dataset published by the [Colección de Aves del Instituto de Investigación de Recursos Biológicos Alexander von Humboldt (IAvH-A)](https://registry.gbif.org/dataset/3bef6fb2-9a1f-4d8d-b5f3-d6d23885905c) : https://doi.org/10.15472/maeoiz.
We noticed that the occurrenceIDs were changed. We have temporarily paused the ingestions of this dataset.

As you might already know, when an occurrence record has a new occurrenceID for a given dataset, our system considers it to be a new occurrence.
This means that it will be given a new gbifid and a new occurrence URL (like this one: https://www.gbif.org/occurrence/1252968762) and the old gbifid and URL will be deprecated.

In this case, this means that the occurrence URLs would be deprecated when ingesting the newest versions of these datasets.

We would like to check with you if those changes were intentional. Do you know if this is the case?
Please let us know, thanks! We are happy to resume the dataset ingestion.

Note that some users rely on those occurrence URLs and gbifids (like https://bionomia.net for example). In an attempt to improve
the stability of the occurrence URLs and gbifids, we have implemented a warning system to detect these type of changes in datasets (see this news item).
If the data publisher can provide us with a list of old and new occurrenceIDs per record, we can avoid the identifier and URL changes. Could that be an option?

Please let us know if you have any question. Thanks!

All the best,

</details>


You can skip/fix identifier validation using [the registry UI](https://registry.gbif.org/dataset/3bef6fb2-9a1f-4d8d-b5f3-d6d23885905c/ingestion-history).

**Comment by gbif-pipelines** [comment]
Identifier validation still  failing for the dataset [Colección de Aves del Instituto de Investigación de Recursos Biológicos Alexander von Humboldt (IAvH-A)](https://registry.gbif.org/dataset/3bef6fb2-9a1f-4d8d-b5f3-d6d23885905c):
- Crawler attempt: 379
- Publishing organization: [Instituto de Investigación de Recursos Biológicos Alexander von Humboldt](https://registry.gbif.org/organization/2a7e3080-28a9-11dd-97cd-b8a03c50a862)
- Publishing country: COLOMBIA
- Installation: [IPT IAvH](https://registry.gbif.org/installation/804b8dd0-07ac-4a30-bf92-3c1d862faf5e)
- Number of occurrences indexed for this dataset at the time of the issue: 15839
- Cause: GBIF ID problems exceed 50% threshold: 100% duplicates; 17303 total records; 17303 absent records
- Pipelines execution steps: [http://api.gbif.org/v1/pipelines/history/execution/4052645/step](http://api.gbif.org/v1/pipelines/history/execution/4052645/step)

```
New IDs sample:


```


```
Old IDs sample:

IAvH:COLECCIONES:AVES:IAvH-A-17179
IAvH:COLECCIONES:AVES:IAvH-A-17294
IAvH:COLECCIONES:AVES:IAvH-A-17178
IAvH:COLECCIONES:AVES:IAvH-A-17295
IAvH:COLECCIONES:AVES:IAvH-A-17296
IAvH:COLECCIONES:AVES:IAvH-A-17297
IAvH:COLECCIONES:AVES:IAvH-A-17298
IAvH:COLECCIONES:AVES:IAvH-A-17299
IAvH:COLECCIONES:AVES:IAvH-A-17300
IAvH:COLECCIONES:AVES:IAvH-A-17301
```

<details>
<summary>Publisher email</summary>

Hello,

I am contacting you from the GBIF Secretariat about a dataset published by the [Colección de Aves del Instituto de Investigación de Recursos Biológicos Alexander von Humboldt (IAvH-A)](https://registry.gbif.org/dataset/3bef6fb2-9a1f-4d8d-b5f3-d6d23885905c) : https://doi.org/10.15472/maeoiz.
We noticed that the occurrenceIDs were changed. We have temporarily paused the ingestions of this dataset.

As you might already know, when an occurrence record has a new occurrenceID for a given dataset, our system considers it to be a new occurrence.
This means that it will be given a new gbifid and a new occurrence URL (like this one: https://www.gbif.org/occurrence/1252968762) and the old gbifid and URL will be deprecated.

In this case, this means that the occurrence URLs would be deprecated when ingesting the newest versions of these datasets.

We would like to check with you if those changes were intentional. Do you know if this is the case?
Please let us know, thanks! We are happy to resume the dataset ingestion.

Note that some users rely on those occurrence URLs and gbifids (like https://bionomia.net for example). In an attempt to improve
the stability of the occurrence URLs and gbifids, we have implemented a warning system to detect these type of changes in datasets (see this news item).
If the data publisher can provide us with a list of old and new occurrenceIDs per record, we can avoid the identifier and URL changes. Could that be an option?

Please let us know if you have any question. Thanks!

All the best,

</details>


You can skip/fix identifier validation using [the registry UI](https://registry.gbif.org/dataset/3bef6fb2-9a1f-4d8d-b5f3-d6d23885905c/ingestion-history).

**Comment by jhnwllr** [comment]
@EstebanMH-SiB Can we proceed with ingestion here?
