### ISSUE TITLE
Identifiers validation failed for dataset PCS Papua New Guinea, 2022-2023

### ISSUE THREAD

**Issue by gbif-pipelines** [gbif/ingestion-management#985]
Identifier validation failed for the dataset [PCS Papua New Guinea, 2022-2023](https://registry.gbif.org/dataset/6691704f-c380-43e0-95ea-1dfd346fa109):
- Crawler attempt: 2
- Publishing organization: [TotalEnergies](https://registry.gbif.org/organization/728e3362-3063-4a43-a6cf-71d61b50025b)
- Publishing country: FRANCE
- Installation: [IPT GBIF France](https://registry.gbif.org/installation/791e3715-7452-4dd0-a906-db21a3852427)
- Number of occurrences indexed for this dataset at the time of the issue: 661
- Cause: GBIF ID problems exceed 50% threshold: 100% duplicates; 18 total records; 18 absent records
- Pipelines execution steps: [http://api.gbif.org/v1/pipelines/history/execution/3503653/step](http://api.gbif.org/v1/pipelines/history/execution/3503653/step)

```
New IDs sample:


```

```
Old IDs sample:

09bd5e32-a0e5-11ee-8c90-0242ac120002
09bd60e4-a0e5-11ee-8c90-0242ac120002
09bd6210-a0e5-11ee-8c90-0242ac120002
09bd631e-a0e5-11ee-8c90-0242ac120002
09bd6422-a0e5-11ee-8c90-0242ac120002
09bd651c-a0e5-11ee-8c90-0242ac120002
09bd686e-a0e5-11ee-8c90-0242ac120002
09bd6986-a0e5-11ee-8c90-0242ac120002
09bd6a80-a0e5-11ee-8c90-0242ac120002
09bd6b7a-a0e5-11ee-8c90-0242ac120002
```

<details>
<summary>Publisher email</summary>

Hello,

I am contacting you from the GBIF Secretariat about a dataset published by the [PCS Papua New Guinea, 2022-2023](https://registry.gbif.org/dataset/6691704f-c380-43e0-95ea-1dfd346fa109) : https://doi.org/10.15468/yg8b8t.
We noticed that the occurrenceIDs were changed. We have temporarily paused the ingestions of this dataset.

As you might already know, when an occurrence record has a new occurrenceID for a given dataset, our system considers it to be a new occurrence.
This means that it will be given a new gbifid and a new occurrence URL (like this one: https://www.gbif.org/occurrence/1252968762) and the old gbifid and URL will be deprecated.

In this case, this means that the occurrence URLs would be deprecated when ingesting the newest versions of these datasets.

We would like to check with you if those changes were intentional. Do you know if this is the case?
Please let us know, thanks! We are happy to resume the dataset ingestion.

Note that some users rely on those occurrence URLs and gbifids (like https://bionomia.net for example). In an attempt to improve
the stability of the occurrence URLs and gbifids, we have implemented a warning system to detect these type of changes in datasets (see this news item).
If the data publisher can provide us with a list of old and new occurrenceIDs per record, we can avoid the identifier and URL changes. Could that be an option?

Please let us know if you have any question. Thanks!

All the best,

</details>

You can skip/fix identifier validation using [the registry UI](https://registry.gbif.org/dataset/6691704f-c380-43e0-95ea-1dfd346fa109/ingestion-history).

**Comment by gbif-pipelines** [comment]
Identifier validation still  failing for the dataset [PCS Papua New Guinea, 2022-2023](https://registry.gbif.org/dataset/6691704f-c380-43e0-95ea-1dfd346fa109):
- Crawler attempt: 3
- Publishing organization: [TotalEnergies](https://registry.gbif.org/organization/728e3362-3063-4a43-a6cf-71d61b50025b)
- Publishing country: FRANCE
- Installation: [IPT GBIF France](https://registry.gbif.org/installation/791e3715-7452-4dd0-a906-db21a3852427)
- Number of occurrences indexed for this dataset at the time of the issue: 661
- Cause: GBIF ID problems exceed 50% threshold: 100% duplicates; 18 total records; 18 absent records
- Pipelines execution steps: [http://api.gbif.org/v1/pipelines/history/execution/3503667/step](http://api.gbif.org/v1/pipelines/history/execution/3503667/step)

```
New IDs sample:


```


```
Old IDs sample:

09bd5e32-a0e5-11ee-8c90-0242ac120002
09bd60e4-a0e5-11ee-8c90-0242ac120002
09bd6210-a0e5-11ee-8c90-0242ac120002
09bd631e-a0e5-11ee-8c90-0242ac120002
09bd6422-a0e5-11ee-8c90-0242ac120002
09bd651c-a0e5-11ee-8c90-0242ac120002
09bd686e-a0e5-11ee-8c90-0242ac120002
09bd6986-a0e5-11ee-8c90-0242ac120002
09bd6a80-a0e5-11ee-8c90-0242ac120002
09bd6b7a-a0e5-11ee-8c90-0242ac120002
```

<details>
<summary>Publisher email</summary>

Hello,

I am contacting you from the GBIF Secretariat about a dataset published by the [PCS Papua New Guinea, 2022-2023](https://registry.gbif.org/dataset/6691704f-c380-43e0-95ea-1dfd346fa109) : https://doi.org/10.15468/yg8b8t.
We noticed that the occurrenceIDs were changed. We have temporarily paused the ingestions of this dataset.

As you might already know, when an occurrence record has a new occurrenceID for a given dataset, our system considers it to be a new occurrence.
This means that it will be given a new gbifid and a new occurrence URL (like this one: https://www.gbif.org/occurrence/1252968762) and the old gbifid and URL will be deprecated.

In this case, this means that the occurrence URLs would be deprecated when ingesting the newest versions of these datasets.

We would like to check with you if those changes were intentional. Do you know if this is the case?
Please let us know, thanks! We are happy to resume the dataset ingestion.

Note that some users rely on those occurrence URLs and gbifids (like https://bionomia.net for example). In an attempt to improve
the stability of the occurrence URLs and gbifids, we have implemented a warning system to detect these type of changes in datasets (see this news item).
If the data publisher can provide us with a list of old and new occurrenceIDs per record, we can avoid the identifier and URL changes. Could that be an option?

Please let us know if you have any question. Thanks!

All the best,

</details>


You can skip/fix identifier validation using [the registry UI](https://registry.gbif.org/dataset/6691704f-c380-43e0-95ea-1dfd346fa109/ingestion-history).

**Comment by gbif-pipelines** [comment]
Identifier validation still  failing for the dataset [PCS PNG, 2022-2023](https://registry.gbif.org/dataset/6691704f-c380-43e0-95ea-1dfd346fa109):
- Crawler attempt: 4
- Publishing organization: [TotalEnergies](https://registry.gbif.org/organization/728e3362-3063-4a43-a6cf-71d61b50025b)
- Publishing country: FRANCE
- Installation: [IPT GBIF France](https://registry.gbif.org/installation/791e3715-7452-4dd0-a906-db21a3852427)
- Number of occurrences indexed for this dataset at the time of the issue: 661
- Cause: GBIF ID problems exceed 50% threshold: 100% duplicates; 18 total records; 18 absent records
- Pipelines execution steps: [http://api.gbif.org/v1/pipelines/history/execution/3503669/step](http://api.gbif.org/v1/pipelines/history/execution/3503669/step)

```
New IDs sample:


```


```
Old IDs sample:

09bd5e32-a0e5-11ee-8c90-0242ac120002
09bd60e4-a0e5-11ee-8c90-0242ac120002
09bd6210-a0e5-11ee-8c90-0242ac120002
09bd631e-a0e5-11ee-8c90-0242ac120002
09bd6422-a0e5-11ee-8c90-0242ac120002
09bd651c-a0e5-11ee-8c90-0242ac120002
09bd686e-a0e5-11ee-8c90-0242ac120002
09bd6986-a0e5-11ee-8c90-0242ac120002
09bd6a80-a0e5-11ee-8c90-0242ac120002
09bd6b7a-a0e5-11ee-8c90-0242ac120002
```

<details>
<summary>Publisher email</summary>

Hello,

I am contacting you from the GBIF Secretariat about a dataset published by the [PCS PNG, 2022-2023](https://registry.gbif.org/dataset/6691704f-c380-43e0-95ea-1dfd346fa109) : https://doi.org/10.15468/yg8b8t.
We noticed that the occurrenceIDs were changed. We have temporarily paused the ingestions of this dataset.

As you might already know, when an occurrence record has a new occurrenceID for a given dataset, our system considers it to be a new occurrence.
This means that it will be given a new gbifid and a new occurrence URL (like this one: https://www.gbif.org/occurrence/1252968762) and the old gbifid and URL will be deprecated.

In this case, this means that the occurrence URLs would be deprecated when ingesting the newest versions of these datasets.

We would like to check with you if those changes were intentional. Do you know if this is the case?
Please let us know, thanks! We are happy to resume the dataset ingestion.

Note that some users rely on those occurrence URLs and gbifids (like https://bionomia.net for example). In an attempt to improve
the stability of the occurrence URLs and gbifids, we have implemented a warning system to detect these type of changes in datasets (see this news item).
If the data publisher can provide us with a list of old and new occurrenceIDs per record, we can avoid the identifier and URL changes. Could that be an option?

Please let us know if you have any question. Thanks!

All the best,

</details>


You can skip/fix identifier validation using [the registry UI](https://registry.gbif.org/dataset/6691704f-c380-43e0-95ea-1dfd346fa109/ingestion-history).

**Comment by gbif-pipelines** [comment]
Identifier validation still  failing for the dataset [PCS PNG, 2022-2023](https://registry.gbif.org/dataset/6691704f-c380-43e0-95ea-1dfd346fa109):
- Crawler attempt: 5
- Publishing organization: [TotalEnergies](https://registry.gbif.org/organization/728e3362-3063-4a43-a6cf-71d61b50025b)
- Publishing country: FRANCE
- Installation: [IPT GBIF France](https://registry.gbif.org/installation/791e3715-7452-4dd0-a906-db21a3852427)
- Number of occurrences indexed for this dataset at the time of the issue: 661
- Cause: GBIF ID problems exceed 50% threshold: 100% duplicates; 18 total records; 18 absent records
- Pipelines execution steps: [http://api.gbif.org/v1/pipelines/history/execution/3503687/step](http://api.gbif.org/v1/pipelines/history/execution/3503687/step)

```
New IDs sample:


```


```
Old IDs sample:

09bd5e32-a0e5-11ee-8c90-0242ac120002
09bd60e4-a0e5-11ee-8c90-0242ac120002
09bd6210-a0e5-11ee-8c90-0242ac120002
09bd631e-a0e5-11ee-8c90-0242ac120002
09bd6422-a0e5-11ee-8c90-0242ac120002
09bd651c-a0e5-11ee-8c90-0242ac120002
09bd686e-a0e5-11ee-8c90-0242ac120002
09bd6986-a0e5-11ee-8c90-0242ac120002
09bd6a80-a0e5-11ee-8c90-0242ac120002
09bd6b7a-a0e5-11ee-8c90-0242ac120002
```

<details>
<summary>Publisher email</summary>

Hello,

I am contacting you from the GBIF Secretariat about a dataset published by the [PCS PNG, 2022-2023](https://registry.gbif.org/dataset/6691704f-c380-43e0-95ea-1dfd346fa109) : https://doi.org/10.15468/yg8b8t.
We noticed that the occurrenceIDs were changed. We have temporarily paused the ingestions of this dataset.

As you might already know, when an occurrence record has a new occurrenceID for a given dataset, our system considers it to be a new occurrence.
This means that it will be given a new gbifid and a new occurrence URL (like this one: https://www.gbif.org/occurrence/1252968762) and the old gbifid and URL will be deprecated.

In this case, this means that the occurrence URLs would be deprecated when ingesting the newest versions of these datasets.

We would like to check with you if those changes were intentional. Do you know if this is the case?
Please let us know, thanks! We are happy to resume the dataset ingestion.

Note that some users rely on those occurrence URLs and gbifids (like https://bionomia.net for example). In an attempt to improve
the stability of the occurrence URLs and gbifids, we have implemented a warning system to detect these type of changes in datasets (see this news item).
If the data publisher can provide us with a list of old and new occurrenceIDs per record, we can avoid the identifier and URL changes. Could that be an option?

Please let us know if you have any question. Thanks!

All the best,

</details>


You can skip/fix identifier validation using [the registry UI](https://registry.gbif.org/dataset/6691704f-c380-43e0-95ea-1dfd346fa109/ingestion-history).

**Comment by ManonGros** [comment]
Hi @SophiePamerlon it looks like this dataset (https://ipt.gbif.fr/resource?r=pcs-r05-papua-new-guinea-2022-2023) ingestion is paused because all the identifiers are new. Would it be possible to take a look?
Also the number of occurrence was 661 in the original version and dropped to 18 in the new versions. Do you know if this is intentional? Should we resume the dataset ingestion?
Let us know, thanks!

**Comment by gbif-pipelines** [comment]
Identifier validation still  failing for the dataset [PCS PNG, 2022-2023](https://registry.gbif.org/dataset/6691704f-c380-43e0-95ea-1dfd346fa109):
- Crawler attempt: 6
- Publishing organization: [TotalEnergies](https://registry.gbif.org/organization/728e3362-3063-4a43-a6cf-71d61b50025b)
- Publishing country: FRANCE
- Installation: [IPT GBIF France](https://registry.gbif.org/installation/791e3715-7452-4dd0-a906-db21a3852427)
- Number of occurrences indexed for this dataset at the time of the issue: 661
- Cause: GBIF ID problems exceed 50% threshold: 100% duplicates; 18 total records; 18 absent records
- Pipelines execution steps: [http://api.gbif.org/v1/pipelines/history/execution/3503702/step](http://api.gbif.org/v1/pipelines/history/execution/3503702/step)

```
New IDs sample:


```


```
Old IDs sample:

09bd5e32-a0e5-11ee-8c90-0242ac120002
09bd60e4-a0e5-11ee-8c90-0242ac120002
09bd6210-a0e5-11ee-8c90-0242ac120002
09bd631e-a0e5-11ee-8c90-0242ac120002
09bd6422-a0e5-11ee-8c90-0242ac120002
09bd651c-a0e5-11ee-8c90-0242ac120002
09bd686e-a0e5-11ee-8c90-0242ac120002
09bd6986-a0e5-11ee-8c90-0242ac120002
09bd6a80-a0e5-11ee-8c90-0242ac120002
09bd6b7a-a0e5-11ee-8c90-0242ac120002
```

<details>
<summary>Publisher email</summary>

Hello,

I am contacting you from the GBIF Secretariat about a dataset published by the [PCS PNG, 2022-2023](https://registry.gbif.org/dataset/6691704f-c380-43e0-95ea-1dfd346fa109) : https://doi.org/10.15468/yg8b8t.
We noticed that the occurrenceIDs were changed. We have temporarily paused the ingestions of this dataset.

As you might already know, when an occurrence record has a new occurrenceID for a given dataset, our system considers it to be a new occurrence.
This means that it will be given a new gbifid and a new occurrence URL (like this one: https://www.gbif.org/occurrence/1252968762) and the old gbifid and URL will be deprecated.

In this case, this means that the occurrence URLs would be deprecated when ingesting the newest versions of these datasets.

We would like to check with you if those changes were intentional. Do you know if this is the case?
Please let us know, thanks! We are happy to resume the dataset ingestion.

Note that some users rely on those occurrence URLs and gbifids (like https://bionomia.net for example). In an attempt to improve
the stability of the occurrence URLs and gbifids, we have implemented a warning system to detect these type of changes in datasets (see this news item).
If the data publisher can provide us with a list of old and new occurrenceIDs per record, we can avoid the identifier and URL changes. Could that be an option?

Please let us know if you have any question. Thanks!

All the best,

</details>


You can skip/fix identifier validation using [the registry UI](https://registry.gbif.org/dataset/6691704f-c380-43e0-95ea-1dfd346fa109/ingestion-history).

**Comment by SophiePamerlon** [comment]
@ManonGros Thanks for notiying me of this issue, I'll get in touch with the data publisher & get back to you asap :)

**Comment by gbif-pipelines** [comment]
Identifier validation still  failing for the dataset [PCS PNG, 2022-2023](https://registry.gbif.org/dataset/6691704f-c380-43e0-95ea-1dfd346fa109):
- Crawler attempt: 7
- Publishing organization: [TotalEnergies](https://registry.gbif.org/organization/728e3362-3063-4a43-a6cf-71d61b50025b)
- Publishing country: FRANCE
- Installation: [IPT GBIF France](https://registry.gbif.org/installation/791e3715-7452-4dd0-a906-db21a3852427)
- Number of occurrences indexed for this dataset at the time of the issue: 661
- Cause: GBIF ID problems exceed 50% threshold: 100% duplicates; 18 total records; 18 absent records
- Pipelines execution steps: [http://api.gbif.org/v1/pipelines/history/execution/3503725/step](http://api.gbif.org/v1/pipelines/history/execution/3503725/step)

```
New IDs sample:


```


```
Old IDs sample:

09bd5e32-a0e5-11ee-8c90-0242ac120002
09bd60e4-a0e5-11ee-8c90-0242ac120002
09bd6210-a0e5-11ee-8c90-0242ac120002
09bd631e-a0e5-11ee-8c90-0242ac120002
09bd6422-a0e5-11ee-8c90-0242ac120002
09bd651c-a0e5-11ee-8c90-0242ac120002
09bd686e-a0e5-11ee-8c90-0242ac120002
09bd6986-a0e5-11ee-8c90-0242ac120002
09bd6a80-a0e5-11ee-8c90-0242ac120002
09bd6b7a-a0e5-11ee-8c90-0242ac120002
```

<details>
<summary>Publisher email</summary>

Hello,

I am contacting you from the GBIF Secretariat about a dataset published by the [PCS PNG, 2022-2023](https://registry.gbif.org/dataset/6691704f-c380-43e0-95ea-1dfd346fa109) : https://doi.org/10.15468/yg8b8t.
We noticed that the occurrenceIDs were changed. We have temporarily paused the ingestions of this dataset.

As you might already know, when an occurrence record has a new occurrenceID for a given dataset, our system considers it to be a new occurrence.
This means that it will be given a new gbifid and a new occurrence URL (like this one: https://www.gbif.org/occurrence/1252968762) and the old gbifid and URL will be deprecated.

In this case, this means that the occurrence URLs would be deprecated when ingesting the newest versions of these datasets.

We would like to check with you if those changes were intentional. Do you know if this is the case?
Please let us know, thanks! We are happy to resume the dataset ingestion.

Note that some users rely on those occurrence URLs and gbifids (like https://bionomia.net for example). In an attempt to improve
the stability of the occurrence URLs and gbifids, we have implemented a warning system to detect these type of changes in datasets (see this news item).
If the data publisher can provide us with a list of old and new occurrenceIDs per record, we can avoid the identifier and URL changes. Could that be an option?

Please let us know if you have any question. Thanks!

All the best,

</details>


You can skip/fix identifier validation using [the registry UI](https://registry.gbif.org/dataset/6691704f-c380-43e0-95ea-1dfd346fa109/ingestion-history).
