### ISSUE TITLE
Identifiers validation failed for dataset PCS Papua New Guinea, 2022-2023

### ISSUE THREAD

**Issue by gbif-pipelines** [gbif/ingestion-management#986]
Identifier validation failed for the dataset [PCS Papua New Guinea, 2022-2023](https://registry.gbif.org/dataset/2e488e38-63f1-4912-a9c8-f8574a200f1b):
- Crawler attempt: 2
- Publishing organization: [TotalEnergies](https://registry.gbif.org/organization/728e3362-3063-4a43-a6cf-71d61b50025b)
- Publishing country: FRANCE
- Installation: [IPT GBIF France](https://registry.gbif.org/installation/791e3715-7452-4dd0-a906-db21a3852427)
- Number of occurrences indexed for this dataset at the time of the issue: 18
- Cause: GBIF ID problems exceed 50% threshold: 100% duplicates; 660 total records; 660 absent records
- Pipelines execution steps: [http://api.gbif.org/v1/pipelines/history/execution/3503709/step](http://api.gbif.org/v1/pipelines/history/execution/3503709/step)

```
New IDs sample:


```

```
Old IDs sample:

554986f6-a0e4-11ee-8c90-0242ac120002
55498c28-a0e4-11ee-8c90-0242ac120002
55498e1c-a0e4-11ee-8c90-0242ac120002
55498fde-a0e4-11ee-8c90-0242ac120002
554991f0-a0e4-11ee-8c90-0242ac120002
554994c0-a0e4-11ee-8c90-0242ac120002
554999d4-a0e4-11ee-8c90-0242ac120002
55499c22-a0e4-11ee-8c90-0242ac120002
55499dda-a0e4-11ee-8c90-0242ac120002
55499f92-a0e4-11ee-8c90-0242ac120002
```

<details>
<summary>Publisher email</summary>

Hello,

I am contacting you from the GBIF Secretariat about a dataset published by the [PCS Papua New Guinea, 2022-2023](https://registry.gbif.org/dataset/2e488e38-63f1-4912-a9c8-f8574a200f1b) : https://doi.org/10.15468/gbz4m4.
We noticed that the occurrenceIDs were changed. We have temporarily paused the ingestions of this dataset.

As you might already know, when an occurrence record has a new occurrenceID for a given dataset, our system considers it to be a new occurrence.
This means that it will be given a new gbifid and a new occurrence URL (like this one: https://www.gbif.org/occurrence/1252968762) and the old gbifid and URL will be deprecated.

In this case, this means that the occurrence URLs would be deprecated when ingesting the newest versions of these datasets.

We would like to check with you if those changes were intentional. Do you know if this is the case?
Please let us know, thanks! We are happy to resume the dataset ingestion.

Note that some users rely on those occurrence URLs and gbifids (like https://bionomia.net for example). In an attempt to improve
the stability of the occurrence URLs and gbifids, we have implemented a warning system to detect these type of changes in datasets (see this news item).
If the data publisher can provide us with a list of old and new occurrenceIDs per record, we can avoid the identifier and URL changes. Could that be an option?

Please let us know if you have any question. Thanks!

All the best,

</details>

You can skip/fix identifier validation using [the registry UI](https://registry.gbif.org/dataset/2e488e38-63f1-4912-a9c8-f8574a200f1b/ingestion-history).

**Comment by gbif-pipelines** [comment]
Identifier validation still  failing for the dataset [PCS Papua New Guinea, 2022-2023](https://registry.gbif.org/dataset/2e488e38-63f1-4912-a9c8-f8574a200f1b):
- Crawler attempt: 3
- Publishing organization: [TotalEnergies](https://registry.gbif.org/organization/728e3362-3063-4a43-a6cf-71d61b50025b)
- Publishing country: FRANCE
- Installation: [IPT GBIF France](https://registry.gbif.org/installation/791e3715-7452-4dd0-a906-db21a3852427)
- Number of occurrences indexed for this dataset at the time of the issue: 18
- Cause: GBIF ID problems exceed 50% threshold: 100% duplicates; 18 total records; 18 absent records
- Pipelines execution steps: [http://api.gbif.org/v1/pipelines/history/execution/3503714/step](http://api.gbif.org/v1/pipelines/history/execution/3503714/step)

```
New IDs sample:


```


```
Old IDs sample:

554986f6-a0e4-11ee-8c90-0242ac120002
55498c28-a0e4-11ee-8c90-0242ac120002
55498e1c-a0e4-11ee-8c90-0242ac120002
55498fde-a0e4-11ee-8c90-0242ac120002
554991f0-a0e4-11ee-8c90-0242ac120002
554994c0-a0e4-11ee-8c90-0242ac120002
554999d4-a0e4-11ee-8c90-0242ac120002
55499c22-a0e4-11ee-8c90-0242ac120002
55499dda-a0e4-11ee-8c90-0242ac120002
55499f92-a0e4-11ee-8c90-0242ac120002
```

<details>
<summary>Publisher email</summary>

Hello,

I am contacting you from the GBIF Secretariat about a dataset published by the [PCS Papua New Guinea, 2022-2023](https://registry.gbif.org/dataset/2e488e38-63f1-4912-a9c8-f8574a200f1b) : https://doi.org/10.15468/gbz4m4.
We noticed that the occurrenceIDs were changed. We have temporarily paused the ingestions of this dataset.

As you might already know, when an occurrence record has a new occurrenceID for a given dataset, our system considers it to be a new occurrence.
This means that it will be given a new gbifid and a new occurrence URL (like this one: https://www.gbif.org/occurrence/1252968762) and the old gbifid and URL will be deprecated.

In this case, this means that the occurrence URLs would be deprecated when ingesting the newest versions of these datasets.

We would like to check with you if those changes were intentional. Do you know if this is the case?
Please let us know, thanks! We are happy to resume the dataset ingestion.

Note that some users rely on those occurrence URLs and gbifids (like https://bionomia.net for example). In an attempt to improve
the stability of the occurrence URLs and gbifids, we have implemented a warning system to detect these type of changes in datasets (see this news item).
If the data publisher can provide us with a list of old and new occurrenceIDs per record, we can avoid the identifier and URL changes. Could that be an option?

Please let us know if you have any question. Thanks!

All the best,

</details>


You can skip/fix identifier validation using [the registry UI](https://registry.gbif.org/dataset/2e488e38-63f1-4912-a9c8-f8574a200f1b/ingestion-history).

**Comment by gbif-pipelines** [comment]
Identifier validation still  failing for the dataset [PCS Papua New Guinea, 2022-2023](https://registry.gbif.org/dataset/2e488e38-63f1-4912-a9c8-f8574a200f1b):
- Crawler attempt: 4
- Publishing organization: [TotalEnergies](https://registry.gbif.org/organization/728e3362-3063-4a43-a6cf-71d61b50025b)
- Publishing country: FRANCE
- Installation: [IPT GBIF France](https://registry.gbif.org/installation/791e3715-7452-4dd0-a906-db21a3852427)
- Number of occurrences indexed for this dataset at the time of the issue: 18
- Cause: GBIF ID problems exceed 50% threshold: 100% duplicates; 18 total records; 18 absent records
- Pipelines execution steps: [http://api.gbif.org/v1/pipelines/history/execution/3503721/step](http://api.gbif.org/v1/pipelines/history/execution/3503721/step)

```
New IDs sample:


```


```
Old IDs sample:

554986f6-a0e4-11ee-8c90-0242ac120002
55498c28-a0e4-11ee-8c90-0242ac120002
55498e1c-a0e4-11ee-8c90-0242ac120002
55498fde-a0e4-11ee-8c90-0242ac120002
554991f0-a0e4-11ee-8c90-0242ac120002
554994c0-a0e4-11ee-8c90-0242ac120002
554999d4-a0e4-11ee-8c90-0242ac120002
55499c22-a0e4-11ee-8c90-0242ac120002
55499dda-a0e4-11ee-8c90-0242ac120002
55499f92-a0e4-11ee-8c90-0242ac120002
```

<details>
<summary>Publisher email</summary>

Hello,

I am contacting you from the GBIF Secretariat about a dataset published by the [PCS Papua New Guinea, 2022-2023](https://registry.gbif.org/dataset/2e488e38-63f1-4912-a9c8-f8574a200f1b) : https://doi.org/10.15468/gbz4m4.
We noticed that the occurrenceIDs were changed. We have temporarily paused the ingestions of this dataset.

As you might already know, when an occurrence record has a new occurrenceID for a given dataset, our system considers it to be a new occurrence.
This means that it will be given a new gbifid and a new occurrence URL (like this one: https://www.gbif.org/occurrence/1252968762) and the old gbifid and URL will be deprecated.

In this case, this means that the occurrence URLs would be deprecated when ingesting the newest versions of these datasets.

We would like to check with you if those changes were intentional. Do you know if this is the case?
Please let us know, thanks! We are happy to resume the dataset ingestion.

Note that some users rely on those occurrence URLs and gbifids (like https://bionomia.net for example). In an attempt to improve
the stability of the occurrence URLs and gbifids, we have implemented a warning system to detect these type of changes in datasets (see this news item).
If the data publisher can provide us with a list of old and new occurrenceIDs per record, we can avoid the identifier and URL changes. Could that be an option?

Please let us know if you have any question. Thanks!

All the best,

</details>


You can skip/fix identifier validation using [the registry UI](https://registry.gbif.org/dataset/2e488e38-63f1-4912-a9c8-f8574a200f1b/ingestion-history).

**Comment by gbif-pipelines** [comment]
Identifier validation still  failing for the dataset [PCS Papua New Guinea, 2022-2023](https://registry.gbif.org/dataset/2e488e38-63f1-4912-a9c8-f8574a200f1b):
- Crawler attempt: 5
- Publishing organization: [TotalEnergies](https://registry.gbif.org/organization/728e3362-3063-4a43-a6cf-71d61b50025b)
- Publishing country: FRANCE
- Installation: [IPT GBIF France](https://registry.gbif.org/installation/791e3715-7452-4dd0-a906-db21a3852427)
- Number of occurrences indexed for this dataset at the time of the issue: 18
- Cause: GBIF ID problems exceed 50% threshold: 100% duplicates; 660 total records; 660 absent records
- Pipelines execution steps: [http://api.gbif.org/v1/pipelines/history/execution/3503724/step](http://api.gbif.org/v1/pipelines/history/execution/3503724/step)

```
New IDs sample:


```


```
Old IDs sample:

554986f6-a0e4-11ee-8c90-0242ac120002
55498c28-a0e4-11ee-8c90-0242ac120002
55498e1c-a0e4-11ee-8c90-0242ac120002
55498fde-a0e4-11ee-8c90-0242ac120002
554991f0-a0e4-11ee-8c90-0242ac120002
554994c0-a0e4-11ee-8c90-0242ac120002
554999d4-a0e4-11ee-8c90-0242ac120002
55499c22-a0e4-11ee-8c90-0242ac120002
55499dda-a0e4-11ee-8c90-0242ac120002
55499f92-a0e4-11ee-8c90-0242ac120002
```

<details>
<summary>Publisher email</summary>

Hello,

I am contacting you from the GBIF Secretariat about a dataset published by the [PCS Papua New Guinea, 2022-2023](https://registry.gbif.org/dataset/2e488e38-63f1-4912-a9c8-f8574a200f1b) : https://doi.org/10.15468/gbz4m4.
We noticed that the occurrenceIDs were changed. We have temporarily paused the ingestions of this dataset.

As you might already know, when an occurrence record has a new occurrenceID for a given dataset, our system considers it to be a new occurrence.
This means that it will be given a new gbifid and a new occurrence URL (like this one: https://www.gbif.org/occurrence/1252968762) and the old gbifid and URL will be deprecated.

In this case, this means that the occurrence URLs would be deprecated when ingesting the newest versions of these datasets.

We would like to check with you if those changes were intentional. Do you know if this is the case?
Please let us know, thanks! We are happy to resume the dataset ingestion.

Note that some users rely on those occurrence URLs and gbifids (like https://bionomia.net for example). In an attempt to improve
the stability of the occurrence URLs and gbifids, we have implemented a warning system to detect these type of changes in datasets (see this news item).
If the data publisher can provide us with a list of old and new occurrenceIDs per record, we can avoid the identifier and URL changes. Could that be an option?

Please let us know if you have any question. Thanks!

All the best,

</details>


You can skip/fix identifier validation using [the registry UI](https://registry.gbif.org/dataset/2e488e38-63f1-4912-a9c8-f8574a200f1b/ingestion-history).

**Comment by ManonGros** [comment]
@SophiePamerlon on dirait bien que deux je de données sont concernées (et ils ont le même titre) sont-il des doublons?

**Comment by SophiePamerlon** [comment]
@ManonGros Après vérification auprès du data publisher, ce sont bien deux jeux de données distincts collectés dans le même pays (les titres ont été modifiés pour plus de clarté) ; le souci d'indexation semble résolu après re-publication de leur part hier car je vois bien les occurrences sur leurs pages respectives ? https://www.gbif.org/dataset/6691704f-c380-43e0-95ea-1dfd346fa109 et https://www.gbif.org/dataset/2e488e38-63f1-4912-a9c8-f8574a200f1b

**Comment by ManonGros** [comment]
En effet, merci @SophiePamerlon !
