### ISSUE TITLE
Identifiers validation failed for dataset TotalEnergies EP Brasil| Projeto de Caracterização Ambiental (PCA)/Environmental Baseline Study (EBS) do Bloco C-M-541, Bacia de Campos: Meiofauna

### ISSUE THREAD

**Issue by gbif-pipelines** [gbif/ingestion-management#989]
Identifier validation failed for the dataset [TotalEnergies EP Brasil| Projeto de Caracterização Ambiental (PCA)/Environmental Baseline Study (EBS) do Bloco C-M-541, Bacia de Campos: Meiofauna](https://registry.gbif.org/dataset/a5bf4314-d23a-4102-98af-4f25b808eaf9):
- Crawler attempt: 4
- Publishing organization: [TotalEnergies](https://registry.gbif.org/organization/728e3362-3063-4a43-a6cf-71d61b50025b)
- Publishing country: FRANCE
- Installation: [IPT Sistema de Informação sobre a Biodiversidade Brasileira - SiBBr](https://registry.gbif.org/installation/d0709e6e-78bf-49e8-8814-384ac4fb139f)
- Number of occurrences indexed for this dataset at the time of the issue: 209
- Cause: GBIF ID problems exceed 50% threshold: 100% duplicates; 209 total records; 209 absent records
- Pipelines execution steps: [http://api.gbif.org/v1/pipelines/history/execution/3512992/step](http://api.gbif.org/v1/pipelines/history/execution/3512992/step)

```
New IDs sample:


```

```
Old IDs sample:

BR_TOTALENERGIES_EBSC-M-541_Bacia de Campos_MeioFauna_Estação 003_Réplica 1_2020: 1
BR_TOTALENERGIES_EBSC-M-541_Bacia de Campos_MeioFauna_Estação 003_Réplica 1_2020: 2
BR_TOTALENERGIES_EBSC-M-541_Bacia de Campos_MeioFauna_Estação 003_Réplica 1_2020: 3
BR_TOTALENERGIES_EBSC-M-541_Bacia de Campos_MeioFauna_Estação 003_Réplica 2_2020: 10
BR_TOTALENERGIES_EBSC-M-541_Bacia de Campos_MeioFauna_Estação 003_Réplica 2_2020: 11
BR_TOTALENERGIES_EBSC-M-541_Bacia de Campos_MeioFauna_Estação 003_Réplica 2_2020: 12
BR_TOTALENERGIES_EBSC-M-541_Bacia de Campos_MeioFauna_Estação 003_Réplica 2_2020: 13
BR_TOTALENERGIES_EBSC-M-541_Bacia de Campos_MeioFauna_Estação 003_Réplica 2_2020: 14
BR_TOTALENERGIES_EBSC-M-541_Bacia de Campos_MeioFauna_Estação 003_Réplica 2_2020: 4
BR_TOTALENERGIES_EBSC-M-541_Bacia de Campos_MeioFauna_Estação 003_Réplica 2_2020: 5
```

<details>
<summary>Publisher email</summary>

Hello,

I am contacting you from the GBIF Secretariat about a dataset published by the [TotalEnergies EP Brasil| Projeto de Caracterização Ambiental (PCA)/Environmental Baseline Study (EBS) do Bloco C-M-541, Bacia de Campos: Meiofauna](https://registry.gbif.org/dataset/a5bf4314-d23a-4102-98af-4f25b808eaf9) : https://doi.org/10.15468/a6cwum.
We noticed that the occurrenceIDs were changed. We have temporarily paused the ingestions of this dataset.

As you might already know, when an occurrence record has a new occurrenceID for a given dataset, our system considers it to be a new occurrence.
This means that it will be given a new gbifid and a new occurrence URL (like this one: https://www.gbif.org/occurrence/1252968762) and the old gbifid and URL will be deprecated.

In this case, this means that the occurrence URLs would be deprecated when ingesting the newest versions of these datasets.

We would like to check with you if those changes were intentional. Do you know if this is the case?
Please let us know, thanks! We are happy to resume the dataset ingestion.

Note that some users rely on those occurrence URLs and gbifids (like https://bionomia.net for example). In an attempt to improve
the stability of the occurrence URLs and gbifids, we have implemented a warning system to detect these type of changes in datasets (see this news item).
If the data publisher can provide us with a list of old and new occurrenceIDs per record, we can avoid the identifier and URL changes. Could that be an option?

Please let us know if you have any question. Thanks!

All the best,

</details>

You can skip/fix identifier validation using [the registry UI](https://registry.gbif.org/dataset/a5bf4314-d23a-4102-98af-4f25b808eaf9/ingestion-history).

**Comment by jhnwllr** [comment]
@ClaraBaringoFonseca this one too
