### ISSUE TITLE
Identifiers validation failed for dataset MICA - Muskrat occurrences collected in West Flanders, Belgium

### ISSUE THREAD

**Issue by gbif-pipelines** [gbif/ingestion-management#990]
Identifier validation failed for the dataset [MICA - Muskrat occurrences collected in West Flanders, Belgium](https://registry.gbif.org/dataset/34b06811-2240-44e0-8a9f-eec5d5a54972):
- Crawler attempt: 7
- Publishing organization: [Research Institute for Nature and Forest (INBO)](https://registry.gbif.org/organization/1cd669d0-80ea-11de-a9d0-f1765f95f18b)
- Publishing country: BELGIUM
- Installation: [INBO IPT](https://registry.gbif.org/installation/9f25fd85-85dc-4dcd-a1b4-b31165442e2b)
- Number of occurrences indexed for this dataset at the time of the issue: 2857
- Cause: GBIF ID problems exceed 50% threshold: 68% duplicates; 2907 total records; 1967 absent records
- Pipelines execution steps: [http://api.gbif.org/v1/pipelines/history/execution/3516935/step](http://api.gbif.org/v1/pipelines/history/execution/3516935/step)

```
New IDs sample:

MICA:W-VL:32007:917
MICA:W-VL:27654:273
MICA:W-VL:27832:276
MICA:W-VL:30314:662
MICA:W-VL:21059:2
MICA:W-VL:28629:360
MICA:W-VL:27381:22
MICA:W-VL:29369:526
MICA:W-VL:29157:461
MICA:W-VL:27921:148
```

```
Old IDs sample:

MICA:W-VL:30104:2565
MICA:W-VL:30118:2566
MICA:W-VL:30120:2567
MICA:W-VL:30121:2754
MICA:W-VL:30123:2568
MICA:W-VL:30124:2755
MICA:W-VL:30124:756
MICA:W-VL:30124:824
MICA:W-VL:30126:2639
MICA:W-VL:30126:759
```

<details>
<summary>Publisher email</summary>

Hello,

I am contacting you from the GBIF Secretariat about a dataset published by the [MICA - Muskrat occurrences collected in West Flanders, Belgium](https://registry.gbif.org/dataset/34b06811-2240-44e0-8a9f-eec5d5a54972) : https://doi.org/10.15468/kpzkx3.
We noticed that the occurrenceIDs were changed. We have temporarily paused the ingestions of this dataset.

As you might already know, when an occurrence record has a new occurrenceID for a given dataset, our system considers it to be a new occurrence.
This means that it will be given a new gbifid and a new occurrence URL (like this one: https://www.gbif.org/occurrence/1252968762) and the old gbifid and URL will be deprecated.

In this case, this means that the occurrence URLs would be deprecated when ingesting the newest versions of these datasets.

We would like to check with you if those changes were intentional. Do you know if this is the case?
Please let us know, thanks! We are happy to resume the dataset ingestion.

Note that some users rely on those occurrence URLs and gbifids (like https://bionomia.net for example). In an attempt to improve
the stability of the occurrence URLs and gbifids, we have implemented a warning system to detect these type of changes in datasets (see this news item).
If the data publisher can provide us with a list of old and new occurrenceIDs per record, we can avoid the identifier and URL changes. Could that be an option?

Please let us know if you have any question. Thanks!

All the best,

</details>

You can skip/fix identifier validation using [the registry UI](https://registry.gbif.org/dataset/34b06811-2240-44e0-8a9f-eec5d5a54972/ingestion-history).

**Comment by ManonGros** [comment]
Hi @DimEvil

Our system paused the ingestion for this dataset because 1,967 out of 2,907 occurrences had new identifiers. This part of our attempt at keeping identifiers stable (see https://data-blog.gbif.org/post/improve-identifier-stability/).

Do you know if this change in occurrenceID was intentional? Should we resume the dataset ingestion?

If you think this might have been an error, you can roll back on the occurrenceIDs and the dataset will be ingested without any issue.
Otherwise, we can either resume the ingestion (which will create new occurrence URLs and delete the old ones) or we can migrate the occurrences (if we have a table of old and new IDs). let us know, thanks!

**Comment by DimEvil** [comment]
Hi @ManonGros 
Thanks for notifying me, I need to check first on what went wrong. there should be no change in the identifiers. So it was not intentional.

**Comment by gbif-pipelines** [comment]
Identifier validation still  failing for the dataset [MICA - Muskrat occurrences collected in West Flanders, Belgium](https://registry.gbif.org/dataset/34b06811-2240-44e0-8a9f-eec5d5a54972):
- Crawler attempt: 8
- Publishing organization: [Research Institute for Nature and Forest (INBO)](https://registry.gbif.org/organization/1cd669d0-80ea-11de-a9d0-f1765f95f18b)
- Publishing country: BELGIUM
- Installation: [INBO IPT](https://registry.gbif.org/installation/9f25fd85-85dc-4dcd-a1b4-b31165442e2b)
- Number of occurrences indexed for this dataset at the time of the issue: 2857
- Cause: GBIF ID problems exceed 50% threshold: 68% duplicates; 2907 total records; 1967 absent records
- Pipelines execution steps: [http://api.gbif.org/v1/pipelines/history/execution/3521914/step](http://api.gbif.org/v1/pipelines/history/execution/3521914/step)

```
New IDs sample:

MICA:W-VL:32007:917
MICA:W-VL:27654:273
MICA:W-VL:27832:276
MICA:W-VL:30314:662
MICA:W-VL:21059:2
MICA:W-VL:28629:360
MICA:W-VL:27381:22
MICA:W-VL:29369:526
MICA:W-VL:29157:461
MICA:W-VL:27921:148
```


```
Old IDs sample:

MICA:W-VL:30104:2565
MICA:W-VL:30118:2566
MICA:W-VL:30120:2567
MICA:W-VL:30121:2754
MICA:W-VL:30123:2568
MICA:W-VL:30124:2755
MICA:W-VL:30124:756
MICA:W-VL:30124:824
MICA:W-VL:30126:2639
MICA:W-VL:30126:759
```

<details>
<summary>Publisher email</summary>

Hello,

I am contacting you from the GBIF Secretariat about a dataset published by the [MICA - Muskrat occurrences collected in West Flanders, Belgium](https://registry.gbif.org/dataset/34b06811-2240-44e0-8a9f-eec5d5a54972) : https://doi.org/10.15468/kpzkx3.
We noticed that the occurrenceIDs were changed. We have temporarily paused the ingestions of this dataset.

As you might already know, when an occurrence record has a new occurrenceID for a given dataset, our system considers it to be a new occurrence.
This means that it will be given a new gbifid and a new occurrence URL (like this one: https://www.gbif.org/occurrence/1252968762) and the old gbifid and URL will be deprecated.

In this case, this means that the occurrence URLs would be deprecated when ingesting the newest versions of these datasets.

We would like to check with you if those changes were intentional. Do you know if this is the case?
Please let us know, thanks! We are happy to resume the dataset ingestion.

Note that some users rely on those occurrence URLs and gbifids (like https://bionomia.net for example). In an attempt to improve
the stability of the occurrence URLs and gbifids, we have implemented a warning system to detect these type of changes in datasets (see this news item).
If the data publisher can provide us with a list of old and new occurrenceIDs per record, we can avoid the identifier and URL changes. Could that be an option?

Please let us know if you have any question. Thanks!

All the best,

</details>


You can skip/fix identifier validation using [the registry UI](https://registry.gbif.org/dataset/34b06811-2240-44e0-8a9f-eec5d5a54972/ingestion-history).

**Comment by DimEvil** [comment]
Hi @ManonGros 

I found the 'bug', I'm trying again, but I'm not sure things are solved. If we get the same issue, the identifiers should be stable...

**Comment by ManonGros** [comment]
Thanks @DimEvil, the data still seems to contain new occurrencdIDs (the newest version is paused as well, with a message that 1,967 occurrences have new IDs).
Perhaps the data wasn't updated in the IPT? Let me know, thanks!

PS: if you think it would best easiest to juts ingest the current data, let me know.
