### ISSUE TITLE
Identifiers validation failed for dataset Base de datos de las Especies y Eventos de las comunidades de plantas del bosque seco en el Caribe tropical de Colombia

### ISSUE THREAD

**Issue by gbif-pipelines** [gbif/ingestion-management#992]
Identifier validation failed for the dataset [Base de datos de las Especies y Eventos de las comunidades de plantas del bosque seco en el Caribe tropical de Colombia](https://registry.gbif.org/dataset/ffb1fe93-b1e9-4a16-8948-9cdf6bf7860e):
- Crawler attempt: 83
- Publishing organization: [Fundación Desarrollo y Ambiente](https://registry.gbif.org/organization/91dec119-ef4a-4f8a-82da-8a1dccf3a86f)
- Publishing country: COLOMBIA
- Installation: [Datos sobre Biodiversidad de Colombia](https://registry.gbif.org/installation/68845aab-a453-4816-b36d-a3ec8455deb0)
- Number of occurrences indexed for this dataset at the time of the issue: 5259
- Cause: GBIF ID problems exceed 50% threshold: 100% duplicates; 7119 total records; 7119 absent records
- Pipelines execution steps: [http://api.gbif.org/v1/pipelines/history/execution/3523014/step](http://api.gbif.org/v1/pipelines/history/execution/3523014/step)

```
New IDs sample:


```

```
Old IDs sample:

001-(127)RANGEL-CH.ETAL.2013/Tabla50:p248-249/01/ZAPT.-T03
001-(127)RANGEL-CH.ETAL.2013/Tabla50:p248-249/02/ZAPT.-T05
001-(127)RANGEL-CH.ETAL.2013/Tabla50:p248-249/03/ZAPT.-T04
001-(127)RANGEL-CH.ETAL.2013/Tabla50:p248-249/04/ZAPT.-T01
001-(127)RANGEL-CH.ETAL.2013/Tabla50:p248-249/07/ZAPT.-P17
001-(127)RANGEL-CH.ETAL.2013/Tabla50:p248-249/08/ZAPT.-P16
001-(127)RANGEL-CH.ETAL.2013/Tabla50:p248-249/09/ZAPT.-P38
001-(127)RANGEL-CH.ETAL.2013/Tabla50:p248-249/10/ZAPT.-P39
001-(127)RANGEL-CH.ETAL.2013/Tabla50:p248-249/11/ZAPT.-P36
001-(127)RANGEL-CH.ETAL.2013/Tabla50:p248-249/12/ZAPT.-P40
```

<details>
<summary>Publisher email</summary>

Hello,

I am contacting you from the GBIF Secretariat about a dataset published by the [Base de datos de las Especies y Eventos de las comunidades de plantas del bosque seco en el Caribe tropical de Colombia](https://registry.gbif.org/dataset/ffb1fe93-b1e9-4a16-8948-9cdf6bf7860e) : https://doi.org/10.15472/l029qu.
We noticed that the occurrenceIDs were changed. We have temporarily paused the ingestions of this dataset.

As you might already know, when an occurrence record has a new occurrenceID for a given dataset, our system considers it to be a new occurrence.
This means that it will be given a new gbifid and a new occurrence URL (like this one: https://www.gbif.org/occurrence/1252968762) and the old gbifid and URL will be deprecated.

In this case, this means that the occurrence URLs would be deprecated when ingesting the newest versions of these datasets.

We would like to check with you if those changes were intentional. Do you know if this is the case?
Please let us know, thanks! We are happy to resume the dataset ingestion.

Note that some users rely on those occurrence URLs and gbifids (like https://bionomia.net for example). In an attempt to improve
the stability of the occurrence URLs and gbifids, we have implemented a warning system to detect these type of changes in datasets (see this news item).
If the data publisher can provide us with a list of old and new occurrenceIDs per record, we can avoid the identifier and URL changes. Could that be an option?

Please let us know if you have any question. Thanks!

All the best,

</details>

You can skip/fix identifier validation using [the registry UI](https://registry.gbif.org/dataset/ffb1fe93-b1e9-4a16-8948-9cdf6bf7860e/ingestion-history).

**Comment by EstebanMH-SiB** [comment]
Hi, we make a small change in one character, from "-" to ">", here is the document with the previous and new occurrenceIDs

[changeOccurrenceIDs.txt](https://github.com/gbif/ingestion-management/files/13953855/changeOccurrenceIDs.txt)

**Comment by ManonGros** [comment]
Thanks @EstebanMH-SiB! I migrated the IDs.
