### ISSUE TITLE
Identifiers validation failed for dataset SHARK - National and regional marine environmental monitoring of Picoplankton in Sweden since 2002

### ISSUE THREAD

**Issue by gbif-pipelines** [gbif/ingestion-management#993]
Identifier validation failed for the dataset [SHARK - National and regional marine environmental monitoring of Picoplankton in Sweden since 2002](https://registry.gbif.org/dataset/588c1bd3-4cf6-4ddb-b3b7-c729d21058a8):
- Crawler attempt: 55
- Publishing organization: [The Swedish Meteorological and Hydrological Institute](https://registry.gbif.org/organization/a067ec85-ef28-4672-80ed-3cdcbf6c2667)
- Publishing country: SWEDEN
- Installation: [IPT GBIF-Sweden](https://registry.gbif.org/installation/4346b227-ca68-4d54-8a77-909148492e0b)
- Number of occurrences indexed for this dataset at the time of the issue: 2407
- Cause: GBIF ID problems exceed 50% threshold: 89% duplicates; 3123 total records; 2794 absent records
- Pipelines execution steps: [http://api.gbif.org/v1/pipelines/history/execution/3523825/step](http://api.gbif.org/v1/pipelines/history/execution/3523825/step)

```
New IDs sample:

TAXA-1897-SIZECLASS-1
TAXA-1139-CELLVOLUME-0.52
TAXA-2196-SIZECLASS-1
TAXA-1915-SIZECLASS-5
TAXA-2252-SIZECLASS-5
TAXA-1822-SIZECLASS-1
TAXA-1969-SIZECLASS-1
TAXA-2273-SIZECLASS-1
TAXA-2198-SIZECLASS-1
TAXA-1855-SIZECLASS-1
```

```
Old IDs sample:

TAXA-2357-SIZECLASS-1
TAXA-2358-SIZECLASS-5
TAXA-2370-SIZECLASS-1
TAXA-2371-SIZECLASS-5
TAXA-2383-SIZECLASS-1
TAXA-2384-SIZECLASS-5
TAXA-2395-SIZECLASS-1
TAXA-2396-SIZECLASS-5
TAXA-2359-SIZECLASS-1
TAXA-2360-SIZECLASS-5
```

<details>
<summary>Publisher email</summary>

Hello,

I am contacting you from the GBIF Secretariat about a dataset published by the [SHARK - National and regional marine environmental monitoring of Picoplankton in Sweden since 2002](https://registry.gbif.org/dataset/588c1bd3-4cf6-4ddb-b3b7-c729d21058a8) : https://doi.org/10.15468/pheept.
We noticed that the occurrenceIDs were changed. We have temporarily paused the ingestions of this dataset.

As you might already know, when an occurrence record has a new occurrenceID for a given dataset, our system considers it to be a new occurrence.
This means that it will be given a new gbifid and a new occurrence URL (like this one: https://www.gbif.org/occurrence/1252968762) and the old gbifid and URL will be deprecated.

In this case, this means that the occurrence URLs would be deprecated when ingesting the newest versions of these datasets.

We would like to check with you if those changes were intentional. Do you know if this is the case?
Please let us know, thanks! We are happy to resume the dataset ingestion.

Note that some users rely on those occurrence URLs and gbifids (like https://bionomia.net for example). In an attempt to improve
the stability of the occurrence URLs and gbifids, we have implemented a warning system to detect these type of changes in datasets (see this news item).
If the data publisher can provide us with a list of old and new occurrenceIDs per record, we can avoid the identifier and URL changes. Could that be an option?

Please let us know if you have any question. Thanks!

All the best,

</details>

You can skip/fix identifier validation using [the registry UI](https://registry.gbif.org/dataset/588c1bd3-4cf6-4ddb-b3b7-c729d21058a8/ingestion-history).

**Comment by jhnwllr** [comment]
Publishers says the Ids were changed automatically by a script. They wish to resume ingestion with the new occurrencesIds, but will work on making the occurrenceIds in the future more stable.
