### ISSUE TITLE
Identifiers validation failed for dataset Colección de Mamíferos del Instituto de Investigación de Recursos Biológicos Alexander von Humboldt (IAvH-M)

### ISSUE THREAD

**Issue by gbif-pipelines** [gbif/ingestion-management#997]
Identifier validation failed for the dataset [Colección de Mamíferos del Instituto de Investigación de Recursos Biológicos Alexander von Humboldt (IAvH-M)](https://registry.gbif.org/dataset/2a337d5a-a784-4f8a-a947-46d69e0fa3eb):
- Crawler attempt: 359
- Publishing organization: [Instituto de Investigación de Recursos Biológicos Alexander von Humboldt](https://registry.gbif.org/organization/2a7e3080-28a9-11dd-97cd-b8a03c50a862)
- Publishing country: COLOMBIA
- Installation: [IPT IAvH](https://registry.gbif.org/installation/804b8dd0-07ac-4a30-bf92-3c1d862faf5e)
- Number of occurrences indexed for this dataset at the time of the issue: 9543
- Cause: GBIF ID problems exceed 50% threshold: 100% duplicates; 10514 total records; 10514 absent records
- Pipelines execution steps: [http://api.gbif.org/v1/pipelines/history/execution/3526309/step](http://api.gbif.org/v1/pipelines/history/execution/3526309/step)

```
New IDs sample:


```

```
Old IDs sample:

IAvH:COLECCIONES:MAMIFEROS:IAvH-M-10617
IAvH:COLECCIONES:MAMIFEROS:IAvH-M-10629
IAvH:COLECCIONES:MAMIFEROS:IAvH-M-10353
IAvH:COLECCIONES:MAMIFEROS:IAvH-M-10354
IAvH:COLECCIONES:MAMIFEROS:IAvH-M-10355
IAvH:COLECCIONES:MAMIFEROS:IAvH-M-10356
IAvH:COLECCIONES:MAMIFEROS:IAvH-M-10357
IAvH:COLECCIONES:MAMIFEROS:IAvH-M-10362
IAvH:COLECCIONES:MAMIFEROS:IAvH-M-10315
IAvH:COLECCIONES:MAMIFEROS:IAvH-M-10316
```

<details>
<summary>Publisher email</summary>

Hello,

I am contacting you from the GBIF Secretariat about a dataset published by the [Colección de Mamíferos del Instituto de Investigación de Recursos Biológicos Alexander von Humboldt (IAvH-M)](https://registry.gbif.org/dataset/2a337d5a-a784-4f8a-a947-46d69e0fa3eb) : https://doi.org/10.15472/aghjkw.
We noticed that the occurrenceIDs were changed. We have temporarily paused the ingestions of this dataset.

As you might already know, when an occurrence record has a new occurrenceID for a given dataset, our system considers it to be a new occurrence.
This means that it will be given a new gbifid and a new occurrence URL (like this one: https://www.gbif.org/occurrence/1252968762) and the old gbifid and URL will be deprecated.

In this case, this means that the occurrence URLs would be deprecated when ingesting the newest versions of these datasets.

We would like to check with you if those changes were intentional. Do you know if this is the case?
Please let us know, thanks! We are happy to resume the dataset ingestion.

Note that some users rely on those occurrence URLs and gbifids (like https://bionomia.net for example). In an attempt to improve
the stability of the occurrence URLs and gbifids, we have implemented a warning system to detect these type of changes in datasets (see this news item).
If the data publisher can provide us with a list of old and new occurrenceIDs per record, we can avoid the identifier and URL changes. Could that be an option?

Please let us know if you have any question. Thanks!

All the best,

</details>

You can skip/fix identifier validation using [the registry UI](https://registry.gbif.org/dataset/2a337d5a-a784-4f8a-a947-46d69e0fa3eb/ingestion-history).

**Comment by ManonGros** [comment]
@EstebanMH-SiB

**Comment by gbif-pipelines** [comment]
Identifier validation still  failing for the dataset [Colección de Mamíferos del Instituto de Investigación de Recursos Biológicos Alexander von Humboldt (IAvH-M)](https://registry.gbif.org/dataset/2a337d5a-a784-4f8a-a947-46d69e0fa3eb):
- Crawler attempt: 384
- Publishing organization: [Instituto de Investigación de Recursos Biológicos Alexander von Humboldt](https://registry.gbif.org/organization/2a7e3080-28a9-11dd-97cd-b8a03c50a862)
- Publishing country: COLOMBIA
- Installation: [IPT IAvH](https://registry.gbif.org/installation/804b8dd0-07ac-4a30-bf92-3c1d862faf5e)
- Number of occurrences indexed for this dataset at the time of the issue: 9543
- Cause: GBIF ID problems exceed 50% threshold: 100% duplicates; 10514 total records; 10514 absent records
- Pipelines execution steps: [http://api.gbif.org/v1/pipelines/history/execution/3997578/step](http://api.gbif.org/v1/pipelines/history/execution/3997578/step)

```
New IDs sample:


```


```
Old IDs sample:

IAvH:COLECCIONES:MAMIFEROS:IAvH-M-10617
IAvH:COLECCIONES:MAMIFEROS:IAvH-M-10629
IAvH:COLECCIONES:MAMIFEROS:IAvH-M-10353
IAvH:COLECCIONES:MAMIFEROS:IAvH-M-10354
IAvH:COLECCIONES:MAMIFEROS:IAvH-M-10355
IAvH:COLECCIONES:MAMIFEROS:IAvH-M-10356
IAvH:COLECCIONES:MAMIFEROS:IAvH-M-10357
IAvH:COLECCIONES:MAMIFEROS:IAvH-M-10362
IAvH:COLECCIONES:MAMIFEROS:IAvH-M-10315
IAvH:COLECCIONES:MAMIFEROS:IAvH-M-10316
```

<details>
<summary>Publisher email</summary>

Hello,

I am contacting you from the GBIF Secretariat about a dataset published by the [Colección de Mamíferos del Instituto de Investigación de Recursos Biológicos Alexander von Humboldt (IAvH-M)](https://registry.gbif.org/dataset/2a337d5a-a784-4f8a-a947-46d69e0fa3eb) : https://doi.org/10.15472/aghjkw.
We noticed that the occurrenceIDs were changed. We have temporarily paused the ingestions of this dataset.

As you might already know, when an occurrence record has a new occurrenceID for a given dataset, our system considers it to be a new occurrence.
This means that it will be given a new gbifid and a new occurrence URL (like this one: https://www.gbif.org/occurrence/1252968762) and the old gbifid and URL will be deprecated.

In this case, this means that the occurrence URLs would be deprecated when ingesting the newest versions of these datasets.

We would like to check with you if those changes were intentional. Do you know if this is the case?
Please let us know, thanks! We are happy to resume the dataset ingestion.

Note that some users rely on those occurrence URLs and gbifids (like https://bionomia.net for example). In an attempt to improve
the stability of the occurrence URLs and gbifids, we have implemented a warning system to detect these type of changes in datasets (see this news item).
If the data publisher can provide us with a list of old and new occurrenceIDs per record, we can avoid the identifier and URL changes. Could that be an option?

Please let us know if you have any question. Thanks!

All the best,

</details>


You can skip/fix identifier validation using [the registry UI](https://registry.gbif.org/dataset/2a337d5a-a784-4f8a-a947-46d69e0fa3eb/ingestion-history).

**Comment by gbif-pipelines** [comment]
Identifier validation still  failing for the dataset [Colección de Mamíferos del Instituto de Investigación de Recursos Biológicos Alexander von Humboldt (IAvH-M)](https://registry.gbif.org/dataset/2a337d5a-a784-4f8a-a947-46d69e0fa3eb):
- Crawler attempt: 387
- Publishing organization: [Instituto de Investigación de Recursos Biológicos Alexander von Humboldt](https://registry.gbif.org/organization/2a7e3080-28a9-11dd-97cd-b8a03c50a862)
- Publishing country: COLOMBIA
- Installation: [IPT IAvH](https://registry.gbif.org/installation/804b8dd0-07ac-4a30-bf92-3c1d862faf5e)
- Number of occurrences indexed for this dataset at the time of the issue: 9543
- Cause: GBIF ID problems exceed 50% threshold: 100% duplicates; 10514 total records; 10514 absent records
- Pipelines execution steps: [http://api.gbif.org/v1/pipelines/history/execution/4052646/step](http://api.gbif.org/v1/pipelines/history/execution/4052646/step)

```
New IDs sample:


```


```
Old IDs sample:

IAvH:COLECCIONES:MAMIFEROS:IAvH-M-10617
IAvH:COLECCIONES:MAMIFEROS:IAvH-M-10629
IAvH:COLECCIONES:MAMIFEROS:IAvH-M-10353
IAvH:COLECCIONES:MAMIFEROS:IAvH-M-10354
IAvH:COLECCIONES:MAMIFEROS:IAvH-M-10355
IAvH:COLECCIONES:MAMIFEROS:IAvH-M-10356
IAvH:COLECCIONES:MAMIFEROS:IAvH-M-10357
IAvH:COLECCIONES:MAMIFEROS:IAvH-M-10362
IAvH:COLECCIONES:MAMIFEROS:IAvH-M-10315
IAvH:COLECCIONES:MAMIFEROS:IAvH-M-10316
```

<details>
<summary>Publisher email</summary>

Hello,

I am contacting you from the GBIF Secretariat about a dataset published by the [Colección de Mamíferos del Instituto de Investigación de Recursos Biológicos Alexander von Humboldt (IAvH-M)](https://registry.gbif.org/dataset/2a337d5a-a784-4f8a-a947-46d69e0fa3eb) : https://doi.org/10.15472/aghjkw.
We noticed that the occurrenceIDs were changed. We have temporarily paused the ingestions of this dataset.

As you might already know, when an occurrence record has a new occurrenceID for a given dataset, our system considers it to be a new occurrence.
This means that it will be given a new gbifid and a new occurrence URL (like this one: https://www.gbif.org/occurrence/1252968762) and the old gbifid and URL will be deprecated.

In this case, this means that the occurrence URLs would be deprecated when ingesting the newest versions of these datasets.

We would like to check with you if those changes were intentional. Do you know if this is the case?
Please let us know, thanks! We are happy to resume the dataset ingestion.

Note that some users rely on those occurrence URLs and gbifids (like https://bionomia.net for example). In an attempt to improve
the stability of the occurrence URLs and gbifids, we have implemented a warning system to detect these type of changes in datasets (see this news item).
If the data publisher can provide us with a list of old and new occurrenceIDs per record, we can avoid the identifier and URL changes. Could that be an option?

Please let us know if you have any question. Thanks!

All the best,

</details>


You can skip/fix identifier validation using [the registry UI](https://registry.gbif.org/dataset/2a337d5a-a784-4f8a-a947-46d69e0fa3eb/ingestion-history).
