### ISSUE TITLE
Identifiers validation failed for dataset Colección de Semillas del Instituto de Investigación de Recursos Biológicos Alexander von Humboldt (IAvH-CS)

### ISSUE THREAD

**Issue by gbif-pipelines** [gbif/ingestion-management#999]
Identifier validation failed for the dataset [Colección de Semillas del Instituto de Investigación de Recursos Biológicos Alexander von Humboldt (IAvH-CS)](https://registry.gbif.org/dataset/97367d97-2b0c-4895-aee7-070f9bb42e5a):
- Crawler attempt: 70
- Publishing organization: [Instituto de Investigación de Recursos Biológicos Alexander von Humboldt](https://registry.gbif.org/organization/2a7e3080-28a9-11dd-97cd-b8a03c50a862)
- Publishing country: COLOMBIA
- Installation: [IPT IAvH](https://registry.gbif.org/installation/804b8dd0-07ac-4a30-bf92-3c1d862faf5e)
- Number of occurrences indexed for this dataset at the time of the issue: 224
- Cause: GBIF ID problems exceed 50% threshold: 100% duplicates; 229 total records; 229 absent records
- Pipelines execution steps: [http://api.gbif.org/v1/pipelines/history/execution/3526315/step](http://api.gbif.org/v1/pipelines/history/execution/3526315/step)

```
New IDs sample:


```

```
Old IDs sample:

IAvH:COLECCIÓN:SEMILLAS:IAvH-CS-146
IAvH:COLECCIÓN:SEMILLAS:IAvH-CS-147
IAvH:COLECCIÓN:SEMILLAS:IAvH-CS-148
IAvH:COLECCIÓN:SEMILLAS:IAvH-CS-149
IAvH:COLECCIÓN:SEMILLAS:IAvH-CS-150
IAvH:COLECCIÓN:SEMILLAS:IAvH-CS-151
IAvH:COLECCIÓN:SEMILLAS:IAvH-CS-152
IAvH:COLECCIÓN:SEMILLAS:IAvH-CS-153
IAvH:COLECCIÓN:SEMILLAS:IAvH-CS-154
IAvH:COLECCIÓN:SEMILLAS:IAvH-CS-155
```

<details>
<summary>Publisher email</summary>

Hello,

I am contacting you from the GBIF Secretariat about a dataset published by the [Colección de Semillas del Instituto de Investigación de Recursos Biológicos Alexander von Humboldt (IAvH-CS)](https://registry.gbif.org/dataset/97367d97-2b0c-4895-aee7-070f9bb42e5a) : https://doi.org/10.15472/b3db3x.
We noticed that the occurrenceIDs were changed. We have temporarily paused the ingestions of this dataset.

As you might already know, when an occurrence record has a new occurrenceID for a given dataset, our system considers it to be a new occurrence.
This means that it will be given a new gbifid and a new occurrence URL (like this one: https://www.gbif.org/occurrence/1252968762) and the old gbifid and URL will be deprecated.

In this case, this means that the occurrence URLs would be deprecated when ingesting the newest versions of these datasets.

We would like to check with you if those changes were intentional. Do you know if this is the case?
Please let us know, thanks! We are happy to resume the dataset ingestion.

Note that some users rely on those occurrence URLs and gbifids (like https://bionomia.net for example). In an attempt to improve
the stability of the occurrence URLs and gbifids, we have implemented a warning system to detect these type of changes in datasets (see this news item).
If the data publisher can provide us with a list of old and new occurrenceIDs per record, we can avoid the identifier and URL changes. Could that be an option?

Please let us know if you have any question. Thanks!

All the best,

</details>

You can skip/fix identifier validation using [the registry UI](https://registry.gbif.org/dataset/97367d97-2b0c-4895-aee7-070f9bb42e5a/ingestion-history).

**Comment by ManonGros** [comment]
@EstebanMH-SiB

**Comment by gbif-pipelines** [comment]
Identifier validation still  failing for the dataset [Colección de Semillas del Instituto de Investigación de Recursos Biológicos Alexander von Humboldt (IAvH-CS)](https://registry.gbif.org/dataset/97367d97-2b0c-4895-aee7-070f9bb42e5a):
- Crawler attempt: 70
- Publishing organization: [Instituto de Investigación de Recursos Biológicos Alexander von Humboldt](https://registry.gbif.org/organization/2a7e3080-28a9-11dd-97cd-b8a03c50a862)
- Publishing country: COLOMBIA
- Installation: [IPT IAvH](https://registry.gbif.org/installation/804b8dd0-07ac-4a30-bf92-3c1d862faf5e)
- Number of occurrences indexed for this dataset at the time of the issue: 224
- Cause: GBIF ID problems exceed 50% threshold: 100% duplicates; 229 total records; 229 absent records
- Pipelines execution steps: [http://api.gbif.org/v1/pipelines/history/execution/3580964/step](http://api.gbif.org/v1/pipelines/history/execution/3580964/step)

```
New IDs sample:


```


```
Old IDs sample:

IAvH:COLECCIÓN:SEMILLAS:IAvH-CS-146
IAvH:COLECCIÓN:SEMILLAS:IAvH-CS-147
IAvH:COLECCIÓN:SEMILLAS:IAvH-CS-148
IAvH:COLECCIÓN:SEMILLAS:IAvH-CS-149
IAvH:COLECCIÓN:SEMILLAS:IAvH-CS-150
IAvH:COLECCIÓN:SEMILLAS:IAvH-CS-151
IAvH:COLECCIÓN:SEMILLAS:IAvH-CS-152
IAvH:COLECCIÓN:SEMILLAS:IAvH-CS-153
IAvH:COLECCIÓN:SEMILLAS:IAvH-CS-154
IAvH:COLECCIÓN:SEMILLAS:IAvH-CS-155
```

<details>
<summary>Publisher email</summary>

Hello,

I am contacting you from the GBIF Secretariat about a dataset published by the [Colección de Semillas del Instituto de Investigación de Recursos Biológicos Alexander von Humboldt (IAvH-CS)](https://registry.gbif.org/dataset/97367d97-2b0c-4895-aee7-070f9bb42e5a) : https://doi.org/10.15472/b3db3x.
We noticed that the occurrenceIDs were changed. We have temporarily paused the ingestions of this dataset.

As you might already know, when an occurrence record has a new occurrenceID for a given dataset, our system considers it to be a new occurrence.
This means that it will be given a new gbifid and a new occurrence URL (like this one: https://www.gbif.org/occurrence/1252968762) and the old gbifid and URL will be deprecated.

In this case, this means that the occurrence URLs would be deprecated when ingesting the newest versions of these datasets.

We would like to check with you if those changes were intentional. Do you know if this is the case?
Please let us know, thanks! We are happy to resume the dataset ingestion.

Note that some users rely on those occurrence URLs and gbifids (like https://bionomia.net for example). In an attempt to improve
the stability of the occurrence URLs and gbifids, we have implemented a warning system to detect these type of changes in datasets (see this news item).
If the data publisher can provide us with a list of old and new occurrenceIDs per record, we can avoid the identifier and URL changes. Could that be an option?

Please let us know if you have any question. Thanks!

All the best,

</details>


You can skip/fix identifier validation using [the registry UI](https://registry.gbif.org/dataset/97367d97-2b0c-4895-aee7-070f9bb42e5a/ingestion-history).

**Comment by gbif-pipelines** [comment]
Identifier validation still  failing for the dataset [Colección de Semillas del Instituto de Investigación de Recursos Biológicos Alexander von Humboldt (IAvH-CS)](https://registry.gbif.org/dataset/97367d97-2b0c-4895-aee7-070f9bb42e5a):
- Crawler attempt: 95
- Publishing organization: [Instituto de Investigación de Recursos Biológicos Alexander von Humboldt](https://registry.gbif.org/organization/2a7e3080-28a9-11dd-97cd-b8a03c50a862)
- Publishing country: COLOMBIA
- Installation: [IPT IAvH](https://registry.gbif.org/installation/804b8dd0-07ac-4a30-bf92-3c1d862faf5e)
- Number of occurrences indexed for this dataset at the time of the issue: 224
- Cause: GBIF ID problems exceed 50% threshold: 100% duplicates; 229 total records; 229 absent records
- Pipelines execution steps: [http://api.gbif.org/v1/pipelines/history/execution/3988615/step](http://api.gbif.org/v1/pipelines/history/execution/3988615/step)

```
New IDs sample:


```


```
Old IDs sample:

IAvH:COLECCIÓN:SEMILLAS:IAvH-CS-146
IAvH:COLECCIÓN:SEMILLAS:IAvH-CS-147
IAvH:COLECCIÓN:SEMILLAS:IAvH-CS-148
IAvH:COLECCIÓN:SEMILLAS:IAvH-CS-149
IAvH:COLECCIÓN:SEMILLAS:IAvH-CS-150
IAvH:COLECCIÓN:SEMILLAS:IAvH-CS-151
IAvH:COLECCIÓN:SEMILLAS:IAvH-CS-152
IAvH:COLECCIÓN:SEMILLAS:IAvH-CS-153
IAvH:COLECCIÓN:SEMILLAS:IAvH-CS-154
IAvH:COLECCIÓN:SEMILLAS:IAvH-CS-155
```

<details>
<summary>Publisher email</summary>

Hello,

I am contacting you from the GBIF Secretariat about a dataset published by the [Colección de Semillas del Instituto de Investigación de Recursos Biológicos Alexander von Humboldt (IAvH-CS)](https://registry.gbif.org/dataset/97367d97-2b0c-4895-aee7-070f9bb42e5a) : https://doi.org/10.15472/b3db3x.
We noticed that the occurrenceIDs were changed. We have temporarily paused the ingestions of this dataset.

As you might already know, when an occurrence record has a new occurrenceID for a given dataset, our system considers it to be a new occurrence.
This means that it will be given a new gbifid and a new occurrence URL (like this one: https://www.gbif.org/occurrence/1252968762) and the old gbifid and URL will be deprecated.

In this case, this means that the occurrence URLs would be deprecated when ingesting the newest versions of these datasets.

We would like to check with you if those changes were intentional. Do you know if this is the case?
Please let us know, thanks! We are happy to resume the dataset ingestion.

Note that some users rely on those occurrence URLs and gbifids (like https://bionomia.net for example). In an attempt to improve
the stability of the occurrence URLs and gbifids, we have implemented a warning system to detect these type of changes in datasets (see this news item).
If the data publisher can provide us with a list of old and new occurrenceIDs per record, we can avoid the identifier and URL changes. Could that be an option?

Please let us know if you have any question. Thanks!

All the best,

</details>


You can skip/fix identifier validation using [the registry UI](https://registry.gbif.org/dataset/97367d97-2b0c-4895-aee7-070f9bb42e5a/ingestion-history).

**Comment by gbif-pipelines** [comment]
Identifier validation still  failing for the dataset [Colección de Semillas del Instituto de Investigación de Recursos Biológicos Alexander von Humboldt (IAvH-CS)](https://registry.gbif.org/dataset/97367d97-2b0c-4895-aee7-070f9bb42e5a):
- Crawler attempt: 98
- Publishing organization: [Instituto de Investigación de Recursos Biológicos Alexander von Humboldt](https://registry.gbif.org/organization/2a7e3080-28a9-11dd-97cd-b8a03c50a862)
- Publishing country: COLOMBIA
- Installation: [IPT IAvH](https://registry.gbif.org/installation/804b8dd0-07ac-4a30-bf92-3c1d862faf5e)
- Number of occurrences indexed for this dataset at the time of the issue: 224
- Cause: GBIF ID problems exceed 50% threshold: 100% duplicates; 229 total records; 229 absent records
- Pipelines execution steps: [http://api.gbif.org/v1/pipelines/history/execution/4043423/step](http://api.gbif.org/v1/pipelines/history/execution/4043423/step)

```
New IDs sample:


```


```
Old IDs sample:

IAvH:COLECCIÓN:SEMILLAS:IAvH-CS-146
IAvH:COLECCIÓN:SEMILLAS:IAvH-CS-147
IAvH:COLECCIÓN:SEMILLAS:IAvH-CS-148
IAvH:COLECCIÓN:SEMILLAS:IAvH-CS-149
IAvH:COLECCIÓN:SEMILLAS:IAvH-CS-150
IAvH:COLECCIÓN:SEMILLAS:IAvH-CS-151
IAvH:COLECCIÓN:SEMILLAS:IAvH-CS-152
IAvH:COLECCIÓN:SEMILLAS:IAvH-CS-153
IAvH:COLECCIÓN:SEMILLAS:IAvH-CS-154
IAvH:COLECCIÓN:SEMILLAS:IAvH-CS-155
```

<details>
<summary>Publisher email</summary>

Hello,

I am contacting you from the GBIF Secretariat about a dataset published by the [Colección de Semillas del Instituto de Investigación de Recursos Biológicos Alexander von Humboldt (IAvH-CS)](https://registry.gbif.org/dataset/97367d97-2b0c-4895-aee7-070f9bb42e5a) : https://doi.org/10.15472/b3db3x.
We noticed that the occurrenceIDs were changed. We have temporarily paused the ingestions of this dataset.

As you might already know, when an occurrence record has a new occurrenceID for a given dataset, our system considers it to be a new occurrence.
This means that it will be given a new gbifid and a new occurrence URL (like this one: https://www.gbif.org/occurrence/1252968762) and the old gbifid and URL will be deprecated.

In this case, this means that the occurrence URLs would be deprecated when ingesting the newest versions of these datasets.

We would like to check with you if those changes were intentional. Do you know if this is the case?
Please let us know, thanks! We are happy to resume the dataset ingestion.

Note that some users rely on those occurrence URLs and gbifids (like https://bionomia.net for example). In an attempt to improve
the stability of the occurrence URLs and gbifids, we have implemented a warning system to detect these type of changes in datasets (see this news item).
If the data publisher can provide us with a list of old and new occurrenceIDs per record, we can avoid the identifier and URL changes. Could that be an option?

Please let us know if you have any question. Thanks!

All the best,

</details>


You can skip/fix identifier validation using [the registry UI](https://registry.gbif.org/dataset/97367d97-2b0c-4895-aee7-070f9bb42e5a/ingestion-history).
